### ISSUE TITLE
charcoal doesn't work with Coal Generator

### ISSUE THREAD

**Issue by paduser** [micdoodle8/Galacticraft#2091] opened 2016-02-17 22:50 UTC
Hey guys
I saw this in the wiki 

> The Coal Generator accepts coal, charcoal, or Blocks of Coal.

But when I try to add a pice of charcoal to the generator it wont accept it.
I'm playing on the latest dev version 1.7-3.0.12.442.

Thanks

**Comment by radfast** [comment] 2016-02-18 00:03
This is intended behaviour.  We want people to be using solar as early as possible, the Coal Generator is only there to get you started with power if you have no other mods.

Wiki is now fixed, thank you for spotting that.

**Closed by radfast** 2016-02-18 00:03 UTC
