### ISSUE TITLE
[1.10.2]  Beta versions - internal map imaging disabled with [Geographicraft]

### ISSUE THREAD

**Issue by silent-mobious** [micdoodle8/Galacticraft#2544] opened 2017-04-10 00:36 UTC
I'm getting a crash whenever a new world gens on my server, I think I've narrowed it down to GC and Geographicraft.  When Geographicraft is in, even just by itself and GC, i get this.  Are they fighting over entity placement?  :

Description: Ticking entity

java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOfRange(Arrays.java:3664)
	at java.lang.StringBuffer.toString(StringBuffer.java:669)
	at org.apache.commons.lang3.exception.ExceptionUtils.getStackTrace(ExceptionUtils.java:586)
	at micdoodle8.mods.galacticraft.core.blocks.MaterialOleaginous.func_76230_c(MaterialOleaginous.java:27)
	at net.minecraft.block.Block.func_176214_u(Block.java:275)
	at net.minecraft.entity.Entity.func_70094_T(Entity.java:1811)
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:222)
	at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:208)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:359)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1932)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:52)
	at net.minecraft.entity.monster.EntitySpider.func_70071_h_(SourceFile:86)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

Here's the full log: https://pastebin.com/sEgH8sxc

Thanks a lot!

Silent

**Comment by MJRLegends** [comment] 2017-04-10 00:38
This isnt a bug, you just need to assign more RAM, it even tells you this in the crash log you provided 
java.lang.**OutOfMemory**Error: GC overhead limit exceeded

**Comment by silent-mobious** [comment] 2017-04-10 00:58
Well, no, with the same 8gb of memory and only 5 mods I was still crashing out with that error.  I just doubled the memory given to it, 16gb, and the same 5 mods, and crash.  I don't think it's a simple needs-more-memory issue, specifically with the micdoodle8.mods.galacticraft.core.util.MapGen calls at the bottom:


[20:48:44] [Thread-8/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.OutOfMemoryError: Java heap space
[20:48:47] [Thread-8/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.world.gen.layer.IntCache.func_76445_a(SourceFile:41)
[20:48:47] [Thread-8/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at climateControl.customGenLayer.GenLayerBreakMergers.func_75904_a(GenLayerBreakMergers.java:26)
[20:48:47] [Thread-8/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at climateControl.customGenLayer.GenLayerIdentifiedClimate.func_75904_a(GenLayerIdentifiedClimate.java:59)
[20:48:47] [Thread-8/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at climateControl.genLayerPack.GenLayerZoom.func_75904_a(GenLayerZoom.java:34)
[20:48:47] [Thread-8/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at climateControl.customGenLayer.GenLayerBreakMergers.func_75904_a(GenLayerBreakMergers.java:25)
[20:48:47] [Thread-8/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at climateControl.customGenLayer.GenLayerOceanicIslands.getSeparatedIslands(GenLayerOceanicIslands.java:123)
[20:48:47] [Thread-8/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at climateControl.customGenLayer.GenLayerOceanicIslands.func_75904_a(GenLayerOceanicIslands.java:78)
[20:48:47] [Thread-8/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at climateControl.customGenLayer.GenLayerAdjustIsland.func_75904_a(GenLayerAdjustIsland.java:34)
[20:48:47] [Thread-8/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at climateControl.customGenLayer.GenLayerSmoothClimate.func_75904_a(GenLayerSmoothClimate.java:45)
[20:48:47] [Thread-8/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at climateControl.customGenLayer.GenLayerBreakMergers.func_75904_a(GenLayerBreakMergers.java:25)
[20:48:47] [Thread-8/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at climateControl.customGenLayer.GenLayerLimitedCache.func_75904_a(GenLayerLimitedCache.java:59)
[20:48:47] [Thread-8/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at climateControl.customGenLayer.GenLayerContinentalShelf.func_75904_a(GenLayerContinentalShelf.java:27)
[20:48:47] [Thread-8/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at climateControl.customGenLayer.GenLayerOceanicMushroomIsland.func_75904_a(GenLayerOceanicMushroomIsland.java:35)
[20:48:47] [Thread-8/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at climateControl.customGenLayer.GenLayerLessRiver.func_75904_a(GenLayerLessRiver.java:31)
[20:48:47] [Thread-8/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at climateControl.genLayerPack.GenLayerZoom.func_75904_a(GenLayerZoom.java:34)
[20:48:47] [Thread-8/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at climateControl.genLayerPack.GenLayerZoom.func_75904_a(GenLayerZoom.java:34)
[20:48:47] [Thread-8/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at climateControl.customGenLayer.GenLayerSubBiome.func_75904_a(GenLayerSubBiome.java:50)
[20:48:47] [Thread-8/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at climateControl.genLayerPack.GenLayerRareBiome.func_75904_a(GenLayerRareBiome.java:22)
[20:48:47] [Thread-8/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at climateControl.genLayerPack.GenLayerZoom.func_75904_a(GenLayerZoom.java:34)
[20:48:47] [Thread-8/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at climateControl.genLayerPack.GenLayerAddIsland.func_75904_a(GenLayerAddIsland.java:26)
[20:48:47] [Thread-8/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at climateControl.customGenLayer.GenLayerSmoothCoast.func_75904_a(GenLayerSmoothCoast.java:43)
[20:48:47] [Thread-8/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at climateControl.customGenLayer.GenLayerPrettyShore.func_75904_a(GenLayerPrettyShore.java:42)
[20:48:47] [Thread-8/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at climateControl.genLayerPack.GenLayerZoom.func_75904_a(GenLayerZoom.java:34)
[20:48:47] [Thread-8/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at climateControl.customGenLayer.GenLayerSmoothCoast.func_75904_a(GenLayerSmoothCoast.java:43)
[20:48:47] [Thread-8/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at climateControl.genLayerPack.GenLayerZoom.func_75904_a(GenLayerZoom.java:34)
[20:48:47] [Thread-8/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at climateControl.genLayerPack.GenLayerZoom.func_75904_a(GenLayerZoom.java:34)
[20:48:47] [Thread-8/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at climateControl.genLayerPack.GenLayerSmooth.func_75904_a(GenLayerSmooth.java:32)
[20:48:47] [Thread-8/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at climateControl.customGenLayer.GenLayerLowlandRiverMix.func_75904_a(GenLayerLowlandRiverMix.java:63)
[20:48:47] [Thread-8/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at climateControl.customGenLayer.GenLayerRiverMixWrapper.func_75904_a(GenLayerRiverMixWrapper.java:78)
[20:48:47] [Thread-8/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at micdoodle8.mods.galacticraft.core.util.MapGen.func_76937_a(MapGen.java:516)
[20:48:47] [Thread-8/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at micdoodle8.mods.galacticraft.core.util.MapGen.getHeightMap(MapGen.java:310)
[20:48:47] [Thread-8/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at micdoodle8.mods.galacticraft.core.util.MapGen.biomeMapOneChunk(MapGen.java:238)


https://pastebin.com/T9XrmTDW


and my server launch command if needed:
MEMORY_OPTS='16G'
	JAVA_OPTS="-XX:+UseG1GC -Dfml.queryResult=confirm -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M"
	FORGE_FILE='forge-1.10.2-12.18.3.2272-universal.jar'
    java -jar $FORGE_FILE -Xms$MEMORY_OPTS -Xmx$MEMORY_OPTS $JAVA_OPTS nogui

**Comment by MJRLegends** [comment] 2017-04-10 01:02
**climateControl**.customGenLayer.GenLayerBreakMergers.func_75904_a(GenLayerBreakMergers.java:26)
[20:48:47] [Thread-8/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: at **climateControl**.customGenLayer.GenLayerIdentifiedClimate.func_75904_a(GenLayerIdentifiedClimate.java:59)
[20:48:47] [Thread-8/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: at **climateControl**.genLayerPack.GenLayerZoom.func_75904_a(GenLayerZoom.java:34)
[20:48:47] [Thread-8/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: at **climateControl**.customGenLayer.GenLayerBreakMergers.func_75904_a(GenLayerBreakMergers.java:25)

Shows to be a issue with climateControl not galacticraft

**Comment by silent-mobious** [comment] 2017-04-10 01:23
That's really weird, could have sworn @MJRLegends and I were having a conversation there...  but... 
 disappeared.  :|

**Comment by radfast** [comment] 2017-04-10 01:25
"GC" in Java internals means the Garbage Collector, not Galacticraft!

But, I can see there is definately an issue here: the cause of all those STDERR is our internal MapGen fighting with **ClimateControl** (is that part of Geographicraft?) 

Our MapGen is making an internal map of the whole world (out to about 12000 blocks from spawn) without actually generating the chunks on the server.  This will be used in future for some awesome views from space, stuff like that, you can also see a preview of it in the local area map shown on the Display Screen.  At present, it only understands vanilla GenLayers so if other mods like Geographicraft or RTG (Realistic Terrain Generation) change the way Minecraft generates the world, then it will error like this.

Unfortunately in this beta version there is no way to switch off our internal MapGen.  Actually I don't **want** to switch it off, because I want to see which other mods it is not working with, so that we can actually fix it instead of switching it off!

I am looking at this over the next day or so.  If I can't fix it quickly, then we will include in a future beta version a way to switch this off so that it doesn't spew errors.

**For now: please try out Galacticraft betas without Geographicraft and without BiomeTweaker**

**Comment by radfast** [comment] 2017-04-10 01:28
This is similar to #2481 but a different type of crash.  We should be able to fix both.

**Comment by silent-mobious** [comment] 2017-04-10 01:51
Ah, thanks for the explanation!  The space views sound really slick!  The Galacticraft betas have been working fine with the other mods I'm using with that one exception of Geographicraft/Climate Control (@Zeno410 changed names for post 1.7.10 builds), so I'll just keep playing around without it and see how the rest of things work and wait for a new build.  

Thanks a lot!

Silent

**Comment by silent-mobious** [comment] 2017-04-10 01:51
Oops.  Close button's a little close, there...

**Comment by radfast** [comment] 2017-04-10 01:56
ok great, let us know if anything else doesn't work with Galactricraft in your current modpack

new build with a fix for this won't be out for a day or two at least, probably.  I'll keep this open until there is some news.

**Comment by radfast** [comment] 2017-04-23 12:12
In Galacticraft BETA build 71 and later, there will now be no crash.  Galacticraft will detect Geographicraft and any other mod that causes a problem with GC's internal map imaging and disable that feature.  There will 1 error message with a link to this thread, no error spam.  The rest of Galacticraft will continue working normally.

I've therefore flagged this now as a "minor" issue, as 99% of things will work normally for you.

**Comment by radfast** [comment] 2017-05-08 00:37
I've had some time to look at this in depth now.  The out-of-memory crashes reported with the Climate Control mod look like actually a hidden memory leak in Climate Control.

Basically it means Climate Control would make the game run out of memory on any server if the server ran for long enough.  Our background mapping simply speeds up the process of generating the biome map, running mapgen at the maximum speed which one core can handle - kind of like a player in creative mode zipping up and down the map from north to south to the preset edges of the map (around 12000 blocks from spawn) as fast as he can move, so generating the map - except that we don't generate the actual block data in chunks, we only generate the biomes at this stage.  So our background mapping makes Climate Control's memory leak more "visible" you could say.

The problem in coding terms is Climate Control is allocating aints from the IntCache, but not releasing them when it's done with them.  I didn't find the exact spot yet where they are forgetting to release  them.  It may be the simplest thing for me to do is find the bug in their code and patch it....  I'm looking at this some more.

**Comment by silent-mobious** [comment] 2017-05-08 02:24
Awesome, thanks for still looking!  I guess I'll have to sideline Geographicraft/RTG until things get fixed up with it.  @Zeno410?  Things have been pretty solid with ATG and Galacticraft, and the family is getting restless to play and they don't understand "bug fixes take _time_"... :)

**Comment by radfast** [comment] 2017-05-08 15:02
As we discussed on your other thread, another solution could be for you to have Galacticraft generate the Overworld map in small bursts, like 5 minutes (or even less) at a time, then stop the server.  Do it over and over a few times until its done.

Probably, a small burst of our accelerated map gen will not be enough to push Climate Control close to the out of memory condition.

It's up to you to figure out how many minutes of map gen it can take without running out of memory...

**Comment by silent-mobious** [comment] 2017-05-08 17:06
Unfortunately that wouldn't work for me, I don't even get 10 seconds after finishing loading before things freeze up and I start getting out of memory errors.  After that I have to kill the process to get out of it.  Thanks!

**Comment by radfast** [comment] 2017-05-08 18:21
I'm sorry, I've realised it may be us causing the memory leak when ClimateControl is present alongside Galacticraft.  Probably no need for **Zeno410** to look at this.

I'm trying to find a solution....

**Closed** 2017-05-08 21:12 UTC
Labels: 1.10+, 1.8, conflict, minor

**Comment by radfast** [comment] 2017-05-10 02:50
As of [Build 85](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/), we are now fully compatible with Geographicraft.

No more crashes!

The world map generated on Display Screens should accurately show the Geographicraft-altered terrain.  (Same for Biomes o'Plenty).
