### ISSUE TITLE
Torch Bug #2

### ISSUE THREAD

**Issue by babybasher** [micdoodle8/Galacticraft#1564] opened 2015-04-10 13:46 UTC
I don't know whether we are meant to reply in 'closed' topics, so will post this here.  I've managed to duplicate an earlier bug of torches not stacking properly on the moon.  

1. In a sealed environment (on the moon) place a normal torch.
2. Break torch and when picked up it won't stack with your original ones.  They will create their own stack.

Interestingly as well..

1. Unseal the room or just place the 'new' stack torches in an unsealed area.  
2. Break these torches and they will stack with the original torches ok.

When you place the 'new' stack torches in the unsealed area, they glow/flicker for a split second before going out.  Normal torches don't display that little oddity.

If you go back to the overworld with the 'new' stack its name remains 'blue' in the inventory.

I tested and confirmed this on a dedicated server (survival) and singleplayer server (creative) using the lastest build .315

I hope this was understandable, thank you.

**Comment by radfast** [comment] 2015-04-11 16:50
Replying on closed topics is OK, and helps keep all related discussion in one place.  Link to #1537.  I get notified of replies on closed topics the same as on open topics.

It's not a bug.  In the world there are two types of torches, the white (vanilla) type and the blue (Galacticraft) type in space dimensions.  When you hold a torch (or a stack of torches), or place a torch in the world, either kind of torch will auto-adjust to the correct type.

It does not auto-adjust in other, non-held, stacks in the player's inventory, or in chests etc, we have no easy way to fix that (it would involve some ugly hacking of the vanilla game code, which could produce compatibility issues).  That has no consequences except that the 2 types of torch will not stack.

The flicker for a split second is interesting, we can maybe do something about that, but it's ultra minor.

I'm going to close this because everything is behaving as currently intended.  I have made a note on my todo list of the glow/flicker thing, but as it's so minor I'm not likely to get to it any time soon.

**Closed by radfast** 2015-04-11 16:50 UTC
