### ISSUE TITLE
Wrong fly

### ISSUE THREAD

**Issue by JanSzumotalski** [micdoodle8/Galacticraft#2284] opened 2016-10-11 18:47 UTC
I fly from Mars to Earth with no selection.

**Comment by EzerArch** [comment] 2016-10-11 20:58
Please, elaborate.

**Comment by radfast** [comment] 2017-02-25 00:47
Closing due to no explanation.

Please re-open if this happens again.  Maybe give screenshots, or a video, or steps to reproduce?

**Closed by radfast** 2017-02-25 00:47 UTC
Labels: 1.7, missing info

**Comment by C1ffisme** [comment] 2017-02-25 04:22
My best guess as to this person's problem is that either:

- You can click launch without selecting, and end up going to Mars OR
- Clicking on a planet sends you to Mars rather than the selected one.

If neither of these can be reproduced, then it was probably an accident or a mis-click.

That's my best guess, though.

**Comment by JanSzumotalski** [comment] 2017-02-25 10:09
I find _error_. This is a rocket launcher.

**Comment by C1ffisme** [comment] 2017-02-25 15:10
> I find _error_. 

Well, I noticed that much, otherwise you wouldn't have created an issue. What kind of error, though. Does the game crash? Does something happen unexpectedly? I nor anyone else here can tell what you mean from just 'error'.

> This is a rocket launcher.

What is? The mod? The issue? You are talking in what is basically a support forum for the mod. Forums are for talking, so please feel free to communicate in much more depth what your problem is.

**Comment by dj3520** [comment] 2017-02-25 15:52
My guesses: 

- The option to go back to Earth while launching from Mars isn't possible (greyed out on selection screen)
- Attempting to launch the rocket on Mars fails.

**Comment by EzerArch** [comment] 2017-02-26 01:41
My guess: assuming he's playing on a server, someone has set up a launch controller to trave from mars to earth. That's the only way I know of to skip the selection screen. (besides OP-command /dimensiontp)

**Comment by radfast** [comment] 2017-02-26 12:20
@JanSzumotalski  please post screenshots
