### ISSUE TITLE
TileEntityCoalGenerator returning null for IEnergyStorage

### ISSUE THREAD

**Issue by clienthax** [micdoodle8/Galacticraft#3845] opened 2019-12-08 02:00 UTC
REVIEW THE GUIDELINES - see [Contributing](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) link on right side.

Minecraft version: 1.12.2
Galacticraft version:
GalacticraftCore-1.12.2-4.0.2.238.jar
Galacticraft-Planets-1.12.2-4.0.2.238.jar
spongeforge-1.12.2-2838-7.1.8-RC3961.jar
SMP

The 1.12.2 Pack

```
[01:56:12] [Server thread/ERROR] [Mekanism EnergyAcceptorWrapper]: Tile TileEntityCoalGenerator{tileType=galacticraftcore:GC Coal Generator, world=WorldServer{Name=world, DimensionId=0, DimensionType=minecraft:overworld}, pos=BlockPos{x=4866, y=59, z=-20747}, blockMetadata=-1} @ BlockPos{x=4866, y=59, z=-20747} told us it had net.minecraftforge.energy.IEnergyStorage cap but returned null
```

![image](https://user-images.githubusercontent.com/1056270/70383097-fa4a9200-195f-11ea-8f3c-fff55f7da80b.png)

**Comment by marcus8448** [comment] 2019-12-08 17:09
Dupe of #3830. Should be fixed in (the upcoming build) 239.

**Comment by radfast** [comment] 2019-12-15 15:13
as marcus8448 said.  :)

Unfortunately build 239 is a bit delayed.  This is due to a problem on the build server which I am not able to fix, micdoodle8 is aware.

**Closed by radfast** 2019-12-15 15:13 UTC
