### ISSUE TITLE
[1.10.2] Vacuum glass render in inventory

### ISSUE THREAD

**Issue by themechman** [micdoodle8/Galacticraft#2639] opened 2017-04-25 01:34 UTC
I am using JEI and am having problems viewing vacuum glass. Pressing "R" to view the recipe shows how to make it, but it does not show the block (Just a blank spot). Tooltip shows you the block.
![2017-04-24_21 33 25](https://cloud.githubusercontent.com/assets/2990361/25365287/ad598806-2935-11e7-8999-cc1911a5a0a3.png)

When in hand, you can see the double glass, but not the border.

**Comment by radfast** [comment] 2017-04-25 03:29
hmm, yes I can't see it in my inventory in 1.10.2 or 1.11.2

This is what it's supposed to look like, currently - screenshot from 1.8.9 version.  Some bug is making it drawn with way too much alpha channel in 1.10+

![glass](https://cloud.githubusercontent.com/assets/6842258/25367724/777b9672-296f-11e7-9b66-73163b503c68.jpg)

It isn't currently intended to have a border / frame when it's in your hand or in the inventory, though I guess we should change that.

**Comment by radfast** [comment] 2017-04-25 03:31
This is kind of a duplicate of #2564 but the issue now has a different cause, and it's specific to versions 1.10+.

**Comment by micdoodle8** [comment] 2017-05-15 21:08
Fixed in the next build. Thanks for the report!

**Closed by micdoodle8** 2017-05-15 21:08 UTC
Labels: rendering
