### ISSUE TITLE
Crash when launching

### ISSUE THREAD

**Issue by casnix** [micdoodle8/Galacticraft#2022] opened 2016-01-15 19:36 UTC
I saw the other issue tickets with the same issue except that the output in my crash report is entirely different. They aren't very specific to my untrained eyes either (I do dirty system development, absolutely no experience with Java and the environment).

Anyway, here's the crash report:
http://pastebin.com/ijrmgNKz

Using Galacticraft 3.0.12.375

**Comment by casnix** [comment] 2016-01-15 19:52
It crashes with GalaxySpace items, so maybe this doesn't belong here

**Comment by radfast** [comment] 2016-01-15 20:13
That will be a tough crash report to troubleshoot.  The stacktrace is not pointing to any mod.  It seems to be vanilla Minecraft is crashing.

Certainly there is nothing to show that Galacticraft is the cause.  What is your reason for posting in this issues list?

The only possible way to troubleshoot this one will be to remove mods, plugins, addons etc from your Minecraft setup until the crash stops happening.  To speed up that process you can use a binary search approach and remove a bunch of things together.  **Bear in mind that if you remove a mod from a server and restart the server, Forge will automatically destroy blocks and items in the world (and in the inventory and Ender Chest of any logged in player) which belong to the mod you removed.**  So use a **test world** for this.

I'm closing this because it doesn't look anything to do with us.  I can re-open it if you can:
1.  show me some evidence it is Galacticraft causing this (or an interaction between Galacticraft and a specified other component, we will also happily troubleshoot that)
2.  confirm the issue still happens with the latest Galacticraft
3.  give steps so I can reproduce this.

As you are a system development guy, you should not be surprised at this response :)

**Closed by radfast** 2016-01-15 20:13 UTC
