### ISSUE TITLE
OxygenHooks crash on dedicated server

### ISSUE THREAD

**Issue by spamenigma** [micdoodle8/Galacticraft#1979] opened 2015-12-24 14:15 UTC
Since updating RotaryCraft I'm getting 'server only' crashing issues which I'm being told most likely is a galacticraft issue. 

https://github.com/micdoodle8/Galacticraft-API/issues/4

If this could be looked into that would be great as I'm stuck! Thanks

**Comment by xKillerbees** [comment] 2015-12-25 03:18
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/501

**Comment by Patman0021** [comment] 2015-12-27 19:56
and 502... and the original.. 484

**Comment by radfast** [comment] 2016-01-03 02:13
This is a duplicate of issue #1990 - or more accurately, #1990 is a duplicate of this!

Thank you for reporting.

This is fixed in the latest Galacticraft build number 407  (or any later build)  - you only need to update to build 407 on servers, clients do not need to update.

**Closed by radfast** 2016-01-03 02:13 UTC
