### ISSUE TITLE
Oil acting as a air block. 1.12

### ISSUE THREAD

**Issue by Mrkuff** [micdoodle8/Galacticraft#3140] opened 2018-01-31 13:13 UTC
Minecraft version: 1.12.2
Galacticraft version: 1.12.2-4.0.1.128
Forge version: 1.12.2-14.23.1.2555 (recommended version)
Java : 1.8.0_161 (latest)
Single player (SSP)

Mods Installed :
GalacticraftCore-1.12.2-4.0.1.128
Galacticraft-Planets-1.12.2-4.0.1.128
MicdoodleCore-1.12.2-4.0.1.128

I've found the [#2620](https://github.com/micdoodle8/Galacticraft/issues/2620) who was closed for version 1.10.2  I don't know if those behaviors are intended or if this was corrected in version 1.10.2 but the oil block act as a air block for a few proprieties for 1.12.2.  I've drop inside a "Oil pocket" while mining, and I've took fall damage, got a clear vision while inside of the room, I can run with double click inside that room and there's no "underwater" breathing meter.  
![2018-01-31_08 01 45](https://user-images.githubusercontent.com/15654765/35624566-5a413e38-065d-11e8-9dad-29a65a79aaa6.png)

For other purpose like flowing (2 blocks wide) and be "bucketable" (a new word!), it's alright.
![2018-01-31_08 00 53](https://user-images.githubusercontent.com/15654765/35624565-5a257d06-065d-11e8-889b-767418c136cc.png)

Edit: I've try to put a torch inside the room, and this didn't work. (as expected for a liquid room).

**Comment by radfast** [comment] 2018-01-31 14:46
Duplicate of #1623 and #2620.  Thank you for the images.

I will close this now, it will automatically be referenced in #1623 and #2620.   As discussed there, I'm aware this is an issue but it is not high priority.  It needs a fix across all Galacticraft 4 versions.

Ideally we want to add:
* breathing effects (should be a problem!)
* visibility effects (should be dark)
* moving effects (should be slow)
* building effects (should be slow, and not affected by Aqua Affinity enchantment)
* possibly, a poison effect

Not **too** severe as we want players to have a chance to survive if they get out of the oil quickly.

**Closed** 2018-01-31 14:47 UTC
Labels: duplicate

**Comment by radfast** [comment] 2018-02-11 03:22
Build 133 is now available from the download site with a fix for some of this.

Also has a really nice new feature: **Hydraulic Platform**
