### ISSUE TITLE
1.11.2: Various Sponge Compatibility Issues

### ISSUE THREAD

**Issue by hugeblank** [micdoodle8/Galacticraft#2953] opened 2017-08-18 23:59 UTC
Minecraft version: 1.11.2
Galacticraft version: 116
Forge version: 13.20.1.2393

Single player (SSP) or Multiplayer (SMP)?
SMP
Galacticraft add-ons and other mods installed?
Yep, an entire modpack. Can be found [here](https://www.kaos-network.com/servers/sonarx )

I'm doing beta testing on my server, and I have the users reporting all issues to me. There's 3 that have me really concerned, and I'm convinced it has something to do with sponge and your mod being incompatible with each other. 

1. Rockets get duplicated when the player goes from dimension to dimension. The player reported having 6 duplicated rockets just because they won't get removed. 
2. Players lose items in the galacticraft tab of their inventory _even though_ keep inventory is on.
3. When making a space station around the overworld, the server crashes, and the player loses all their items. (Yes there's a log for this, I will add it when I can get to my computer [on mobile])

Hopefully these will be of use for you! Of course I'll provide additional information if you need it. I plan on linking this issue and contacting sponge devs, and some plugin devs (that may be responsible for issue) as well, so if any of these are out of your control just mention it :P

**Comment by radfast** [comment] 2017-08-19 18:06
First up, none of these issues occurs in our testing with Galacticraft on a 1.11.2 Sponge server using the version we recommend.  (Obviously we would not ship the mod with basic issues like you describe.)  So we're going to need you to work with us to figure out what is different about your setup.

Which Sponge version are you running?

Seems like you did not read and apply our [documentation for Sponge](https://wiki.micdoodle8.com/wiki/Sponge) if you are using Forge .2393.

Please test whether the issues still occur when using the version of Sponge we recommend.

Item 1 may be a duplicate of #2902.
Item 2 may be a duplicate of #2233 (but seems unlikely, that's a different Minecraft version)
Item 3 needs a crash report or log to take it any further.

We may ask you to open separate issues for some of these later, but first I want to know if they are caused by us or by Sponge.  Which depends on whether they still occur with the recommended Sponge...

**Comment by hugeblank** [comment] 2017-08-19 23:49
@radfast 

Yeah, I didn't read, apply or even see the documentation for sponge, considering near all mods don't have issues with sponge, but now that it has been brought up, I'll downgrade. 

Item 1: Yes, is similar to #2902. Here is a quote from the user that it occurred to: 
```yeah, the problem is when i place the rocket on the launch pad it is still in my inventory. When i break the rocket it doesn't give me another rocket back, so thats good, but when i get into space it gives me fuel, the launch pad, and an extra rocket```
Item 2: Well, it probably is a _partial_ duplicate of #2233 in that the user there was using thermos, another server plugin modifier. In my case, I am using a plugin that changes gamerule slightly. What I'll test is using the default `minecraft:gamerule`, and see if that has any effect on the issue.
Item 3: For some reason (can't remember why), I cleared the crash log folder. Because of that, I requested the user to repeat what they did, and they were able to create the space station this time around... but a new issue occurred: They weren't able to interact with any of the blocks. Now I'm not going to off the bat blame this on galacticraft because this sounds like something that one of the plugins I am using would cause. 

I'll be testing all of this with the suggested version of sponge. I would really recommend putting that sponge documentation in a warning before downloading, as I had no idea, and would never had assumed that this mod doesn't work with any version of sponge.

**Comment by hugeblank** [comment] 2017-08-20 00:46
I can't get the server to start using the recommended sponge and forge versions.
Here's 2 issues:
1. the forge version required by sponge is .2227, the one you recommend is .2228.
2. Sponge gives an error that looks something like this: 
```
*/
[01:40:34] [main/INFO] [Sponge]: /* A critical error was encountered while blending Sponge with Forge!                                                                                        */
[01:40:34] [main/INFO] [Sponge]: /*                                                                                                                                                           */
[01:40:34] [main/INFO] [Sponge]: /*   Possible causes are:                                                                                                                                    */
[01:40:34] [main/INFO] [Sponge]: /*                                                                                                                                                           */
[01:40:34] [main/INFO] [Sponge]: /*    * An incompatible Forge "core mod" is present. Try removing other mods to                                                                              */
[01:40:34] [main/INFO] [Sponge]: /*      see if the problem goes away.                                                                                                                        */
[01:40:34] [main/INFO] [Sponge]: /*                                                                                                                                                           */
[01:40:34] [main/INFO] [Sponge]: /*    * You are using the wrong version of Minecraft Forge. You must use the                                                                                 */
[01:40:34] [main/INFO] [Sponge]: /*      correct version of Forge when running Sponge, this version is for                                                                                    */
[01:40:34] [main/INFO] [Sponge]: /*      13.20.0.2227 (you are running 13.20.0.2227)                                                                                                          */
[01:40:34] [main/INFO] [Sponge]: /*                                                                                                                                                           */
[01:40:34] [main/INFO] [Sponge]: /*    * An error exists in Sponge itself. Ensure you are running the latest version                                                                          */
[01:40:34] [main/INFO] [Sponge]: /*      of Sponge.                                                                                                                                           */
[01:40:34] [main/INFO] [Sponge]: /*                                                                                                                                                           */
[01:40:34] [main/INFO] [Sponge]: /*    * Gremlins are invading your computer. Did you feed a Mogwai after midnight?                                                                           */
[01:40:34] [main/INFO] [Sponge]: /*                                                                                                                                                           */
[01:40:34] [main/INFO] [Sponge]: /*-----------------------------------------------------------------------------------------------------------------------------------------------------------*/
[01:40:34] [main/INFO] [Sponge]: /*                                                                                                                                                           */
[01:40:34] [main/INFO] [Sponge]: /* Technical details:                                                                                                                                        */
[01:40:34] [main/INFO] [Sponge]: /*                                                                                                                                                           */
[01:40:34] [main/INFO] [Sponge]: /*      Failed on class : net.minecraft.world.World                                                                                                          */
[01:40:34] [main/INFO] [Sponge]: /*         During phase : DEFAULT                                                                                                                            */
[01:40:34] [main/INFO] [Sponge]: /*                Mixin : world.MixinWorld                                                                                                                   */
[01:40:34] [main/INFO] [Sponge]: /*               Config : mixins.forge.core.json                                                                                                             */
[01:40:34] [main/INFO] [Sponge]: /*           Error Type : org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException                                                           */
[01:40:34] [main/INFO] [Sponge]: /*            Caused by : Unknown                                                                                                                            */
[01:40:34] [main/INFO] [Sponge]: /*              Message : PRIVATE @Overwrite method func_175638_a in mixins.forge.core.json:world.MixinWorld cannot reduce visibiliy of PUBLIC target method */
[01:40:34] [main/INFO] [Sponge]: /*                                                                                                                                                           */
[01:40:34] [main/INFO] [Sponge]: /*************************************************************************************************************************************************************/
```

I'll do a little bit more testing, but as it stands, sponge is rejecting anything I do in attempt to fix.

**Comment by hugeblank** [comment] 2017-08-20 05:31
Results: 

forge 13.20.0.2310 (The latest sponge version that functions with the sponge version that you recommended)
sponge 2227-6.0.0-BETA-2244

Issue 1: still exists
Issue 2: still exists
Issue 3: Because I'm using an old sponge version, the plugin I use to prevent grief does not function. Because that is gone, _technically_ this issue is resolved, but now I don't have a grief prevention plugin...

**Comment by TheQuadShot** [comment] 2017-08-20 22:54
@hugeblank I've never run a sponge client/server and have a few questions to ask if you don't mind. I've asked other people why they run sponge and the only answer I get is "there are some good plug-in's" but they don't really tell me exactly what/why, and I've not seen any that aren't available from Forge based Mods. I have used FTB Utils which has your grieving problem covered. So I guess my question would be: What does Sponge do that I can't do with FTB Utils and a few other mods? 
Thanks in advance!

**Comment by hugeblank** [comment] 2017-08-21 01:50
@TheQuadShot I haven't had much experience with FTB Utils, and that little bit of experience I _DID_ have wasn't very good. Here's just a few benefits of plugins over FTButils, just on the server I use:
- The user doesn't have to clutter up their mods directory with more than necessary
- permissions are much more in-depth, and you can easily modify what a user can and can't do
- FTBUtils is chunk based. Most protection plugins are block based, allowing you to precisely pick where your boundaries are.
- player based economy that is unified across the server platform.
- Dimension creation and modification to allow for things like plot worlds, and hub worlds. 
- [nucleus](https://nucleuspowered.org/index.html).
The answer to your question is ridiculously general in that there are a lot of answers to it. I'm pretty sure just looking through [here](https://forums.spongepowered.org/c/plugins/plugin-releases) can give you a good idea why sponge is better.

**Comment by radfast** [comment] 2017-08-21 02:45
The CauseTracker issue is a complex bug in Sponge, it's not an issue caused by or specifically connected with Galacticraft.  It's an issue whenever a player **changes dimension**.  Obviously, in Galacticraft, players change dimension a lot.  The dimensions are kind of the point of Galacticraft.


CoFH and other mods don't have different dimensions, so they don't have this issue with the recent Sponge / CauseTracker.  But if affects Galacticraft.  And any other mod with dimensions.

We cannot fix it.  We have reported it to Sponge devs and they have said they will prioritise it, but they didn't fix it yet (so I'm not too sure what prioritise means there).

Meanwhile, we recommend you use the older Sponge.  There must be versions of your other mods which work with the older Sponge, because those other mods existed in March 2017.  It's up to you to figure out which versions you need.

We are happy to fix any **reproducable** issue in the Galacticraft mod.  Most of the issues you / your players are describing are, by the sound of it, **likely** caused by the Sponge issue but I can't be sure, without you testing it.  Could also be interaction with one of your other mods / plugins, but I suggest start with the most likely cause i.e. Sponge version.

----

@TheQuadShot   setting up a Forge server with plugins working stable is a complex, multi-week task.  Once server owners find plugins and configs which work for them, they generally don't want to change that at all.  Running a big multi-player server is way more complicated than a LAN server ... you have to check player activities, players may have different status / ranks etc, some players deliberately try to break the rules and grief, then there's a server economy with in-game money and shops etc.  Also chat filters and so on.  Although there are maybe now Forge mods which cover some of these tasks, the plugins are more mature code and better supported by the server community.

**Comment by hugeblank** [comment] 2017-08-21 03:43
@radfast Hm... that's a pain in the rear. Can you offer a link to the causetracker issue report?

As for reproducable issues: I'll try the pack without sponge, but I doubt that will fix anything, as I backported to the version of sponge without causetracker, and the main issues I am having still persisted ; rocket duplication, and galacticraft inventory loss. I'll post results in a little bit.

**Comment by TheQuadShot** [comment] 2017-08-21 03:56
Thanks guy's! I've only run servers for my kids, and grand-kids and a few friends they invite(30ish users). So I've never run a "public" server and can see the reasons why now.
Thanks Again!

**Comment by hugeblank** [comment] 2017-08-21 04:25
Found issue 1 on the [spongeforge issue tracker](https://github.com/SpongePowered/SpongeForge/issues/1591). Maybe if you would, insert your input? 

And [here ](https://github.com/SpongePowered/SpongeForge/issues/1742) is the issue report I made for issue 2.

**Comment by radfast** [comment] 2017-08-21 17:26
Please do not open issue reports unnecessarily, especially not on Sponge, they have enough to do.

The 3 issues you're describing are - I believe - all 3 different "symptoms" of the same root problem.  The root problem is [reported 2 months ago](https://github.com/SpongePowered/SpongeForge/issues/1552) like I already told you.

The solution I recommend is to use the version of Sponge we recommend - which works perfecly fine and is stable - and if you have plugins or other Forge mods which need a more recent Sponge, just roll back to an earlier version which works with the older Sponge.  Versions from around March / April 2017 should be good.  Personally I think it's bad practice to hard-code a Forge mod to require a more recent Sponge version.

I'm closing this for now, as you said all 3 issues are fixed.

If you still have issues using Galacticraft **with the version of Sponge we recommend** please comment or re-open.

**Closed by radfast** 2017-08-21 17:26 UTC
Labels: cant reproduce, missing info

**Comment by radfast** [comment] 2017-08-21 22:12
UPDATE:

Please try the very **latest** Sponge that's version 1.11.2-2393-6.1.0-BETA-2592.  That looks to have fixed the main issue I was talking about here.

Item 1, the "rocket dupe" issue, is also fixed from next Galacticraft build 117 **if** that was an issue with Tier 1 Rockets only.

Any remaining issues please comment or re-open.

**Comment by hugeblank** [comment] 2017-08-22 15:56
:D @radfast Thank you sir! you're the man!
