### ISSUE TITLE
Infinite cycle crash 

### ISSUE THREAD

**Issue by butich** [micdoodle8/Galacticraft#3711] opened 2019-06-30 19:36 UTC
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 4.0.2.211

LAN

Game is running into infinite cycle and then crashing when Hekx is connecting.
[latest.log](https://github.com/micdoodle8/Galacticraft/files/3343267/latest.log)

**Comment by marcus8448** [comment] 2019-07-02 04:35
Try running minecraft through the vanilla launcher, *not* through tlauncher.

**Comment by radfast** [comment] 2019-08-29 21:15
Looking in detail at the crash report, this doesn't look like an infinite loop, as the game code (actually vanilla Minecraft `world.setBlockToAir()` and notifying neighbors) is not going over and over through the same block.  Instead, it is running through a large number of **differently** located blocks - each one is neighbor to the last one.  See also all the "block being updated" messages giving the co-ordinates of the blocks being updated.

It's likely what has happened here is a common block in the world, like Plain Stone, has had its ID swapped with a Galacticraft torch block (in fact, here it's a **Stone Torch**, i.e. the type of unlit torch we include for TConstruct compatibility).   When the world is loaded, there are therefore thousands and thousands of torch blocks, all unsupported by walls.  The game code is cycling through these torch blocks, dropping them all.  It's not an _infinite_ cycle, just very large.

The fundamental problem here is the block ID change.  The log is telling that it is ID 592.

The most likely cause of a block ID change is that there were substantial changes to the mods list, in an existing world.  That's never a good idea.

We are not going to be able to reproduce this problem, because it's a block ID change.  I think we have to mark this as unsolvable, and close it.

**Closed by radfast** 2019-08-29 21:15 UTC
