### ISSUE TITLE
Crashes when last item is inserted into Nasa Workbench build 79

### ISSUE THREAD

**Issue by jjjworley** [micdoodle8/Galacticraft#2672] opened 2017-05-03 01:23 UTC
With build 76 the rocket would not build (you don't need schematic for tier 1 rocket, do you?)

Build 79 will crash when inserting the last item into Nasa Workbencch to build tier 1 rocket.
[crash-2017-05-02_20.00.01-server.txt](https://github.com/micdoodle8/Galacticraft/files/972294/crash-2017-05-02_20.00.01-server.txt)
[crash-2017-05-02_20.09.12-client.txt](https://github.com/micdoodle8/Galacticraft/files/972298/crash-2017-05-02_20.09.12-client.txt)

P.S. Don't know if it matters, but I was shift clicking the items into the workbench.

Edit: Tested and still crashes when inserting items by hand.

**Comment by radfast** [comment] 2017-05-03 02:32
Thank you for beta testing.  No, you don't need a Schematic for Tier 1 Rocket!!

This will be fixed in next build 80.

Please do report any similar crashes to us, there could be a few like this left in 1.11.2.  You're probably the first person to try crafting a rocket in the NASA Workbench in 1.11.2.

**Comment by radfast** [comment] 2017-05-03 04:31
[Build 80](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/) now available

**Closed by radfast** 2017-05-03 04:31 UTC

**Comment by jjjworley** [comment] 2017-05-03 07:01
Wow! You are really fast! It's working as intended. I've placed the rocket on the pad with no problems.

But this reminds me of an issue I've always had with Galacticraft. I don't know if it's intended or not, but it really bugs me. When coming out of the rocket, you are left in third person and you have to hit f5 to get back to first person. Not a problem, just an annoyance. 

Next task, see if the rocket will take on fuel.

**Comment by radfast** [comment] 2017-05-03 13:24
* Fuel loader visual connection to launch pad, is a known issue, see #2480 (F).

* You don't need to delete the config.   If we add something new to the config, Galacticraft will auto-add it to your existing config with a default setting.  If we stop using something in the config, Galacticraft will just ignore that line.   Having said that, it **is** a good idea to delete your config when making major version updates like from Galacticraft 3 to Galacticraft 4, just for tidiness.  Though there are some people (probably including me!) who still have the same config from Galacticraft 1 and Galacticraft 2 days without any actual problems.

* The staying in third person view when you come out of a rocket is intended behaviour, otherwise if you hit right-click to exit and right-click to re-mount the rocket, several times quickly, you will have a lot of view changes and it can even make people nauseous (if they're using 3d glasses or other immersive setups).  There is a config option to switch off the third person / zoomed view completely, I think.

----

> Next task, see if the rocket will take on fuel.

Please do report any issues you find, however small!  If in doubt whether it is reported already, I'd rather you report it than not.

We very much appreciate testing of 1.11.2 by experienced Galacticraft players who know how things should work.  There may be more issues hiding in there like the NASA Workbench crash you posted.  Basically, 1.8.9 and 1.10.2 and 1.11.2 are all the same and should now be stable.  But 1.11.2 still has these potential issues which the other versions don't have.  The issues are hard to find without playing through the whole mod in survival mode using every possible machine and I don't have time to do it :(
