### ISSUE TITLE
The regular season

### ISSUE THREAD

**Issue by denwd** [micdoodle8/Galacticraft#1673] opened 2015-05-28 19:11 UTC
# Enter IDs of other mods' ores here for Galacticraft to generate them on the Moon and other planets. Format is BlockName or BlockName:metadata. Use opti
onal parameters at end of each line: /RARE /UNCOMMON or /COMMON for rarity in a chunk; /DEEP /SHALLOW or /BOTH for height; /SINGLE /STANDARD or /LARGE for cl
ump size; /XTRARANDOM for ores sometimes there sometimes not at all.  /ONLYMOON or /ONLYMARS if wanted on one planet only.  If nothing specified, defaults ar
e /COMMON, /BOTH and /STANDARD.  Repeat lines to generate a huge quantity of ores.
    S:"Other mods ores for GC to generate on the Moon and planets" <
    ProjRed|Exploration:projectred.exploration.ore:0 /BOTH /ONLYMARS
    ProjRed|Exploration:projectred.exploration.ore:1 /BOTH /ONLYMARS
    ProjRed|Exploration:projectred.exploration.ore:2 /BOTH /ONLYMARS
     >

![2015-05-29_00 10 53](https://cloud.githubusercontent.com/assets/3863970/7868691/e183a0fc-058e-11e5-8996-c8a2f84cde6c.png)

no work((

**Comment by denwd** [comment] 2015-05-30 17:26
You are not in fashion not supported by the | character in the regular season

**Comment by radfast** [comment] 2015-05-31 00:21
Duplicate of #1670.

I still cannot understand you.

Maybe write in your language and I can find a way to translate it to English better?

Also please __post your complete fml-client-latest.log__.

**Closed by radfast** 2015-05-31 00:21 UTC

**Comment by denwd** [comment] 2015-05-31 04:38
Добрый день, я хочу сделать ресурсы из Project Red на марсе
но при вводе в конфиг ProjRed|Exploration:projectred.exploration.ore:2 /BOTH /ONLYMARS
ресурсы там не сгенерировались.
Я думаю либо это из за меты либо из за | знака в регулярке.

**Comment by Alaberti** [comment] 2015-05-31 08:47
Aaaah, I think I understand the issue.@denwd is saying that the meta for the ores in ProjectRED includes a pip (|) which does not appear to parse correctly when trying to assign ores to spawn.

**Comment by denwd** [comment] 2015-05-31 09:45
Yes )))

**Comment by radfast** [comment] 2015-05-31 22:40
OK, thanks guys, I understand now.  I will find a fix.

Comments in Russian are always welcome.  We have plenty of Russian-speaking players who can help.  And Russia was the first country in space :)

**Comment by denwd** [comment] 2015-06-01 14:25
thanks))
