### ISSUE TITLE
(EXTRA SOLAR SYSTEMS) Bugs List

### ISSUE THREAD

**Issue by mattparks** [micdoodle8/Galacticraft#1651] opened 2015-05-17 21:51 UTC
I have been creating a addon that adds a solar system with 4 planets, each planet has a moon or two, but in making this addon I have found some galacticraft bugs.

1. You cannot click to focus on any celestial body outside of the default solar system in map (ANY OBJECT).
2. You cannot add moons to any planet outside of the default solar system.
3. Side map's Catalog does not recognize any other star systems. 
4. When manually zooming into a star system at a certain distance everything disappears.

**Comment by radfast** [comment] 2015-05-17 22:51
@mattparks you should know better than to post an issue like this.
* Did you do a search?  Some of the issues described sound like issues which have been recently closed.
* Number 2 seems like a duplicate of #1617
* Some of these issues could be in your Add On not in Galacticraft - have you confirmed they are issues present in other released Add Ons?
* You have not stated which GC version
* In any event, it is impossible for me to test or reproduce these issues without an Add On to test with.
* I dislike multiple issues being combined in one issue report

Please be more sensible in future.

**Closed by radfast** 2015-05-17 22:51 UTC

**Comment by mattparks** [comment] 2015-05-18 00:37
Sorry I was in a bit of a rush before, I'm using 1.7-3.0.12.338, and these issues have been plaguing me and my friend who are making two separate addons that add solar systems. I'm using my addon 4Space ( http://4space.mods.center ) version 4.1.6. I still face the bugs in witch I cannot zoom into any of my other solar systems planets or star, and moons do not show up orbiting or on the list. It would be nice if addon star systems showed up in the left side bar along with the planets.

**Comment by mattparks** [comment] 2015-05-18 01:50
@radfast I made a video of my bugs, with annotations. https://www.youtube.com/watch?v=imTwX_CX9JU

**Comment by radfast** [comment] 2015-05-18 10:30
Before I can get interested in this:

> have you confirmed they are issues present in other released Add Ons?

**Comment by mattparks** [comment] 2015-05-18 11:05
@radfast yes as I had said my friend who is currently creating a addon has this bug, he has not released it though, three or four months ago another one of my friends tried making a system and faced these issues. I am positively certain it's a galacticraft problem.

**Comment by radfast** [comment] 2015-05-18 11:57
@mattparks you seem to have missed an important word in what I wrote:
>  have you confirmed they are issues present in other __released__ Add Ons?

By "released" Add Ons I mean __More Planets__ by @SteveKunG, __Galaxy Space__ by @BlesseNtumble, and maybe now __Extra Planets__ by @MJRLegends.

**Comment by mattparks** [comment] 2015-05-18 12:21
@radfast I've been talking with the More Planets addons creator for some time he has no extra star systems I do not believe Galaxycraft has extra star systems. Though if 3 addons have this issue it's eather a code bug or something that needs documentation.
