### ISSUE TITLE
Some chunks in GC dimensions stay permanently loaded when not intended

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#1978] opened 2015-12-24 07:36 UTC
The mod keeps executing and printing "Oxygen Sealer Check", every tic, for every sealer of every dimension. You can be in a dimension where there isn't a sealer, still the mod will check every sealer of every dimension.

```
[04:38:12] [Server thread/INFO] [Galacticraft]: Oxygen Sealer Check Completed at x-332 y74 z240
[04:38:12] [Server thread/INFO] [Galacticraft]:    Sealed: false
[04:38:12] [Server thread/INFO] [Galacticraft]:    Loop Time taken: 0.003011ms
[04:38:12] [Server thread/INFO] [Galacticraft]:    Place Time taken: 0.014456ms
[04:38:12] [Server thread/INFO] [Galacticraft]:    Total Time taken: 0.017467ms
[04:38:12] [Server thread/INFO] [Galacticraft]:    Found: 1 sealers
[04:38:12] [Server thread/INFO] [Galacticraft]:    Looped through: 1 blocks
```
Log: https://gist.github.com/EzerArch/1fae61e0458602d30b07

if this is intended, how to disable this logging?

**Comment by dj3520** [comment] 2015-12-25 04:00
Is debug mode on in the config?

**Comment by EzerArch** [comment] 2015-12-25 06:59
@dj3520 thank you! Mic had asked me to enable that to test the sealers way in the past. Forgot completely.

**Comment by dj3520** [comment] 2015-12-25 07:05
No problem. Glad to help.

**Comment by radfast** [comment] 2016-01-06 01:46
@EzerArch Minor issue, but I'm wondering why it is checking more than one dimension, if only one player is online.  Something must be keeping the chunks loaded - do you have Launch Controllers or any other chunk loader present in your bases?

**Comment by EzerArch** [comment] 2016-01-06 02:23
@radfast, I do. But a question: how large is the range of these chunks loaders, namely Launch Controllers? Do they keep loaded only the chunk they are in?

There were so many Oxygen Sealers in the log so I suspect some of them aren't close enough to a chunks loader. I would like to do a proper test.

**Comment by radfast** [comment] 2016-01-06 02:32
Chunk loading is a complex issue.  An active Launch Controller might sometimes load the chunk adjacent to it, for example if there is a power cable running into that chunk.  It also depends on how the server is loaded.  Every tick, the server unloads chunks which were not recently used, if no player is nearby.

**Comment by dj3520** [comment] 2016-01-06 02:41
What happens if I build a rocket pad in the intersection of 4 chunks?

**Comment by radfast** [comment] 2016-01-06 02:46
@dj3520 Goodness, I hope that isn't the cause of the missing cargo rockets problem.  I plan to do some extensive testing, later this week, of chunk loading / active chunk type issues with the Launch Controller and also the Short Range Telepad.

**Comment by dj3520** [comment] 2016-01-06 03:10
I might be able to do some testing myself and report back if you'd be
interested. I have access to a creative copy of my server that I use for
testing many things.

**Comment by radfast** [comment] 2016-01-06 15:36
Yes all testing is helpful.  I especially like specific instructions on how to reproduce an issue (+ screenshots of the build where relevant).  A good issue report helps lead to a fix much more quickly, meaning I have more time to fix other issues or to get back to adding new features to the mod.

**Comment by EzerArch** [comment] 2016-01-06 21:34
Reopening for sake of further testing.

**Comment by radfast** [comment] 2016-01-07 21:34
I don't think this needs to stay open for testing the chunk loading issues.  There are other open issues re: chunk loading for Launch Controller and Short Range Telepad.

The original issue, i.e. log spam, is fixed.  There's nothing wrong with the Oxygen Sealers, the only reason they can be proccing is either because of a chunk loader nearby, or just because the server still did not unload those chunks yet.

**Comment by radfast** [comment] 2016-01-08 17:19
hmmm

More info on Chunk Loading.

I think if a server has **static dimensions** AND 'Force overworld spawn'=false in the GC config, then all of the GC static dimensions will keep some chunks permanently loaded.  The loaded chunks are a 18x18 chunk grid centered on the spawn position in the world, or (0,64,0) if there is no spawn position.

The chunks around the spawn position in the Overworld will also always stay loaded, all the time, that is Minecraft default.

This isn't good.  But I'm looking at whether we can make active use of this to ease some of the problems with rocket transfers between worlds, when there is server/client lag.

**Comment by radfast** [comment] 2016-01-08 17:21
@EzerArch do you have static dimensions + force overworld spawn=false.  (More accurately, *did* you at the time these issues occurred?)

(Or Oxygen Sealers near overworld spawn, although that seems unlikely ...)

**Comment by radfast** [comment] 2016-01-08 17:22
This also could explain why I have in the past not been able to reproduce some of the problems connected with Launch Controllers / Short Range Telepads, because mostly I test things in a newly generated world and obviously I am close to Overworld spawn in those tests!

**Comment by radfast** [comment] 2016-01-09 02:41
This is now fixed by https://github.com/micdoodle8/Galacticraft/commit/53e0f92e642f7378e42c980b61d4d1f0bf50d296 - please look for this improvement in build 411

**Closed by radfast** 2016-01-09 02:41 UTC
