### ISSUE TITLE
[1.11.2] Astro Miner does not want to be docked + Another Issue

### ISSUE THREAD

**Issue by ThomasAunvik** [micdoodle8/Galacticraft#2595] opened 2017-04-15 20:52 UTC
A Stack of Build (64)

I have made the docking system (a 2x2x2 frame w/Astro Miner Base) and i tried shift right click it with an Astro Miner (Item)

Exception Thrown:
```
Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.minecraft.util.Util.func_181617_a(SourceFile:47)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at java.util.Collections.copy(Collections.java:555)
	at micdoodle8.mods.galacticraft.planets.asteroids.entities.EntityAstroMiner.<init>(EntityAstroMiner.java:201)
	at micdoodle8.mods.galacticraft.planets.asteroids.entities.EntityAstroMiner.spawnMinerAtBase(EntityAstroMiner.java:1955)
	at micdoodle8.mods.galacticraft.planets.asteroids.tile.TileEntityMinerBase.spawnMiner(TileEntityMinerBase.java:247)
	at micdoodle8.mods.galacticraft.planets.asteroids.items.ItemAstroMiner.func_180614_a(ItemAstroMiner.java:119)
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:823)
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:165)
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:479)
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:685)
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55)
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11)
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.minecraft.util.Util.func_181617_a(SourceFile:46)
	... 5 more
```

Including this issue another bug follows.
Breaking one block off the base will not stop rendering of the base. Breaking some even more blocks the rendering disappears and the blocks will turn invisible.

You can see both of the bugs happening here:
https://youtu.be/nezsJZkA2H0

**Comment by radfast** [comment] 2017-05-01 21:18
Thank you for reporting this, andthanks for the video.

The exception thrown on placement is fixed in next build 79.

The glitches in the dock blocks on placing, I can't reproduce in build 78 - thanks for that video!   It's possible this issue has been fixed already.

If you see it happening in build 79, please let us know!

**Closed by radfast** 2017-05-01 21:18 UTC

**Comment by radfast** [comment] 2017-05-01 21:20
Hmm that's weird, the [commit](https://github.com/micdoodle8/Galacticraft/commit/98df7ca6dad47d76f10c10ed35e2514af4921bae) which should have fixed the Miner Dock block breaking issue was already included in build 64 that gave rise to this issue.

**Comment by radfast** [comment] 2017-05-01 21:47
[Build 79](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/#post-43421) now available
