### ISSUE TITLE
Problems with Astro Miner Base

### ISSUE THREAD

**Issue by Romsik788** [micdoodle8/Galacticraft#3082] opened 2018-01-07 18:51 UTC
Minecraft version:1.11.2
Galacticraft version:4.0.1.120
Forge version:1.11.2-13.20.1.2579

Single player (SSP) or Multiplayer (SMP)? SSP

Galacticraft add-ons and other mods installed?
NEI
scenter
voxelmap
Please provide screenshots / crash report / log as needed.
![2018-01-07_20 29 07](https://user-images.githubusercontent.com/33905242/34652730-cd2b790c-f3ea-11e7-9504-32e5638aead3.png)
![2018-01-07_20 29 42](https://user-images.githubusercontent.com/33905242/34652731-ce72d72e-f3ea-11e7-80c1-f348ce134ae8.png)

1.The battery (infinite) inserted into the battery slot in the Astro Miner Base is incorrectly displayed.
2.When stripped off by Astro Miner, it does not disappear in the Astro Miner Base.

**Comment by radfast** [comment] 2018-01-08 00:15
1 is a duplicate of #2985 

Please explain 2 some more - please give more screenshots from different angles.

**Comment by Romsik788** [comment] 2018-01-08 08:36
2.When Astro Miner is traveling then if you look at the Astro Miner Base then there is another Astro Miner (although it can not be controlled)
![2018-01-08_10 14 07](https://user-images.githubusercontent.com/33905242/34663325-ff944422-f45e-11e7-9509-2225decc1fdb.png)
![2018-01-08_10 14 12](https://user-images.githubusercontent.com/33905242/34663326-002cc68e-f45f-11e7-82e9-eaf73ef785ef.png)
![2018-01-08_10 14 39](https://user-images.githubusercontent.com/33905242/34663328-00d5335a-f45f-11e7-8569-ceda5b5beb38.png)
![2018-01-08_10 14 44](https://user-images.githubusercontent.com/33905242/34663334-04d67072-f45f-11e7-8f1a-04ff30ebf919.png)

**Comment by MJRLegends** [comment] 2018-01-27 06:33
Fixed by commit 9724864c110ccd7c4aaceee883035632956ba86e needs closing

**Comment by radfast** [comment] 2018-01-28 14:08
OK, I can reproduce this issue **in Creative Mode** by clicking twice on the AstroMiner base with the same AstroMiner.

A chat message is seen "A second Astro Miner was detected at the same base, the first will now freeze".

If this happens, you can fix the problem simply by hitting the (stationary) Astro Miner until it breaks.

**Comment by radfast** [comment] 2018-04-02 18:51
I can't any longer reproduce the issue in latest 1.11.2 after a lot more testing.  It may be one of our recent updates has fixed this.

Closing now.  Any more problems, please comment or re-open with **exact** steps to reproduce the issue.

**Closed by radfast** 2018-04-02 18:51 UTC
Labels: 1.8+
