### ISSUE TITLE
[1.11.2] [WAILA] Crash after placing large solar panel

### ISSUE THREAD

**Issue by KillerMapper** [micdoodle8/Galacticraft#2500] opened 2017-04-07 07:39 UTC
GC Version: .11.2-4.0.0.53-BETA
Used mods: GC, GCPlanets, MicdoodleCore, Hwyla, JEI

Crash report: https://pastebin.com/63X8GE4q

When placing a big solar panel, the game crashes 1-2 seconds later, telling me that something is wrong with some properties.

When reloading the world, the solar panel is here working and no crash happens.

Edit: after more tests, the crash seems to happen after a bit when reloading the worlds without doing anything else.

**Comment by radfast** [comment] 2017-04-07 09:07
Thanks for beta testing!

This is the same issue as #2498.  It's caused by an interaction between **WAILA** and large (multiblock) structures in Galacticraft.  If you are able to play without WAILA then please try that for now.  We are aiming to have a new BETA version with a fix for this out in the next 1-2 days.

**Comment by micdoodle8** [comment] 2017-04-08 05:57
Thanks, committed. Should be working normally in the next build.

**Closed by micdoodle8** 2017-04-08 05:57 UTC
Labels: 1.10, 1.11, duplicate
