### ISSUE TITLE
[1.11.2] Galacticraft Crash "Ticking Block Entity"

### ISSUE THREAD

**Issue by hugeblank** [micdoodle8/Galacticraft#2995] opened 2017-09-26 03:53 UTC
Minecraft version: 1.11.2
Galacticraft version: 117
Forge version: 13.20.1.2454

Single player (SSP) or Multiplayer (SMP)?
SMP
Galacticraft add-ons and other mods installed?
ExtraPlanets

Please provide screenshots / [crash report](https://github.com/micdoodle8/Galacticraft/files/1331763/crash-2017-09-26_04.34.55-server.txt) <-- / log as needed.

I'm no crash report professional, but what it looks like is going on here is a hopper is being fed into a generator potentially and causing the server to crash. This keeps happening, and because I haven't been able to acces the server until very recently, and it automatically restarts... the [crash-reports directory filled up](https://user-images.githubusercontent.com/16393543/30841891-65cb3e72-a233-11e7-8414-7ee43f1b0619.png)...

Modlist, and other potentially relevant info can be found [here](https://kaos-network.com/servers/sonarx).

**Comment by BrisingrAerowing** [comment] 2017-09-30 16:49
It looks like you are using Sponge. Sponge often breaks things, and most mod authors want a test without it to see if it still happens.

**Comment by radfast** [comment] 2017-10-01 13:38
Hi @hugeblank 

Please can you provide a screenshot of your hopper?  Which Galacticraft machine / generator are you trying to feed from the hopper?  I can't tell which it is, from that crash report...

**Comment by hugeblank** [comment] 2017-10-01 17:37
Hey @radfast I believe it was the electric compressor, however don't hold me to that, it could also have been the circuit fabricator.

**Comment by radfast** [comment] 2017-10-02 20:59
I don't think it can be either of those machines, because their inventories are much larger than 3.

Seems most likely it was an Electric Arc Furnace under your hopper, and this is a manifestation of #2981.  I'm still trying to figure out the root cause of this, maybe a corrupted save as it does not happen in normal testing of the mod.

**Comment by radfast** [comment] 2017-10-02 21:42
Thanks for reporting, this is fixed in next build 118.

**Closed by radfast** 2017-10-02 21:42 UTC
Labels: Priority

**Comment by hugeblank** [comment] 2017-10-03 02:03
Are you sure though, does the electric compressor not have exactly 3 slots?

**Comment by radfast** [comment] 2017-10-07 11:40
Electric compressor has 12 slots.

There was a known issue with the Electric Arc Furnace in build 117, where sometimes (after loading a save) the code thought it had 3 slots like a basic Electric Furnace, instead of the intended 4 slots.

**Comment by hugeblank** [comment] 2017-10-08 05:44
Ahh alright. We’ll thanks for fixing
