### ISSUE TITLE
Lauch Controller From Space Station to Mars Crash

### ISSUE THREAD

**Issue by Simonwp2** [micdoodle8/Galacticraft#2452] opened 2017-03-12 14:49 UTC
As the title says when a launch controller is set to launch a rocket from a Space Station and to a mars. The game crashes.

**Comment by radfast** [comment] 2017-03-12 15:25
Post your full crash report please.

**Comment by radfast** [comment] 2017-03-12 17:45
You fixed it?

**Comment by Simonwp2** [comment] 2017-03-12 18:56
When i set a Launch Controller to send a Rocket to another Launch Controller Station that is located on either a Space Station or Mars and that rocket is player-rideable. I go inside of it and then the Launch controller launches the Rocket to the destination with a player inside of it, and when the loading screen is done after i've launched into the exit-point of the dimension. I see a split second of the destination-point dimension. The game completely crashes.

**Comment by dj3520** [comment] 2017-03-12 20:32
>Post your full crash report please.

**Comment by radfast** [comment] 2017-03-13 02:27
Crash report is in your `.minecraft` folder, `crash-reports`

You'll see the reports are named with their date and time.

Please post the latest report of this problem.  Best way to post it is click on [Gist](https://gist.github.com/) then post the link to that Gist here.

**Comment by radfast** [comment] 2017-03-15 14:40
I've had a [crash](https://github.com/micdoodle8/Galacticraft/issues/2459#issuecomment-286758353) in this situation myself now :)  Assuming it's the same crash, the problem is found and fixed in latest build 3.0.12.478.

**Closed by radfast** 2017-03-15 14:40 UTC
Labels: missing info
