### ISSUE TITLE
Possible NASA Workbench Dupe

### ISSUE THREAD

**Issue by MrHelp** [micdoodle8/Galacticraft#1622] opened 2015-04-29 20:17 UTC
If i open GUI in workbench and my friend will delete this workbech(pickage for example) i will see GUI but not will have workbench.

**Comment by SportsFan10** [comment] 2015-04-30 22:24
So for a dev to help you they are going to need,
1. Your Minecraft Forge Version
2. Your Galacticraft Version
3. Any other mods you are using
4. A very detailed explanation of the bug

**Comment by radfast** [comment] 2015-05-01 01:17
This is a description of a common duping technique that _can_ work with many blocks in Minecraft, or used to work in older versions:
* Player 1 right-clicks the block to open the GUI and keeps it open on his screen
* Player 2 breaks the block so it drops the items it contains (or maybe use TNT or a creeper or a piston instead of Player 2 if you have no friends)
* Player 1 can still take items out of the GUI on his screen after the block was broken.

On most blocks in Galacticraft, the duping is impossible because the GUI auto-closes if the block gets broken.  Vanilla chests are the same.

For blocks which do not hold a permanent inventory (for example, crafting table) it's not really necessary to block the duping, because it only makes "ghost items" - pick them up, or try to put them from your inventory into a chest, and they will disappear.

For this reason, the NASA Workbench GUI in Galacticraft is not set to auto-close.  It's like a Crafting Table, it does not have permanent storage and so I think the duping only makes "ghost items".

If somebody figured out a way to dupe with the NASA workbench something more than "ghost items" then that's a problem which I can easily fix, but some confirmation would be good first.

**Comment by SportsFan10** [comment] 2015-05-01 02:37
I did a little testing for you and it seems like I couldn't dupe the items but I may have done things wrong.

With the help of a creeper, I opened the GUI and quickly placed in a Tier 1 plate after the creeper came over and exploded the GUI did remain open and I was able to pull the item out.  I looked around on the ground and did not find another tier 1 plate so I'm assuming I couldn't dupe it.

GC Version 1.7-3.0.11.324

**Comment by radfast** [comment] 2015-05-01 11:51
Thank you @SportsFan10, much appreciated.  That confirms my testing as well.  Generally, most mods will leave the GUI up if the block works like a crafting table without permanent storage - because the item is not really "in" the block, the item is in your (player inventory + GUI) all the time.  

Still, I am wondering if somebody found a way to dupe here using 2 players or something, so will leave this open for now.

@MrHelp can you help some more, or maybe post screenshots or a short video?

**Comment by SportsFan10** [comment] 2015-05-01 13:32
Later today I eill try and recreate the two player setup on ny server.  With the same version.

**Comment by MrHelp** [comment] 2015-05-01 13:43
Give me a few days pls.

**Comment by radfast** [comment] 2015-05-18 10:38
@MrHelp  can you - or anyone please? - confirm that items are actually being __duplicated__?

Maybe post a video or screenshots?

**Comment by MrHelp** [comment] 2015-05-18 10:43
Sorry my computer is dead. I can't. But plugin MODFIXNG fix this dupe.

**Comment by radfast** [comment] 2015-05-18 10:46
@MrHelp  I want to fix the dupe for everybody, if they have the plugin or not.  A dupe is a problem for the mod.  But first I need to reproduce the dupe...

**Comment by MrHelp** [comment] 2015-05-18 10:52
okay. I will wait for my computer and give you video. Thanks for your answer.

**Comment by micdoodle8** [comment] 2015-07-01 05:25
There seems to be no progress on this issue, and I was unable to recreate any dupe with two clients. Closing, but feel free to re-open if further information on a possible dupe is found.

**Closed by micdoodle8** 2015-07-01 05:25 UTC
Labels: exploit, follow-up please, Priority
