### ISSUE TITLE
No exit button in galaxy map

### ISSUE THREAD

**Issue by MPeti1** [micdoodle8/Galacticraft#3390] opened 2018-05-03 19:29 UTC
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.7.10 (Forge 10.13.4.1614)
Galacticraft version: 3.0.12.504

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP

Galacticraft add-ons and other mods installed?
ABO-MC1.7.10-BC7.1release4.0.9.jar
ae2stuff-0.5.0.56-mc1.7.10.jar
appliedenergistics2-rv2-stable-10.jar
Aroma1997Core-1.7.10-1.0.2.16.jar
AromaBackup-1.7.10-0.1.0.0.jar
AttachableGrinder-4.0.0.jar
bdlib-1.9.4.109-mc1.7.10.jar
BiblioCraft[v2.2.5][MC1.10.2].jar
BigReactors-0.4.3A.jar
BiomesOPlenty-1.7.10-2.1.0.1889-universal.jar
buildcraft-7.1.23.jar
BuildcraftAdditions-1.7.10-2.2.5.jar
buildcraft-compat-7.0.8.jar
Carpenter's Blocks v3.3.8.1 - MC 1.7.10.jar
ChickenChunks-1.7.10-1.3.4.19-universal.jar
Chisel-2.9.5.11.jar
CodeChickenCore-1.7.10-1.0.7.47-universal.jar
CoFHCore-[1.7.10]3.1.4-329.jar
CoFHLib-[1.7.10]1.2.1-185.jar
CompactSolars-1.7.10-4.4.39.315-universal.jar
ComputerCraft1.75.jar
denseores-1.6.2.jar
Dimensional-Anchors-Mod-1.7.10.jar
DimensionalDoors-2.2.5-test9.jar
EnderCore-1.7.10-0.2.0.39_beta.jar
EnderIO-1.7.10-2.2.8.381.jar.disabledolder
EnderIO-1.7.10-2.3.0.422_beta.jar
EnderStorage-1.7.10-1.4.7.37-universal.jar
Eureka-1.7.10-3.0.2.jar
ExtraCarts-1.7.10-1.0.0.jar
ExtraCells-1.7.10-2.3.14b200.jar
ExtraPlanets-1.7.10-2.0.1.jar
extrautilities-1.2.12.jar
fastcraft-1.25.jar.disabled
FlatSigns-1.7.10-universal-2.1.0.19.jar
GalacticraftCore-1.7-3.0.12.504.jar
Galacticraft-Planets-1.7-3.0.12.504.jar
generators-0.9.20.123-mc1.7.10.jar
GregsLighting-1.11.2-mc1.7.10.jar
GuiltTrip-4.0.0.jar
HelpFixer-1.0.7.jar
iChunUtil-4.2.2.jar.disabledold
iChunUtil-4.2.3.jar
IGW-Mod-1.7.10-1.1.12-34-universal.jar
ImmersiveEngineering-0.7.7.jar
immibis-core-59.1.4.jar
industrialcraft-2-2.2.827-experimental.jar
INpureCore-[1.7.10]1.0.0B9-62.jar
IntelligentEnergistics-1.7.10-2.2.1.610-universal.jar
InventoryTweaks-1.59-dev-156.jar
ironchest-1.7.10-6.0.62.742-universal.jar
Jabba-1.2.2_1.7.10.jar
JourneyMap5.0.0RC2_Unlimited_MC1.7.10.jar.disabled
Keygrip-Standalone-Not-iChun-Mod-Compatible-4.0.0.jar.disabledincompat
Little-Blocks-Mod-1.7.10.jar
malisiscore-1.7.10-0.14.3.jar
malisisdoors-1.7.10-1.13.2.jar
Mantle-1.7.10-0.3.2b.jar
mcjtylib-1.8.1.jar
MicdoodleCore-1.7-3.0.12.504.jar
MineFactoryReloaded-[1.7.10]2.8.1-174.jar.disabledold
MineFactoryReloaded-[1.7.10]2.8.2B1-201.jar
MineMenu-1.7.10-1.2.0.B44-universal.jar
MineTweaker3-1.7.10-3.0.10B.jar
MoarPeripherals-1.7.10-1.7-1.53.jar
MobiusCore-1.2.5_1.7.10.jar
mod_voxelMap_1.7.0b_for_1.7.10.litemod
ModularPowersuits-0.11.0.283.jar.disabledolder
ModularPowersuits-1.7.10-0.11.1.114.jar
More-Planets-1.7.10-1.4.4-GC502.jar
Morph-Beta-0.9.3.jar.disabled
Morpheus-1.7.10-1.6.21.jar
mystcraft-1.7.10-0.12.3.04.jar
natura-1.7.10-2.2.0.1.jar
NEI_RedPowerPlugin 1.4.3.1.jar
neiaddons-1.12.14.40-mc1.7.10.jar
NEIIntegration-MC1.7.10-1.1.2.jar
NoMoreRecipeConflict-0.3(1.7.10).jar
NotEnoughItems-1.7.10-1.0.5.120-universal.jar
Numina-0.4.1.105.jar
PiP-4.0.0.jar
Railcraft_1.7.10-9.12.2.0.jar
RefinedRelocation-mc1.7.10-1.1.34.jar
rftools-4.01.jar
rftoolsctrl-1.12-1.8.1.jar
RouterReborn-1.7.10-1.2.0.43-universal.jar
SlimevoidLibrary-2.0.4.7.jar
StevesFactoryManagerA93.jar
TConstruct-1.7.10-1.8.8.jar
theoneprobe-1.12-1.4.22.jar
ThermalDynamics-[1.7.10]1.2.1-172.jar
ThermalExpansion-[1.7.10]4.1.5-248.jar
ThermalFoundation-[1.7.10]1.2.6-118.jar
TiCTooltips-mc1.7.10-1.2.5.jar
TMechworks-1.7.10-0.2.15.106.jar
Torched-4.0.0.jar
Waila-1.5.10_1.7.10.jar
WAILAPlugins-MC1.7.10-0.2.0-25.jar
Wawla-1.0.5.120.jar

Please provide screenshots / crash report / log as needed.
![kep](https://user-images.githubusercontent.com/9215491/39598421-c6465c2c-4f18-11e8-9191-b525275a7592.png)

It happened to me after i set the map key to "í" (long i in a Hungarian key layout), which is written as "NONE" in the keybinding settings. I would not complain if i could exit the map by pressing esc.

**Comment by radfast** [comment] 2018-05-03 22:58
Duplicate of #3389.   (Very very very strange that you two guys have the same issue in the same week.  We have literally millions of players playing Galacticraft, with this problem, and nobody noticed/complained before now!)

I will backport the fix to 1.7.10 as well.

It might be a few days before a new 1.7.10 build is available to download.

Meanwhile, please change the Galacticraft keys to something which is not "NONE".

**Closed by radfast** 2018-05-03 22:58 UTC
