### ISSUE TITLE
Astroid dimension does not load in newest beta

### ISSUE THREAD

**Issue by GiantNuker** [micdoodle8/Galacticraft#2180] opened 2016-04-17 05:55 UTC
^^^
I just get the "downloading terrain" screen forever

**Comment by Brycey92** [comment] 2017-02-25 18:20
@GiantNuker Please retry with the latest version, and close this issue if the problem is resolved.

**Comment by radfast** [comment] 2017-03-19 03:23
Unfortunately nobody responded to this for 10 months (I've been away from the mod most of that time due to personal reasons).

I'm going to close this due to lack of information - I'm not sure what "newest beta" means - and because I can't reproduce it and nobody else has reported the issue.

Minecraft will very occasionally get stuck in World Generation even on the Overworld with a small modlist, could be it's a JVM memory issue or some other problem specific to a computer setup, not in the mod itself.

If the issue is still happening, please comment or re-open, and provide:
* GC version, Forge version, and is this single player or on a server (if a server, which type of server)
* a full copy of `fml-client-latest.log`
* a copy of the .minecraft/configs/galacticraft/planets.conf config file
* explanation of how you are getting to the Asteroid dimension - Tier 3 rocket, or **/dimensiontp** command?
* do other dimensions (Moon, Mars) build OK?

**Closed by radfast** 2017-03-19 03:23 UTC
Labels: 1.7, cant reproduce
