### ISSUE TITLE
[SpongeForge - 1.12.2] While stopping server, Server Fails to Unload Dimension -1

### ISSUE THREAD

**Issue by CDAGaming** [micdoodle8/Galacticraft#3185] opened 2018-02-23 03:36 UTC
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 4.0.1.139
Forge version: 14.23.2.2618
SpongeForge Version: 1.12.2-2611-7.1.0-BETA-2934

Single player (SSP) or Multiplayer (SMP)?
Multiplayer
Galacticraft add-ons and other mods installed?
Extra Planets & More Planets, though both Reference Galacticraft Core as erroring.
Please provide screenshots / crash report / log as needed.
https://hastebin.com/olulivinol.vbs

**Comment by MJRLegends** [comment] 2018-02-23 03:39
Already reported see https://github.com/micdoodle8/Galacticraft/issues/2975 and https://github.com/SpongePowered/SpongeForge/issues/1429

**Comment by radfast** [comment] 2018-03-04 16:13
Duplicate of #2864 also

**Closed** 2018-03-04 16:16 UTC
