### ISSUE TITLE
Oxygen Sealer Freezes Server

### ISSUE THREAD

**Issue by Sir-Will** [micdoodle8/Galacticraft#1803] opened 2015-07-30 19:48 UTC
Version: GalacticraftCore-1.7-3.0.12.350

```
[21:39:25] [Thread Locksmith Watchdog/INFO]: Stacktrace:
[21:39:25] [Thread Locksmith Watchdog/INFO]:  - gnu.trove.impl.hash.TLongHash.indexRehashed(TLongHash.java:241)
[21:39:25] [Thread Locksmith Watchdog/INFO]:  - gnu.trove.impl.hash.TLongHash.index(TLongHash.java:219)
[21:39:25] [Thread Locksmith Watchdog/INFO]:  - gnu.trove.impl.hash.TLongHash.contains(TLongHash.java:163)
[21:39:25] [Thread Locksmith Watchdog/INFO]:  - gnu.trove.map.hash.TLongObjectHashMap.containsKey(TLongObjectHashMap.java:181)
[21:39:25] [Thread Locksmith Watchdog/INFO]:  - gnu.trove.impl.sync.TSynchronizedLongObjectMap.containsKey(TSynchronizedLongObjectMap.java:79)
[21:39:25] [Thread Locksmith Watchdog/INFO]:  - net.minecraft.world.gen.ChunkProviderServer.func_73149_a(ChunkProviderServer.java:97)
[21:39:25] [Thread Locksmith Watchdog/INFO]:  - micdoodle8.mods.galacticraft.api.vector.BlockVec3.getBlockIDsafe_noChunkLoad(BlockVec3.java:194)
[21:39:25] [Thread Locksmith Watchdog/INFO]:  - micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.unseal(ThreadFindSeal.java:408)
[21:39:25] [Thread Locksmith Watchdog/INFO]:  - micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.check(ThreadFindSeal.java:199)
[21:39:25] [Thread Locksmith Watchdog/INFO]:  - micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.<init>(ThreadFindSeal.java:88)
[21:39:25] [Thread Locksmith Watchdog/INFO]:  - micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.<init>(ThreadFindSeal.java:44)
[21:39:25] [Thread Locksmith Watchdog/INFO]:  - micdoodle8.mods.galacticraft.core.oxygen.OxygenPressureProtocol.updateSealerStatus(OxygenPressureProtocol.java:64)
[21:39:25] [Thread Locksmith Watchdog/INFO]:  - micdoodle8.mods.galacticraft.core.tile.TileEntityOxygenSealer.func_145845_h(TileEntityOxygenSealer.java:144)
[21:39:25] [Thread Locksmith Watchdog/INFO]:  - net.minecraft.world.World.func_72939_s(World.java:2512)
[21:39:25] [Thread Locksmith Watchdog/INFO]:  - net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
[21:39:25] [Thread Locksmith Watchdog/INFO]:  - net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
[21:39:25] [Thread Locksmith Watchdog/INFO]:  - net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
[21:39:25] [Thread Locksmith Watchdog/INFO]:  - net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
[21:39:25] [Thread Locksmith Watchdog/INFO]:  - net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
[21:39:25] [Thread Locksmith Watchdog/INFO]:  - java.lang.Thread.run(Thread.java:745)
```

World files with the issue:
https://mega.co.nz/#!a8Q1BK7Z!9dCS2_GjUzv1OmM-AAP_jxJLYU8XAjAF31ek99ILoCw

**Comment by SirWilli** [comment] 2015-08-02 18:45
Update: looks like the issue is the oxygen storage upgrade. After removing it we couldn't reproduce the issue.

**Comment by radfast** [comment] 2016-01-06 18:47
What is the "oxygen storage upgrade"?

**Comment by SirWilli** [comment] 2016-01-06 19:32
*Oxygen Storage Module

**Comment by radfast** [comment] 2016-01-12 03:21
I've found a minor memory leak connected with Oxygen Sealers, if there are large numbers of sealers and it keeps changing which one is the 'head' sealer.  I doubt that this would be enough to freeze a server ever, even with a huge setup (I have tested huge rooms with 128 sealers on a Cauldron server) but anyhow this will be fixed in version 413.

I will continue to study the world files with the issue, when I have time...

**Comment by SirWilli** [comment] 2016-01-12 05:01
I assume this is related to this change as I just got this crash after updating to your dev build:
```
java.lang.NullPointerException: Ticking block entity
	at micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.check(ThreadFindSeal.java:359)
	at micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.<init>(ThreadFindSeal.java:92)
	at micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.<init>(ThreadFindSeal.java:47)
	at micdoodle8.mods.galacticraft.core.oxygen.OxygenPressureProtocol.updateSealerStatus(OxygenPressureProtocol.java:64)
	at micdoodle8.mods.galacticraft.core.tile.TileEntityOxygenSealer.func_145845_h(TileEntityOxygenSealer.java:163)
	at net.minecraft.world.World.func_72939_s(World.java:2513)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.check(ThreadFindSeal.java:359)
	at micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.<init>(ThreadFindSeal.java:92)
	at micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.<init>(ThreadFindSeal.java:47)
	at micdoodle8.mods.galacticraft.core.oxygen.OxygenPressureProtocol.updateSealerStatus(OxygenPressureProtocol.java:64)
	at micdoodle8.mods.galacticraft.core.tile.TileEntityOxygenSealer.func_145845_h(TileEntityOxygenSealer.java:163)

-- Block entity being ticked --
Details:
	Name: Air Sealer // micdoodle8.mods.galacticraft.core.tile.TileEntityOxygenSealer
	Block type: ID #183 (tile.sealer // micdoodle8.mods.galacticraft.core.blocks.BlockOxygenSealer)
	Block data value: 2 / 0x2 / 0b0010
	Block location: World: (6683,71,12184), Chunk: (at 11,4,8 in 417,761; contains blocks 6672,0,12176 to 6687,255,12191), Region: (13,23; contains chunks 416,736 to 447,767, blocks 6656,0,11776 to 7167,255,12287)
	Actual block type: ID #183 (tile.sealer // micdoodle8.mods.galacticraft.core.blocks.BlockOxygenSealer)
	Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:2513)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
```

**Comment by radfast** [comment] 2016-01-12 14:40
Sorry about that @SirWilli.

I will build and upload 414a to fix it, later today.  Thank you for your patience.

**Comment by radfast** [comment] 2016-01-13 03:28
Build 414a is now uploaded.  [Links](https://github.com/micdoodle8/Galacticraft/issues/2001#issuecomment-171146658)

**Comment by SirWilli** [comment] 2016-01-14 09:55
Thanks, I will close this issue now and reopen if it should arise again with the new build.

**Comment by SirWilli** [comment] 2016-03-11 06:53
An Oxygen Sealer just started to freeze the server again:

```
[07:32:43] [Thread Locksmith Watchdog/INFO]: Stacktrace:
[07:32:43] [Thread Locksmith Watchdog/INFO]:  - java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1012)
[07:32:43] [Thread Locksmith Watchdog/INFO]:  - java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
[07:32:43] [Thread Locksmith Watchdog/INFO]:  - micdoodle8.mods.galacticraft.core.tick.TickHandlerServer.scheduleNewBlockChange(TickHandlerServer.java:149)
[07:32:43] [Thread Locksmith Watchdog/INFO]:  - micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.makeSealGood(ThreadFindSeal.java:394)
[07:32:43] [Thread Locksmith Watchdog/INFO]:  - micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.check(ThreadFindSeal.java:294)
[07:32:43] [Thread Locksmith Watchdog/INFO]:  - micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.<init>(ThreadFindSeal.java:99)
[07:32:43] [Thread Locksmith Watchdog/INFO]:  - micdoodle8.mods.galacticraft.core.tick.TickHandlerServer.onWorldTick(TickHandlerServer.java:586)
[07:32:43] [Thread Locksmith Watchdog/INFO]:  - cpw.mods.fml.common.eventhandler.ASMEventHandler_448_TickHandlerServer_onWorldTick_WorldTickEvent.invoke(.dynamic)
[07:32:43] [Thread Locksmith Watchdog/INFO]:  - cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[07:32:43] [Thread Locksmith Watchdog/INFO]:  - cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
[07:32:43] [Thread Locksmith Watchdog/INFO]:  - cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:259)
[07:32:43] [Thread Locksmith Watchdog/INFO]:  - net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:974)
[07:32:43] [Thread Locksmith Watchdog/INFO]:  - net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
[07:32:43] [Thread Locksmith Watchdog/INFO]:  - net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
[07:32:43] [Thread Locksmith Watchdog/INFO]:  - net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
[07:32:43] [Thread Locksmith Watchdog/INFO]:  - java.lang.Thread.run(Thread.java:745)
```
```
[07:40:23] [Thread Locksmith Watchdog/INFO]: Stacktrace:
[07:40:23] [Thread Locksmith Watchdog/INFO]:  - java.util.Arrays.copyOf(Arrays.java:3181)
[07:40:23] [Thread Locksmith Watchdog/INFO]:  - java.util.concurrent.CopyOnWriteArrayList.addAll(CopyOnWriteArrayList.java:827)
[07:40:23] [Thread Locksmith Watchdog/INFO]:  - micdoodle8.mods.galacticraft.core.tick.TickHandlerServer.scheduleNewBlockChange(TickHandlerServer.java:148)
[07:40:23] [Thread Locksmith Watchdog/INFO]:  - micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.makeSealGood(ThreadFindSeal.java:394)
[07:40:23] [Thread Locksmith Watchdog/INFO]:  - micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.check(ThreadFindSeal.java:294)
[07:40:23] [Thread Locksmith Watchdog/INFO]:  - micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.<init>(ThreadFindSeal.java:99)
[07:40:23] [Thread Locksmith Watchdog/INFO]:  - micdoodle8.mods.galacticraft.core.tick.TickHandlerServer.onWorldTick(TickHandlerServer.java:586)
[07:40:23] [Thread Locksmith Watchdog/INFO]:  - cpw.mods.fml.common.eventhandler.ASMEventHandler_448_TickHandlerServer_onWorldTick_WorldTickEvent.invoke(.dynamic)
[07:40:23] [Thread Locksmith Watchdog/INFO]:  - cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[07:40:23] [Thread Locksmith Watchdog/INFO]:  - cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
[07:40:23] [Thread Locksmith Watchdog/INFO]:  - cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:259)
[07:40:23] [Thread Locksmith Watchdog/INFO]:  - net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:974)
[07:40:23] [Thread Locksmith Watchdog/INFO]:  - net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
[07:40:23] [Thread Locksmith Watchdog/INFO]:  - net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
[07:40:23] [Thread Locksmith Watchdog/INFO]:  - net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
[07:40:23] [Thread Locksmith Watchdog/INFO]:  - java.lang.Thread.run(Thread.java:745)

[07:40:03] [Thread Locksmith Watchdog/INFO]: Stacktrace:
[07:40:03] [Thread Locksmith Watchdog/INFO]:  - java.util.LinkedList.clear(LinkedList.java:459)
[07:40:03] [Thread Locksmith Watchdog/INFO]:  - micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.check(ThreadFindSeal.java:361)
[07:40:03] [Thread Locksmith Watchdog/INFO]:  - micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.<init>(ThreadFindSeal.java:99)
[07:40:03] [Thread Locksmith Watchdog/INFO]:  - micdoodle8.mods.galacticraft.core.tick.TickHandlerServer.onWorldTick(TickHandlerServer.java:586)
[07:40:03] [Thread Locksmith Watchdog/INFO]:  - cpw.mods.fml.common.eventhandler.ASMEventHandler_448_TickHandlerServer_onWorldTick_WorldTickEvent.invoke(.dynamic)
[07:40:03] [Thread Locksmith Watchdog/INFO]:  - cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[07:40:03] [Thread Locksmith Watchdog/INFO]:  - cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
[07:40:03] [Thread Locksmith Watchdog/INFO]:  - cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:259)
[07:40:03] [Thread Locksmith Watchdog/INFO]:  - net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:974)
[07:40:03] [Thread Locksmith Watchdog/INFO]:  - net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
[07:40:03] [Thread Locksmith Watchdog/INFO]:  - net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
[07:40:03] [Thread Locksmith Watchdog/INFO]:  - net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
[07:40:03] [Thread Locksmith Watchdog/INFO]:  - java.lang.Thread.run(Thread.java:745)

[07:39:58] [Thread Locksmith Watchdog/INFO]: Stacktrace:
[07:39:58] [Thread Locksmith Watchdog/INFO]:  - java.util.HashMap.resize(HashMap.java:734)
[07:39:58] [Thread Locksmith Watchdog/INFO]:  - java.util.HashMap.putVal(HashMap.java:662)
[07:39:58] [Thread Locksmith Watchdog/INFO]:  - java.util.HashMap.put(HashMap.java:611)
[07:39:58] [Thread Locksmith Watchdog/INFO]:  - java.util.HashSet.add(HashSet.java:219)
[07:39:58] [Thread Locksmith Watchdog/INFO]:  - micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.doLayer(ThreadFindSeal.java:622)
[07:39:58] [Thread Locksmith Watchdog/INFO]:  - micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.check(ThreadFindSeal.java:168)
[07:39:58] [Thread Locksmith Watchdog/INFO]:  - micdoodle8.mods.galacticraft.core.oxygen.ThreadFindSeal.<init>(ThreadFindSeal.java:99)
[07:39:58] [Thread Locksmith Watchdog/INFO]:  - micdoodle8.mods.galacticraft.core.tick.TickHandlerServer.onWorldTick(TickHandlerServer.java:586)
[07:39:58] [Thread Locksmith Watchdog/INFO]:  - cpw.mods.fml.common.eventhandler.ASMEventHandler_448_TickHandlerServer_onWorldTick_WorldTickEvent.invoke(.dynamic)
[07:39:58] [Thread Locksmith Watchdog/INFO]:  - cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[07:39:58] [Thread Locksmith Watchdog/INFO]:  - cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
[07:39:58] [Thread Locksmith Watchdog/INFO]:  - cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:259)
[07:39:58] [Thread Locksmith Watchdog/INFO]:  - net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:974)
[07:39:58] [Thread Locksmith Watchdog/INFO]:  - net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
[07:39:58] [Thread Locksmith Watchdog/INFO]:  - net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
[07:39:58] [Thread Locksmith Watchdog/INFO]:  - net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
[07:39:58] [Thread Locksmith Watchdog/INFO]:  - java.lang.Thread.run(Thread.java:745)
```

**Comment by radfast** [comment] 2016-03-12 03:32
Thank you, I'll look at this - it's late here so it will be tomorrow now.

**Comment by radfast** [comment] 2016-03-13 00:14
That code seems to be working normally.  Those are possibly slightly slow operations, but I don't see a loop or lock up situation.  Is your Thread Locksmith Watchdog being too sensitive?

**Comment by SirWilli** [comment] 2016-03-13 02:55
No, server doesn't react on anything until I do a force restart.

**Comment by radfast** [comment] 2016-03-13 04:00
I'm planning to re-write that code anyway as I thought of a way to improve performance, so I'll bring that up the schedule and do it next.  Might be a couple of days.

If possible please can you keep a copy of the problem base / sealer for future testing.  Meanwhile I'm sure you want to keep your server running so I guess the only thing is to shut down that sealer.

**Comment by SirWilli** [comment] 2016-03-13 08:15
I couldn't find the base which was causing it and after multiple restarts it somehow stopped.

**Comment by radfast** [comment] 2016-03-14 02:19
The problem may be fixed anyhow in latest GC builds (452 is stable) which reduce unwanted chunkloading, and therefore are less likely to be loading sealers in the bases of players who are away from their base.

(How chunkloading works:  Launch Controllers are chunk loaders, but only for the 1x1 chunk they are in, and only if the player who owns the Launch Controller came online in the server session.  If the player does not come online, his Launch Controllers will not act as chunk loaders.)

**Comment by radfast** [comment] 2017-03-06 19:03
This thread has useful Thread Locksmith stacktraces and useful discussion - much appreciated.

Even so, I'm going to close this now as this looks like basically the same issue (or the same class of issues) as is being discussed in #2129 and in the other more recent issues referenced there, and we don't need all these different issues open.

**Closed by radfast** 2017-03-06 19:03 UTC
Labels: 1.7
