### ISSUE TITLE
Bug : rocket sounds and launch controller

### ISSUE THREAD

**Issue by PhysicalNova** [micdoodle8/Galacticraft#3454] opened 2018-06-27 16:01 UTC
Minecraft version: 1.12.2
Galacticraft version:4.0.1.181

Single player

No Galacticraft add-ons installed. 
Mods installed : Mr Crayfish's Furniture Mod, CharCoal (personnal mod), JEI, Scenter and Tree Chopper.
It doesn't seem like it's another mod fault.

Due to the fact that this is a sound bug, I cannot provide screenshots (and due to my computer, cannot provide video either, sorry). 
However, let me explain how to reproduce the bug : 
-Use the Launch controller, 
-Land on another moon/planet
-The rocket sound will play indefinitly, even if you got out of the rocket. 
The noise seems to follow the player. The bug stop when exiting then reentering the world or when breaking the rocket.

**Comment by radfast** [comment] 2018-06-27 21:40
Thanks for reporting.  I think this is a duplicate of #3383.  But your explanation may give further clues to that I can fix it, so thank you :)

**Closed by radfast** 2018-06-27 21:40 UTC
