### ISSUE TITLE
[Crash] Galacticraft 446 - java.lang.NullPointerException: Ticking block entity (Oxygen Sealer)

### ISSUE THREAD

**Issue by Yanniclord** [micdoodle8/Galacticraft#2132] opened 2016-03-09 09:39 UTC
So this one did definitely come with 446, as it has to do with the Oxygen Sealers, but in another way. They seem to cause a Ticking Block Entity Crash.

Log: http://pastebin.com/iN1vEdw6

**Comment by DraksterAU** [comment] 2016-03-09 13:28
Try reproducing this without GalaxySpace.... Ive tried to reproduce this and cant... on the same version of KCauldron.

@robotia Is Lagfix mod something you think Cauldron can handle? Most of the time I've read about these types of plugins and Cauldron it didn't end well.

**Comment by Yanniclord** [comment] 2016-03-09 13:32
Well it does not happen normally, so "reproducing" isn't the easiest thing. I think at best that the devs look into this, maybe they see something there.

**Comment by DraksterAU** [comment] 2016-03-09 13:34
I'm not saying they shouldn't look into it...

**Comment by Robotia** [comment] 2016-03-09 13:54
Code line at fault in OxygenPressureProtocol:
```java
    public static void updateSealerStatus(TileEntityOxygenSealer head)
    {
        try
        {
            head.threadSeal = new ThreadFindSeal(head);
        }
        catch (IllegalThreadStateException e)
        {

        }
    }
```
The head is null

**Comment by DraksterAU** [comment] 2016-03-09 13:59
Noted... :P

**Comment by Robotia** [comment] 2016-03-09 14:10
It doesn't make sense though...it probably cannot be reproduced :/

**Comment by DraksterAU** [comment] 2016-03-09 14:16
So a TileEntityOxygenSealer has to have a null head value for this to occur? Meaning the TE itself was messed up?

**Comment by Robotia** [comment] 2016-03-09 16:09
That ten second timer is for world generation, it would not affect this

**Comment by valentinp72** [comment] 2016-03-09 17:49
The same problem appears with the oxygen bubble distributors, sometime, the client crashes : http://pastebin.com/xmL9qATv

**Comment by Yanniclord** [comment] 2016-03-10 15:02
Crashed again, seems to be happening when no one is at the Space Station for multiple hours.

http://pastebin.com/nua3wzYE

**Comment by radfast** [comment] 2016-03-11 02:11
Yes, the oxygen bubble distributor crash seems similar.
As @Robotia said - thank you for looking at this :)  - it doesn't make a lot of sense.

The ```head``` cannot possibly be null in the [code in question](https://github.com/micdoodle8/Galacticraft/blob/77b96217bb6eaa37f3f390d2d3346ddf1c989e45/src/main/java/micdoodle8/mods/galacticraft/core/oxygen/ThreadFindSeal.java#L65), it is a freshly created object in the [calling code](https://github.com/micdoodle8/Galacticraft/blob/77b96217bb6eaa37f3f390d2d3346ddf1c989e45/src/main/java/micdoodle8/mods/galacticraft/core/oxygen/ThreadFindSeal.java#L48).

The only possibility here is that there is a ```null``` entry when iterating over [```TileEntityOxygenSealer.loadedTiles```](https://github.com/micdoodle8/Galacticraft/blob/77b96217bb6eaa37f3f390d2d3346ddf1c989e45/src/main/java/micdoodle8/mods/galacticraft/core/tile/TileEntityOxygenSealer.java#L47).  _The situation for the oxygen bubble distributors reported by @valentinp72 is similar._

That should not be possible either.

The only explanation I can think of is that this is connected with **multithreaded code** on the server - maybe that **Spigot asynchronous lighting code** - and a different thread is loading and unloading chunks, leading to a race condition when adding or removing elements to ```TileEntityOxygenSealer.loadedTiles```.

Anything like that is not the mod's fault.  Multithreaded code should not be loading and unloading chunks, that obviously is going to cause multiple issues.  Seems to me that the Spigot asynchronous lighting feature is not yet ready for public release. 

Guys with this issue: my recommendation is in ```spigot.yml``` config set this setting to be false: >        use-async-lighting:false

**Comment by radfast** [comment] 2016-03-11 02:16
You can let me know if that fixes it.  For now, I'm going to flag this as not a Galacticraft issue and close the issue report, but you are welcome to comment here with any further findings, and if it looks like it has a cause inside our mod then we can re-open.

Note: it might not by Spigot asynchronous lighting: if there is other asynchronous code running it could be that instead.  I have suggested it is Spigot asynchronous lighting because that's the only common asynchronous code I know about, and that's also a fairly reason change in KCauldron and Thermos, I think.

**Closed** 2016-03-11 02:16 UTC
Labels: not a Galacticraft issue

**Comment by valentinp72** [comment] 2016-03-11 05:28
Thanks, but this problem appears when I'm in singleplayer.. Right now, I don't have optifine installed.

I could put all my mods on a server to correct this problem, but I prefer to play in single player if it's possible.

I'm not sure if this is related, and I'm not on my computer now (so I don't have the logs, I will put them on this post tonight (French time zone)), but sometimes, my world just quits, then, I'm redirected to a screen with an error (don't remember exactly), and when I quit that screen, I'm on the multiplayer screen (even if I was in single player). 


Thanks,
Valentin

**Comment by radfast** [comment] 2016-03-11 05:40
Thank you @valentinp72 - in that case I will look at your issue again, it must have a different cause.

The issue reported by the OP, YannicLord, is on a KCauldron server.

**Comment by Robotia** [comment] 2016-03-11 10:55
Hmm yes honestly I think I am going to force use of synchronous lighting on Thermos...it is causing way too many problems for people to be worth it

**Comment by DraksterAU** [comment] 2016-03-11 11:03
@robotia maybe just default to having async off?

**Comment by Robotia** [comment] 2016-03-11 11:54
Yes but then people who don't read this stuff will never disable it

**Comment by DraksterAU** [comment] 2016-03-11 12:39
Hmmm. Maybe have a list of configs that can cause issues have warnings on startup?

Removing a feature that works for anyone not using Galacticraft is a bummer.

**Comment by DraksterAU** [comment] 2016-03-11 12:42
If the default is off and there is a warning on startup that a setting can cause compatibility issues when it is enabled means anyone who reports these bugs can be told off instead of helped xD

**Comment by Robotia** [comment] 2016-03-11 14:04
It affects everyone else, the only case where it would really be helpful if someone had a modpack with only 1 or 2 mods, and even then, lighting has been optimized with the ChunkBlockHashMap changes I have made.. Someone had it enabled and the stupidity of Thaumic leaves always updating light values caused the async thread to create 16% on WarmRoast.

**Comment by Yanniclord** [comment] 2016-03-11 15:30
@radfast So i disabled the async lightning in the spigot.yml, see if that fixes it. I guessed it would have something to do with chunkloading, so i will try (if it happens again), to chunkload the entire Space Station, not just parts of it. If that fixes it, we are on step closer to the answer.

**Comment by radfast** [comment] 2016-03-12 01:07
> Removing a feature that works for anyone not using Galacticraft is a bummer.

It's not specific to Galacticraft, please don't say that.  I'm sure other mods have the same type of issues, any complex mod with TileEntities is likely to.

**Comment by Yanniclord** [comment] 2016-03-12 01:13
@radfast Issue #2129 is still very true, could you take a look at the latest comments if you have time?

**Comment by radfast** [comment] 2016-03-12 03:24
@Robotia question for you please:
has Thermos (or Cauldron) changed the way that this operates in ```net.minecraft.world.gen.ChunkProviderServer```:

>     public boolean chunkExists(int p_73149_1_, int p_73149_2_)
    {
        return this.loadedChunkHashMap.containsItem(ChunkCoordIntPair.chunkXZ2Int(p_73149_1_, p_73149_2_));
    }

Galacticraft uses the ```world.ifBlockExists()``` check to test whether chunks are loaded, before calling ```world.getTileEntity()```, in an attempt to avoid loading unloaded chunks 'by accident' when doing neighbouring tile entity checks.
