### ISSUE TITLE
cannot shift-click items into tier-1, 56-item holding ship

### ISSUE THREAD

**Issue by Lightningtow** [micdoodle8/Galacticraft#2221] opened 2016-06-21 16:22 UTC
no crash or anything just kinda annoying, takes forever to load.

tier 1, 56-item holding ship, on launchpad with a full tank of fuel. only other mod was optifine.

**Comment by dj3520** [comment] 2016-06-21 19:00
Version of Galacticraft? (working for me with v460)

**Comment by Lightningtow** [comment] 2016-06-22 15:43
1.7-3.0.12.375 according to the download page...

**Comment by dj3520** [comment] 2016-06-22 19:05
This appears to be a duplicate of issue #1997 and was fixed in GC v411.

**Comment by Lightningtow** [comment] 2016-06-22 19:50
hmmm idk i just downloaded the recommended versions the green ones
(galacticraft mcdoodle8 core mod and gcplanets)

**Comment by dj3520** [comment] 2016-06-23 18:54
Downloading the latest (red) should resolve the problem for you

**Comment by Lightningtow** [comment] 2016-06-23 22:29
thanks :)

**Comment by dj3520** [comment] 2016-06-25 05:11
Could you close this issue?

**Comment by radfast** [comment] 2016-06-26 15:19
The red are the recommended versions.

**Closed by radfast** 2016-06-26 15:19 UTC

**Comment by dj3520** [comment] 2016-06-26 19:00
It's not hard to misinterpret the downloads page.
> Green builds are recommended for download while blue builds are stable.

**Comment by Lightningtow** [comment] 2016-06-30 20:52
you had just said that the red are the latest, then said that they are the
reccommended ones. I downloaded the green one the recommended one. As
opposed to the red one the latest one. now i am going to shut up and quit
bickering.
