### ISSUE TITLE
[1.10.2][Chicken Chunks]Can't find provider for dim-28

### ISSUE THREAD

**Issue by Pyrom4nia** [micdoodle8/Galacticraft#2652] opened 2017-04-29 14:29 UTC
When enter world after 5-10 minute, the game will crash randomly 
https://pastebin.com/8yNPrJZE

**Comment by radfast** [comment] 2017-04-29 17:28
Appears to be caused by a chunk loader.  Maybe ```mychunkloader``` or do you have ChickenChunks?

Quite possible the root cause is ```dimensionloader```, I've no idea what that does but it doesn't sound good.

Please try your world without those two mods.  (Make a full backup of your world and settings first, otherwise you can have issues if you delete mods from an existing world.)

Let us know how you get on.

**Comment by Pyrom4nia** [comment] 2017-04-30 04:28
I've been trying remove mods but seems after remove FTB Util everythings seems fine

**Comment by Pyrom4nia** [comment] 2017-04-30 04:32
Took me a long time to discover it haha

**Comment by Pyrom4nia** [comment] 2017-04-30 04:46
Also the chickenchunks

**Comment by radfast** [comment] 2017-04-30 11:15
that's great news that you found the cause

can you post up the FTB Util configs from before the crash, maybe we can find some answers in something in that config?

Also, **which exact chicken chunks version**?   Now that we know it's this mod, I can take a detailed look at their code and try to find the bug so we can maybe workaround it.

**Comment by Pyrom4nia** [comment] 2017-04-30 13:10
About Chickenchunks, it's version 2.2.0.52
But sadly I have already delete all the config so I think it's impossible to reproduce the FTBUtil crash

**Comment by BrisingrAerowing** [comment] 2017-05-23 17:39
@radfast 

I use chicken chunks rather extensively and have never had this crash. Same version as  @Pyrom4nia as well

**Comment by radfast** [comment] 2017-05-23 18:10
Thanks @BrisingrAerowing   That's very helpful, I think in that case I will close this.

Looking at this again, it seems that the actual cause was **FTB Util** and something wrong in its configs.  So probably not ChickenChunks.  It's unlikely for an issue to have two causes...

But yes, this type of "dimension provider not found" crash can probably happen with badly messed up configs.  That's not a Galacticraft issue...

**Closed by radfast** 2017-05-23 18:10 UTC
Labels: conflict, not a Galacticraft issue
