### ISSUE TITLE
[1.10.2][Build 77]Launching the rocket without the player in it will crash the game

### ISSUE THREAD

**Issue by Pyrom4nia** [micdoodle8/Galacticraft#2655] opened 2017-04-30 08:30 UTC
As the title, launching the rocket without the play in it will crash the game
It will also corrupt the save
https://pastebin.com/L716yD91

**Comment by radfast** [comment] 2017-04-30 11:16
thanks for beta testing

don't worry about corrupting the save, I'm sure we can fix this quickly

**Comment by radfast** [comment] 2017-04-30 11:52
This fix will be in build 79, probably out by 'tonight', that's _around_ 15 hours from the time of posting this.

**Closed** 2017-04-30 11:52 UTC

**Comment by Pyrom4nia** [comment] 2017-04-30 13:47
welp thanks 
Also rocket seems unbreakable when launching
Can you make it a feature in build 79?
Or it's intended?

**Comment by radfast** [comment] 2017-04-30 19:15
Please explain more, when are you trying to break the rocket?   Is it still on the launching pad counting down 20 ... 0, or it's already flying?  Creative mode or survival?

**Comment by Pyrom4nia** [comment] 2017-05-01 03:10
In survival, the rocket is unbreakable after launched from the pad

**Comment by radfast** [comment] 2017-05-01 03:17
That's intended behaviour.

More specifically, you can't break a rocket which is already in flight and above an altitude of y:300.

It's not clear why you'd want to break it anyhow?  Seems like a pretty dangerous thing to do!

I'm also not clear on how you're managing to keep level with a flying rocket for long enough to damage it?

**Comment by Pyrom4nia** [comment] 2017-05-01 03:21
Maybe when missing equipment or space station sources
How about adding a self-destruct(?) feature thingy

**Comment by radfast** [comment] 2017-05-01 03:35
When your rocket is already in flight seems a little late to realise you are missing equipment ... 

A self-destruct option is on the suggestions list at the forum (somewhere!), might be added at some point in future.

Please let us know if you spot any more issues in the betas.

**Comment by radfast** [comment] 2017-05-01 21:46
[Build 79](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/#post-43421) now available
