### ISSUE TITLE
Rendering sleeping player wrong

### ISSUE THREAD

**Issue by TheJulianJES** [micdoodle8/Galacticraft#1361] opened 2015-01-04 19:02 UTC
http://imgur.com/a/Go6NW (sorry for the wrong album title...)
First Image with Galacticcraft
Second without (also Coremods)
Versions:
Minecraft: 1.7.10
Forge: 10.13.2.1277
MicdoodleCore: 3.0.6.250
GalacticraftCore: 3.0.6.250
Galacticraft-Planets: 3.0.6.250

**Comment by radfast** [comment] 2015-01-05 02:04
Thanks for reporting.  It's a duplicate of open issue #897 so I will close this now.

**Closed by radfast** 2015-01-05 02:04 UTC

**Comment by TheJulianJES** [comment] 2015-01-05 12:19
@radfast Sorry, I searched but didn't found anything.

**Comment by radfast** [comment] 2015-01-05 18:55
It's no problem, I definitely prefer to have the bugs reported twice than not at all!
