### ISSUE TITLE
[1.10.2][Build 77]Volcanic Pickaxe copy Galacticaft machines

### ISSUE THREAD

**Issue by Pyrom4nia** [micdoodle8/Galacticraft#2657] opened 2017-04-30 14:32 UTC
Volcanic Pickaxe will copy GC machines after breaking it
But the block didn't actually broke and stuck people which stand on it

**Comment by radfast** [comment] 2017-04-30 15:22
Thanks for beta testing!  This is a duplicate of #2636 so I will close this as that one is still open.

**Closed by radfast** 2017-04-30 15:22 UTC

**Comment by radfast** [comment] 2017-05-01 21:46
[Build 79](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/#post-43421) now available
