### ISSUE TITLE
No more Mekanism compatibility?

### ISSUE THREAD

**Issue by styltus** [micdoodle8/Galacticraft#2922] opened 2017-07-29 22:04 UTC
-Minecraft version: 1.10.2
-Galacticraft version: 1.10.2-4.0.0.114
-Forge version: 1.10.2-12.18.3.2422
-Single player (SSP)
-No Galacticraft add-ons
-Some other mods are installed, especially newest version of mekanism (9.2.2.301)

I tried to connect a oxygen-producing mekanism machine with the oxygen compressor (Galac.), but only the basic logistically transporters(Mek.)/fluid pipes (Galac.) connected to my oxygen compressor. But there was no chance to transfer oxygen from the electrolytic seperator. Is this a bug or is there no compatibility anymore?

**Comment by radfast** [comment] 2017-07-29 22:14
This is a duplicate of #2847, so I will close it as we only need one open issue for this.

Currently Mekanism gas pipes are not working with Galacticraft, this is something we intend to fix but we didn't have time to get to this issue yet, sorry.

**Closed by radfast** 2017-07-29 22:14 UTC

**Comment by radfast** [comment] 2017-08-06 22:55
Should be improved in build 116 now available.
