### ISSUE TITLE
Mars has an incorrect gravity of 0.058 instead of 0.58

### ISSUE THREAD

**Issue by ghost** [micdoodle8/Galacticraft#3893] opened 2020-02-26 03:16 UTC
Minecraft version: 1.12.2
Galacticraft version: 4.0.2.237

Multiplayer (SMP)

Any Galacticraft add-ons installed? 
- Galacticraft Planets: 4.0.2.237
- galacticrafttweaker: 1.0.3

![image](https://user-images.githubusercontent.com/31835205/75308405-3e349100-5803-11ea-8ca8-c62b7ab61560.png)

**Comment by MJRLegends** [comment] 2020-02-26 03:57
Where/how did you come to the conclusion it should be 0.58?

**Comment by radfast** [comment] 2020-02-26 22:59
This data screen is provided by Extra Planets add-on - it's not provided by Galacticraft _per se_.

I'm happy if you and @MJRLegends (dev of Extra Planets) want to continue a discussion in this thread.  But I will close this, as it's not a Galacticraft issue.  You can both continue posting here even after the issue is closed.  I guess Github will send both of you email notifications of posts.

Note: in the Minecraft game, the gravity factor used is not in "units" of metres per second squared.  Instead it's given in internal game units, which are based on ticks.  (1 tick = 1/20 second)  So that could maybe explain the difference here?   One solution could be for Extra Planets to convert the internal game number into m/s<sup>2</sup> when rendering?

**Closed by radfast** 2020-02-26 22:59 UTC

**Comment by MJRLegends** [comment] 2020-02-26 23:10
My mod just reads the value from the world provider which it says 0.058 in there

**Comment by EzerArch** [comment] 2020-02-27 01:45
> My mod just reads the value from the world provider which it says 0.058 in there

The issue with such value is that it is meaningful only for the machine, but not for humans. It would be better if it were "translated" to a more inteligible value, such as percentages ([see 2nd table](https://wiki.micdoodle8.com/wiki/Dimensions#Overview)).

Currently these are the gravity values (`getGravity()`) in the source code:
- Overworld ????
- Space Station 0.0
- Asteroids 0.072
- Moon 0.062
- Mars 0.058
- Venus 0.0375
But since I don't have the Overworld's value I can't do much... anybody please?

**Comment by radfast** [comment] 2020-02-28 23:01
If those figures for gravity in a dimension are _X_ then the y motion **change** per game tick due to gravity is:
    0.08 - _X_

So the Moon's figure of 0.062 results in a low gravity of 0.018.  Mars has higher gravity of 0.022 (I'm not sure why that's so close to the Moon's figure - seems a bit strange?)  Asteroids have lower gravity of 0.008, that's really low microgravity.

The motion is - of course - in blocks per game tick.  Therefore 1 game unit corresponds to 20 m/s.  A Minecraft block is 1 m<sup>3</sup> - I guess Minecraft is subtly teaching American kids the metric system.

So 20 ticks of Overworld acceleration at 0.08 would give a falling speed of 1.6 blocks/t which equates to a real-world speed of 32 m/s. 

That's obviously too high, in the real world it should be 9.8 m/s after 1 second.  The game also applies some deceleration to entity motion each tick, to simulate air resistance and to make the game playable....  It's a 2% deceleration to the y motion.   So the falling speed after 1 second is actually only around 26 m/s in real world units.  That still seems too high... must be something I'm missing but I can't see it.

The Minecraft source code for this is at `EntityLivingBase.travel()` if you want to take a look for yourself.
