### ISSUE TITLE
GalactiCraft and EnderIO cable crash

### ISSUE THREAD

**Issue by jamesbat1** [micdoodle8/Galacticraft#3429] opened 2018-06-06 07:02 UTC
There was a player on my server that crossed aluminum wire (Galacticraft) over enhanced energy conduits (EnderIO) so they connected and caused who ever that looked at them to crash

Minecraft version: 1.12.2
Galacticraft version: GalacticraftCore-1.12.2-4.0.1.177

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Multiplayer

Galacticraft add-ons and other mods installed?
Enderio

**Comment by radfast** [comment] 2018-06-06 16:45
Seems like a duplicate of #3422.

Please can you let us know the **exact** EnderIO and EnderCore version used?

**Closed** 2018-06-06 16:45 UTC
Labels: duplicate

**Comment by jamesbat1** [comment] 2018-06-06 16:47
EnderIO-1.12.2-5.0.25

EnderCore-1.12.2-0.5.30

**Comment by radfast** [comment] 2018-06-06 16:58
thanks, we'll test those as well against the issue reported.  should have a fix for this by the weekend if all goes well
