### ISSUE TITLE
[1.11.2] Display Screen rendering stops working when a Satellite Dish in the same chunk is broken

### ISSUE THREAD

**Issue by kyleedwardsny** [micdoodle8/Galacticraft#3032] opened 2017-11-15 19:20 UTC
Minecraft version: 1.11.2
Galacticraft version: 4.0.0.118
Forge version: 13.20.1.2386

Single player (SSP)

I have observed this issue both with Galacticraft Core only and with Planets installed.

Place a Display Screen and a Satellite Dish in the same chunk. Turn the screen to any channel. Break the satellite dish. The screen will stop working.

It doesn't always break... it seems to depend on the coordinates of the screen and the dish. I haven't figured out the exact relationship, but it shouldn't be too hard to find a configuration that reproduces the issue.

This is a relatively minor issue, but I found it because I'm making a mod that uses the dish and the screen to display the time on other celestial bodies (something players have wanted for a while since the time sync behavior was changed), so it would be very nice to get a fix for this.

**Comment by TheQuadShot** [comment] 2017-11-15 22:05
iirc, on the GC (side anyway. They don't interact in any way. That is to say that the Dish is just "eye candy" atm.

**Comment by kyleedwardsny** [comment] 2017-11-16 03:21
You are correct, they don't.

However, I have narrowed down the exact cause of the issue: at least in the 1.11 branch, the `TileEntityScreen` class overrides the `writeToNBT()` method, but doesn't override the `getUpdateTag()` method, which is sent by the server during a chunk update. Because of this, the client receives NBT data that doesn't have the custom `TileEntityScreen`-specific data, and as a result defaults the screen number to 0. I have a working fix in 1.11, and will post a pull request soon.

**Comment by MJRLegends** [comment] 2017-11-16 04:40
Nice, im sure the devs will accept the pull request and pull it back to earlier mc versions @kyleedwardsny

**Comment by kyleedwardsny** [comment] 2017-11-16 05:57
Note for the devs: it seems that earlier version of Minecraft had a `getDescriptionPacket()` method, which appears to be the predecessor to `getUpdateTag()`. Keep this in mind when backporting my fix.

**Comment by radfast** [comment] 2017-11-18 23:03
Thanks @kyleedwardsny - really appreciate this!  We should be able to incorporate your fix into next update version 119.

**Comment by radfast** [comment] 2017-11-19 12:36
Should now be fixed in 1.10.2 and 1.11.2, and this may help with other issues too, like #2105.

I don't think any fix is needed / possible in 1.8.9.  ```getUpdateTag()``` becomes relevant when vanilla Minecraft changed ```writeToNBT()``` to ```writeInternal()```, which looks like a change they introduced in 1.10.

Thanks again, really appreciate that you took time to identify the cause of the issue.  And now I've fixed the similar code for a few other tiles, this may resolve quite a few small / niggling issues and make the mod overall more stable.

If you feel like looking at solving some more issues, feel free 👍 :)

**Closed by radfast** 2017-11-19 12:36 UTC
