### ISSUE TITLE
[1.7.10] Water Electrolyzer output tanks wrongly labelled "Liquid" oxygen and "Liquid" hydrogen

### ISSUE THREAD

**Issue by Brycey92** [micdoodle8/Galacticraft#2464] opened 2017-03-17 01:29 UTC
A water electrolyzer should output oxygen and hydrogen in gas form, but the outputs are called liquids. This results in their being 2 confusing liquid oxygen types, when only the one that's output from a gas liquefier is actually liquid. I'm using build 475.

**Comment by dj3520** [comment] 2017-03-17 04:10
I agree (and it doesn't help that I made the gas and liquid the same colors) though I believe this is for ease of use, especially when there is no universal "gas pipe" (heard there's one for 1.8.9) though for counter-argument it does make storing gases easy.

**Comment by Brycey92** [comment] 2017-03-17 12:05
I had players insisting the mod was broken all day, then I thought the mod was broken for about an hour before I figured it out.

**Comment by radfast** [comment] 2017-03-17 13:07
> the outputs are called liquids

Evidence please?

The outputs of the Water Electrolyser are gases.  They can be piped using the gas pipes which Galacticraft provides (oxygen pipe and hydrogen pipe).  All this should be fully covered on the [wiki](https://wiki.micdoodle8.com/wiki/Gases), if there is an error on the wiki please let me know.

**Comment by Brycey92** [comment] 2017-03-17 13:53
![](http://i.imgur.com/rYeQwbT.png)

![](http://i.imgur.com/T5LU69F.png)

**Comment by radfast** [comment] 2017-03-17 16:18
Thank you.  This is an error in the en_US and other language files, will fix in the next version.  It definitely is not intended for the Water Electolyser to produce liquid hydrogen and liquid oxygen - otherwise the Gas Liquefier would be pointless!

**Comment by radfast** [comment] 2017-03-17 20:10
@Brycey92 I've investigated this some more.  It looks like this is not being caused by Galacticraft, but by some other mod.   Another mod has registered Forge fluids with internal names "oxygen" and "hydrogen" but displayed names "Liquid Oxygen" and "Liquid Hydrogen".

Please list your mods, especially any which have Liquid Hydrogen in them.  Any GC submods?  Advanced Rocketry?

Galacticraft does **not** contain Liquid Hydrogen (currently....), so it is not possible that this has come from Galacticraft.

**Comment by Brycey92** [comment] 2017-03-20 16:24
Sorry for the delay. My mods can be found at https://www.technicpack.net/modpack/galaxy-craft-modpack.210706/mods.

**Comment by radfast** [comment] 2017-03-20 18:07
This is your own modpack, Brycey92, so you must know details of the mods you have included.  Which of those other mods provides "Liquid Hydrogen"?

If you can identify the specific mod which is causing the problem, I can look at finding a solution.

**Comment by Brycey92** [comment] 2017-03-20 18:26
Whoops, thanks for pointing out the typo! It's been fixed. As for the GC version, I've been busy with coursework recently, but I'll update it as soon as I have the chance.

I'll find a list of mods that add liquid hydrogen later and make a new comment here.

**Comment by radfast** [comment] 2017-03-20 20:05
If you have space for a third credit, **fishtaco567** wrote the worldgen for the Moon, Mars and Asteroids, so he's been an important author in the past but not active recently.

**Comment by radfast** [comment] 2017-04-02 18:48
It's [Mekanism](https://github.com/aidancbrady/Mekanism/blob/master/src/main/resources/assets/mekanism/lang/en_US.lang#L331) which is the problem.  They are registering their Liquid Oxygen as "oxygen", which I don't think is right - other mods use that fluid name for gaseous oxygen.

We normally have quite a good relationship with Mekanism, so I'm hoping they will be willing to fix this.  I've opened https://github.com/aidancbrady/Mekanism/issues/4290

I will close this issue here for now.

**Closed by radfast** 2017-04-02 18:48 UTC
Labels: 1.7, cant reproduce, conflict, follow-up please, not a Galacticraft issue

**Comment by Brycey92** [comment] 2017-04-04 00:18
Thank you for investigating this for me!

**Comment by radfast** [comment] 2017-04-04 01:02
On further analysis, it's actually **only** the names which are wrong.  The fluid in the tanks is correct.  That's because Galacticraft loads before Mekanism so Galacticraft gets to register the fluid "oxygen" first.

The names are wrong, because the way Minecraft / Forge works is, whichever mod loads **last** gets to name the fluid.  So Mekanism loads its .lang files after Galacticraft, and because Mekanism has a translation for "fluid.oxygen" as "Liquid Oxygen", then that's the name that sticks.

You could say this is a bug in Forge: it should give the localised name to whichever mod successfully registered the fluid.  But the problem arises only when there is a conflict between mods, with two mods wanting the same fluid name.
