### ISSUE TITLE
Fuel loader can't fuel Tier 3 Rockets

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#1778] opened 2015-07-13 00:14 UTC
(**Note:** this is a duplicate of  #1771, but the discussion developed better here.)

I'm using:
journeymap-1.7.10-5.1.0-unlimited.jar
CodeChickenCore-1.7.10-1.0.4.29-universal.jar
NotEnoughItems-1.7.10-1.0.3.74-universal.jar
Galacticraft-Planets-1.7-3.0.12.350.jar
GalacticraftCore-1.7-3.0.12.350.jar
MicdoodleCore-1.7-3.0.12.350.jar

This is my fuel loader:
![2015-07-12_21 12 13](https://cloud.githubusercontent.com/assets/6743303/8640774/cbea68ba-28da-11e5-8c1b-89895173e66d.png)

And the Tier 3 Rocket:
![2015-07-12_21 12 27](https://cloud.githubusercontent.com/assets/6743303/8640780/f8e07e9a-28da-11e5-9606-e6bceff2c2c6.png)

----

For those who want to help: can anyone say in which this bug started happening?

You can download the dev builds here (http://ci.micdoodle8.com/job/Galacticraft-1.7/), please test, tell us the last good build and the 1st bad one.

**Comment by TheQuantumGeneral** [comment] 2015-07-17 11:12
I am also having this issue.

GalacticraftCore-1.7-3.0.12.350
Galacticraft-Planets-1.7-3.0.12.350
MicdoodleCore-1.7-3.0.12.350

**Comment by MJRLegends** [comment] 2015-07-19 13:44
Im getting the same problem :(

**Comment by SteveKunG** [comment] 2015-07-20 01:59
Your issue its mean "can't" ?

**Comment by MJRLegends** [comment] 2015-07-20 02:01
@SteveKunG What do you mean?

**Comment by TheQuantumGeneral** [comment] 2015-07-20 02:04
The title says the fuel loader CAN load tier 3, it is incorrect and meant to say CAN'T.

**Comment by MJRLegends** [comment] 2015-07-20 02:05
@TheQuantumGeneral oh yeah i didnt even notice that. im not the owner of this issue anyways haha :D

**Comment by EzerArch** [comment] 2015-07-20 03:55
> The title says the fuel loader CAN load tier 3, it is incorrect and meant to say CAN'T.

Thanks for spotting. Probably I had "Fuel loader can no longer fuel Tier 3 Rockets" in my mind and erased the "no longer" part on a second thought.

**Comment by TheQuantumGeneral** [comment] 2015-07-20 04:58
I didn't notice either until Steve brought it up ;)

**Comment by jonabrv1965** [comment] 2015-07-22 04:53
Hi all,I just found that I have this very same issue with Tier 3 rocket (I tested the lauch pad setup with my old  tier 2 and tier 1 rockets and those load fuel just fine... So... After all this dig and mining.... we are stuck!! :-1: ).
MC 1.7.10, NEI/Waila latest versions, GalacticraftCore-1.7-3.0.12.350, Galacticraft-Planets-1.7-3.0.12.350,MicdoodleCore-1.7-3.0.12.350....(and another 55 mods... if requested I can send the details of those...)

**Comment by EzerArch** [comment] 2015-07-22 05:34
For those who want to help: can anyone say in which this bug started happening?

You can download the dev builds here (http://ci.micdoodle8.com/job/Galacticraft-1.7/), please test, tell us the last good build and the 1st bad one.

**Comment by TheQuadShot** [comment] 2015-07-22 07:33
I just checked .339 and it works fine for me, if you need me to provide anymore info, just let me know

**Comment by dj3520** [comment] 2015-07-22 07:54
Duplicate of #1771
v349 does not work

>.445 and it works fine for me

@TheQuadShot You sure that's the right version number?

**Comment by MJRLegends** [comment] 2015-07-23 13:04
im still having a issue and im using 3.0.12.350?

**Comment by dj3520** [comment] 2015-07-24 03:13
@MJRLegends The issue won't be fixed until what causes it is apparent. Somewhere along the line it broke, from the looks of things between .345 and .349

Usually what happens next is we downgrade to .345 and work upwards one version at a time until it breaks again and then blame that version. We look at what was changed and make a fix.

If you're looking for a temporary fix, downgrade to .345 (according to @TheQuadShot)
If you'd like to help, make a new test world and start testing which versions have the problem.

**Comment by TheQuadShot** [comment] 2015-07-24 08:56
Looks like it's broken in .346

**Comment by dj3520** [comment] 2015-07-24 20:58
>Looks like it's broken in .346

Makes sense. 346 had updates to landing and includes tweaks to a "fuelable" condition:
 ef140e3
 7b45f9b

Unfortunately I don't know java, let alone modding, or else I'd help.

**Comment by EzerArch** [comment] 2015-07-24 23:08
@dj3520:

> ef140e3

Not to take the blame. It's just language file.

If 346 the 1st bugged version, I recommend downgrading to 345, and wait until @micdoodle8 or @radfast fixes the bug.

**Comment by Dream-Master** [comment] 2015-08-02 23:19
Any news here?

**Comment by EzerArch** [comment] 2015-08-02 23:23
@Dream-Master 

Not yet. We need to wait for our devs to be back from their break time. Unless someone else who knows java picks up and tries to address the problem.

**Comment by katzenpapst** [comment] 2015-08-13 19:36
Is there any kind of news when/if the developers will return? Also, it would be nice if someone would make somehow public that 345 is the last usable build in forum or wiki or both..

**Comment by Dream-Master** [comment] 2015-08-13 19:38
Yes good idea. I downgrading all ready.

**Comment by micdoodle8** [comment] 2015-08-15 06:42
Sorry about the delay guys, will be fixed in the next build.

**Closed** 2015-08-15 06:42 UTC
