### ISSUE TITLE
No moon boss treasure empty

### ISSUE THREAD

**Issue by TheLogan** [micdoodle8/Galacticraft#2006] opened 2016-01-12 03:15 UTC
Hi, I tried searching for this issue, and the only result I found was that the same has been experienced on mars, but I want to let it be known that it can happen elsewhere too.
I'm playing Space Astronomy, which utilizes "CalacticraftCore-1.7-3.0.12.404"
I found the entrance to the moon dungeon, and I've done dungeons before, this one only had one room with monsterspawners and then it ended in a dead end.
I dug my way through the dead end and found a new pathway on the other side
one side of the pathway lead to the treasure room (yay), and the other side lead to a monsterroom with no exits.
However, it looks like the generator tried to place entrance and exit at the same spot, as the middle of the hallway has a wall going through it, as evident by the image below
![Image of error](http://i.imgur.com/OOs9iLl.png)

After digging around a bit, trying to find the boss cave and discovering that it was evidently not spawned I decided to just cheat in a tier 1 dungeon key and opened to the chest with it, turns out the chest was empty (though I'm questioning if this may be because the boss is technically unconquered? )

**Comment by TheLogan** [comment] 2016-01-12 03:18
In case it helps; the seed I'm playing on is:

-3242444508639655617

**Comment by radfast** [comment] 2016-01-12 03:32
Thank you, your screenshot and seed are very helpful, and I think you may be right about the reason.

I am very grateful for this, the reported missing rooms issue is one I have not been able to reproduce in my testing.

**Comment by TheLogan** [comment] 2016-01-12 12:15
You're very welcome, if you need more info be sure to let me know.

**Comment by radfast** [comment] 2016-01-12 12:39
Can you give me map coordinates of that dungeon, please?

**Comment by TheLogan** [comment] 2016-01-12 13:04
Certainly, it's located at:
X= -1621
Z= 1642
Are there more than one dungeon per planet? Or is there no way to easily cheat the game to give up its location? =)

**Comment by radfast** [comment] 2016-01-12 13:48
Many dungeons per planet, it's at least around 1 per 100 chunks, I don't remember the exact percentage chance (it also tests for proximity to other dungeons).  They are not like the Fortress in vanilla.

**Comment by TheLogan** [comment] 2016-01-12 13:52
Ah, yeah, I went hunting after having written the last post, and I've found a bunch more dungeons that were not bugged.

**Comment by TheLogan** [comment] 2016-01-12 18:53
X -1621
z= 1644
Found a dungeon on mars, which oddly enough has approximately the same coordinates as the dungeon on the moon, seems to be more or less an exact copy of the bugged dungeon on the moon, with the same problem (same seed).

**Comment by radfast** [comment] 2016-01-12 18:55
Thank you :)   And lol, are our dungeons on the Mars and Moon copies?  I didn't know that.

**Comment by TheLogan** [comment] 2016-01-12 19:25
It would definitely seem that way from that specific dungeon xD
Though I haven't checked the other dungeons on mars, might have been an unlucky fluke =P

**Comment by radfast** [comment] 2016-02-11 18:08
See also #1126

**Comment by kernelstubbs** [comment] 2016-03-09 14:26
In my playthrough, I've come across three dungeons now that have no boss rooms.  One on the moon and two on Mars.  Two of them has treasure rooms and the third had neither...seems related.  My seed is AWNF01 and I'm playing with GC added to FTB DW20 1.10.0

Cheers!

**Comment by kernelstubbs** [comment] 2016-03-09 14:27
#1126 is basically exactly what I'm describing in my world -.-

**Comment by EzerArch** [comment] 2016-03-27 12:05
> #1126 is basically exactly what I'm describing in my world -.-

I think this issue could be closed and any *new* info should be reposted there.

**Comment by radfast** [comment] 2016-06-26 17:24
OK thanks guys, I will close this because issue #1126 is the same  (Moon / Mars, the problem happens on both).  This thread is useful though for the world seed, that will help in further testing.

**Closed by radfast** 2016-06-26 17:24 UTC
