### ISSUE TITLE
Energy Storage Cluster disconnects output

### ISSUE THREAD

**Issue by pyure** [micdoodle8/Galacticraft#1392] opened 2015-01-19 14:47 UTC
I use Energy Storage Clusters as a conversion block between RF<->EU.  Occassionally I'll notice that the output side (a gold IC2 cable) has disconnected.  It almost seems like the block has forgotten which side was the output.

So far only noticed in server play (haven't tested in single player)

Can be worked around (usually) by logging out and back in a few times until it reconnects.

The block itself is a tiny bit wonky: can we provide the option to explicitly specify what end is the input vs output?  (Unless the dots are different color; I'm a bit colorblind so I can't tell)

**Comment by radfast** [comment] 2015-01-19 17:14
It sounds like an IC2 bug, not a Galacticraft bug.  It's impossible for an Energy Storage Cluster to "forget" which side is the output, that's fixed in orientation to how the block is placed.

It also sounds like it may be a purely visual issue - so even if it "looks" disconnected on the client, it may in fact be transmitting energy OK on the server?

Please do post up a screenshot the next time you see this.

On the GC block, the dots are different colours, red for output, green for input.  It's the same on the Energy Storage Module and has been this way since GC1.  I apologise, we have not taken into account the difficulty that using red+green dots can cause for colour-blind players, although to be fair all players are in the same situation after wires are connected, because the wires cover the dots.

Hopefully this will help:
* when you first place down the Energy Storage Cluster, the left side is the output, the right side is the input
* each time you wrench it once, it will rotate clockwise 90 degrees (viewed from above)
* so, wrench it once, the output is at the back, the input is at the front.

**Closed** 2015-01-19 17:14 UTC

**Comment by radfast** [comment] 2015-01-21 11:54
See also:
http://forum.micdoodle8.com/index.php?threads/energy-storage-cluster-disconnecting-ic2-cables.4865/

I'm happy to continue the discussion on either place.

I think most likely this is a bug in IC2 where, when you load a chunk, it thinks each block the wires are connected to is either an input block (like a machine) or an output block (like a generator).  A Galacticraft Energy Storage Cluster is both, obviously - input on one side, output on the other.  My guess is that IC2 has a bug so that - when loading the chunk and looking to see what the wires are connected to - it finds the input side first, and stops looking for an output side.  I am not 100% about that, I have not checked IC2 code, it is just a guess at this point.

You should raise this issue with the IC2 dev team also.

It would also be a good idea to check whether this is only a visual bug (so energy still transmits even though they look disconnected), and whether the same bug happens with energy storage blocks from other mods if there's one which works with IC2.

**Comment by pyure** [comment] 2015-01-21 14:58
Thanks a bunch radfast for replying.

I'll mention this to the IC2 team.  For now, I can clarify the following:
1) The problem is definitely not visual.  No energy is being converted (and the clusters are 100% full as a result, with an empty IC2 energy storage block (MFSU) on the other end.
2) The IC2 cables do not appear to have any trouble disconnecting from Railcraft turbines but I need to triple-check this the next time the issue occurs.  They're the only other mod I can think of that accepts IC2 power in this pack.
3) Next time it happens I'll test if GC cables do connect correctly
4) I have seen a trend whereby the cables are more likely to disconnect if the chunks unload, possibly supporting your theory.
5) Wouldn't your theory about IC2 be disproven by breaking the IC2 cable and putting it back?  I have tried that and it does not reconnect.
6) You *can* reconnect by breaking the GC cluster and putting it back

**Comment by pyure** [comment] 2015-01-21 15:23
For your information:
http://bt.industrial-craft.net/view.php?id=1517

**Comment by radfast** [comment] 2015-01-21 15:34
Thank you for the extra info.  I am not a member at industrial-craft.net so I'm not sure if I can post there, but if you have a chance to relay these comments to the IC2 team that would be great:

The Galacticraft Energy Storage Cluster block implements both

```ic2.api.energy.tile.IEnergyEmitter.emitsEnergyTo(TileEntity receiver, ForgeDirection direction)```

and

```ic2.api.energy.tile.IEnergyAcceptor.acceptsEnergyFrom(TileEntity emitter, ForgeDirection direction)```

On tile loading, we fire this event on each of our tiles:
```ic2.api.energy.event.EnergyTileLoadEvent(IEnergyTile tile)```

**Comment by radfast** [comment] 2015-01-21 15:36
One more test for you to try: set up a Galacticraft Energy Storage block with IC2 wiring on both the input and the output sides.  In a disconnection situation, does it disconnect from both sides or only the output side?

**Comment by pyure** [comment] 2015-01-21 20:33
radfast: I've passed that along as requested.

I'll do that test for you within 6 hours.

**Comment by pyure** [comment] 2015-01-24 05:20
Took me a while but I was able to replicate that bug with ic2 wiring on both sides.  See http://imgur.com/fTHt5pM

(The bottom-right energy-cluster has ic2 inputs/outputs.)

I found the wiring in this state when I logged in this evening; no other players in chunkloading radius.

**Comment by pyure** [comment] 2015-01-24 05:23
Also: reconnecting this time "fixes" the issue (which is sporadically true)

**Comment by radfast** [comment] 2015-01-24 05:48
I've been testing and I have not managed to reproduce the issue, with just IC2 and Galacticraft.  I'm wondering if it's because you have other mods like EnderIO in the mix as well.

How often does this randomly happen?  Like 1 time out of 2, or 1 time out of 10?

Please confirm your disconnect / reconnect process - I mean, is Minecraft re-started at all (on client? on server?) or is it literally a situation where the server is running all the time and you, the player, connect to the multiplayer server, disconnect, then connect again a couple minutes later?

One more question - are the IC2 gold cables and Energy Storage Clusters all in the same chunk?

And please can you add one more GC machine to that base for testing purposes - place down any GC machine which uses energy (for example, Oxygen Collector) so it is connected to the IC2 gold cable and we can see whether the cable disconnects from that block as well.

**Comment by pyure** [comment] 2015-01-24 07:11
Hi radfast.

Definitely could be because of other mods.  Enderio as you can see is in the mix.

It happens frequently when I leave the area, but not always.  Half the time perhaps. (3/4 times tonight but I wouldnt' say thats the prevalent trend)

The environment is server: specifically an Infitech2 modpack server.  Tonight I logged on for the first time and saw the problem right away.  I disconnected/reconnect from the server (without closing the client) and the issue resolved itself. 

Oxygen machine added.  I recreated the issue by teleporting far away and returning 30 seconds later.

Interestingly the oxygen machine did not disconnect. 
http://imgur.com/WSv5Ipt

Confirmed: cables and blocks are on same chunk.

**Comment by pyure** [comment] 2015-01-24 07:14
Also, and I have NO idea if this is relevant, but the max output sometimes flips between 228 eu/t and 274 eu/t.  I can't account for it.

**Comment by radfast** [comment] 2015-01-24 16:24
Max output of the Energy Storage Cluster?  Using /gcenergyunits EU?  That's strange that it flips, but it is not related to this connection issue.

Because the Oxygen Machine did not disconnect, I'm 99% sure now that this is an IC2 bug.  Energy Storage Cluster in GC uses the same code as Oxygen Collector for input connections, the only difference is that Energy Storage Cluster also adds the output connection.

**Comment by radfast** [comment] 2015-01-24 16:25
I suggest you add that oxygen machine image to the IC2 issue report.

**Comment by pyure** [comment] 2015-01-24 17:47
Understood, thx kindly as always.
