### ISSUE TITLE
Rocket Launch Pad Crash

### ISSUE THREAD

**Issue by roks12** [micdoodle8/Galacticraft#1513] opened 2015-03-22 11:31 UTC
When 9 launch pads are placed server crashes with this error

Description: Ticking block entity

java.lang.NoSuchFieldError: field_73244_f
	at micdoodle8.mods.galacticraft.core.blocks.BlockAdvancedTile.func_149749_a(BlockAdvancedTile.java:53)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:625)
	at net.minecraft.world.World.func_147465_d(World.java:793)
	at micdoodle8.mods.galacticraft.core.tile.TileEntityLandingPadSingle.func_145845_h(TileEntityLandingPadSingle.java:37)
	at net.minecraft.world.World.func_72939_s(World.java:2491)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Thread.java:745)

-- Head --
Stacktrace:
	at micdoodle8.mods.galacticraft.core.blocks.BlockAdvancedTile.func_149749_a(BlockAdvancedTile.java:53)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:625)
	at net.minecraft.world.World.func_147465_d(World.java:793)
	at micdoodle8.mods.galacticraft.core.tile.TileEntityLandingPadSingle.func_145845_h(TileEntityLandingPadSingle.java:37)

-- Block entity being ticked --
Details:
	Name: Landing Pad // micdoodle8.mods.galacticraft.core.tile.TileEntityLandingPadSingle
	Block type: ID #954 (tile.landingPad // micdoodle8.mods.galacticraft.core.blocks.BlockLandingPad)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (61,69,2284), Chunk: (at 13,4,12 in 3,142; contains blocks 48,0,2272 to 63,255,2287), Region: (0,4; contains chunks 0,128 to 31,159, blocks 0,0,2048 to 511,255,2559)
	Actual block type: ID #954 (tile.landingPad // micdoodle8.mods.galacticraft.core.blocks.BlockLandingPad)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:2491)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)

**Comment by radfast** [comment] 2015-03-22 12:50
It's a bug in Cauldron which has been there for 6 months, but Galacticraft only just started referencing it in .296.  Please update your server to 3.0.9.297 which has a fix.
http://ci.micdoodle8.com/job/Galacticraft-1.7/297/

(players do not need to update, they can stay on 296).

Alternatively everyone can update to 3.0.10, that's your call.

**Comment by radfast** [comment] 2015-03-22 12:51
Duplicate of #1508

**Closed by radfast** 2015-03-22 12:51 UTC
