### ISSUE TITLE
[1.11.2] : The cargo rocket never landed

### ISSUE THREAD

**Issue by Nicologique** [micdoodle8/Galacticraft#2820] opened 2017-06-09 09:59 UTC
Hello everyone,
I have a problem with the cargo rocket, I can send them to a carefree destination. On arrival, it slows down and stops slightly in the landing platform (I do not know if it is related). But even if it does not move anymore, the recteurs are always lit and consume fuel without I can stop or redo it.

    If this can help you, I try with a Tier 3 rocket, launched via a launch control and the same problem occurred. So I think there's a problem with launch control.

                         Thanks for your help.

**Comment by radfast** [comment] 2017-06-09 13:32
Duplicate of #2815 

We are looking at this and should be able to fix it in next version.  It's the "rocket has landed" detection which is not working correctly.

**Closed** 2017-06-09 13:32 UTC
Labels: duplicate
