### ISSUE TITLE
Oxygen Sealer Problems

### ISSUE THREAD

**Issue by Comixmunkey** [micdoodle8/Galacticraft#1545] opened 2015-04-05 04:08 UTC
Alright. I have a little oxygen sealer problem. I am using version 3.0.11.310 of galacticraft and the issue occurs on all dimensions (moon, mars, and the asteroids). Whenever I set up all the sealers in a confined space and get it to work, everything is working without issues. Then when I go back to earth and do stuff stuff there, then I go back to space to work on my base in whatever dimension. Then, when I go into my base (I properly set up airlocks at the entrance) the sealers are unsealed with the message: "Area too big/Unsealed". So I add a few more sealers then it works fine again. I go back to earth and come back, and when I go back inside, apparently my base magically expanded and the area is once again too big. So I add even more sealers, and of course it solved the problem. Then I go back to earth, come back, and then I get the same problem. Its a real pain to constantly make more oxygen sealers and wire them up, along with the increased demand of energy and oxygen. I even tried cutting off power and letting the power in them drain, then re-powering them as a sort of "reboot" and that doesn't work. The weird part is that I can light fire and yet, I still suffocate.
I tried everything and even read the wiki without any luck of solving the problem. 
![2015-04-05_10 17 25](https://cloud.githubusercontent.com/assets/11803062/6998247/8aec33a8-db9f-11e4-9c3c-8ac0ef80afc9.png)
![2015-04-05_10 20 00](https://cloud.githubusercontent.com/assets/11803062/6998248/8aef989a-db9f-11e4-9634-64c13ecb7b0f.png)
![2015-04-05_10 20 26](https://cloud.githubusercontent.com/assets/11803062/6998249/8b019a68-db9f-11e4-80e6-1bca44a59013.png)

**Comment by radfast** [comment] 2015-04-05 10:04
I don't much like your attitude.

Maybe start with:
1.  Which version of Galacticraft are you using
2.  Screenshot showing your build.

**Comment by Comixmunkey** [comment] 2015-04-05 15:03
Okay, listen. Looking back at what I said, I can see I was rude and I SINCERELY apologize for my attitude. I immediately regretted putting it that way the second I looked back on it. I hope that you don't see me as a mean guy as I was a little frustrated while writing it. Anyway, I edited my post and put the given information you asked for. I hope this will help future development.
Again, i'm sorry for that, I know programming isn't easy and I don't want to rush you on anything.
Keep up the good work! :D|

**Comment by radfast** [comment] 2015-04-06 21:01
OK all good, thank you for what you wrote, and that's a good looking Hollow Asteroid base.

If I understand correctly, the Oxygen Sealers are becoming unsealed when you use the airlock - even though you have a proper pair of airlocks?

The best way to troubleshoot this will be for you to enable Debug mode in Galacticraft core.conf
>     B:"Enable Debug Messages"=true

This will spam your log with messages about the oxygen sealers seal checks.  Please run through a whole cycle, like go back to the Overworld then take a rocket (or /dimensiontp command) back to your Asteroids base and post up the complete log from the arrival moment in the Asteroids dimension, for about 1-2 minutes after that.

__While testing, it would also be a good idea to use the Infinite Oxygen Supply item in all your Oxygen Sealers + Infinite Battery for testing purposes - this will show whether it is an issue with your build not having enough oxygen or not enough power.__

**Comment by Comixmunkey** [comment] 2015-04-07 00:47
Ok, I enabled the debug messages but for some reason nothing showed up in my chat. When I traveled to my asteroid base, the sealers were not sealed. I don't think its the airlock because when it was working, I spammed the airlock to see if it was the problem but everything remained sealed. So far the only thing that causes this is to leave the dimension and come back. Could it have something to do with chunk loading? I even put infinite oxygen supply and and the infinite battery in the system.
![2015-04-06_19 32 08](https://cloud.githubusercontent.com/assets/11803062/7015134/73ab2c4e-dc94-11e4-9a23-00d0cd32b86e.png)
The sealers didn't seem to initiate the seal check at any point.
I'm trying to give you all the information i can. I hope its helping.

**Comment by dj3520** [comment] 2015-04-07 00:49
The extra information from turning the debugging on would be in the server
log, not the chat.

**Comment by radfast** [comment] 2015-04-07 01:36
Chunk loading is certainly a possible cause.  Especially if:
* your base is large
* your power systems are spread out, like a crucial power link is far away
* you didn't think about chunk boundaries
* and if you don't already understand what's written here about chunk loading radius: http://wiki.micdoodle8.com/wiki/Sealed_Space#Example_of_correct_sealer_spacing

To eliminate these possible causes, we need you to put Infinite Oxygen + Infinite Battery in __all your Oxygen Sealers__ not just in the system some other place, because maybe that other place did not chunk load.  The screenshot you posted just now, shows there is no infinite oxygen + battery item in that sealer.  Put infinite items in __all__ the sealers then test going away and coming back to your base and see how the seal is.

**Comment by radfast** [comment] 2015-05-04 14:02
Any update on this?  It's been 4 weeks.  I will close soon if there's no update, as it seems likely the cause of the issue is chunk loading for different chunks at different times meaning that the sealers have no power for a while.

**Comment by TheQuadShot** [comment] 2015-06-17 08:12
I was having a problem with them as well, but my issue was getting them to initially seal an are. The thing that "fixed" it for me was to replace the floor with stone. With moon turf I couldn't get them to work. I don't have a problem with it becoming un-sealed, but I have power and o2 storage units in one chunk (based on nei info). Hope that helps some :)

**Comment by radfast** [comment] 2016-01-11 03:51
I'm closing this issue.  It is very old and the OP never came back with an update.  I still believe the most likely cause was chunkloading issues caused by the vanilla Minecraft engine.

@TheQuadShot there is no sealing difference between moon turf and stone.  My guess is there may have been a 1-block difference in your build or something else which you didn't think of letting out the air, and you replaced that block also with stone.

**Closed by radfast** 2016-01-11 03:51 UTC
