### ISSUE TITLE
Ticking World Crash (related?)

### ISSUE THREAD

**Issue by DeinoRaptor** [micdoodle8/Galacticraft#3074] opened 2018-01-02 22:06 UTC
I have been getting this new crash just today. I am not sure what is causing it, but I think it is a Galacticraft Mod or Addon (which is a majority of my pack). I would like help.

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 1/2/18 1:21 PM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:144)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:144)

-- Affected level --
Details:
	Level name: wwwww
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 0 Drop: 0
	Level seed: 5341901272786124469
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 358219064 bytes (341 MB) / 922746880 bytes (880 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_E3 48 mods loaded, 48 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	finitewater{0.2} [finitewater] (minecraft.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems_1.7.10_1.0.5.120_universal.jar) 
	UCHIJAAAA	tickratechanger{1.0.2e} [Tickrate Changer] (minecraft.jar) 
	UCHIJAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.502.jar) 
	UCHIJAAAA	SpaceCore{4.1.9} [4Space Core] (4Space-4.1.9.jar) 
	UCHIJAAAA	ExoCore{0.1.2} [4Space Exoplanets Core] (4Space-4.1.9.jar) 
	UCHIJAAAA	ExoElipse{0.1.2} [4Space Exoplanets Elipse] (4Space-4.1.9.jar) 
	UCHIJAAAA	SpaceCallisto{4.1.9} [4Space Callisto] (4Space-4.1.9.jar) 
	UCHIJAAAA	SpaceEuropa{4.1.9} [4Space Europa] (4Space-4.1.9.jar) 
	UCHIJAAAA	SpaceVenus{4.1.9} [4Space Venus] (4Space-4.1.9.jar) 
	UCHIJAAAA	SpaceIo{4.1.9} [4Space Io] (4Space-4.1.9.jar) 
	UCHIJAAAA	SpaceMercury{4.1.9} [4Space Mercury] (4Space-4.1.9.jar) 
	UCHIJAAAA	SpacePluto{4.1.9} [4Space Pluto] (4Space-4.1.9.jar) 
	UCHIJAAAA	Paleocraft{1.7.10 Cambrian 1.6.0} [Paleocraft] ([1.7.10] Paleocraft Cambrian 1.6 BETA 2.jar) 
	UCHIJAAAA	ccritter{1.7.10-0.3.4c} [CCritter] (ccritter-1.7.10-0.3.4c.jar) 
	UCHIJAAAA	BuildMod{v1.0} [Build Mod] (coroutil-1.7.10-1.1.5.jar) 
	UCHIJAAAA	CoroPets{v1.0} [CoroPets] (coroutil-1.7.10-1.1.5.jar) 
	UCHIJAAAA	CoroAI{v1.0} [CoroAI] (coroutil-1.7.10-1.1.5.jar) 
	UCHIJAAAA	ExtendedRenderer{v1.0} [Extended Renderer] (coroutil-1.7.10-1.1.5.jar) 
	UCHIJAAAA	ConfigMod{v1.0} [Extended Mod Config] (coroutil-1.7.10-1.1.5.jar) 
	UCHIJAAAA	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d(29oct17).jar) 
	UCHIJAAAA	DamageIndicatorsMod{3.2.0} [Damage Indicators] (damage_indicators_mod_1.7.10.jar) 
	UCHIJAAAA	darwin{1.0} [Darwin Unofficial] (Darwin-1.1.jar) 
	UCHIJAAAA	ExtendedPlanets{1.3.1 ALPHA} [Extended Planets] (ExtendedPlanets-1.3.1 ALPHA.jar) 
	UCHIJAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.502.jar) 
	UCHIJAAAA	ExtraPlanets{1.9.2} [Extra Planets] (ExtraPlanets-1.9.2.jar) 
	UCHIJAAAA	GCFarScape{0.0.1} [FarScape] (Farscape-0.0.1 Pre-alpha.jar) 
	UCHIJAAAA	fnafmod{1.0} [FNaF Universe Mod] (FNaFUniverseMod-1.7.10_v11.6_.jar) 
	UCHIJAAAA	llibrary{1.5.1} [LLibrary] (llibrary-1.5.1-1.7.10.jar) 
	UCHIJAAAA	fossil{7.3.2} [Fossils and Archeology Revival] (fossilsarcheology-7.3.2.jar) 
	UCHIJAAAA	GalaxySpace{1.1.9} [GalaxySpace] (GalaxySpace-1.1.9 STABLE.jar) 
	UCHIJAAAA	hungryanimals{1.7.10-10.13.2.1291-1.0.4.2} [Hungry Animals] (hungryanimals-1.0.4.2.beta014.jar) 
	UCHIJAAAA	kerencysystem{1.0.0} [Kerency Space System] (Kerency Addons-1.7.jar) 
	UCHIJAAAA	manysystems{0.9.8.2 ALPHA} [Many Systems] (Many Systems-0.9.8.5 BETA.jar) 
	UCHIJAAAA	MorePlanet{1.4.4} [More Planets] (More-Planets-1.7.10-1.4.4-GC502.jar) 
	UCHIJAAAA	starwarsmod{1.3.3} [Parzi's Star Wars Mod] (Parzi's Star Wars Mod v1.3.3.jar) 
	UCHIJAAAA	GCPixelGalaxy{0.9.3} [Pixel Galaxy] (PixelGalaxy_1.0.0SNS14w01aAlpha_1.7.jar) 
	UCHIJAAAA	SpaceAdvanced{0.5.3} [SpaceAdvanced] (Space Advanced 0.5.4.0.1.jar) 
	UCHIJAAAA	tropicraft{v6.0.5} [Tropicraft] (tropicraft-6.0.5.jar) 
	UCHIJAAAA	VacuumHorizon{AV-0.4} [Vacuum Horizon] (VacuumHorizon[AV-0.4].jar) 
	UCHIJAAAA	weather2{v2.3.11} [Localized Weather & Storms] (weather2-1.7.10-2.3.10.jar) 
	UCHIJAAAA	worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.7.10-6.1.1-dist.jar) 
	UCHIJAAAA	ZoocraftDiscoveries{1.0} [Zoocraft Discoveries] (Zoocraft Discoveries 1.7.10-1.1.0.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.7.10_HD_U_E3
	Render Distance Chunks: 7
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13397 Compatibility Profile Context 15.200.1055.0
	OpenGlRenderer: AMD Radeon HD 7500G
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 2

**Comment by radfast** [comment] 2018-01-03 01:00
This is an issues list for reporting issues discovered in the Galacticraft mod.

It is not a place for discussing issues in Galacticraft Add-ons, or in other mods.  It is not a place for asking for general Minecraft or modpack help.

Judging from your other recent reports, it seems unlikely that it's a Galacticraft issue, and therefore for now I will close this.

If you can show that the issue is in Galacticraft - for example, by testing with Galacticraft as the only mod installed - then we can re-open this.

**Closed by radfast** 2018-01-03 01:00 UTC

**Comment by radfast** [comment] 2018-01-04 15:31
You have the following mods present, apart from Galacticraft:

```CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar)
finitewater{0.2} [finitewater] (minecraft.jar)
Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar)
NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems_1.7.10_1.0.5.120_universal.jar)
tickratechanger{1.0.2e} [Tickrate Changer] (minecraft.jar)
SpaceCore{4.1.9} [4Space Core] (4Space-4.1.9.jar)
ExoCore{0.1.2} [4Space Exoplanets Core] (4Space-4.1.9.jar)
ExoElipse{0.1.2} [4Space Exoplanets Elipse] (4Space-4.1.9.jar)
SpaceCallisto{4.1.9} [4Space Callisto] (4Space-4.1.9.jar)
SpaceEuropa{4.1.9} [4Space Europa] (4Space-4.1.9.jar)
SpaceVenus{4.1.9} [4Space Venus] (4Space-4.1.9.jar)
SpaceIo{4.1.9} [4Space Io] (4Space-4.1.9.jar)
SpaceMercury{4.1.9} [4Space Mercury] (4Space-4.1.9.jar)
SpacePluto{4.1.9} [4Space Pluto] (4Space-4.1.9.jar)
Paleocraft{1.7.10 Cambrian 1.6.0} [Paleocraft] ([1.7.10] Paleocraft Cambrian 1.6 BETA 2.jar)
ccritter{1.7.10-0.3.4c} [CCritter] (ccritter-1.7.10-0.3.4c.jar)
BuildMod{v1.0} [Build Mod] (coroutil-1.7.10-1.1.5.jar)
CoroPets{v1.0} [CoroPets] (coroutil-1.7.10-1.1.5.jar)
CoroAI{v1.0} [CoroAI] (coroutil-1.7.10-1.1.5.jar)
ExtendedRenderer{v1.0} [Extended Renderer] (coroutil-1.7.10-1.1.5.jar)
ConfigMod{v1.0} [Extended Mod Config] (coroutil-1.7.10-1.1.5.jar)
customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d(29oct17).jar)
DamageIndicatorsMod{3.2.0} [Damage Indicators] (damage_indicators_mod_1.7.10.jar)
darwin{1.0} [Darwin Unofficial] (Darwin-1.1.jar)
ExtendedPlanets{1.3.1 ALPHA} [Extended Planets] (ExtendedPlanets-1.3.1 ALPHA.jar)
ExtraPlanets{1.9.2} [Extra Planets] (ExtraPlanets-1.9.2.jar)
GCFarScape{0.0.1} [FarScape] (Farscape-0.0.1 Pre-alpha.jar)
fnafmod{1.0} [FNaF Universe Mod] (FNaFUniverseMod-1.7.10_v11.6_.jar)
llibrary{1.5.1} [LLibrary] (llibrary-1.5.1-1.7.10.jar)
fossil{7.3.2} [Fossils and Archeology Revival] (fossilsarcheology-7.3.2.jar)
GalaxySpace{1.1.9} [GalaxySpace] (GalaxySpace-1.1.9 STABLE.jar)
hungryanimals{1.7.10-10.13.2.1291-1.0.4.2} [Hungry Animals] (hungryanimals-1.0.4.2.beta014.jar)
kerencysystem{1.0.0} [Kerency Space System] (Kerency Addons-1.7.jar)
manysystems{0.9.8.2 ALPHA} [Many Systems] (Many Systems-0.9.8.5 BETA.jar)
MorePlanet{1.4.4} [More Planets] (More-Planets-1.7.10-1.4.4-GC502.jar)
starwarsmod{1.3.3} [Parzi's Star Wars Mod] (Parzi's Star Wars Mod v1.3.3.jar)
GCPixelGalaxy{0.9.3} [Pixel Galaxy] (PixelGalaxy_1.0.0SNS14w01aAlpha_1.7.jar)
SpaceAdvanced{0.5.3} [SpaceAdvanced] (Space Advanced 0.5.4.0.1.jar)
tropicraft{v6.0.5} [Tropicraft] (tropicraft-6.0.5.jar)
VacuumHorizon{AV-0.4} [Vacuum Horizon] (VacuumHorizon[AV-0.4].jar)
weather2{v2.3.11} [Localized Weather & Storms] (weather2-1.7.10-2.3.10.jar)
worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.7.10-6.1.1-dist.jar)
ZoocraftDiscoveries{1.0} [Zoocraft Discoveries] (Zoocraft Discoveries 1.7.10-1.1.0.jar)```

It's likely one of those is causing the problem, or maybe two of them in combination.

For a start, we **strongly advise against** combining lots of different Galacticraft add-ons unless you have tested them carefully for compatibility.

You should also understand that most of the minor add-ons for Galacticraft 1.7.10 were in alpha or beta unstable versions, never stable final releases.  You'll be lucky if they are still supported by their authors.  If you're having problems with one of them, you should remove it from your pack.
