### ISSUE TITLE
GC3 r232: Missing NEI usage support for some items

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#1251] opened 2014-11-15 12:34 UTC
Small issue.

NEI doesn't show the usage of some items, as fuel or crafting recipe, in some Galacticraft machines:

* Charcoal and coal as fuel in the Coal Generator and the Compressor.
* (more to come)

EDIT: scratch "(more to come)" part. I haven't found any other issues of this kind.

**Comment by radfast** [comment] 2016-02-29 02:05
Looking at NEI today, so I took another look at this.

I don't think we have any NEI display at all for electricity generation in the Coal Generator, because no item is created.  Does this need changing?  We don't have displays for other generators or machines which do not create items, they are not really something for NEI to cover.  For example there is no display to show that you can charge items in a Energy Storage Module.

The Ingot Compressor animation shows fuel being consumed, including coal, saplings, etc, so that is working correctly.  [It appears to be NEI policy](https://github.com/micdoodle8/Galacticraft/blob/master/dependencies/main/java/codechicken/nei/recipe/FurnaceRecipeHandler.java#L104) that fuel items are shown only once in NEI, for the vanilla furnace only - "sub-classes" in the code comment there means anything in any mod which is based on a furnace.  That kind of makes sense, otherwise for common fuel items like wooden planks, you could have 50+ NEI usage pages covering each mod's different fuel-burning machines.  That would be bad, I think, so I respect this choice.  Also I think all Minecraft players understand about fuels that can be used (anyhow, the Ingot Compressor animation shows them).

Small point: the Coal Generator does not accept charcoal, only coal.  It's a very non-green device.  We want people to be using solar as soon as possible ... :)

I think this can be closed as 'Intended Behaviour'.

**Closed by radfast** 2016-02-29 02:05 UTC
Labels: minor

**Comment by radfast** [comment] 2016-02-29 02:11
I've updated the LEFT SHIFT description of the Coal Generator.

**Comment by EzerArch** [comment] 2016-02-29 02:44
Thank you.
