### ISSUE TITLE
[1.11.2] thermal gear render error

### ISSUE THREAD

**Issue by Agentx49** [micdoodle8/Galacticraft#2610] opened 2017-04-17 13:18 UTC
when you put on thermal gear this happens:
![2017-04-17_09 12 59](https://cloud.githubusercontent.com/assets/26726223/25089951/9eafe8d2-234e-11e7-931e-a49a2893f2f9.png)
![2017-04-17_09 15 22](https://cloud.githubusercontent.com/assets/26726223/25089952/9eb39680-234e-11e7-8e67-a1a028a4c7ce.png)

**Comment by radfast** [comment] 2017-04-17 14:22
Thank you for beta testing.

This seems like a duplicate of #2600.

**Comment by micdoodle8** [comment] 2017-05-15 19:23
I can't seem to recreate this. Are you using anything that would alter texture resolution?

**Comment by radfast** [comment] 2018-03-12 17:26
Closing due to lack of information and nobody else has reported similar.

(This must be caused by a change made by another mod, or else someone changed things in a resource pack?)

**Closed by radfast** 2018-03-12 17:26 UTC
Labels: cant reproduce, rendering
