### ISSUE TITLE
Invisible yet (sometimes) breakable blocks

### ISSUE THREAD

**Issue by SEC9Bigfoot** [micdoodle8/Galacticraft#1382] opened 2015-01-14 23:46 UTC
Unable to see/interact with a few different placed machinery blocks. The ones I tested include most of the oxygen machines (not including the detector or storage block) and a few generators.

I had a similar issue with the Advanced Solar Panel(Array?) except I was able to physically interact with at least the panel itself.

Also experienced a crash when placing at least one of the 3 walkway types. Tried the plain walkway first, no issues there. Unfortunately though, this made it impossible to load into the game, but since I'm bug testing my pack, it was a brand new world. So also no worries there. :)

Crash log:
http://pastebin.com/69BtzKzA

I just checked your download page and I am now trying the 254 build. I was running 252. I'll update if this is still an issue. May have just been a download error that lost some texture and/or class files. Thanks! :)

Edit:
Just tried placing an Adv. Solar Panel running a fresh copy of the newest version and got the same invisible result. Don't particularly want to test the Walkway, but since I can just reload the world, I will if you need me to.

**Comment by radfast** [comment] 2015-01-15 01:56
Must be something weird with your modpack, there are no invisible machine blocks in Galacticraft. Are you able to test Galacticraft:  a. alone and  b.  with a reduced set of other mods from your pack?

**Comment by radfast** [comment] 2015-01-15 02:03
That crash, which is not connected with the invisible blocks issue.  It's because you have another mod in your pack which has brought a pre-6.3.1 version of the Buildcraft API into your pack as well as 6.3.1 Buildcraft, so basically two different, incompatible versions of the Buildcraft API.  You need to fix that.  Meanwhile there's a setting in Galacticraft config to help, look up Buildcraft on the Galacticraft wiki.

**Comment by Cracks777** [comment] 2015-01-21 02:42
![invis](https://cloud.githubusercontent.com/assets/10608111/5830347/cf605ac8-a0e4-11e4-8465-73a8e824e302.jpg)


Is this what you mean, this is what is happening to me?

**Comment by radfast** [comment] 2015-02-03 01:47
Any follow-up on this?

I asked whether you were seeing the same issue with only Galacticraft installed, no other mods?
(Test this in a new world, obviously: it will delete blocks from any existing world.)

If the issue goes away if Galacticraft is installed without other mods, then you can put back other mods into the /mods folder until the issue starts happening, then you will know which mod is the problem one.

**Comment by radfast** [comment] 2015-03-01 12:52
Generally issues like this happen because of causes like:
* different Forge versions or different versions of a mod (not necessarily Galacticraft, could be a different mod) on client and server
* one of your mods is not a 1.7.10 version or needs updating
* conflict between two different mods

If you can give more information about which exact other mod is conflicting with Galacticraft - like test only those two mods together and you still see the same invisible blocks problem - then let us know and I will happily look into it some more.  Closing this issue meanwhile.

**Closed by radfast** 2015-03-01 12:52 UTC
Labels: missing info

**Comment by Cracks777** [comment] 2015-03-01 16:09
sorry i totaly lost this one. ill have to test. i still get this sometimes tho.

**Comment by radfast** [comment] 2015-03-01 16:18
OK - if you can get it down to "this happens with only X other mod and Galacticraft" then I am happy to look into this further, but it seems like it must be one of the causes I mentioned because most people do not have this issue.

**Comment by Cracks777** [comment] 2015-03-01 16:23
ok thank you.
