### ISSUE TITLE
circuit fabricator does nothing

### ISSUE THREAD

**Issue by acegoal07** [micdoodle8/Galacticraft#3691] opened 2019-05-15 16:16 UTC
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 210

Single player (SSP)

full modlist as needed
![Capture](https://user-images.githubusercontent.com/39467245/57792038-f240b180-76f2-11e9-897b-9911b3ddcbc7.PNG)

when i go to make anything in the circuit fabricator it does nothing

**Comment by marcus8448** [comment] 2019-05-15 22:43
Please post logs (preferably on gist or pastebin). Are you sure you're putting in the correct items? It seems fine for me.

**Comment by acegoal07** [comment] 2019-05-16 06:44
I have tried all the combinations to make something in it and it does nothing.

**Comment by marcus8448** [comment] 2019-05-17 01:33
Can you post a log?

**Comment by TheQuadShot** [comment] 2019-05-17 05:17
maybe a silly question, but. Did you provide power? and if so, could you provide some screen shots of your set up?

**Comment by acegoal07** [comment] 2019-05-17 14:57
![2019-05-17 3 47 32 pm](https://user-images.githubusercontent.com/39467245/57936480-ec74d880-7878-11e9-81c4-c70f32272381.jpeg)

[2019-05-17 3.56.16 pm.mov.zip](https://github.com/micdoodle8/Galacticraft/files/3192009/2019-05-17.3.56.16.pm.mov.zip)

**Comment by acegoal07** [comment] 2019-05-17 18:16
@marcus8448 I don’t know how to get a log

**Comment by TheQuadShot** [comment] 2019-05-18 03:31
In "most" cases it's in %appdata%/.mineccraft/logs/latest.log
else it is in the logs directory where you installed minecraft

**Comment by acegoal07** [comment] 2019-05-18 06:39
I don’t know if this has anything to do with it but as this issue started Minecraft always crashes when I try and quit it

**Comment by acegoal07** [comment] 2019-05-18 07:26
[latest.log](https://github.com/micdoodle8/Galacticraft/files/3193782/latest.log)

that's the most recent log

**Comment by dj3520** [comment] 2019-05-19 16:34
The crashing on quit seems to be whatever launcher you're using.
Can you screenshot opening the circuit fabricator and trying to use it?
Also your buildcraft is outdated.

**Comment by acegoal07** [comment] 2019-05-19 16:45
Thanks for point out that build craft is outdated and I have also fixed the launcher crashing.

And in the screenshot I put stuff in and waited a couple seconds.

**Comment by TheQuadShot** [comment] 2019-05-19 22:47
I'm thinking your problem is with power, since you have BuildCraft; it handles power differently, and your UI doesn't show the power "level" as seen on the WIKI https://wiki.micdoodle8.com/wiki/Circuit_Fabricator
You should also check out https://wiki.micdoodle8.com/wiki/BuildCraft and re-check your config
(power-GC.conf)

**Comment by acegoal07** [comment] 2019-05-20 12:46
Thanks for helping finding the issue but I am not sure I have to do to fix it

**Comment by acegoal07** [comment] 2019-05-21 16:08
@TheQuadShot I have been messing around with my mods and even when I don’t have buildcraft installed the circuit fabricator still does nothing (only the circuit fabricator does not work everything else works)

**Comment by dj3520** [comment] 2019-05-21 17:30
@TheQuadShot There's nothing buildcraft power related here. A GC solar panel powering a GC circuit fabricator. And the amount of power in the machine does not need to be 100% to start the process. 

From what I can tell this might be a valid issue. Might have to wait until one of the developers reviews this before it can move forward. Until then the only thing I can suggest doing is start installing older versions of Galacticraft until the circuit fabricator works. If the exact versions for when it worked and when it stopped working are found, the changes between those two versions can be seen as a possible culprit towards this problem, which could speed up getting it fixed.

**Comment by acegoal07** [comment] 2019-05-21 18:00
Okay I will go through and find a version that it works on and report back

**Comment by MJRLegends** [comment] 2019-05-21 18:17
Btw your buildcraft version was downloaded from 9minecraft and thats wrong and wont work

**Comment by MJRLegends** [comment] 2019-05-21 18:18
And iron chests, refined storage, and a few others. Basically im not surprised your having issues

**Comment by acegoal07** [comment] 2019-05-21 20:49
I have been able to fix the issue it was an issue with the mod nuclearcraft

**Comment by dj3520** [comment] 2019-05-25 18:44
If the issue is resolved, please close this report. Also never download mods from 9minecraft. Always go to official sources like the mod author's site or curseforge.

**Closed** 2019-05-25 18:46 UTC
