### ISSUE TITLE
[1.10.2]  [InventoryTweaks installed] Cannot create space station (Creative)

### ISSUE THREAD

**Issue by BrisingrAerowing** [micdoodle8/Galacticraft#2730] opened 2017-05-20 20:16 UTC
For some reason, the button to create a space station on the galaxy map screen doesn't work, only exiting out of the selection of the overworld.

This was tried in creative, both with and without the needed item in my inventory.

Galacticraft 4.0.0.91 (Also .89)
Minecraft 1.10.2
Forge 12.18.3.2297

[Modlist](http://www.modlister.com/user/BrisingrAerowing)

(Yeah, I have lots of mods)

**Comment by micdoodle8** [comment] 2017-05-20 22:33
Going to need the server log after you try creating a space station. It might provide an easy solution to the problem.

**Comment by BrisingrAerowing** [comment] 2017-05-20 22:47
This was a singleplayer world. I will get the logs as soon as I get my instance running again (I got rid of a few mods I didn't like all that much, and in doing so corrupted the instance in MultiMC somehow, so I have had to rebuild it :-/)

**Comment by BrisingrAerowing** [comment] 2017-05-20 23:16
I found where the event should have happened in the logs (right towards the bottom), and there is nothing related to this there.


[latest.log.txt](https://github.com/micdoodle8/Galacticraft/files/1016559/latest.log.txt)

**Comment by BrisingrAerowing** [comment] 2017-05-20 23:29
I looked at the Celestial Selection GUI code, and found that the only place an instance is created passes true for mapMode, but the station creation code is in an if with !mapMode, preventing said code from running, or am I missing something here? I used the search feature to find the class name, BTW.

**Comment by radfast** [comment] 2017-05-20 23:30
How did you get to the Galaxy Map Screen?

You flew in a rocket?  Or you pressed 'M'?

**Comment by radfast** [comment] 2017-05-20 23:47
Please try without any of the Galacticraft add-ons (Blank Planet, Extra Planets, etc), it could be one of them causing this.

**Comment by BrisingrAerowing** [comment] 2017-05-21 00:13
I just tested with Galacticraft, Extra Planets, and Blank Planet to see if the issue occurred in a minimal setup and it does, so I can rule out all my other mods.

(Thank God for that, I did NOT want to go through my modlist one by one to find the issue)

I just removed Blank Planet to test without that, and if it still doesn't work I will try without Extra Planets as well.

I should report back soon (this instance doesn't take long to load)

**Comment by BrisingrAerowing** [comment] 2017-05-21 00:26
It was Blank Planet causing this. Not sure why I installed it in the first place, actually. I'll just remove it for now.

**Comment by radfast** [comment] 2017-05-21 00:29
ok, good job, I'm pleased the cause is identified.

@MJRLegends ...

**Comment by BrisingrAerowing** [comment] 2017-05-21 01:53
I just came across the same issue with all mods readded. I have two major suspects, both of which do major changes to GUIs. I will test without those and see what happens (the most likely is RPG-HUD, which completely changes the HUD to a custom system. The other is NEI, as that has a lot of GUI ASM stuff).

**Comment by radfast** [comment] 2017-05-21 02:24
can you be more specific about "doesn't work"?
are the recipe items matching the numbers that you actually have in your inventory?
what colour is the button?
does the button respond to the mouse, only it's not doing what it should (ie creating a station)?
also a world should only allow a player to create a space station once, is it possible with all the changes that it's flagged that you've done that?  best to test in a new world, I suggest

**Comment by MJRLegends** [comment] 2017-05-21 02:28
I doubt BlankPlanet is causing this issue unless you have changed a config option to cause it

**Comment by BrisingrAerowing** [comment] 2017-05-21 14:06
I just found the actual culprit: InventoryTweaks!

**Comment by radfast** [comment] 2017-05-21 15:02
ok thank you, I'll re-open this

**Comment by BrisingrAerowing** [comment] 2017-05-21 17:36
BTW, I was using the latest 1.10.2 Alpha of Inventory Tweaks, as that fixed a few bugs. I haven't tried the actual release version yet.

**Comment by radfast** [comment] 2017-05-21 19:03
@BrisingrAerowing  thanks for alerting us to this.

It's not a mod conflict, it's much more prosaic than that!  Just the button is now drawn in a different place (maybe also dependent on your language).  Click around "1 line of text" higher than the drawn 'Create' button and it still works.

I'll close this issue now, and keep issue #2735 open if that's OK with you, as SteveKunG who made that issue is one of the developers contributing to the mod.

**Closed by radfast** 2017-05-21 19:03 UTC
Labels: 1.10+, conflict, Priority

**Comment by BrisingrAerowing** [comment] 2017-05-21 19:59
That's an interesting glitch.

**Comment by radfast** [comment] 2017-05-21 20:04
Fixed in new build 95, please update :)
