### ISSUE TITLE
GALACTICRAFT 1.7.10 HUGE ERROR!!!

### ISSUE THREAD

**Issue by fosra** [micdoodle8/Galacticraft#2044] opened 2016-01-24 05:44 UTC
I was playing on a private modded server with my friend. We were in the asteroid belt and tried to take off with rockets to go back to the overworld but when we did the server crashed. (common error we noticed when we try to take off sometimes) When we loaded back in i was the first in and i spawned in the overworld. I noticed that the game was really laggy. Like more laggy than normal. I flew around a little and found the source of the lagging. And my friend was freaking out reading the server script. It said that galacticraft core had had an error that replaced a bunch of things in the game with other things. For example it turned stone brick into redstone blocks, ballons for archamedes ship mod was turned into coffins from a dinosaur mod, and tree leaves into electronic fridges. Also we had made a shop using custom npcs mod and it cost 1 gold coin for a invintory pet, but it turned it into nano helmet for a wierd green thing that wasent supposed to be in the game. It just kept getting worse and worse until we were forced to delete all of the files for the server and start over with a fresh world and carefully picked mods NOT including galacticraft until this glitch is noted and fixed. I hope that it dosent ruin anyone elses server/world. Please try to fix this because it took us a long time to fix the server because this glitch completely broke it.

**Comment by dj3520** [comment] 2016-01-24 06:04
Highly doubt this is a Galacticraft issue, especially with all of the other
mods involved. Sounds like item IDs to me but that's a 1.6.4 thing.

**Comment by fosra** [comment] 2016-01-24 06:06
I said the same thing to my friend but he read all of the script from the server and it said that galacticraft changed all these things and that we should report it

**Comment by XFactHD** [comment] 2016-01-24 11:35
What about posting a log snippet of this HUGE ERROR?

**Comment by fosra** [comment] 2016-01-24 15:52
I will and a picture of the trees after they turned

**Comment by radfast** [comment] 2016-01-24 18:08
I'm closing this.

Paste (or link to) server logs covering when this happened, and if it's a problem caused by Galacticraft we will re-open this.

**Closed by radfast** 2016-01-24 18:08 UTC
