### ISSUE TITLE
[1.10.2] Game still crashes when its ran with GC, BiomeTweaker

### ISSUE THREAD

**Issue by mchetvorkata** [micdoodle8/Galacticraft#2520] opened 2017-04-08 13:00 UTC
Game crashes on bootup when i try to run BiomeTweaker and Galacticraft!

here is a crash report: https://pastebin.com/vmfSPwz9

**Comment by ThomasAunvik** [comment] 2017-04-08 14:51
Tried it. But i somehow got a different crash report.
You used BiomeTweaker version: 2.1.230,
I used BiomeTweaker version: 2.3.246

This is the crash report that i got:
[Client Server Crash Report](https://pastebin.com/gcQXZFLv)

**Comment by ThomasAunvik** [comment] 2017-04-08 19:11
Duplicate of https://github.com/micdoodle8/Galacticraft/issues/2520

**Comment by radfast** [comment] 2017-04-09 15:07
@mchetvorkata  The crash report you posted is caused by a bug in BiomeTweaker, I think they fixed it in https://github.com/superckl/BiomeTweaker/commit/e3197b3b01d548e52ea311a62cb8e22d02204bf4 so maybe if you update BiomeTweaker that will fix it.

@ThomasAunvik the issue you have posted is a duplicate of #2481 

This can be closed.  I'm flagging it as not a Galacticraft issue, because the issue in the OP was caused by BiomeTweaker, not by GC.

**Closed by radfast** 2017-04-09 15:07 UTC

**Comment by radfast** [comment] 2017-04-15 03:12
The crash with the up-to-date versions of BiomeTweaker (2.3.246 and after) is fixed from our next build 64.
