### ISSUE TITLE
Compatibility problem with the Spider Queen reborn mod. 

### ISSUE THREAD

**Issue by Volter967** [micdoodle8/Galacticraft#1437] opened 2015-02-09 00:23 UTC
I've Been playing Minecraft ever since it very first came out. And the Spider Queen mod was the first mod I've ever played on and it was amazing in till the mod died off. Finally someone remade the mod and I fell back in love. I also really love this space mod. I tried to put the two together and yeah it works just fine everything is functional. But the spider queen model (which looks f*cking alsome) is over righted to look like Steve. I have no clue why and it is so annoying. Please help.

-Thank you.
-Volter

**Comment by radfast** [comment] 2015-02-09 02:17
I'm not seeing why this is a Galacticraft issue.
Maybe post your fml-client-latest.log and a screenshot of the issue and I'll take a look

**Comment by Robijnvogel** [comment] 2015-02-09 15:55
You might want to take a look at #1428 
I am not saying that this is and/or solves your problem, but it has similarities.

**Comment by radfast** [comment] 2015-02-09 16:15
I'm assuming that @Volter967 is playing Single Player here, not on a server.  Please confirm, @Volter967 ?

(#1428 was an issue in Multiplayer due to the server and the client using different versions of the same mods.)

**Comment by Volter967** [comment] 2015-02-09 22:58
Yes I'm playing on single player. And Yeah let me get a picture.

**Comment by Volter967** [comment] 2015-02-09 23:08
![2015-02-09_18 05 38](https://cloud.githubusercontent.com/assets/5566968/6117938/99e7bd76-b086-11e4-802b-e8e326a7f02f.png)

With out the Galacticraft mod installed. (Spider queen model working fine)

**Comment by Volter967** [comment] 2015-02-09 23:09
WIth Galacticraft installed. 
(Spider queen model replaced by steve)

![2015-02-09_18 01 50](https://cloud.githubusercontent.com/assets/5566968/6117963/c6ad08ca-b086-11e4-9c05-52721676d0be.png)

**Comment by Volter967** [comment] 2015-02-09 23:09
(don't worry about the texture of the grass it's just a texture pack)

**Comment by radfast** [comment] 2015-02-10 10:35
Please download and install the mod "RenderPlayerAPI" and let me know if that makes a difference?

(RenderPlayerAPI will not change anything in the game, it just makes Galacticraft, and other mods like Galacticraft, behave differently.)

**Comment by radfast** [comment] 2016-01-30 13:38
Closing this now due to no reply in 12 months ...

Like I said, this type of issue should be fixed by installing PlayerAPI + RenderPlayerAPI.
If not, then the problem is in the other mod.

**Closed by radfast** 2016-01-30 13:38 UTC
Labels: conflict, minor, missing info, rendering

**Comment by Robijnvogel** [comment] 2016-01-30 15:33
Doesn't Galacticraft have a general incompatibility with Player API, Smart Moving etc. ?
A week ago, I tested my modpack with the latest version of both and my console log was spammed with render errors for Galacticraft mobs. The problem stopped after I removed Player API etc.

**Comment by radfast** [comment] 2016-01-30 20:17
> Doesn't Galacticraft have a general incompatibility with Player API, Smart Moving etc. ?

No!  Why would you think that?  If someone on a forum (etc) told you that, I'd like a quiet word with them please ....

We are [fully compatible](http://wiki.micdoodle8.com/wiki/Compatibility) with both PlayerAPI and Smart Moving.

Seems like you may be using an out of date Galacticraft.  If there's render errors or log spam in the current version, obviously I'd like to know about it ... let's see those logs.

**Comment by Robijnvogel** [comment] 2016-01-31 08:28
My bad, it was actually Father Toast's SpecialMobs that was incompatible with Smart Moving and Galacticraft showing up in the stacktrace, because of its SM compatibility I guess?
http://pastebin.com/qJ4N7zV2

**Comment by radfast** [comment] 2016-01-31 15:10
The log that you posted shows an issue which formerly happened when a skeleton spawned wearing non-vanilla armor (for example, Glowstone armor from Mekanism).  That issue was fixed at least 2 weeks ago, it is definitely fixed in latest Galacticraft.

**Comment by Robijnvogel** [comment] 2016-02-06 15:38
Actually, this happens with the latest Galacticraft, Smart Moving (and Render) and Player API:
http://pastebin.com/fYLkBGf3

And yes, I am that same guy that told you some fable because of "mixing up stacktraces"...
