### ISSUE TITLE
Mining a meteor crashed the game

### ISSUE THREAD

**Issue by veiko45** [micdoodle8/Galacticraft#3078] opened 2018-01-05 16:24 UTC
Minecraft version: 1.10.2
Galacticraft version: 4.0.1.120
Forge version: 12.18.3.2551

Single player (SSP) or Multiplayer (SMP)?
SSP
Galacticraft add-ons and other mods installed?
GC Planets and Extra Planets: Space Astronomy 2 modpack on Curseforge
Please provide screenshots / crash report / log as needed.
https://pastebin.com/pXKv3P17

**Comment by MJRLegends** [comment] 2018-01-05 16:56
Im unable to reproduce this myself with my mod pack (Space Astronomy 2)

**Comment by MJRLegends** [comment] 2018-01-05 16:57
Oh wait i just managed to reproduce it

**Comment by radfast** [comment] 2018-01-07 14:49
Thanks guys.  This is a clear bug in Galacticraft, we should be able to fix it in our next bugfix update.

>      at net.minecraft.world.World.func_189509_E(World.java:218)
    at net.minecraft.world.World.func_175625_s(World.java:2390)
    at micdoodle8.mods.galacticraft.core.blocks.BlockFallenMeteor.colorMultiplier(BlockFallenMeteor.java:197)
    at micdoodle8.mods.galacticraft.core.proxy.ClientProxyCore$1.func_186720_a(ClientProxyCore.java:189)

**Comment by radfast** [comment] 2018-01-14 00:00
This fix will be included in next version 121.

**Closed** 2018-01-14 00:00 UTC
Labels: fixed
