### ISSUE TITLE
Power Conversion issue Galacticraft 11.350 & Mekanism 8.1.5.246

### ISSUE THREAD

**Issue by mrgrey1** [micdoodle8/Galacticraft#1786] opened 2015-07-21 13:03 UTC
Hi, I updated Galacticraft from 11.333 to 11.350. It was the only change I made to my pack. I have a large number of Mekanism Advanced solar panels on Mars. They usually produce an excess of 7-8000RF/T. This dropped to 7-800RF/t after I updated. I reverted Galacticraft to 11.333 and power generation returned to its previous state. I double checked and the power-GC3.conf is the same in both versions. I changed no other configs. It appears to be a factor 10 drop in power coming from the Mekanism Advanced solars. All the solar panels are using GC Aluminum wire and/or GC Wire Walkways for cabling.

**Comment by radfast** [comment] 2016-01-05 23:32
Sorry to take so long to get to this.

I have tested Mekanism Advanced Solar Panels with Galacticraft 12.407 and I do not see any problems.  Using aluminium wires, the power stored in a GC Energy Storage Module after giving the solar panel sunlight for 16.6 seconds is the same (50 kJ) as when the solar panel is directly connected to a Mek energy storage cube, also the same (50 kJ) as when the solar panel is connected to nothing and stores power in its internal storage.

Galacticraft RF default conversion ratios have not changed from 11.333 to 11.350 (anyhow your power-GC3.conf is unchanged).  It's a bit weird to talk about power in terms of "RF" when Mekanism generates Joules and Galacticraft works in gJ, but whatever, all these types of power are convertible.

One change from 11.333 to 11.350 was that **Galacticraft's** solar panels power generation rates were nerfed on Mars - because there is less sunlight.  Therefore if the player has a blend of GC panels and Mek panels, he will notice less power being generated overall.

It is also maybe possible that some power-consuming component changed to consume more power from 11.333 to 11.350, so that there is less 'excess' power after updating versions.

Closing this issue, because I see no reproducible problem here.

If the OP (or anyone else) can show me an actual problem - maybe with screenshots of the setup used - then we can reopen this.

**Closed by radfast** 2016-01-05 23:32 UTC

**Comment by mrgrey1** [comment] 2016-01-08 06:45
I did a full pack update today and decided to try updating GC as well. A power drop is still there. The Mek Solar panels are now only generating 62RF as compared to their previous 180. I'm assuming the mentioned decrease in Sun intensity is the cause. I looked for an Energy Multiplier in the config like you have for the Space Station but couldn't find one. Maybe it would be an option worth adding in the interests of flexibility? Certainly has my vote for a wanted feature. :)  Anyway now I know what's up and it's intended and not a bug I'm going to try work around it although it's going to require some major reworking of my power setup. Cheers.

**Comment by radfast** [comment] 2016-01-08 12:42
Confirmed this is intended behaviour.  I checked the [Mekanism code](https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/generators/common/tile/TileEntitySolarGenerator.java#L117-L139) and it is importing the Galacticraft "solar level" so that Mekanism solar panels will also - like GC solar panels - generate different amounts of power on different planets.  Nice work, @aidancbrady !

**Comment by aidancbrady** [comment] 2016-01-08 12:42
:)

**Comment by radfast** [comment] 2016-01-08 12:57
@aidancbrady  greetings :)

I think [your Wiki](http://wiki.aidancbrady.com/wiki/Advanced_Solar_Generator) needs a small update, the table reads 180 J/t when the text says it generates [300 J/t](https://github.com/aidancbrady/Mekanism/blob/4040a57a16b5a1f68a03810816acb69e9f3dc374/src/main/java/mekanism/generators/common/GeneratorsCommonProxy.java#L80). The wiki could also maybe mention the GC solar level implementation :)
