### ISSUE TITLE
[Add on] GC map is now conflicting with GC addons moons

### ISSUE THREAD

**Issue by drunksob** [micdoodle8/Galacticraft#1617] opened 2015-04-27 20:06 UTC
Issue: You can no longer travel to moons in other solar systems in More-Planets-GC because the GC map has no sub menus for them, the map cords only work for zooming if you have the same screen resolution as the coder which apparently isn't the standard 1080, so you cant manually select them to launch because you cant see them. 

Possible Fixes:(Im not sure if this is fixable by you guys or SteveKunG @ MP or if it affects other mods)
*Add up down left right, click to drag, or zoom button functionality that doesn't zero out your cords to the default solar system. 
*or you could be lazy and re-add the sub-menus for moons in the selection menu if you don't care about visual appeal, nostalgia, ambiance, theatrics which is the whole appeal of your mod so I would encourage you to do this only as a temp fix.

I have already fixed this issue on my clan server but I figured Id get on here and give you guys a heads up I've also posted this Issue here https://github.com/SteveKunG/More-Planets-GC/issues/11

**Comment by radfast** [comment] 2015-04-28 14:29
First up, please specify which versions of Galacticraft and More Planets you are using.

Second, you seem to be suggesting this is dependent on your screen resolution - in that case, please specify your resolution.

@SteveKunG  I would appreciate any help you can give on this - even if the issue is in GC, it would be great if you can show me where the issue is or make a PR.

**Comment by drunksob** [comment] 2015-04-29 15:05
sorry Galacticraft1.7-3.11.319 and More-planets-1.7.10-1.2.6. 

It seems as though, coordinates in the galacticraft map for other solar systems(GCaddons) correspond to where they visually show up. It seems as though having  a different screen resolution than the one that who ever set up those cordshad on there screen can make the galaxies planets moons show up in a very different place

heres a vid
<iframe width="560" height="315" src="https://www.youtube.com/embed/nRSz7Hq63SM" frameborder="0" allowfullscreen></iframe>

**Comment by micdoodle8** [comment] 2015-05-02 18:33
@SteveKunG Did you apply the gist code I sent you in an email? It will fix the wonky coordinates seen at the end of the video above. I still have the gist link, if you need it.

@drunksob Some of the issues in the video are fixed, I'll look at implementing the others. In the next build there will be both mouse-click dragging and ASWD controls to control the map. That way you shouldn't have to be so far zoomed out to click the planets.

**Comment by drunksob** [comment] 2015-05-03 16:42
That's awesome. Thanks to all of you for being attentive programmers You guys Rock. Cant wait!

**Comment by drunksob** [comment] 2015-05-12 08:02
Was testing this update 1.7-3.0.11.333 and the main problem of not being able to get to moons in other solar systems isn't fixed for me. I do LOVE the movement on the map now, but when in 'zoomed in mode' on a planet, awsd or click to drag functionality zooms you back out, so it does not help to adjust to see/select moons if visual coordinates are off. There is also still no longer sub menus for moons when in 'zoomed in mode'.  I'm just using a temp text selection/tele style menu for now :) I'll make a vid for a better disc when I can.

**Comment by SteveKunG** [comment] 2015-06-11 12:13
I open source now. Please check it out.

**Comment by SteveKunG** [comment] 2016-01-06 12:01
This issue should closed for now.

**Comment by radfast** [comment] 2016-01-06 15:39
Thank you @SteveKunG.  Closing now.

If the problem re-surfaces with latest builds of GC + latest add-ons, please re-open this.

**Closed by radfast** 2016-01-06 15:39 UTC
