### ISSUE TITLE
Rare: Milk Way showing up + Gravity in overworld

### ISSUE THREAD

**Issue by SujakAlkesh** [micdoodle8/Galacticraft#2277] opened 2016-09-30 17:29 UTC
Howdy, 
Recently i have been having some trouble on my server, after some playtime players including me get the milkway shown in the sky and the oxygen tank GUI in the upper right corner aswell as the moon gravity.
All this is happening in the OVERWORLD and for most of the players its unplayable. Any idea how to fix this

**Comment by micdoodle8** [comment] 2016-10-13 01:51
Are you using any other GC addons or separate mods that you suspect might change how Galacticraft functions?

**Comment by radfast** [comment] 2017-02-25 18:15
Any follow up from @SujakAlkesh?

Please provide:
1.  Screenshot
2.  Your modlist
3.  `fml-client-latest.log` from a player who is playing on your server

**Comment by radfast** [comment] 2017-03-18 03:14
This is maybe a duplicate of #2186 ?  The only thing I don't get is:

> after some playtime

**Comment by EzerArch** [comment] 2017-03-18 04:28
It's a very, very, very rare bug. I think I've witnessed it just twice or three times ever.

From memory: I once loaded the game, started in the overworld with low gravity, the sky was Mars-reddish with GalaxySpace's stars and nebulae; it happens after a while playing the game. However I can't confirm that this has only happened with GS loaded.

**Comment by radfast** [comment] 2017-03-19 13:15
Thank you to both.

I think this occurs when there is a dimension ID conflict on the server - possibly after changing the configs of another mod or the configs of one of the Galacticraft add-ons?

Anyhow, should be fixed from build 482.  The planet with the conflicting dimension ID will be unreachable, of course.

**Closed by radfast** 2017-03-19 13:15 UTC
Labels: 1.7, missing info
