### ISSUE TITLE
Inventory GUI Tab Uncompatibility

### ISSUE THREAD

**Issue by kenijey** [micdoodle8/Galacticraft#2645] opened 2017-04-27 17:45 UTC
With the [More Player Models](https://minecraft.curseforge.com/projects/more-player-models) mod.
**this is before click:**
![1](https://cloud.githubusercontent.com/assets/24831406/25496644/5a12bad0-2b8a-11e7-92f3-297303d7a8ed.PNG)
**and after click:**
![2](https://cloud.githubusercontent.com/assets/24831406/25496654/60d4fa68-2b8a-11e7-96bc-1dd0b249c2c0.PNG)
please help, thanks ^^
using forge 2284, galacticraft b76 and MorePlayerModels_1.11.2(26jan17).jar

**Comment by kenijey** [comment] 2017-04-27 17:47
https://minecraft.curseforge.com/projects/more-player-models/issues/4

**Comment by radfast** [comment] 2017-04-27 19:13
It's the same issue as for CustomNPCs #2497

I sent private email to Noppes (author of CustomNPCs and More Player Models) around 2 weeks ago.

He didn't answer yet :(

I will close this for now, because it's a duplicate issue.  If Noppes answers my email in the next few days, we can reach a good solution, otherwise we will have to look for hacky workarounds.

**Closed by radfast** 2017-04-27 19:14 UTC

**Comment by kenijey** [comment] 2017-04-27 21:22
oh, sorry for dupe. thanks..

**Comment by radfast** [comment] 2017-04-28 00:19
no it's fine, I didn't know it was affecting both MPM and CustomNPCs - wasn't really aware until now that Noppes was the author of both of them.

Like I say, I've written politely to him to request compatibility on his side, as its basically our API code that he's using here.  (OK in reality the original code is from a combination of TConstruct and us, but TConstruct are not maintaining the tabs system any longer, and we are.) 

Roughly speaking the problem is like this: Noppes mods are still using API code from 1.7.10 for tabs, instead of using the way we do it now in 1.10.2 and 1.11.2.

**Comment by kenijey** [comment] 2017-04-28 06:55
Hmm... hope he hears you :D

**Comment by EzerArch** [comment] 2017-04-30 01:02
If these CustomNPCs tabs are not important or necessary for you:

1. Open CustomNpcs.cfg.
2. Find `InventoryGuiEnabled=true`
3. Change it to `InventoryGuiEnabled=false`
4. Done. Load Minecraft.

**Comment by radfast** [comment] 2017-04-30 12:00
As mentioned in #2497, I've been in touch directly with Noppes (author of CustomNPCs and MorePlayerModels). We've chatted on Skype. This problem will be fixed by a change on his side, he'll be including this in the next builds of his mods.

I don't know when his next builds will come - looking at his download page, it looks like he makes new builds around monthly or even less often, so I guess it will be a few weeks yet for this.

Meanwhile there is the InventoryGuiEnabled config setting which EzerArch said ^^^^^^^^^^^^

**Comment by kenijey** [comment] 2017-04-30 12:01
i already did that config, i reported this to help the development of the mods.

**Comment by radfast** [comment] 2017-04-30 12:04
@kenijey we appreciate your help :)  it's led to a fix which should help many people
