### ISSUE TITLE
Tconstruct torches

### ISSUE THREAD

**Issue by Sweety42** [micdoodle8/Galacticraft#1630] opened 2015-05-07 00:52 UTC
Hi, 
I dont know if you can do something about that but the tinker's construct torches work in space/other planets.

**Comment by radfast** [comment] 2015-05-07 19:26
Duplicate of #413 and #1396.  Please read the "Guidelines for Contributors" before posting a New Issue.

All that's really needed is for someone to make us a graphical version of an extinguished stone torch.  That 'someone' could be you, maybe?  I took a look and it's way easier than I thought: all that is really needed here is to redesign this without a flame:
https://github.com/SlimeKnights/TinkersConstruct/blob/master/resources/assets/tinker/textures/blocks/torch_stone.png

**Comment by radfast** [comment] 2015-05-07 19:31
Stop Press:  seems like another player was already kind enough to do this for us:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1287888-galacticraft-3-4-100-000-downloads?page=128#c2563

**Comment by radfast** [comment] 2015-05-13 21:03
This will be in next build version 3.0.12.336 coming today or tomorrow.

**Closed** 2015-05-13 21:03 UTC

**Comment by radfast** [comment] 2015-05-14 02:04
Build 3.0.12.336 now out.  @jecowa may be interested.
