### ISSUE TITLE
[1.10.2] Crashing after placing Heavy Aluminum Wire in world

### ISSUE THREAD

**Issue by Bobynoby** [micdoodle8/Galacticraft#2502] opened 2017-04-07 10:04 UTC
Hello its me again :)

Weird crash occurred after I placed a Heavy Aluminum Wire in the world, It generated a crash report but Minecraft itself goes into an "Incorrect State" according to the last message in logs. Minecraft just hangs there and does nothing, Doesn't close either just sits. Game crashes on loading the same world after restarting game.

**Last Message in console (Not sure if related):**
`[21:55:18] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.` 

**Galacticraft (And cores) Versions:**
GalacticraftCore-1.10.2-4.0.0.53-BETA
Galacticraft-Planets-1.10.2-4.0.0.53-BETA
MicdoodleCore-1.10.2-4.0.0.53-BETA

**Forge Version:** 1.10.2 12.18.3.2254
**Crash Report:** https://pastebin.com/nywB2LmZ

**Comment by radfast** [comment] 2017-04-07 11:28
Thanks, this is very helpful.

Again we should be able to fix this fairly quickly, please bear with us while we get to it.

**Comment by radfast** [comment] 2017-04-08 17:49
This issue will only occur when **IndustrialCraft2** is present.
I'm seeing what we can do to fix it, it's possible I've tried to be too clever in https://github.com/micdoodle8/Galacticraft/commit/6295ae26cc32bf67c4f7c6803c77af84b60197d1

**Comment by radfast** [comment] 2017-04-08 18:40
Actually seems like the issue is already fixed by https://github.com/micdoodle8/Galacticraft/commit/80ce8a12b97e56854c95ccd0ea5a8b579a2e2787.  This should be working fine in next version 57 when it becomes available - hopefully later today or tomorrow.

**Closed by radfast** 2017-04-08 18:40 UTC
Labels: 1.10
