### ISSUE TITLE
[1.10.2] [Fixed in ExtraPlanets Update] Shading Glitch on Planets

### ISSUE THREAD

**Issue by CaveMiner1215** [micdoodle8/Galacticraft#2936] opened 2017-08-02 19:38 UTC
I am having a weird shading glitch on celestial bodies other than the moon.  This glitch happens on Mars, Venus, and the planets and moons added by the ExtraPlanets addon.  The shadows fix themselves when I either look at a block or entity (close enough that WAILA will tell me what it is), pause the game, or open my inventory.  I haven't seen this issue anywhere else on the issues list.

Minecraft version: 1.10.2
Galacticraft version: 4.0.0.115 (latest)
Forge version: 12.18.3.2422 (latest)
This is on my single player worlds.

Like I mentioned above, I have the ExtraPlanets addon installed, but no other addons.  I have many other mods installed for a grand total of 73 mods according to forge.  Let me know if you need a mod list.

Here are some screenshots:
This first one is of the error occurring on Mars.
![2017-08-02_15 21 24](https://user-images.githubusercontent.com/30667792/28891270-ea951ff4-7797-11e7-9958-f5e456eb19e8.png)
This next one is of the error fixing itself when I look at a block.
![2017-08-02_15 21 26](https://user-images.githubusercontent.com/30667792/28891368-34d0fb60-7798-11e7-96e3-0d2d677a06d3.png)

Help would be most appreciated.

**Comment by MJRLegends** [comment] 2017-08-02 22:50
Any chance you have FoamFix, Optifine, BetterFPS? if so maybe try without without them as they are designed to mess with mc code including but not limited to lighting rendering

**Comment by CaveMiner1215** [comment] 2017-08-02 22:58
> Any chance you have FoamFix, Optifine, BetterFPS?

I have none of those mods.  I don't have shaders mod either.

**Comment by radfast** [comment] 2017-08-03 12:24
must be one of your other mods, otherwise every Galacticraft player would see it ... but you are the first to report it.

Please test using a reduced mod list, or else start at the other end - start with a clean mods folder with only Galacticraft, and add other mods into the folder in groups until you notice the issue occurring.

I would actually start by looking at WAILA and all WAILA submods like WAWLA, as it seems this issue is somehow affected by WAILA.

**Comment by MJRLegends** [comment] 2017-08-03 12:26
I will be prepared to look at it if it turns out to be ExtraPlanets with a few mods but like @radfast said you'd be the first to report it for me too, as im sure that would of been picked up by my players of ExtraPlanets and one of my mod packs since the mod is in there too :D

**Comment by CaveMiner1215** [comment] 2017-08-03 15:08
It appears to be a problem with the ExtraPlanets addon.  Whenever there is a rocket from the ExtraPlanets addon in my hotbar, this glitch happens.  I can take it out of my hotbar or get it out of my inventory to stop the glitch.  This doesn't happen with normal Galacticraft rockets.

**Comment by MJRLegends** [comment] 2017-08-03 15:09
Ok yeah i know why i can fix it

**Comment by MJRLegends** [comment] 2017-08-03 15:14
A update will be out today @CaveMiner1215 to fix that

**Comment by CaveMiner1215** [comment] 2017-08-03 15:18
Ok, Thanks!

**Comment by MJRLegends** [comment] 2017-08-03 15:20
@CaveMiner1215 Its probably best to close this issue since its not a galacticraft thing

**Closed** 2017-08-03 15:21 UTC
Labels: conflict - large modlist, rendering

**Comment by MJRLegends** [comment] 2017-08-03 15:48
Updates have been posted to curse, they are waiting approval, probably will be within the next 1-3 hours

**Comment by MJRLegends** [comment] 2017-08-03 15:50
Seems like they have been approved already :P Curse team are up to speed today :D

**Comment by s4rgeLegit** [comment] 2020-02-24 16:14
Hello, 2 years later, and the issue is still out there, got Technic Pack Modpack "The 1.12.2 Pack", I have this glitch while Quantum Entagloporter form mekanism is in my hotbar, removing it fixes the issue.

https://cdn.discordapp.com/attachments/374557605051367424/681533321733472298/unknown.png
https://cdn.discordapp.com/attachments/374557605051367424/681533351458635787/unknown.png

**Comment by MJRLegends** [comment] 2020-02-24 17:13
@s4rgeLegit if thats the case then thats a mekanism issue or some rendering mod
