### ISSUE TITLE
Taking damage in Air Lock

### ISSUE THREAD

**Issue by olavjens777** [micdoodle8/Galacticraft#2644] opened 2017-04-27 16:17 UTC
Whilst walking through my space station in survival I noticed that I had taken damage. Upon closer inspection I came to know that the damage came from "suffocating in the Air Lock". Is there anything to do about this? The airlock settings are as follows: Only "Player is within 1 meter is enabled". This shouldn't be changed to 2 meters or else my whole station isn't properly sealable.

**Comment by tabepic** [comment] 2017-04-27 16:18
Did you get damage from not having oxygen?
If so, did you set up an oxygen sealer?

**Comment by radfast** [comment] 2017-04-27 17:12
hey @olavjens777 

Which Galacticraft version?  1.7.10?

Are you saying the Airlock closed too fast, so that the player was caught "inside" those blocks?  It's possible if you have it set to "1 metre" and if you walk slowly... ...

If that's the problem, maybe change the position of your Airlock Controller.  You can put it at the **top centre** or **base centre** of your airlock.   In my builds, I think base centre is best.

**Comment by olavjens777** [comment] 2017-04-27 19:40
Its Galacticraft version 1.11.2-4.0.0.76-BETA. I have the controller at the center of the base of the air lock. Im sprinting at the lock, so speed shouldn't be the problem. I was taking damage from not being able to breathe due to not having oxygen, while I had a sealer installed on both sides of the Air Lock.

**Comment by olavjens777** [comment] 2017-04-27 19:42
I can make a video of the problem if you want that.

**Comment by radfast** [comment] 2017-04-27 23:33
Don't worry about a video for now, the devs can try to recreate this ourselves by doing the same actions.

One more question please:   are you in single player or on a server?  (if it's a server please give details)

**Comment by dj3520** [comment] 2017-04-28 17:37
Could this be caused by the blocks changing and causing another check? If so I'd imagine this happens in 1.7.10 as well. Perhaps the _air lock_ should be treated a bit special for sealers.

**Comment by olavjens777** [comment] 2017-04-28 19:28
Single player.

**Comment by jobensingh** [comment] 2017-05-03 04:53
I can verify this happens with Build 79 1.10.2 on my server

**Comment by micdoodle8** [comment] 2017-05-15 15:56
Should be fixed in the next build. Please re-open if not.

**Closed by micdoodle8** 2017-05-15 15:56 UTC
Labels: 1.10+

**Comment by ElSaam** [comment] 2017-06-03 21:55
Same happening again on build 106 and 107

**Comment by VirtualZer0** [comment] 2019-01-04 21:02
Also its hapenning again in 4.0.1.181

**Comment by BLEEPBLOOPforLife** [comment] 2019-01-25 07:49
I can verify that this is happening in 4.0.1.189 as well.
