### ISSUE TITLE
Galacticraft 2: Crash when using deobfuscate builds

### ISSUE THREAD

**Issue by RonFall** [micdoodle8/Galacticraft#2181] opened 2016-04-20 17:49 UTC
Hello! I have a problem with loading deobfuscate builds Galacticraft 2 for Minecraft 1.6.4 Explain me please, how correctly using Galacticraft deobfuscate files for my workspace. If you have previous topic, please give me link.Thank you. And sorry for my bad English :D
Crash:
`апр 20, 2016 8:48:21 PM net.minecraft.launchwrapper.LogWrapper log
INFO: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
апр 20, 2016 8:48:22 PM net.minecraft.launchwrapper.LogWrapper log
INFO: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
апр 20, 2016 8:48:22 PM net.minecraft.launchwrapper.LogWrapper log
INFO: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
2016-04-20 20:48:22 [INFO] [ForgeModLoader] Forge Mod Loader version 6.99.19.963 for Minecraft 1.6.4 loading
2016-04-20 20:48:22 [INFO] [ForgeModLoader] Java is Java HotSpot(TM) Client VM, version 1.7.0_80, running on Windows 8.1:x86:6.3, installed at C:\Program Files (x86)\Java\jre7
2016-04-20 20:48:22 [INFO] [ForgeModLoader] Managed to load a deobfuscated Minecraft name- we are in a deobfuscated environment. Skipping runtime deobfuscation
2016-04-20 20:48:22 [INFO] [ForgeModLoader] Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
2016-04-20 20:48:22 [INFO] [ForgeModLoader] Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
2016-04-20 20:48:22 [INFO] [ForgeModLoader] Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
2016-04-20 20:48:22 [INFO] [ForgeModLoader] Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
2016-04-20 20:48:22 [INFO] [ForgeModLoader] Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
2016-04-20 20:48:24 [INFO] [STDOUT] Loaded 40 rules from AccessTransformer config file fml_at.cfg
2016-04-20 20:48:25 [SEVERE] [ForgeModLoader] The binary patch set is missing. Either you are in a development environment, or things are not going to work!
2016-04-20 20:48:28 [SEVERE] [ForgeModLoader] The minecraft jar file:/C:/Users/murat/.gradle/caches/minecraft/net/minecraftforge/forge/1.6.4-9.11.1.963/forge-1.6.4-9.11.1.963-mcp.jar!/net/minecraft/client/ClientBrandRetriever.class appears to be corrupt! There has been CRITICAL TAMPERING WITH MINECRAFT, it is highly unlikely minecraft will work! STOP NOW, get a clean copy and try again!
2016-04-20 20:48:28 [SEVERE] [ForgeModLoader] FML has been ordered to ignore the invalid or missing minecraft certificate. This is very likely to cause a problem!
2016-04-20 20:48:28 [SEVERE] [ForgeModLoader] Technical information: ClientBrandRetriever was at jar:file:/C:/Users/murat/.gradle/caches/minecraft/net/minecraftforge/forge/1.6.4-9.11.1.963/forge-1.6.4-9.11.1.963-mcp.jar!/net/minecraft/client/ClientBrandRetriever.class, there were 0 certificates for it
2016-04-20 20:48:28 [SEVERE] [ForgeModLoader] FML appears to be missing any signature data. This is not a good thing
2016-04-20 20:48:28 [INFO] [ForgeModLoader] Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
2016-04-20 20:48:28 [INFO] [STDOUT] Loaded 110 rules from AccessTransformer config file forge_at.cfg
2016-04-20 20:48:28 [INFO] [ForgeModLoader] Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
2016-04-20 20:48:33 [INFO] [ForgeModLoader] Launching wrapped minecraft {net.minecraft.client.main.Main}
2016-04-20 20:48:52 [INFO] [Minecraft-Client] Setting user: Player734
2016-04-20 20:48:55 [INFO] [Minecraft-Client] LWJGL Version: 2.9.0
2016-04-20 20:49:01 [INFO] [Minecraft-Client] Reloading ResourceManager: Default
2016-04-20 20:49:03 [INFO] [MinecraftForge] Attempting early MinecraftForge initialization
2016-04-20 20:49:03 [INFO] [STDOUT] MinecraftForge v9.11.1.963 Initialized
2016-04-20 20:49:03 [INFO] [ForgeModLoader] MinecraftForge v9.11.1.963 Initialized
2016-04-20 20:49:03 [INFO] [STDOUT] Replaced 112 ore recipies
2016-04-20 20:49:04 [INFO] [MinecraftForge] Completed early MinecraftForge initialization
2016-04-20 20:49:04 [INFO] [ForgeModLoader] Reading custom logging properties from E:\Work Space\ModEditor\1.6.4\gradle\eclipse\config\logging.properties
2016-04-20 20:49:04 [OFF] [ForgeModLoader] Logging level for ForgeModLoader logging is set to ALL
2016-04-20 20:49:05 [INFO] [ForgeModLoader] Searching E:\Work Space\ModEditor\1.6.4\gradle\eclipse\mods for mods
2016-04-20 20:49:09 [SEVERE] [ForgeModLoader] FML has detected a mod that is using a package name based on 'net.minecraft.src' : net.minecraft.src.Start. This is generally a severe programming error.  There should be no mod code in the minecraft namespace. MOVE YOUR MOD! If you're in eclipse, select your source code and 'refactor' it into a new package. Go on. DO IT NOW!
2016-04-20 20:49:09 [SEVERE] [ForgeModLoader] FML has detected a mod that is using a package name based on 'net.minecraft.src' : net.minecraft.src.FMLRenderAccessLibrary. This is generally a severe programming error.  There should be no mod code in the minecraft namespace. MOVE YOUR MOD! If you're in eclipse, select your source code and 'refactor' it into a new package. Go on. DO IT NOW!
2016-04-20 20:49:10 [INFO] [ForgeModLoader] Forge Mod Loader has identified 5 mods to load
2016-04-20 20:49:10 [INFO] [mcp] Activating mod mcp
2016-04-20 20:49:10 [INFO] [FML] Activating mod FML
2016-04-20 20:49:10 [INFO] [Forge] Activating mod Forge
2016-04-20 20:49:10 [INFO] [GalacticraftCore] Activating mod GalacticraftCore
2016-04-20 20:49:10 [INFO] [GalacticraftMars] Activating mod GalacticraftMars
2016-04-20 20:49:10 [WARNING] [Galacticraft Core] Mod Galacticraft Core is missing a pack.mcmeta file, things may not work well
2016-04-20 20:49:10 [WARNING] [Galacticraft Mars] Mod Galacticraft Mars is missing a pack.mcmeta file, things may not work well
2016-04-20 20:49:10 [INFO] [Minecraft-Client] Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Galacticraft Core, FMLFileResourcePack:Galacticraft Mars
2016-04-20 20:49:10 [INFO] [ForgeModLoader] Registering Forge Packet Handler
2016-04-20 20:49:10 [INFO] [ForgeModLoader] Succeeded registering Forge Packet Handler
2016-04-20 20:49:11 [INFO] [ForgeModLoader] Configured a dormant chunk cache size of 0
2016-04-20 20:49:11 [SEVERE] [GalacticraftMars] Skipping event FMLPreInitializationEvent and marking errored mod GalacticraftMars since required dependency GalacticraftCore has errored
2016-04-20 20:49:11 [SEVERE] [ForgeModLoader] Fatal errors were detected during the transition from PREINITIALIZATION to INITIALIZATION. Loading cannot continue
2016-04-20 20:49:11 [SEVERE] [ForgeModLoader] 
	mcp{8.09} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
	FML{6.99.19.963} [Forge Mod Loader] (forge-1.6.4-9.11.1.963-mcp.jar) Unloaded->Constructed->Pre-initialized
	Forge{9.11.1.963} [Minecraft Forge] (forge-1.6.4-9.11.1.963-mcp.jar) Unloaded->Constructed->Pre-initialized
	GalacticraftCore{2.0.4} [Galacticraft Core] (GC-Dev-Deobf-1.6.4-2.0.4.42.jar) Unloaded->Constructed->Errored
	GalacticraftMars{2.0.4} [Galacticraft Mars] (GC-Planets-Dev-Deobf-1.6.4-2.0.4.42.jar) Unloaded->Constructed->Errored
2016-04-20 20:49:11 [SEVERE] [ForgeModLoader] The following problems were captured during this phase
2016-04-20 20:49:11 [SEVERE] [ForgeModLoader] Caught exception from GalacticraftCore
java.lang.NoSuchFieldError: field_76246_e
	at micdoodle8.mods.galacticraft.moon.blocks.GCMoonBlock.<init>(GCMoonBlock.java:43)
	at micdoodle8.mods.galacticraft.moon.blocks.GCMoonBlocks.initBlocks(GCMoonBlocks.java:18)
	at micdoodle8.mods.galacticraft.moon.GalacticraftMoon.preLoad(GalacticraftMoon.java:59)
	at micdoodle8.mods.galacticraft.core.GalacticraftCore.preInit(GalacticraftCore.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:523)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
	at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
	at com.google.common.eventbus.EventBus.post(EventBus.java:267)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:197)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
	at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
	at com.google.common.eventbus.EventBus.post(EventBus.java:267)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:108)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:493)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:175)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:473)
	at net.minecraft.client.Minecraft.run(Minecraft.java:808)
	at net.minecraft.client.main.Main.main(Main.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
2016-04-20 20:49:11 [INFO] [STDOUT] ---- Minecraft Crash Report ----
2016-04-20 20:49:11 [INFO] [STDOUT] // I bet Cylons wouldn't have this problem.
2016-04-20 20:49:11 [INFO] [STDOUT] 
2016-04-20 20:49:11 [INFO] [STDOUT] Time: 20.04.16 20:49
2016-04-20 20:49:11 [INFO] [STDOUT] Description: There was a severe problem during mod loading that has caused the game to fail
2016-04-20 20:49:11 [INFO] [STDOUT] 
2016-04-20 20:49:11 [INFO] [STDOUT] cpw.mods.fml.common.LoaderException: java.lang.NoSuchFieldError: field_76246_e
2016-04-20 20:49:11 [INFO] [STDOUT] 	at cpw.mods.fml.common.LoadController.transition(LoadController.java:152)
2016-04-20 20:49:11 [INFO] [STDOUT] 	at cpw.mods.fml.common.Loader.loadMods(Loader.java:494)
2016-04-20 20:49:11 [INFO] [STDOUT] 	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:175)
2016-04-20 20:49:11 [INFO] [STDOUT] 	at net.minecraft.client.Minecraft.startGame(Minecraft.java:473)
2016-04-20 20:49:11 [INFO] [STDOUT] 	at net.minecraft.client.Minecraft.run(Minecraft.java:808)
2016-04-20 20:49:11 [INFO] [STDOUT] 	at net.minecraft.client.main.Main.main(Main.java:101)
2016-04-20 20:49:11 [INFO] [STDOUT] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2016-04-20 20:49:11 [INFO] [STDOUT] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2016-04-20 20:49:11 [INFO] [STDOUT] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2016-04-20 20:49:11 [INFO] [STDOUT] 	at java.lang.reflect.Method.invoke(Unknown Source)
2016-04-20 20:49:11 [INFO] [STDOUT] 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
2016-04-20 20:49:11 [INFO] [STDOUT] 	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
2016-04-20 20:49:11 [INFO] [STDOUT] Caused by: java.lang.NoSuchFieldError: field_76246_e
2016-04-20 20:49:11 [INFO] [STDOUT] 	at micdoodle8.mods.galacticraft.moon.blocks.GCMoonBlock.<init>(GCMoonBlock.java:43)
2016-04-20 20:49:11 [INFO] [STDOUT] 	at micdoodle8.mods.galacticraft.moon.blocks.GCMoonBlocks.initBlocks(GCMoonBlocks.java:18)
2016-04-20 20:49:11 [INFO] [STDOUT] 	at micdoodle8.mods.galacticraft.moon.GalacticraftMoon.preLoad(GalacticraftMoon.java:59)
2016-04-20 20:49:11 [INFO] [STDOUT] 	at micdoodle8.mods.galacticraft.core.GalacticraftCore.preInit(GalacticraftCore.java:196)
2016-04-20 20:49:11 [INFO] [STDOUT] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2016-04-20 20:49:11 [INFO] [STDOUT] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2016-04-20 20:49:11 [INFO] [STDOUT] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2016-04-20 20:49:11 [INFO] [STDOUT] 	at java.lang.reflect.Method.invoke(Unknown Source)
2016-04-20 20:49:11 [INFO] [STDOUT] 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:523)
2016-04-20 20:49:11 [INFO] [STDOUT] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2016-04-20 20:49:11 [INFO] [STDOUT] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2016-04-20 20:49:11 [INFO] [STDOUT] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2016-04-20 20:49:11 [INFO] [STDOUT] 	at java.lang.reflect.Method.invoke(Unknown Source)
2016-04-20 20:49:11 [INFO] [STDOUT] 	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
2016-04-20 20:49:11 [INFO] [STDOUT] 	at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
2016-04-20 20:49:11 [INFO] [STDOUT] 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
2016-04-20 20:49:11 [INFO] [STDOUT] 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
2016-04-20 20:49:11 [INFO] [STDOUT] 	at com.google.common.eventbus.EventBus.post(EventBus.java:267)
2016-04-20 20:49:11 [INFO] [STDOUT] 	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:197)
2016-04-20 20:49:11 [INFO] [STDOUT] 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:177)
2016-04-20 20:49:11 [INFO] [STDOUT] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2016-04-20 20:49:11 [INFO] [STDOUT] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2016-04-20 20:49:11 [INFO] [STDOUT] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2016-04-20 20:49:11 [INFO] [STDOUT] 	at java.lang.reflect.Method.invoke(Unknown Source)
2016-04-20 20:49:11 [INFO] [STDOUT] 	at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
2016-04-20 20:49:11 [INFO] [STDOUT] 	at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
2016-04-20 20:49:11 [INFO] [STDOUT] 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
2016-04-20 20:49:11 [INFO] [STDOUT] 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
2016-04-20 20:49:11 [INFO] [STDOUT] 	at com.google.common.eventbus.EventBus.post(EventBus.java:267)
2016-04-20 20:49:11 [INFO] [STDOUT] 	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:108)
2016-04-20 20:49:11 [INFO] [STDOUT] 	at cpw.mods.fml.common.Loader.loadMods(Loader.java:493)
2016-04-20 20:49:11 [INFO] [STDOUT] 	... 10 more
2016-04-20 20:49:11 [INFO] [STDOUT] 
2016-04-20 20:49:11 [INFO] [STDOUT] 
2016-04-20 20:49:11 [INFO] [STDOUT] A detailed walkthrough of the error, its code path and all known details is as follows:
2016-04-20 20:49:11 [INFO] [STDOUT] ---------------------------------------------------------------------------------------
2016-04-20 20:49:11 [INFO] [STDOUT] 
2016-04-20 20:49:11 [INFO] [STDOUT] -- System Details --
2016-04-20 20:49:11 [INFO] [STDOUT] Details:
2016-04-20 20:49:11 [INFO] [STDOUT] 	Minecraft Version: 1.6.4
2016-04-20 20:49:11 [INFO] [STDOUT] 	Operating System: Windows 8.1 (x86) version 6.3
2016-04-20 20:49:11 [INFO] [STDOUT] 	Java Version: 1.7.0_80, Oracle Corporation
2016-04-20 20:49:11 [INFO] [STDOUT] 	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
2016-04-20 20:49:11 [INFO] [STDOUT] 	Memory: 905297224 bytes (863 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
2016-04-20 20:49:11 [INFO] [STDOUT] 	JVM Flags: 3 total; -Xincgc -Xmx1024M -Xms1024M
2016-04-20 20:49:11 [INFO] [STDOUT] 	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
2016-04-20 20:49:11 [INFO] [STDOUT] 	Suspicious classes: FML and Forge are installed
2016-04-20 20:49:11 [INFO] [STDOUT] 	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
2016-04-20 20:49:11 [INFO] [STDOUT] 	FML: MCP v8.11 FML v6.99.19.963 Minecraft Forge 9.11.1.963 5 mods loaded, 5 mods active
2016-04-20 20:49:11 [INFO] [STDOUT] 	mcp{8.09} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized
2016-04-20 20:49:11 [INFO] [STDOUT] 	FML{6.99.19.963} [Forge Mod Loader] (forge-1.6.4-9.11.1.963-mcp.jar) Unloaded->Constructed->Pre-initialized
2016-04-20 20:49:11 [INFO] [STDOUT] 	Forge{9.11.1.963} [Minecraft Forge] (forge-1.6.4-9.11.1.963-mcp.jar) Unloaded->Constructed->Pre-initialized
2016-04-20 20:49:11 [INFO] [STDOUT] 	GalacticraftCore{2.0.4} [Galacticraft Core] (GC-Dev-Deobf-1.6.4-2.0.4.42.jar) Unloaded->Constructed->Errored
2016-04-20 20:49:11 [INFO] [STDOUT] 	GalacticraftMars{2.0.4} [Galacticraft Mars] (GC-Planets-Dev-Deobf-1.6.4-2.0.4.42.jar) Unloaded->Constructed->Errored
2016-04-20 20:49:11 [INFO] [STDOUT] #@!@# Game crashed! Crash report saved to: #@!@# E:\Work Space\ModEditor\1.6.4\gradle\eclipse\.\crash-reports\crash-2016-04-20_20.49.11-client.txt
`

**Comment by RonFall** [comment] 2016-04-23 21:12
I still can not solve the problem. Help me please.

**Comment by Zachman338** [comment] 2016-04-28 22:12
This crash report is very messy... Can you please post another one if possible?

**Comment by Zachman338** [comment] 2016-04-28 22:23
`[INFO] [STDOUT] cpw.mods.fml.common.LoaderException: java.lang.NoSuchFieldError: field_76246_e`

I think you should maybe look at this thread: https://forum.micdoodle8.com/index.php?threads/how-to-code-a-new-planet.1962/page-3

The problem is I think you have tried to run it in your eclipse workspace, and that currently does not work with the 1.6 builds for some unknown reason. So what you will have to do is you will have to re-obfuscate the files and run them in the actual minecraft client. I hope this helped. :smiley:

- Zachman338

**Comment by RonFall** [comment] 2016-04-30 20:06
Thanks for the answer! I have already used these instructions: 
_"These instructions are for eclipse, since if you mod, you should probably be using Eclipse. Download the latest micdoodle8core and Galacticraft jars from the website. Put those files in /forge/mcp/lib. Next, in eclipse, change your workspace to /forge/mcp/eclipse. Once done, there should be a single project called "Minecraft". Right click on the title, and then click on "properties", at the bottom of the menu. Go to "Java Build Path" and click "Add External Jars". Select the GalacticraftCore jar from the lib folder, then repeat the process for Micdoodle8Core."_
I did exactly as instructed, and it did not help.

**Comment by radfast** [comment] 2016-06-25 17:58
This is the only documentation:
https://wiki.micdoodle8.com/wiki/Testing_Workspace

I can't help further with this, it's not something I have ever personally done - when I used to work in Minecraft 1.6.4 I always re-obfuscated the files before running the game.  The source code is valid and should work, in theory.  It's hard to find any online guide to setting up Eclipse correctly with a dev workspace.

The wiki has much [better information](https://wiki.micdoodle8.com/wiki/GC3_API) for Minecraft 1.7.10, maybe move to working in that?

Anyhow, I must close this issue because it is not a bug in Galacticraft.  I hope you find a solution.

**Closed by radfast** 2016-06-25 17:58 UTC

**Comment by radfast** [comment] 2016-06-25 18:00
https://forum.micdoodle8.com/index.php?threads/nosuchfielderror-field_76246_e-eclipse.2836/
