### ISSUE TITLE
Build 105 Spider Boss Not dropping key

### ISSUE THREAD

**Issue by SebaSphere** [micdoodle8/Galacticraft#2795] opened 2017-06-04 18:52 UTC
When One of my players Defeats the venus Spider Boss, It doesn't drop a key.

**Comment by MJRLegends** [comment] 2017-06-05 21:36
Are you able to reproduce this yourself @SebaSphere ?

**Comment by SebaSphere** [comment] 2017-06-05 21:37
Let me check right now. Haven't tested with a actual chest generated

**Comment by MJRLegends** [comment] 2017-06-05 21:39
@SebaSphere Ok because im 99% sure this must be a rare or issue based on the setup used

**Comment by SebaSphere** [comment] 2017-06-05 21:46
Wait. I thought this was the other github issue I posted. This was tested at actual dungeon with me seeing that player defeat boss.

**Comment by SebaSphere** [comment] 2017-06-05 21:47
Did /invsee just to make sure He wasn't lying.

**Comment by MJRLegends** [comment] 2018-01-09 18:52
@radfast i believe this issue was fixed in a pull request by me a long time back, probably best to close

**Comment by radfast** [comment] 2018-02-12 23:36
thanks, yes that was #2930

**Closed by radfast** 2018-02-12 23:36 UTC
Labels: cant reproduce
