### ISSUE TITLE
Crash when used with ChromatiCraft.

### ISSUE THREAD

**Issue by Chromotron** [micdoodle8/Galacticraft#1573] opened 2015-04-12 16:41 UTC
See http://pastebin.com/TGjQhhqA.
Removing either CC or GC avoids the crash.

**Comment by radfast** [comment] 2015-04-12 16:55
Duplicate of #1571

**Closed by radfast** 2015-04-12 16:55 UTC

**Comment by radfast** [comment] 2015-04-13 18:50
Reika and I have worked together to fix this - it should be fixed in the next ChromatiCraft release v6e later today.
