### ISSUE TITLE
Beam receiver connecting to alum wire [Intended?]

### ISSUE THREAD

**Issue by dj3520** [micdoodle8/Galacticraft#1701] opened 2015-06-09 22:32 UTC
This is either an "unintended behavior" or "graphical error" issue.
If this is intended behavior (which is doubtful) there is no way to change to transfer energy out of the wire, only to accept.

![image](https://cloud.githubusercontent.com/assets/8284194/8071057/a5de2d34-0ed4-11e5-8e95-efe0311c36fa.png)
![image](https://cloud.githubusercontent.com/assets/8284194/8071063/b512e420-0ed4-11e5-936a-fdc836c8c4ee.png)

**Comment by dj3520** [comment] 2015-06-09 22:39
Small update: Energy transfer is OK. Correction to first post that energy can not be pulled out of the wire, not put in (which it can.)

**Comment by babybasher** [comment] 2015-06-10 12:50
Firstly I wish to add, if this is not intended behavior, then please make it so.  I really want the ability to have beam receivers on aluminium wiring!

Secondly, it is bugged :(

Energy DOES transfer through the wire, however it eats up ALL the energy.

Try the below example, using any machine. No matter how much power you got it will drain you dry.

http://postimg.org/image/ymfweu7h5/

Take the aluminium wire off and put the beam receiver directly on the machine and its all good.

**Comment by TheQuadShot** [comment] 2015-06-17 07:41
Just my 2 cents worth: Yes, It would be Great if they did, They don't attach to the sealable wire's or the walkway's either.

**Comment by dj3520** [comment] 2015-11-06 17:29
Retest with 400. No longer does energy transfer but still connects. Also, interesting thing I noticed.

Initial setup.
![image](https://cloud.githubusercontent.com/assets/8284194/11003659/c316b9de-8481-11e5-83ff-a462d279c1fd.png)
Connect beam and receiver on wire disappears.
![image](https://cloud.githubusercontent.com/assets/8284194/11003676/dc9e8562-8481-11e5-959d-9b7832878d06.png)
Only fixable by replacing the receiver. Wouldn't be surprised if others don't have this problem since I have Optifine (among other things.)

**Comment by radfast** [comment] 2016-01-07 02:17
The 'Beam Receiver connecting to Aluminium Wire' problem (which is unintended behaviour - sorry, @babybasher and @TheQuadShot) is fixed and will be in next build, see d5090c4.

The "disappearing" / "invisible" Beam Receiver problem is covered in issue #1720.

Therefore this issue can now be closed.  Thanks to all contributors.

**Closed by radfast** 2016-01-07 02:17 UTC
