### ISSUE TITLE
[With Sync and other mods] Cannot jump after equipping Galacticraft parachute

### ISSUE THREAD

**Issue by MJRLegends** [micdoodle8/Galacticraft#1929] opened 2015-11-08 02:59 UTC
See https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/97 for details

**Comment by dj3520** [comment] 2015-11-08 04:03
I feel like it's impossible that this is caused by only Galacticraft.

**Comment by MJRLegends** [comment] 2015-11-09 00:15
If thats the case its still the Galacticraft parachute thats the source!

**Comment by dj3520** [comment] 2015-11-09 02:45
True but going to need a mods list either way.

**Comment by MJRLegends** [comment] 2015-11-13 03:10
http://pastebin.com/zpYfac2E

**Comment by MJRLegends** [comment] 2015-11-15 20:09
Any news on this problem being fixed?

**Comment by radfast** [comment] 2016-01-10 14:07
@MJRLegends:
* regular Galacticraft by itself (or with a combination of other mods which I regularly test with) does not have this issue
* therefore it is specific to Space Astronomy - it is something in that modpack or configs which is causing this
* I do not have time or inclination to download, install and debug that modpack - I have limited time for working on Galacticraft and it will take time away from other issues which affect everyone, and progress on future features of the mod

If you can please do some A/B testing - on a test platform and with a new world, obviously do not test on an existing world or you can damage it - you should be able to identify in a few minutes which other mod is conflicting with Galacticraft and so causing this.  The best way is to do a binary search, so: remove half your mods, start game, test if the issue still occurs: if yes, then remove half of the remaining mods again (make a note which ones - easy to do using named folders) and test again - or if no, then put back in half the ones you removed.  You should be able to identify the mod this way in 5, 6, or 7 iterations.

I suggest start with the mods which are custom to that modpack or which have the smallest number of users, because if any of the major mods was having this issue then someone else would have reported it before.  Maybe look at Gravitation also.

**Comment by radfast** [comment] 2016-01-19 18:08
I think this issue might have been fixed in recent Galacticraft updates.

Is someone in a position to test the latest GC version please?  The latest version would need to be running on the **server**.  Latest current version is 426, that will be updated to 427 later today, both should be good for this test.

**Comment by MJRLegends** [comment] 2016-01-24 23:44
Seems to be fixed as im unable to reproduce it using the GC v427

**Comment by radfast** [comment] 2016-01-25 03:09
Nice.  Thanks for confirming.

I hope that your modpack can use latest GC.  There will continue to be incremental updates over the coming days.  But I recommend you update the pack around now, there's been a lot of recent improvements which players may notice.

Build 431 coming out later today adds redstone control throughout Galacticraft for most machines.  (Redstone signal = stop machine)

**Comment by MJRLegends** [comment] 2016-01-25 08:03
Yeah the next update will probably be next week sometime

**Comment by MJRLegends** [comment] 2016-06-29 14:35
@radfast this issue has seemed to come back up again https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/332

**Comment by MJRLegends** [comment] 2016-07-14 13:48
@radfast @micdoodle8 any thought on message above ^^^

**Closed** 2017-05-30 14:47 UTC
Labels: 1.7, fixed

**Comment by radfast** [comment] 2017-05-30 14:49
You've closed this because the issue is fixed, or because you've given up waiting? :p

**Comment by MJRLegends** [comment] 2017-05-30 14:50
@radfast I think its fixed but i dont use the Sync mod anymore due to dupe glitches with it (with other mods)

**Comment by radfast** [comment] 2017-05-30 14:52
ok great :)

**Comment by MJRLegends** [comment] 2017-05-30 14:52
@radfast Thinking about i have had reports in the last 2 month with the cant jump after putting on parachute but no one seems to give me details on the issue so im unable to report it to you and midoodle as i have no information to go off and im sure that will be the same when trying to reproduce the bug yourself as i cant reproduce it myself

**Comment by radfast** [comment] 2017-05-30 15:00
ok, if someone figures out a way to reproduce the issue, please re-open this.  I'm guessing it can't be connected with Sync, though :)

**Comment by MJRLegends** [comment] 2017-05-30 16:23
@radfast yeah, i really cant reproduce it, and its annoying because the people who do say they get it never give me any information on it and never reply back to my message :( ...
