### ISSUE TITLE
[1.10.2] [Forge Server] Not falling after taking a rocket to the Moon

### ISSUE THREAD

**Issue by tabepic** [micdoodle8/Galacticraft#2559] opened 2017-04-11 01:07 UTC
After the dimension loads, the client shows an empty world with the sky rendered, and nothing else.
(The moon lander doesn't appear)
It appears that the chunks are generated, but F3 shows 'Outside of world...' and approximately Y: 900

Forge: 12.18.3.2281
Galanticraft Build 61
Server log: https://ptpb.pw/Ybl0

**Comment by MJRLegends** [comment] 2017-04-11 01:08
This isnt a bug, you spawn that high up as you are falling into the planet

**Comment by tabepic** [comment] 2017-04-11 01:09
Except I don't fall.

**Comment by MJRLegends** [comment] 2017-04-11 01:09
The y level was increase from the 1.7 version

**Comment by tabepic** [comment] 2017-04-11 01:11
Yeah, but my Y stays the same (I'm not falling down onto the planet)

**Comment by MJRLegends** [comment] 2017-04-11 01:12
@tabepic ok which planet, and have you changed any config options?

**Comment by tabepic** [comment] 2017-04-11 01:12
The moon, and the config was regenerated

**Comment by radfast** [comment] 2017-04-11 01:14
There's a lot of mods in your modpack, this makes this difficult to troubleshoot

Are you in Creative Mode?  I think in Creative Mode you won't fall immediately, after you spawn in a Galacticraft dimension.

**Comment by tabepic** [comment] 2017-04-11 01:15
Yeah, I was in creative mode.

**Comment by radfast** [comment] 2017-04-11 01:16
problem solved?

**Comment by tabepic** [comment] 2017-04-11 01:16
Yeah.

**Comment by tabepic** [comment] 2017-04-11 01:21
Update: that wasn't the problem.
I returned, and I determined that you can't actually move when in the air. Teleporting to ~ 200 ~ still didn't load the world, although the debug screen showed 'Waiting for chunk...'

**Comment by radfast** [comment] 2017-04-11 01:41
I'm really not sure what's going on here.  It's very difficult to test Galacticraft in large modpacks, because we need memory and resources for our developer tools, and it takes such a long time to load the modpack.  (I probably re-start Minecraft more than 100 times a day.)

Please could you try the same with:
* Galacticraft build 61 only
* Galacticraft + a reduced amount of other mods

**Comment by tabepic** [comment] 2017-04-11 01:41
Okay, will do

**Comment by tabepic** [comment] 2017-04-11 01:42
Also, BTW, same behavior with survival mode

**Comment by tabepic** [comment] 2017-04-11 01:53
Tried with just Galanticraft and it worked as intended.
Trying with a few mods now.

**Comment by radfast** [comment] 2017-04-11 01:55
thank you for testing.
you could may be test going to Venus also, see if that still crashes without some of these mods (#2558)

**Comment by tabepic** [comment] 2017-04-11 01:56
Ok

**Comment by tabepic** [comment] 2017-04-11 02:09
Alright, with Optifine and Wawla added, I finished landing on the moon, however the lower half of the screen was white (see screenshot). I then took a rocket to Venus and it crashed; I could see the yellow/brown textures, and shortly after it crashed.
Crash log: https://ptpb.pw/4AA2

**Comment by radfast** [comment] 2017-04-11 02:28
The Venus crash #2546 is a big mystery to me, maybe @micdoodle8 will have some ideas.

The lower half of the screen white is probably Optifine.  I'm going to move that to a new issue.

So we don't know yet which other mod is causing the issue in this thread (not falling)?  The cause is most likely a mod which **changes player motion** - even if it's walking or falling or gliding that the other mod changes, that could be the cause.  I don't know what features all your mods have, some of them I know of course but others I never tried.

**Comment by tabepic** [comment] 2017-04-11 02:31
Ok, I'm going to try different mods until I can narrow it down to one or two.

**Comment by tabepic** [comment] 2017-04-11 22:04
Update: Tried with Galanticraft Build 63 (and all of the mods I used at the start), and it worked perfectly.

**Comment by radfast** [comment] 2017-04-11 22:31
That's good news!  Thanks for letting us know!  It was probably the same cause as the Venus crash, see https://github.com/micdoodle8/Galacticraft/issues/2556#issuecomment-293219898

Basically that problem in build 61 would have been seen by anyone who **didn't** have NEI.  Micdoodle8 and I both use NEI for testing, so we could never see this problem!

**Comment by tabepic** [comment] 2017-04-11 23:02
I don't know what to think anymore; made a new world, went to the moon in survival, and lo and behold, the bug is back.
Back to testing it is.

**Comment by radfast** [comment] 2017-04-11 23:27
hmm

it's likely a _different_ bug, just happening at the same time!

Do server and client have the same GC version?  (just a thought)
Does the server have **Sponge**?  Sponge is currently bugged so it breaks Galacticraft.

**Comment by tabepic** [comment] 2017-04-11 23:29
Same GC version, and I never even heard of Sponge before this :)

**Comment by NevCrow** [comment] 2017-04-11 23:30
https://www.spongepowered.org/
It is like bukkit but has vanilla and forge versions etc.

**Comment by tabepic** [comment] 2017-04-13 00:07
Got a screenshot of when I used /kill to move to the surface
![Screenshot](https://cloud.githubusercontent.com/assets/9892196/24984465/d23541c2-1faa-11e7-8ab8-5eb5fd8cc62a.png)

**Comment by tabepic** [comment] 2017-04-19 22:54
Still present in Build 69...
I should note that even w/ LAN open, it works.
Just the dedicated server doesn't
I'm going to test with smaller amounts of mods now

**Comment by tabepic** [comment] 2017-04-19 23:14
I don't think the other mods have anything to do with it, because I just used GC Build 69 and nothing else, and the bug was still there.

**Comment by radfast** [comment] 2017-04-19 23:40
OK.  I have a dedicated server setup in 1.10.2 now (with Sponge as well, for testing Sponge), so I can test this myself.

**Comment by radfast** [comment] 2017-04-21 16:17
I think this issue is connected with **tilting the rocket during its launch**.  Tilting the rocket makes it fly sideways, and was causing the player, and the rocket or lander or landing pod, to arrive on the destination planet in different spots.  Because the player wasn't in any landing vehicle, the player became "stuck" in the air, basically waiting for a landing vehicle to spawn but it never spawned there.

Anyhow, that ^^^^ is one issue which has been happening...

If that is the cause of your issue, then this is fixed in next build 70.

**Comment by tabepic** [comment] 2017-04-21 16:39
Ok, I will test it tonight.

**Comment by tabepic** [comment] 2017-04-22 19:31
Nope, problem is still there, even without tilting the rocket at all.

**Comment by radfast** [comment] 2017-04-22 20:39
I've tested build 71 on a dedicated server, also tried giving one reduced memory, a large chunk radius and other heavy activity on my PC to try to simulate an overloaded server.  I can't reproduce this problem.

please can you give me **exact** minimum steps to reproduce it, e.g.  like this, or tell me what's different

1.  Galacticraft build 70/71 on both server **and** client (please check both!)
2.  which Forge version on server and on client?
3.  no other mods installed except JEI?
4.  clean configs on server and on client (delete ```configs/Galacticraft``` on both)
5.  new world on server (delete the ```/world``` folder)
6.  start the server, wait for it to generate the Overworld spawn area
7.  on the client, join the server and start playing
8.  use JEI to spawn in 9 rocket pads and 1 rocket pre-fueled (what type?)
9.  place pads, place rocket, climb inside and launch  (no Launch Controller?)
10.  no tilting of the rocket in flight, don't touch any buttons
11.  in Celestial Selection pick the Moon and hit Launch

**Comment by radfast** [comment] 2017-04-22 22:52
Update: as discussed on #2628 I think you have **packet loss** between your server and client.  (Otherwise the solar generators client-side would be updated to tell them they are generating 0 gJ/tick at night time.)

Packet loss will cause problems when taking rockets.  In rough terms, the server has sent a packet to the client saying "spawn a lander at height 900", and it's waiting for the client to say "I've got it" before anything will start moving.

We maybe need to do something about that in Galacticraft, as obviously packet loss can happen.  (Actually there is not usually so much packet loss, unless something is wrong.  Before I joined the Galacticraft team, I was admin on a modded server in the US, iDreams / Voltz, with 100-200 players online together, all over the world including Europe and Australia.  We didn't have too many problems.  Galacticraft is a big part of the Voltz modpack, so Galacticraft was performing OK in that challenging environment.)

Can you tell me about your specific server setup.  Is your server on the same PC, or on your home network, or somewhere else?  Is the connection saturated?  Have you noticed any other packet loss issues?

**Comment by tabepic** [comment] 2017-04-23 04:07
My laptop is connected directly to the router, and the server is connected to the same router via a wifi connection.
The connection wasn't heavily used, and I can upload to the server at about 10MB/s consistently (if it helps)
The entire system is on a home network

**Comment by radfast** [comment] 2017-04-23 12:07
OK, there shouldn't be packet loss then!

Sorry that you are experiencing these issues.  Next build 72 has another change to the landing system.  There's a good chance that will fix it for you.

**Comment by radfast** [comment] 2017-04-25 03:35
Build 73 is now available.  There's a good chance that fixes this.  I'm interested to know how it is for you now, @tabepic  :)

(Build 72 went bad, we have to skip that one!)

**Comment by tabepic** [comment] 2017-04-25 16:09
Ok, I'll try it as soon as I can fix my server (It won't boot for some reason)
Probably in the next few days

**Comment by radfast** [comment] 2017-04-28 02:49
I will close this, because I think the issue is most likely fixed (once you succeed in booting your server!)

If you notice the same problem happening again, please comment here or re-open, I will be notified of your comments.

**Closed by radfast** 2017-04-28 02:49 UTC
Labels: cant reproduce
