### ISSUE TITLE
Problems with Dragon API

### ISSUE THREAD

**Issue by Skkubah** [micdoodle8/Galacticraft#2379] opened 2017-01-22 03:11 UTC
Greetings,

A while ago, I've decided to create a private modpack for me and a couple of friends using the MC v1.7.10, and while finishing it, I've noted there is this problem (It's not game-breaking, but it still bothers me...): wherever I or any other player stay partially immersed or completely immersed in water or any other transparent liquid and while in the Third-Person view, it seems that the player's body appear like it would be outside the water (The screenshots will make this very clear...).

![636205139019185280](https://cloud.githubusercontent.com/assets/10351506/22179582/2b92bf70-e03f-11e6-9c0c-18300c7622d1.png)

![636205139076999245](https://cloud.githubusercontent.com/assets/10351506/22179583/2e39b6ca-e03f-11e6-9c3c-d074a6341742.png)

![636205139106531270](https://cloud.githubusercontent.com/assets/10351506/22179584/309fe966-e03f-11e6-99bb-78d593b54369.png)

After isolating the problem, I've discovered that it is some kind of problem between: GalactiCraft Core + Planets + MicdoodleCore (confirmed in builds 463 and 464) with Dragon API v16d (core mod for Reika's mods, like RotaryCraft), however, this doesn't happen in the latest recommended build of GalactiCraft (which is 375).

Thank you for your time.

**Comment by EzerArch** [comment] 2017-01-22 13:59
Those screenshots are so tiny.

**Comment by Skkubah** [comment] 2017-01-22 17:58
I'm sorry, I didn't noticed this, here are other screenshots:

![2017-01-22_15 56 26](https://cloud.githubusercontent.com/assets/10351506/22184577/803b6c12-e0bb-11e6-9b6e-0657cee0eaeb.png)

![2017-01-22_15 56 36](https://cloud.githubusercontent.com/assets/10351506/22184579/857a86fe-e0bb-11e6-81e1-4789a130130a.png)

![2017-01-22_15 56 47](https://cloud.githubusercontent.com/assets/10351506/22184581/88b65262-e0bb-11e6-8823-d89bcec4e17d.png)

**Comment by MJRLegends** [comment] 2017-01-30 02:00
@ReikaKalseki

**Comment by ReikaKalseki** [comment] 2017-01-30 08:55
This is an artifact of the player model render overhaul DragonAPI performs (and the way render passes interact). I would not get hopeful for a fix.

**Comment by radfast** [comment] 2017-02-25 00:29
Thank you @ReikaKalseki 

I don't think there's much we can do about this from our side.  I think [this](https://github.com/micdoodle8/Galacticraft/commit/331a7daa9d006ff686e69344af350f9ebe08270f) is the code which caused the situation to change.  Looks like a race between GC and DragonAPI for which one gets the 'other player' renderer (meaning 3rd person view) registered first.  You could maybe try renaming GalacticraftCore.jar to AAGalacticraftCore.jar so that it loads first, or to ZZGalacticraftCore so that it loads last.

GC update 443 was designed to improve compatibility of third person view with a large number of other mods, it means that oxygen equipment will be shown correctly.

**Comment by ReikaKalseki** [comment] 2017-02-25 00:30
DragonAPI changes the player entity to render on pass one as well as pass zero; that is the likely cause here.

**Comment by radfast** [comment] 2017-02-25 16:16
Thank you.
In that case I will close this as "can't fix".
Sorry, Skkubah

**Closed by radfast** 2017-02-25 16:16 UTC
Labels: conflict, minor, rendering
