### ISSUE TITLE
Lander dissappeared

### ISSUE THREAD

**Issue by kremsy** [micdoodle8/Galacticraft#1710] opened 2015-06-14 13:50 UTC
Yesterday ive landet on the moon, today when I jouned the server the Lander (dunno if its the correct name) was still there, was going a bit away from the base and when I came back it just dissapeared (not there anymore, also the rocket and everything what was inside is gone with it).

**Comment by radfast** [comment] 2015-06-14 15:01
This is not the place for your support issues.  Please take it to here:

http://forum.micdoodle8.com/index.php?threads/lander-de-spawned-with-my-rocket-and-landing-pad-in-it.5503/#post-38364

**Comment by EzerArch** [comment] 2016-02-04 23:41
Mister, now you cannot deny this: :sweat_smile: 

![lander2a](https://cloud.githubusercontent.com/assets/6743303/12833335/3953d3ec-cb87-11e5-8215-b9091ec2395e.gif)

It's a very interesting behavior, innit?

![lander](https://cloud.githubusercontent.com/assets/6743303/12833392/86073d6e-cb87-11e5-8979-b0a2e8d03a1b.gif)

The lander is not stable on the floor, it keeps bouncing up and down all the time. If you walk about 3 chunks away, the lander starts to sink very slowly, and emerges from the floor if you approach.

If you away to the point to unload the chunk, say bye-bye to your lander. It's sunken underground, sometimes near the bedrock, if not below.

**Comment by C1ffisme** [comment] 2016-02-06 15:50
I've seen it go all the way through the ground when some lag happened. (Possibly because Minecraft couldn't update it's collision?)

**Comment by kremsy** [comment] 2016-02-06 18:40
Noticed the same issue when I created the issue.

**Comment by radfast** [comment] 2016-02-06 19:21
ok, sorry seems like I closed this wrongly.

So the issue is the lander is sinking into blocks.

**Comment by kremsy** [comment] 2016-02-06 19:34
Yes and than dissapearing after a while when it sunk about 50% or something (not sure exactly anymore)

**Comment by EzerArch** [comment] 2016-03-27 05:35
I made a test with the moon lander and landing balloons. I spawned both on the overworld with ```/summon``` (ref. #1266).

Interesting that the lander bobs and sinks 1/16 block every minute...
![2016-03-27_01 00 37](https://cloud.githubusercontent.com/assets/6743303/14063971/8829a834-f3c3-11e5-8b6a-5eca54be88f0.png)

... and stopped sinking when it sank completely in the ground.
![2016-03-27_01 19 01](https://cloud.githubusercontent.com/assets/6743303/14063972/8842aadc-f3c3-11e5-9bdd-2b73db7fad6b.png)

Then I went away a bit and it sank 1 block down.
![2016-03-27_01 27 02](https://cloud.githubusercontent.com/assets/6743303/14063973/886d6d12-f3c3-11e5-8866-a8be859021a1.png)

The landing balloons stood there quietly minding its own business. It didn't sink any bit. Sometimes it rolls a bit.

The jet is from MCHeli mod. it's there just for comparison.

**Comment by Cronosus** [comment] 2016-06-13 20:56
i hate this bug too

**Comment by radfast** [comment] 2017-04-21 14:30
This is fixed in build 487 (and later) of Galacticraft 3, and in build 70 (and later) of Galacticraft 4.

**Closed by radfast** 2017-04-21 14:30 UTC
Labels: 1.7

**Comment by EzerArch** [comment] 2017-04-22 12:22
After reloading chunks and the world itself, it seems this is the proof the Lander will not _"eppur si muove"_.

![2017-04-22_09 09 18](https://cloud.githubusercontent.com/assets/6743303/25304320/69afdfca-273b-11e7-97b6-2d44d191063a.png)

Interestingly, if I summon the lander you can still find there's still some Y-motion. Probably that's why the lander kept sinking.

![2017-04-22_09 20 30](https://cloud.githubusercontent.com/assets/6743303/25304411/f6c5e46c-273c-11e7-93c2-3ebc40c7cd0d.png)

**Comment by radfast** [comment] 2017-04-22 17:12
Galileo :)

I think you're the only person who summons these large entities :p   I don't even know the command for it, lol!  So do we need to to worry too much if a summoned entity snags like this.  **Probably** you can fix it by summoning it in an **aerial position** and then letting it fall naturally - if it falls naturally it should set its motion to 0 when it hits the ground.  Or place a block 1 position higher than you want it, summon it onto that block, then break the block and let it fall.

yMotion of -0.008 is normal in Minecraft, that's (kind of) the gravity which keeps everything on the ground.  To be more clear, Minecraft tests whether an entity is _on the ground_ by attempting to give it this yMotion each tick, and seeing if it can actually move.  The yMotion of -0.008 is what's left over, after the entity's motion update tick.

**Comment by EzerArch** [comment] 2017-04-28 18:01
> So do we need to to worry too much if a summoned entity snags like this?

Nope. I thought I had found via /summon the evidence why the lander sunk.

> I think you're the only person who summons these large entities

Sometimes I need them for the wiki ([example](https://wiki.micdoodle8.com/wiki/File:Space_Lander.png )).

**Comment by radfast** [comment] 2017-04-28 19:07
not for riding then?  ;)

**Comment by Cronosus** [comment] 2017-04-28 19:11
i use them as decorate

**Comment by EzerArch** [comment] 2017-04-28 19:48
> not for riding then? ;)

> i use them as decorate

Yea, to decorate. Say you gonna ride 'em, everybody will lose their minds. :3

**Comment by EzerArch** [comment] 2017-04-28 19:50
> not for riding then? ;)

> i use them as decorate

Yea, to decorate. Say [you gonna ride 'em](https://youtu.be/3eSIg6WtfZ4), everybody will lose their minds. :3

**Comment by EzerArch** [comment] 2017-04-28 23:48
@radfast, BTW, try this summon command in a command block.

`/summon galacticraftplanets.juicer ~ ~1 ~ {Passengers:[{id:galacticraftcore.evolved_creeper,IsBaby:1}]}`

**Comment by radfast** [comment] 2017-04-28 23:56
https://cdn.meme.am/instances/56130721.jpg
