### ISSUE TITLE
[1.12.2] Exception ticking world entities

### ISSUE THREAD

**Issue by TheBaiRuo** [micdoodle8/Galacticraft#3704] opened 2019-06-16 03:23 UTC
When I log in to my space station, the server will shut down.
The client displays "server close".

Minecraft version: 1.12.2
Galacticraft version: 1.12.2-4.0.2.211

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SMP

Any Galacticraft add-ons installed? please list all
No.

Please provide screenshots / crash report / log / full modlist as needed
https://pastebin.com/HXRKdsXq

**Comment by marcus8448** [comment] 2019-06-16 05:38
Dupe of #3704

**Comment by TheBaiRuo** [comment] 2019-06-17 11:09
Sorry, the server has been restarted, so I don't have the latset. log when it crashes

**Closed** 2019-08-26 22:02 UTC

**Comment by radfast** [comment] 2019-08-26 22:04
Should be fixed next build.  It seems that the server wants to `invalidate()` an Arc Lamp tile before it has run the `onLoad()` method which it initialises it, so I've added an initialisation check to invalidate() as well.

@marcus8448 did you intend to reference another duplicate in your June 16 comment, I couldn't find it?

**Comment by radfast** [comment] 2019-08-27 03:21
Please try build 1.12.2 - 4.0.2.234.
