### ISSUE TITLE
GC Canisters not working correctly with Thermal Expansion machines

### ISSUE THREAD

**Issue by ArkwrightSteel** [micdoodle8/Galacticraft#1618] opened 2015-04-28 01:50 UTC
I found this bug when I was messing around with Thermal expansion, Mekanism, and GalacticCraft with current version 3.0.11 and Thermal Expansion 4

If i put a liquid oxygen canister into the liquid transposer it does add liquid to the transposer but does
not come out empty but full.

In my testing world, I was able to make a looping rig that gives me infinite liquid oxygen, this bug should be fixed ASAP

-your fan

**Comment by radfast** [comment] 2015-04-28 14:31
> this bug should be fixed ASAP

It's a bug in Thermal Expansion.  See also https://github.com/micdoodle8/Galacticraft/issues/1464
Apparently it's been around for a long time ...

**Comment by KingLemming** [comment] 2015-04-29 19:34
Yeah, I've already closed this on TE's end. The transposer works with literally everything else. Fix your canisters. ;)

**Comment by radfast** [comment] 2015-04-29 23:12
Thanks for looking in @KingLemming 

The canister works OK with every other mod we have tested with, i.e. Buildcraft, IC2 bottling plant, Railcraft tanks, etc.

It would help me if you can show me the source code for the TE Transposer - please email rradfast@gmail.com

**Comment by radfast** [comment] 2015-04-29 23:15
@KingLemming  do you have any comment on what @sww1235 wrote on #1464?

> After further testing, I believe it was a bug with thermal expansion so I am closing this for now. The only fluid handler that actually worked correctly with the fluid transposer was thermal expansion's own.

**Comment by KingLemming** [comment] 2015-04-30 16:13
Not really, no. It works with literally everything else, not just TE things.

**Comment by KingLemming** [comment] 2015-04-30 16:18
You also shouldn't need the source code for the transposer simply because every other mod is compatible without trying. The transposer fills things that are in the FluidContainerRegistry or are IFluidContainerItems.

If GC's canisters are both, the API is being used incorrectly and that may be the cause.

**Comment by KingLemming** [comment] 2015-04-30 16:19
Also. Not trying to be terse or short, I'm just on a phone.

**Comment by radfast** [comment] 2015-04-30 16:39
> If GC's canisters are both, the API is being used incorrectly and that may be the cause.

Aha, thank you that helps me.  Yes, they are both.  And seeing as how net.minecraftforge.fluids.ItemFluidContainer says "Author: King Lemming", I imagine you are right about this :)

Sorry about anything said earlier, I was going by what sww1235 reported as I hope is clear.

**Comment by KingLemming** [comment] 2015-04-30 17:15
Don't worry about it at all. How are they meant to work - as one-shot things, things w/ durability, what?

**Comment by radfast** [comment] 2015-04-30 17:24
They are re-usable and they have levels from 0 to 1000mB or anything in between.  The level is stored as a durability figure so that it is depicted visibly on the item __and__ the fluid content is stored in the Forge way.  A little extra complication is that each type of Galacticraft fluid has its own canister item, but they all revert to an empty oil canister when emptied.

They do work as intended, currently, in Galacticraft and in all cross-mod situations except the TE Transposer.  Probably because the TE Transposer is the only machine to use the fluid API to its full capabilities or correctly...

**Comment by KingLemming** [comment] 2015-04-30 17:33
Are they used in crafting table recipes?

**Comment by radfast** [comment] 2015-04-30 17:33
I suspect this is the part which is of most concern in fact:
https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/GalacticraftCore.java#L215-223

It registers literally 1000 of these to cover each possible content level of each canister, so probably 6000 in all.  That must have a performance effect.  If we can eliminate that, it would be good.

I'm understanding from what you're saying that there may be no need to register in the ContainerRegistry at all.  Galacticraft's own code does not require that, and I guess it was done only in an attempt for compatibility with other mods - it was coded before I joined the team but I should take ownership of it now.

**Comment by KingLemming** [comment] 2015-04-30 17:34
Yeah...that in particular is amazingly terrible.

**Comment by radfast** [comment] 2015-04-30 17:35
They are used in crafting table recipes occasionally, yes.  Some recipes involve return of a part-filled canister.  The Canister of Liquid Oxygen can be used to "top up" other items in game, and returns a part-filled canister of liquid oxygen.  It's a neat mechanic, I hope there won't be any reason here to change that.

**Comment by KingLemming** [comment] 2015-04-30 17:37
If you use custom Recipes, there isn't. If you're relying on those 1000 registrations and default crafting table behavior, then that's a bit kludgey and will have to be reworked.

**Comment by radfast** [comment] 2015-04-30 17:42
No we have custom Canister recipes so that should be OK.

This 1000 registrations has been in Galacticraft from before the very beginning of the Github, which was around 2 years ago: https://github.com/micdoodle8/Galacticraft/blob/1fbc2b6ebbf0ad2d4889261017cf1441e450119a/common/micdoodle8/mods/galacticraft/core/GalacticraftCore.java#L258

**Comment by radfast** [comment] 2015-04-30 17:43
Custom recipe: https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/planets/asteroids/recipe/CanisterRecipes.java

**Comment by KingLemming** [comment] 2015-04-30 17:43
That's definitely going to be terrible for performance, yes.

Honestly, with IFluidContainerItem, you can remove a lot of the extra code here. Have a generic canister that can hold any fluid, it'll be *far* more elegant.

**Comment by radfast** [comment] 2015-04-30 17:47
OK, well I'm going to try simply removing the container registration and see how that goes.  I'm very grateful for your help.

**Comment by KingLemming** [comment] 2015-04-30 17:54
No worries. :) I think there's quite a bit of potential for cleanup and optimization there if you want to discuss it further at some point.

**Comment by radfast** [comment] 2015-04-30 17:59
That's kind, but I'm thinking best not to change all the items to generic, as that would cause item loss in existing saves, at least unless I have dual items (generic and specific) going forward in which case the point of switching to generic is gone.

Also, apart from the appalling container registration issue, the specific canisters are elegantly coded IMHO right now: as subclasses of the generic item all the Forge fluid interfacing is handled by the generic item, but any specific functions they have - for example some do [interesting things](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/planets/asteroids/items/ItemCanisterLiquidNitrogen.java#L83) when right-clicked - are their own, and I plan to add more diverse functions like that in future.  Possibly dimension dependent, hmmm.  We didn't yet get to the gas planets and outer moons with lakes of liquid methane, but that will come one day I hope ...

**Comment by radfast** [comment] 2015-05-03 03:23
The liquid duping is fixed in latest Galacticraft build 3.0.11.330.

Unfortunately it looks like now the empty canister gets duplicated, inside the Transposer - so after emptying, the canister stays in the input slot, even though a copy of the empty canister is made in the output slot.  This does not happen with the IC2 Bottling Plant which has similar functionality.  I'm still investigating...

**Closed** 2015-05-03 19:31 UTC
Labels: exploit, Priority

**Comment by radfast** [comment] 2015-05-03 19:55
Hi @KingLemming 

Quick update for you.  I've overhauled the Galacticraft code and it's working as intended now, the canisters perform correctly.

In the process I've uncovered what seems like a CoFH issue.  When the Transposer is working with an IFluidContainerItem, when it's done emptying/filling it, it replaces the ItemStack in the input slot with the result of ```cofh.lib.util.helpers.ItemHelper.consumeItem(stack)``` - and the Transposer does that _at the same time_ as creating the resulting item in the output slot.  This seems to have the effect of duping the empty container item in all my testing.  Seems to be because, for an IFluidContainerItem ```item``` the return value of that ```ItemHelper.consumeItem(stack)``` is effectively, ```item.getContainerItem(stack)```.  

In GC I have made a workaround for this by detecting calls to ```item.getContainerItem(stack)``` originating from the TileTransposer and returning ```null```.  Not an elegant solution but the only one which works.  https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/items/ItemCanisterGeneric.java#L61-74

In testing today I've also noticed that if you right click with a TE Portable Tank onto an EnderIO Tank (so, transferring the fluid contents) no empty container item is returned - your Portable Tank is lost.  My guess is that the TE portable fluid tank is returning a null ```item.getContainerItem(stack)``` when EnderIO is expecting an ItemStack there....  Seems like it could be a related issue.
