### ISSUE TITLE
Automatic cargo rocket blows up

### ISSUE THREAD

**Issue by iPencil** [micdoodle8/Galacticraft#1759] opened 2015-06-30 16:11 UTC
Galacticraft version: 1.7-3.0.12.345
No other Galacticraft-Addons

This has happened twice now:

We have a cargo rocket that is automated to transport ores from the moon the overworld, and back.
Both ends are chunkloaded (the launch controller chunkloads too I think? Just to be sure).
It worked fine for a day, except that floating rocket bug (but that's a known bug I saw). Then suddenly there is a huge explosion and a large crater where the launch pad was supposed to be. We thought maybe it didn't slow down?

Today my friend was online when it happened. He saw the rocket land and start multiple times in a row and then explode. Like it was going up and down repeatedly. 

Please tell me if you need any more information. Screenshots/logs/the place where it landed, anything!

**Comment by micdoodle8** [comment] 2015-06-30 19:19
Is it possible that the rocket ran out of fuel? Any automatic rockets should land properly if there's enough fuel in the tank. If you're sure this wasn't caused by the rocket not being refilled properly I can look into this some more.

**Comment by iPencil** [comment] 2015-06-30 19:30
It's being refueled automatically. It's draining fuel from a tank that also supplies our manual rocket, which are all still getting fuel. 

I am going to do some further testing, and make sure that the fuel supply is 100% working (even tho I'm sure it was), I'll report to you later if the explosion happens again. The weird part was that the rocket seemed to try to land/start multiple times in rapid succession. It would look like it's bugging up and down before it exploded (that's what my friend told me, he saw it happen)

**Comment by iPencil** [comment] 2015-06-30 19:32
Also, theoretically, what would happen IF the launch controller, the one on the moon where the rocket started, shortly went out of energy while the rocket on the overworld was trying to start/land? I'm quite sure that it was powered all the time, but I'm just trying to figure out why it exploded.

Also, the rocket has to land at y ~25, going down a hole as big as the launch pad for probably 100 blocks. Would that cause issues?

**Comment by micdoodle8** [comment] 2015-06-30 19:48
If the launch controller runs out of energy the rocket will land fine. The power is only needed when the rocket is finding it's target controller. And no, the rocket will always fly straight down, so the tunnel won't make a difference. I'll look into it some more. I'll attempt to fix the floating rocket bug and might come across the issue.

**Comment by iPencil** [comment] 2015-06-30 19:56
Okay that's awesome. I'll leave my recoding software running over night while the rocket is active and maybe I'll catch it crashing on video.

**Comment by dj3520** [comment] 2015-06-30 20:01
I'm having a problem similar to this, but it might be different. For me the rocket appears to explode, but if I have something inside the blast radius (a redstone clock for example) it continues running even when it looks to be destroyed. Relogging shows a perfectly landed rocket.

**Comment by iPencil** [comment] 2015-06-30 20:05
Nope, the block damage is permanent for me :)

**Closed** 2015-07-02 14:15 UTC

**Comment by micdoodle8** [comment] 2015-07-02 14:17
So I was able to recreate the issue with the rocket trying to land several times unsuccessfully. This would leave the rocket 'running' on the pad, so the fuel would eventually run out and the rocket would explode. This should be fixed in the next build. Thanks for the report.
