### ISSUE TITLE
Oxygen Collector Not Affected By Leaves on Overworld.

### ISSUE THREAD

**Issue by SportsFan10** [micdoodle8/Galacticraft#1442] opened 2015-02-11 00:53 UTC
Oxygen collectors are no longer affected by leaves.  Before the more leaves you had the better the Oxygen collection would go.  Currently no matter how many leaves the collector stays at the standard 180 Oxygen/Second.  

Forge:10.13.2.1307-1.7.10
Galacticraft Version-1.7-3.0.8.263
Other Mods Include
-Code Chicken Core:1.7.10-1.0.4.29
-Not Enough Items:1.7.10-1.0.4.83

Video for a clearer description: https://www.youtube.com/watch?v=5wTccP08cbw&feature=youtu.be

**Comment by EzerArch** [comment] 2015-02-11 02:12
I can confirm Oxygen Collector is not behaving as usual.

**Before:** it required a minimum number of leaf blocks to start working. In space: 14 blocks = 20 air points per second. If on the Overworld, 180 air points per second, no leaf required. I don't remember if leaves would boost the collector.

**Now:** It starts working with 2 leaf blocks, collecting about 3 air points per second, but the Oxygen collector's GUI says "Status: Active; Collecting: 0/s". If on the Overworld, 180 air points per second, no leaf required. Leaf blocks don't boost the collector.

**Comment by radfast** [comment] 2015-02-11 11:34
On the Overworld leaf blocks have never been required.

**Comment by SportsFan10** [comment] 2015-02-12 00:50
I'm sorry this was a mistake on my part.  The collector works 100% on other planets besides the overworld.  Leaves do affect it on other planets as I got it to 220 oxygen/sec on the moon.  I simply though it use to get affected on the overworld as well.  Once again my apologies.

**Comment by EzerArch** [comment] 2015-02-12 02:24
Looks like this page needs a bit of rewrite now: http://wiki.micdoodle8.com/wiki/Oxygen_Collector :)

But still, on the subject:

> Seems to me that everything is working exactly as intended, except maybe a rounding down issue in the collector's GUI?

I think so, just to be sure:
- The string "Collecting: {value}/s" in the GUI remains zero if Oxygen Collector collects less than 20/s.
- Oxygen Collector doesn't work with 1 leaf block, but does with 2 blocks. Is this intended?

**Comment by radfast** [comment] 2015-03-01 00:49
The "Collecting: xxx/s" value is now fixed for collecting less than 20/s

It is intended that the Oxygen Collector doesn't work with 1 leaf block, that is too little.

**Closed by radfast** 2015-03-01 00:49 UTC
Labels: intended behavior
