### ISSUE TITLE
DUPE MAJOR

### ISSUE THREAD

**Issue by MrHelp** [micdoodle8/Galacticraft#1683] opened 2015-05-31 13:06 UTC
http://youtu.be/Q3GwuQxBwjs

**Comment by radfast** [comment] 2015-05-31 22:50
Thanks for reporting.  This is fixed, the fix will be in the next build.

**Closed** 2015-05-31 22:49 UTC

**Comment by SteveKunG** [comment] 2015-06-03 11:35
Hi @radfast, I'm found 2 crash on Short Range Telepad and Solar Panel when placing on Y 254.
http://pastebin.com/2SuM6As6
http://pastebin.com/P3QH6v5r

**Comment by radfast** [comment] 2015-06-04 10:30
@SteveKunG   I can't reproduce that - placing Solar Panel at y=254 is fine for me now.

Which dimension are you testing in?  What is the world height?  Are you using the latest code?

**Comment by MrHelp** [comment] 2015-06-04 13:46
In version 340 and world. they fix it.I test it and it work normally. Thanks

**Comment by SteveKunG** [comment] 2015-06-05 12:15
I testing on Moon dimension and get crashes. I think this method is a problem.
https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/dimension/WorldProviderMoon.java#L264
