### ISSUE TITLE
Bad TileEntity in Telepad Handler

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#1974] opened 2015-12-18 08:45 UTC
My game log keeps getting this error every 1 or 2 seconds, regardless the dimension I'm in:

```
[05:08:15] [Server thread/ERROR] [FML]: Bad TileEntity in Telepad Handler: address(1) dim0 x-268 y69 z253
[05:08:15] [Server thread/ERROR] [FML]: Bad TileEntity in Telepad Handler: address(2) dim0 x-347 y70 z155
```

Sometimes followed by this:
```
[05:08:18] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2534ms behind, skipping 50 tick(s)
```

What I have noticed from my Telepads: even if both telepads are in loaded chunks, they lose their destination links. I have to get very close to them both to restore their links. Once restored, the Bad TileEntity error stops.

![2015-12-18_06 44 48](https://cloud.githubusercontent.com/assets/6743303/11892850/e7ad6c6a-a552-11e5-845d-d48f00fdd81c.png)

**Comment by radfast** [comment] 2016-01-03 23:36
I can reproduce this in testing.  I think it must be connected with the "issue"/feature in vanilla Minecraft where any machine (furnace, minecart) stops working when you move around 3-4 chunks away from it, even though the chunk is still loaded.

**Comment by radfast** [comment] 2016-01-03 23:57
We can fix this, but it's not a quick fix - needs the frequency system for telepads to be coded differently, basically to store a permanent record of any Telepad whenever it gets loaded (even if the chunk later becomes unloaded or dormant).

I'll do this asap.  I think this means Telepads are not really useful outside very short ranges, until this is fixed.

**Comment by radfast** [comment] 2016-01-04 01:03
This is also partly a duplicate of #1949, do you agree?   I will close #1949 as I'm happy to cover both aspects under this issue report.

**Closed** 2016-02-07 03:41 UTC

**Comment by radfast** [comment] 2016-02-07 03:45
Thoroughly fixed in build 441.

You will need to load mapchunks with Telepads at least one time after build 441 to have them working.  Once they have been loaded that one time, the game should remember them permanently if you quit and re-load the same map.

(For anyone who is interested, turns out the cause of this was a "feature" of Forge where servers do not immediately load unloaded map chunks when you ask them to, instead they 'queue' them to load asynchronously.  That's fine for players who are walking around the map loading chunks, it takes a while for chunks to be sent to players over the network anyhow.  But it messes up machinery which needs to know immediately if something in a different map position is OK or not.)

**Comment by EzerArch** [comment] 2016-02-07 04:01
"Short Range Telepads now working properly for the first time ever" LOL! Thank you.
