### ISSUE TITLE
[1.10.2] Sounds in Venus dim

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#2762] opened 2017-05-28 06:26 UTC
So far:
1. Can't hear the thunder, as in the old versions.
2. Punching the Tier 3 Dungeon Chest produces no sound.
3. (New) Parachute deployment produces no sound.

**Comment by radfast** [comment] 2017-05-28 10:14
Possibly I broke this in https://github.com/micdoodle8/Galacticraft/commit/8a54008ef0f00666ccc605aef06743f72a443b61#commitcomment-22125108 though it seemed OK in testing at the time.

**Comment by EzerArch** [comment] 2017-05-28 19:58
There's another one which may not be a bug, but rather an inconsistency (a.k.a. "I feel there's something missing"): Parachute deployment produces no sound.

You can hear that when the player enters the Overworld, but not in Venus.

**Comment by radfast** [comment] 2017-05-29 23:01
It's a strange one, sounds on Venus are still working correctly in 1.8.9 but not 1.10.2

**Comment by radfast** [comment] 2017-05-30 00:00
I've fixed the thunder sound, not sure if that never worked in 1.10.2 before (maybe "old version" in your first post means 1.8.9?)

I can't reproduce any problem with closing the Tier 3 Dungeon Chest, that sounds ok to me.

Parachute deployment in the Venus Entry Pod never made a sound, I think.  We should probably add one ...

**Closed by radfast** 2017-05-30 00:00 UTC

**Comment by EzerArch** [comment] 2017-05-30 04:19
> (maybe "old version" in your first post means 1.8.9?)

1.10.2 Beta 43 (17 jan 17), at least. I'm sure because I had even recorded a video to show micdoodle the 1st boss fight and I could hear the thunder sounds.

> I can't reproduce any problem with closing the Tier 3 Dungeon Chest

Not the closing, it's the punching sound.

> Parachute deployment in the Venus Entry Pod does not currently make a sound in any GC version, I think.

For a moment, I thought the parachute sound was played upon the player entering the Overworld _and_ Mars (landing balloons) -- surely, it's only in the Overworld entry. To be precise, the parachute simply deploying midway so silently, out of blue, made me feel that was something off or missing.

Originally this issue report was intended to report only about the thunder, but then I decided I could add other occurrences, including minor ones, as I stumble upon them during the tests, instead of opening an issue report for each. I hope I'm not nitpicking much. :x

**Comment by radfast** [comment] 2017-05-30 09:54
I don't think these things have a common cause.  And someone else tweeted at the weekend that music isn't working on Venus - but it is working!

I'll move the punching sound into the KNOWN ISSUES list.

The parachute deployment sound is something we should look at adding in future, specifically for Venus.  Venus has a dense (ultra dense!) atmosphere so even quiet sounds should carry long distances.
