### ISSUE TITLE
Cargo rockets not arriving at destination

### ISSUE THREAD

**Issue by jeridan** [micdoodle8/Galacticraft#1981] opened 2015-12-27 19:35 UTC
Using Galacticraft version 1.7-3.0.12.404
Forge version 10.13.4.1448

Launch controllers, fuel loaders, cargo unloader on moon.  Same except cargo loader on mars.
Set frequencies at each controller to point to the other (Using 1 and 2)
Set launch on redstone signal.
Activate redstone signal, rocket launches.
Rocket never arrives at destination.
Tried in both directions.

**Comment by dj3520** [comment] 2015-12-27 19:48
Do you have a method of chunk loading?

**Comment by jeridan** [comment] 2015-12-27 20:15
Yes, I have a Dimesional Anchor setup keeping the chunk each GC setup is in loaded.

**Comment by dj3520** [comment] 2015-12-27 21:48
Hmm. Just in case can you try again with a player at both launch pads?

**Comment by jeridan** [comment] 2015-12-27 23:11
SSP world.  Is there a fake player in GC?

**Comment by EzerArch** [comment] 2015-12-28 00:38
There's something wrong:

1. Sent a cargo rocket from OW to the moon: the launch controller is green, the rocket lifts off, but didn't arrive.

2. Tried to send to cargo rocket from the moon to OW, same pads: the launch controller is green, the rocket lifts off, but when it reached the moon's "atmorphere", the game crashed: https://gist.github.com/EzerArch/c23e1e154e1783819292

**Comment by jeridan** [comment] 2015-12-28 04:07
Just setup a server instance of my world and cargo rockets work as expected.  Must be a SSP thing.

**Comment by radfast** [comment] 2016-01-04 00:28
There is not a fake player in GC.  We have chunkloaders in GC for the launchpads.  You should not need to use any Dimensional Anchor unless you have power systems or something else the launchpad needs, which is not in the same chunk.

It's a concern if this is not working on SSP, thank you for reporting.

I will also look at the crash reported by EzerArch.  Not sure yet whether that is the same issue or something different.

**Comment by radfast** [comment] 2016-01-14 02:28
@EzerArch 
> 2. Tried to send to cargo rocket from the moon to OW, same pads: the launch controller is green, the rocket lifts off, but when it reached the moon's "atmosphere", the game crashed: https://gist.github.com/EzerArch/c23e1e154e1783819292. Never arrived after game reload.

This crash you reported appears to be a Forge bug.  Something like this: you launched Minecraft as a client, but it later became a server, and Forge didn't update everything to server mode properly.  Is there any chance you still have the full log for this session?   27/12/15 22:34

**Comment by EzerArch** [comment] 2016-01-14 03:30
> Is there any chance you still have the full log for this session? 27/12/15 22:34

I got you fam. Say no more! https://gist.github.com/EzerArch/c89bf22c46732edca436

**Comment by radfast** [comment] 2016-01-14 03:47
@EzerArch thank you :)

Looking at that log, I still do not understand how this is possible.  For any coders reading this thread: the ```worldObj``` is not remote - which tells us the tile is server-side - but ```GalacticraftCore.proxy``` set by ```@sidedproxy``` is the client side proxy. That should be totally impossible.  Somehow, Forge has mixed up the client and server threads.  I still think this is a Forge bug.  Has the same crash ever happened again, or only that one game session?

**Comment by radfast** [comment] 2016-01-14 04:12
* I have found one minor issue with Cargo Rockets in build 415:  if you place the Cargo Rocket down on a launch pad and then *after* that you build the Launch Controller, the Cargo Rocket is not controlled - the Cargo Rocket will not move until you break it and place it on the pad again.  Now fixed in 416, see: https://github.com/micdoodle8/Galacticraft/commit/8354f3bf4084e60ea7125b48410bb653cc288ccc

* I cannot reproduce the issue described by @jeridan .  I'm on the moon, 2 Launch Controllers 256 blocks apart, Cargo Rockets are flying properly between them 10/10 times.  Everything is good and smooth.  The rocket launch and landing looks so nice.  I <3 Galacticraft.

Please test if the "disappearing Cargo Rocket" issue still occurs in latest build 416.

If it still occurs for you, please:

1. In ```.minecraft/config/Galacticraft/conf.core``` set ```B:"Enable Debug Messages"=true```

2.  Test the issue again, and post the log covering the time of the test - there should be messages about the cargo rocket.

**Comment by EzerArch** [comment] 2016-01-14 05:19
Jenkins says 416 build failed.

**Comment by radfast** [comment] 2016-01-14 11:54
415 = 414 = 413.  It has changes.  I ran it through three builds, to bring the numbering into line with the numbers I have been using while the site was down.  415 comes after 414a.

**Comment by radfast** [comment] 2016-01-14 12:49
Build 418 now available on Jenkins and download site.  This includes even more logging for Cargo Rockets.  People with the Cargo Rockets problem, please test with 418, with debug enabled, and provide logs -> that should help me to find a fix for this soon now.

**Comment by EzerArch** [comment] 2016-01-15 04:11
I was hitting my head wondering, why any version 413 and above was crashing, it was GalaxySpace that became incompatible with GC. (I should pay more attention to [the error log](https://gist.github.com/EzerArch/6ca044809cfa82991b85) --- this log is not important now).

Well, sorry for making you wait. I tested twice with different mod packages. The rocket was supposed to go from OW (address 1) to the Moon (address 2):

* With all mods: https://gist.github.com/EzerArch/933ab58a1ba0b132220f

* With few mods: https://gist.github.com/EzerArch/03eedf66e1f4984edefd

It seems the mod is mixing up the dimension addresses the rocket was supposed to use, as you can see here (line 1791, 2nd log):
```
[02:03:14] [Server thread/INFO] [Galacticraft/]: Debug: [Serverside] Cargo rocket reached space, heading to 2
[02:03:14] [Server thread/INFO] [Galacticraft/]: Debug: Destination location = [231,66,197]
[02:03:14] [Server thread/INFO] [Galacticraft/]: Debug: Destination is in different dimension: -28
```
This message spams 21 times and then stops. Cargo rocket disappears.

**Comment by radfast** [comment] 2016-01-15 18:50
The message looks correct to me, if the destination Launch Controller was set with frequency '2' and if that destination was on the Moon (dim -28) at the location given.

I'm assuming that you the starting launch pad is **not** on the Moon, so it is correct to log that the destination is in a different dimension.

Spamming the message 21 times is a big problem, that should not be happening -> I'll take a look.

Thanks for the error report with GalaxySpace, please do tell me about stuff like that if it was working before and suddenly stops working.  In this case I changed the API yesterday without offering legacy compatibility, so any Add On which did not immediately update yesterday is going to have a crash.  I should not have done that, that will be fixed in GC 420 so that Add Ons will not crash.

**Comment by EzerArch** [comment] 2016-01-15 21:49
> I'm assuming that your the starting launch pad is not on the Moon.

Correct. I was sending the cargo rocket from the overworld to the moon.

**Comment by radfast** [comment] 2016-01-16 04:14
Good news.  I have fixed this issue, I think.   And at the same time, this will fix several other intermittent / rare glitches with Galacticraft in SSP mode.

Big thanks to @EzerArch for perseverance with this and detailed descriptions of the problem.  Turned out that crash report from higher up was also very relevant...

So roughly what was going on here is that a couple of core things buried deep inside Galacticraft were sometimes randomly initialising themselves in "client mode" inside the internal server of a SSP game.  (I'm sure you guys all know that in an SSP game, Minecraft runs a client side and an internal server as well, in the same game.)  You could say it was a coding error by us, but incredibly obscure and hard to spot.  For any Java devs reading, the problem is that if a ```@SidedProxy``` is referenced from inside a ```static``` method in a class, it seems the side of the proxy will be determined according to which side was randomly the current side when the static method in the class was first initialised - and not according to the current thread.

**Closed** 2016-01-16 04:18 UTC
Labels: follow-up please, Priority

**Comment by EzerArch** [comment] 2016-01-17 04:46
You should feel proud. :)

![2016-01-17_02 41 57](https://cloud.githubusercontent.com/assets/6743303/12375989/69a845b8-bcc4-11e5-8686-acd913fb9a4e.png)

![2016-01-17_02 45 16](https://cloud.githubusercontent.com/assets/6743303/12375990/69a9b588-bcc4-11e5-8a48-95f7cde4754b.png)

**Comment by radfast** [comment] 2016-01-17 13:43
:)  Took me most of a day to find and fix that.  But I'm glad it's fixed.  It should solve a few of the more rare/strange issues.
