### ISSUE TITLE
AL lib: (EE) alc_cleanup: 1 device not closed

### ISSUE THREAD

**Issue by Romsik788** [micdoodle8/Galacticraft#3488] opened 2018-07-27 15:40 UTC
Minecraft version: 1.12.2
Galacticraft version:4.0.1.181

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP not opened to LAN
Galacticraft add-ons and other mods installed?

Please provide screenshots / crash report / log as needed.
Minecraft crash in my ide Eclipse when I fly to Venus
[crash-2018-07-27_18.33.35-client.txt](https://github.com/micdoodle8/Galacticraft/files/2236384/crash-2018-07-27_18.33.35-client.txt)

**Comment by radfast** [comment] 2018-07-29 14:41
That's not a Galacticraft issue.

The problem is sometimes when running Minecraft in Eclipse it does not shut down the Audio Library correctly (especially if the game crashed).

If the Audio Library did not shut down correctly, you will see this next time you start the game.

Start the game again and the problem should be fixed.

**Closed by radfast** 2018-07-29 14:41 UTC
