### ISSUE TITLE
Mob skull isn't properly fitted onto the player's head

### ISSUE THREAD

**Issue by OfficialCFM** [micdoodle8/Galacticraft#3192] opened 2018-02-25 04:12 UTC
Minecraft version: 1.12.2
Galacticraft version: 140
Forge version: 14.23.2.2611

When putting a mob skull in the helmet slot, they will not follow the player's rotation properly.

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
This happens both in singleplayer and multiplayer.

Galacticraft add-ons and other mods installed?
See below:  
```
GalacticraftCore-1.12.2-4.0.1.140  
Galacticraft-Planets-1.12.2-4.0.1.140  
MicdoodleCore-1.12.2-4.0.1.140  
```

Screenshots:
![Screenshot 1](https://i.imgur.com/n532BJF.png)
![Screenshot 2](https://i.imgur.com/qxgJsyw.png)
![Screenshot 3](https://i.imgur.com/9dsr49R.png)

**Comment by radfast** [comment] 2018-02-25 12:11
thank you for reporting, this one shouldn't be too hard to fix

**Comment by marcus8448** [comment] 2018-03-02 03:18
Partial duplicate of #2990

**Comment by radfast** [comment] 2018-03-05 01:03
This is fixed in next build 151.  Thanks again for the report and images.

**Closed** 2018-03-05 01:03 UTC
