### ISSUE TITLE
[1.10.2] GC4 Server Crash in Asteroid dimension

### ISSUE THREAD

**Issue by rashdanml** [micdoodle8/Galacticraft#2908] opened 2017-07-20 16:36 UTC
Minecraft version: 1.10.2
Galacticraft version: 4.0.0.114
Forge version: 12.18.3.2297

SMP. Modlist: https://pastebin.com/4s3E844G Happens mainly when generating chunks, iirc. I crash almost instantly when I load back in after the first crash. 

Crash report:
Description: Exception ticking world

java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
    at java.util.ArrayList$Itr.next(ArrayList.java:851)
    at micdoodle8.mods.galacticraft.planets.asteroids.world.gen.ChunkProviderAsteroids.func_185931_b(ChunkProviderAsteroids.java:712)
    at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000)
    at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:983)
    at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
    at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
    at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Thread.java:745)

(I will have the full crash reports soon). 

Detailed Crash report: https://gist.github.com/rashdanml/fc373be00fab432b625c8ab23ca7c30d

**Comment by radfast** [comment] 2017-07-20 21:41
Thank you for reporting.

This is a duplicate of #2899, and will be fixed in next build 115.

**Closed by radfast** 2017-07-20 21:41 UTC

**Comment by MJRLegends** [comment] 2017-07-25 01:59
@radfast Is there any chance you could make a build for 1.10.2 and 1.11.2 on Jenkins please, it would be amazing if you could. Sorry i know your busy :D

**Comment by radfast** [comment] 2017-07-29 21:55
build 115 will be up for all versions later tonight, maybe 1 hour from time of posting this
