### ISSUE TITLE
[1.7.10] [GalaxySpace] Delete schematics, if destroy Nasa workbench

### ISSUE THREAD

**Issue by BlesseNtumble** [micdoodle8/Galacticraft#2471] opened 2017-03-20 23:48 UTC
Removing the schematics, if you destroy the workbench NASA.

**Comment by radfast** [comment] 2017-03-21 01:37
I don't understand.  Please give more explanation / steps.

**Comment by BlesseNtumble** [comment] 2017-03-21 12:11
The player activates new schemes in the workbench (Tier 2, 3, buggy, etc.)
But after he breaks the workbench - he needs to look again for these schemes.
No saving of unlocked schemes.

**Comment by MJRLegends** [comment] 2017-03-21 19:57
im unable to reproduce this with the latest 1.7 commits, not sure if this helps :D

**Comment by radfast** [comment] 2017-03-21 23:21
Schematics are saved on a **per-player** basis.  This happens automatically and permanently, as soon as the player unlocks a schematic.

If this isn't working in your game, it means one of three things:
* the player is not a GCEntityPlayerMP (in which case, you should also have oxygen gear issues)
* playerdata is not saving correctly
* internal handling of `galacticraft.api.recipe.SchematicEvent.unlock` is broken

Did you change something related in your add-on?

**Comment by BlesseNtumble** [comment] 2017-03-21 23:34
This is not in addition.
This is in a clean GC3 on a server with a Thermos core.

**Comment by radfast** [comment] 2017-03-21 23:40
aaarggh  Thermos
Very hard for me to debug

**Comment by BlesseNtumble** [comment] 2017-03-21 23:52
https://ci.micdoodle8.com/job/Galacticraft-1.7/482/

**Comment by radfast** [comment] 2017-03-21 23:54
There is no change in 482 relevant to Schematics.  Code relating to Schematics has not changed at all for _approximately_ 1 year.

**Comment by radfast** [comment] 2017-03-22 00:10
This player.dat you sent me has unlocked Schematics pages 2, 4, 6, 7, 8, 9, 10.
I don't know what those all are, but should be maybe T2 rocket, T3 rocket, and 5 other rocket tiers from your addon.  I think you had an addon installed previously, and now you removed it.  This is causing an error in Galacticraft because it is not recognising schematics 6, 7, 8, 9, 10 and so it fails with a null somewhere.

**Comment by radfast** [comment] 2017-03-22 00:15
Please try new build 483

**Comment by radfast** [comment] 2017-03-23 14:57
I'm going to close this on the **assumption** this issue is fixed by build 483.
If it's still a problem after 483, please comment or re-open.

**Closed by radfast** 2017-03-23 14:57 UTC
Labels: 1.7, cant reproduce

**Comment by BlesseNtumble** [comment] 2017-03-23 23:19
The problem is fixed. However, this bug remained when the player died.

**Comment by radfast** [comment] 2017-03-24 01:14
and GalaxySpace is not installed, currently?  (when the player died?)

**Comment by radfast** [comment] 2017-03-24 01:21
When the player died, could be a totally different bug.  Please list all installed mods.

**Comment by BlesseNtumble** [comment] 2017-03-24 13:58
![1](https://pp.userapi.com/c638222/v638222755/322b7/C-WQ__FMKNM.jpg)

Thermos last version.

**Comment by ensirius** [comment] 2017-09-04 09:19
My server players loosing unlocked schematics too with thermos and 502 build

**Comment by radfast** [comment] 2018-01-15 12:24
Please provide a copy of server-side startup log - I'm looking to see whether micdoodleCore reported any transform errors.

**Comment by vagola** [comment] 2019-01-07 17:04
``` cat latest.log | grep "MicdoodleTransformer"
[09:39:26] [main/INFO]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1989]: Galacticraft successfully injected bytecode into: ahb (1 / 1)
[09:39:26] [main/INFO]: [micdoodle8.mods.miccore.MicdoodleTransformer:printResultsAndReset:1905]: Potential problem: Galacticraft did not complete injection of bytecode into: oi (4 / 6)
[09:39:26] [main/INFO]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1989]: Galacticraft successfully injected bytecode into: sv (1 / 1)
[09:39:26] [main/INFO]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1989]: Galacticraft successfully injected bytecode into: xk (1 / 1)
[09:39:27] [main/INFO]: [micdoodle8.mods.miccore.MicdoodleTransformer:printLog:1989]: Galacticraft successfully injected bytecode into: zc (1 / 1)
```
