### ISSUE TITLE
Potion effect on Galaticraft mob in nether

### ISSUE THREAD

**Issue by skaviouz** [micdoodle8/Galacticraft#1366] opened 2015-01-08 09:24 UTC
Original source: http://www.resonant-rise.com/topic/4602-crash-in-the-nether/
Finder: MrMallenby
Version: 1.7.10 - 3.0.6 - 245 (checked changelog, newer versions mentions nothing related, bug exists in newer version [upto 250])
pastebin: http://pastebin.com/FA8feSuZ

#### Premise:
A potion effect on a galaticraft mob (MRHeavyMetal_SIR) while in the nether caused a java.lang.NullPointerException: Ticking entity.

#### Note:
This was tested in RR 3.2.1.0 experimental pack using GC 245. I'll go ahead and edit/update issue after I can get another sample / crash in build 250.

#### Speculation:
Special Mobs 3.0.3, but I thought this only replaced some vanilla mobs with SpecialSkelleton / SpecialPigZombie with extra special attributes. Well let's find out with some vanilla potions and gunpowder ;)

**Comment by radfast** [comment] 2015-01-08 12:15
Duplicate of #1365.
I do not think either one is a Galacticraft issue.
If you have any reason for thinking it is a Galacticraft issue, please explain.

**Closed by radfast** 2015-01-08 12:15 UTC

**Comment by radfast** [comment] 2015-01-08 12:18
See also #1323 which looks the same.
Do you have either Infernal Mobs or Biomes o' Plenty installed?

**Comment by radfast** [comment] 2015-02-01 17:10
On #1365 it's been suggested that __Blood Magic__ may be the cause.
