### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by ThewolfGod** [micdoodle8/Galacticraft#3807] opened 2019-10-05 05:45 UTC
Minecraft version:1.12.2
Galacticraft version:Galacticraft-Planets-1.12.2-4.0.2.237

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? SMP
server CatServerPro
link: https://github.com/Luohuayu/CatServer

Any Galacticraft add-ons installed? please list all
ExtraPlanets-1.12.2-0.5.8
More-Planets-1.12.2-2.0.21-GC224

Please provide screenshots / crash report / log / full modlist as needed

crash
[crash-2019-10-05_00.27.52-server.txt](https://github.com/micdoodle8/Galacticraft/files/3692889/crash-2019-10-05_00.27.52-server.txt)

logs
[2019-10-05-3.log.gz](https://github.com/micdoodle8/Galacticraft/files/3692890/2019-10-05-3.log.gz)

**Comment by TheQuadShot** [comment] 2019-10-05 07:25
This is a Turret crash, and a snippet from the log:

Description: Exception in server tick loop
java.lang.NoSuchFieldError: timeSinceShot
	at micdoodle8.mods.galacticraft.planets.venus.tile.TileEntityLaserTurret.<init>(TileEntityLaserTurret.java:98)

**Comment by ThewolfGod** [comment] 2019-10-05 11:47
> 这是炮塔崩溃，也是日志中的一个片段：
> 
> 说明：服务器刻度循环中的异常
> java.lang.NoSuchFieldError：
> micdoodle8.mods.galacticraft.planets.venus.tile.TileEntityLaserTurret。（TileEntityLaserTurret.java:98）上的timeSinceShot

Is that Communications Dish?

**Comment by TheQuadShot** [comment] 2019-10-05 19:55
attempt this, 
edit this file and set this line to =true

/config/forge.cfg
    B:removeErroringTileEntities=false

so the above should now be
    B:removeErroringTileEntities=true

**Comment by radfast** [comment] 2019-10-17 21:44
Duplicate of #3795.   This is fixed in next build 238 - thank you for reporting.

**Closed by radfast** 2019-10-17 21:44 UTC
