### ISSUE TITLE
Class casting failure causing server crash

### ISSUE THREAD

**Issue by apertureos** [micdoodle8/Galacticraft#4059] opened 2020-09-13 02:41 UTC
Minecraft version: 1.12.2
Galacticraft version: 4.0.2.280

Multiplayer running 1.12.2-forge-14.23.5.2854 (just forge, not sponge or anything else)

Galacticraft addons: Galacticraft-Planets 4.0.2.280, GalaxySpace 2.0.14

Crash log:
The mod list is provided in the crash log

Download site: micdoodle8.com

**Comment by dj3520** [comment] 2020-09-14 23:49
Does this still happen without the Fire and Ice mod installed?

**Comment by CrypticSiri** [comment] 2020-09-14 23:58
The crash only occurs when a fire dragon shoots a fireball, so no, it does not. However, a very similar fireball-induced class casting crash was reported earlier for Ice and Fire (https://github.com/Alex-the-666/Ice_and_Fire/issues/740 ticket numbers #694, #733, #734), where the developer stated that the problem was not caused by Ice and Fire but rather Thaumcraft. They also explained that the problem was fixed on their side, so I figured something similar might be happening here. I apologize if I'm wrong, though.

**Closed** 2023-05-01 02:31 UTC
