### ISSUE TITLE
Galacticraft server generating high amount of outgoing network traffic on Moon

### ISSUE THREAD

**Issue by zedekblue** [micdoodle8/Galacticraft#2266] opened 2016-09-08 10:33 UTC
So I'm running a small (-ish) server from a remote location. [Here's the modlist if you wanna check it.](http://pastebin.com/ZSm15Dnp)  

Anyways, the issue is lag on the moon, and although untested, might be on other planets too.  
It happens when I'm in a single area for a period of time. Constantly moving fixes the issue almost entirely, but it's impossible to build anything.

After some testing, I figured out:
1. This happens on the moon/galacticraft dimensions only. Overworld, nether, and all other dimensions load and run just fine.
2. Both the server and client are running just fine. There's enough resources on both ends to keep up with everything.
3. Entity count is fine. Stays around 40-80.
4. Tracking upload/download speeds, it seems the longer I'm there, the more and more the server is uploading. Eventually this just becomes too much for the client to download, or the server to upload.
5. The upload speed/lag fluctuates. I'll have perfect connection when the upload speeds are low, and slow connection when they're high. Sometimes the speeds change every minute or so.

Nothing is built on the moon yet. I tried setting up a small room with leaves and oxygen, but the lag gave me issues and I tore it down to test.

Attached is a couple screenshots of the upload/download tracker at different times.
![gcissue](https://cloud.githubusercontent.com/assets/17040113/18346320/d10cb93e-757c-11e6-8561-b4b18b0b3d65.png)

**Comment by radfast** [comment] 2017-02-25 19:46
Hi, sorry for slow response, I've been away for a few months.  I'm interested in trying to fix issues like this - if it is a Galacticraft issue.

But that's a large modlist you have.  Any chance of testing the Moon on your server with a much smaller modlist, maybe GC only?

BTW what upload/download tracker is that?  Looks nice.

**Comment by dj3520** [comment] 2017-02-25 20:56
it's from nettools 5

**Comment by radfast** [comment] 2017-02-25 22:18
If anyone else has time to help us reduce Galacticraft network traffic, the help will be appreciated.

What is needed (with **only** Galacticraft loaded please)
* screenshots like @zedekblue posted, showing total outgoing network traffic from a server (uploads) in different game situations
* if you have a way of sniffing the Minecraft / Forge packets to see what the traffic mainly is, that would really help - I've heard there is a way to do this, but I don't know it myself

**Comment by zedekblue** [comment] 2017-02-25 22:19
Yeah, I won't be able to follow up with this, you'll probably need to close the issue. The modpack has been drastically changed and almost entirely abandoned since 1.10 happened. We no longer run on a windows environment so I wouldn't even know where to start measuring comparable data.
Galacticraft was still using a metric ton of bandwidth and CPU, but I ended up forced to just upgrade the machine altogether to handle it. I spent a few days removing batches of mods to try and narrow this issue down, but it was such an inconsistent issue (took 10-15 minutes for the lag to really kick in), that I eventually gave up.
Thanks for following up though. Love the work you've done.

**Comment by radfast** [comment] 2017-02-25 22:50
thanks for the update

> Galacticraft was still using a metric ton of bandwidth and CPU

I will leave this issue open a few days, in case somebody else wants to comment on network traffic, we do want to deal with this if it's a problem affecting a lot of servers, but I will need help from testers so I know which parts of Galacticraft to look at.

**Comment by radfast** [comment] 2017-04-19 13:32
I've done some profiling.  II think it's caused by [footprint updates](https://github.com/micdoodle8/Galacticraft/blob/MC1.7/src/main/java/micdoodle8/mods/galacticraft/core/tick/TickHandlerServer.java#L302) triggered by [block breaking](https://github.com/micdoodle8/Galacticraft/blob/MC1.7/src/main/java/micdoodle8/mods/galacticraft/core/blocks/BlockBasicMoon.java#L423-#454)

I don't know yet why so many Moon Turf blocks are breaking every tick, but I've noticed it's a lot every tick even in quiet server with 0 players in the dimension, and only a few spawn chunks loaded.

**Comment by radfast** [comment] 2017-04-21 14:29
This is fixed in build 487 (and later) of Galacticraft 3, and in build 70 (and later) of Galacticraft 4.

(It wasn't the Moon Turf + footprints, it was the Lander.)

**Closed by radfast** 2017-04-21 14:29 UTC
Labels: 1.7
