### ISSUE TITLE
Hunger bar depletes fast after returning from a GC world

### ISSUE THREAD

**Issue by Hazmatik** [micdoodle8/Galacticraft#2278] opened 2016-10-02 23:37 UTC
When I return to the overworld from any GC world using the Essentials /home command on a server or by any other way other than launching back with a rocket, my hunger bar depletes insanely fast. I fill it up and it's empty again in less than 2 minutes. The only way to stop it from doing so seems to be to relog.

Playing on Bevo Tech Pack Reborn version 2.0

GC & GC Planets version: 1.7-3.0.12.454

Pack also includes GalaxySpace addon version 1.0.8STABLE not sure if this could have something to do with it.

**Comment by radfast** [comment] 2016-11-20 13:05
I can think of no Galacticraft explanation for this.  Galacticraft does not do anything special to player hunger bars (except adding to them when you eat Galacticraft canned food).

You mention "other ways", please describe a couple of the other ways you are using to change planets, apart from /home.  Could be connected with the way these other methods are spawning a player on the overworld, although usually what you'd see would be a lot of Galacticraft stuff not working properly, but basic Minecraft elements like the hunger bar working OK.

I took a quick look at Bevo TP, looks like a huge modpack with around 100 mods.  If this is caused by a conflict between Galacticraft and another mod, it's going to take an inordinately long time to figure which one it is.

**Comment by radfast** [comment] 2016-11-20 13:56
I've thought about this some more ...

* Do you have any mods installed that change food or hunger?

* Does the same hunger bar issue happen if you go to the **Nether** or the **End** and then use Essentials /home (or other ways, not GC rockets) to return to the Overworld?

**Comment by radfast** [comment] 2017-02-25 19:18
Closing due to lack of follow-up, and because it appears this is not a Galacticraft issue.

Please re-open if it happens **only** with GC worlds and not with other worlds like the Nether or the End.

**Closed by radfast** 2017-02-25 19:18 UTC
Labels: 1.7, follow-up please, not a Galacticraft issue
