### ISSUE TITLE
[Intel graphics] Fatal Error When Loading Worlds With Galacticraft [3.0.11]

### ISSUE THREAD

**Issue by zachman338** [micdoodle8/Galacticraft#1657] opened 2015-05-18 19:01 UTC
For some reason when I try to load worlds with the galacticraft mod my game will automatically shutdown and crash.

Here Are The Game Output Logs: 
#1: http://pastie.org/10195296
#2: http://pastebin.ca/3005106
#3: http://pastebin.ca/3005107
#4: http://pastie.org/10195284 

Here Is The Crash Log: http://pastie.org/10195277

**Comment by radfast** [comment] 2015-05-18 21:42
Duplicate of #619.

Things to try:

* Test whether your Minecraft starts without Galacticraft and MicdoodleCore installed (on #619, the same issue was in vanilla Minecraft)

*  Try reducing your rendering distance - you can change the Options from the main Minecraft menu

*  Both players reporting the issue seem to be using Intel integrated graphics.  This could be a graphics card issue.  If possible update your drivers, and improve your OpenGL settings (accessible via your Graphics Properties page), for example give more memory to stuff like buffers,

**Comment by zachman338** [comment] 2015-05-19 15:33
I think this issue was a Java location problem. I had it set to my old location which was incorrect. I changed that and set my render to 8 and that fixed the problem. Thank you for your time assessing this isssue.

**Closed** 2015-05-19 15:33 UTC
