### ISSUE TITLE
Display Screen not working in Multiplayer

### ISSUE THREAD

**Issue by Zunno** [micdoodle8/Galacticraft#2841] opened 2017-06-18 12:16 UTC
Hey,

i added Galacticraft in FTB Beyond (MC Version 1.10.2) playing on a multiplayer Server.
My Friend builded a Display Screen but it dosen't turn on. 
We are using the Version 4.0.0.108 of Galacticraft.
I also tested it on singleplayer, but in singleplayer it works fine.

Greets Zunno

**Comment by radfast** [comment] 2017-06-18 14:53
Thanks for reporting, this is very helpful.

This is a duplicate of #2831 so I'll merge the issues and deal with it there.  We should be able to fix this quite easily.

**Closed by radfast** 2017-06-18 14:53 UTC

**Comment by radfast** [comment] 2017-06-18 16:24
This is fixed in next build 109, which should be available soon.
