### ISSUE TITLE
Game/Server Crashes When Hopper Touches Energy Storage Cluster

### ISSUE THREAD

**Issue by VoidFyre** [micdoodle8/Galacticraft#2971] opened 2017-09-03 04:21 UTC
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.10.2
Galacticraft version: 4.0.0.117
Forge version:  12.18.3.2422-Universal

Single player (SSP) or Multiplayer (SMP)?
Both

Galacticraft add-ons and other mods installed?

Applied Energistics 2
AutoRegLib
Backpacks-Mod-1.10.2
Baubles
BiblioCraft
BiomesOPlenty
Botania
Mr. Crayfish's Furniture mod
Chameleon
Chisels and Bits
CodeChickenLib
CoFH Core
Davinci's Vessels
Elevator Mod
EnderCore
EnderIO
ExtraPlanets
Extra Utilities
Industrialcraft
JEI
MCMultiPart
ModularPowersuits
Movingworld
Quark
Railcraft
StorageDrawers
Sublib
Telepads
Thermal Expansion
Thermal Foundation
Waila

Please provide screenshots / crash report / log as needed.

[23:48:39] [Server thread/INFO]: Nytefallen[/127.0.0.1:54944] logged in with entity id 189 at (-691.0, 64.23559998512266, -1461.0)
[23:48:39] [Server thread/INFO]: Nytefallen joined the game
[23:48:45] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:715) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) ~[ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 3
	at micdoodle8.mods.galacticraft.core.energy.tile.TileBaseElectricBlockWithInventory.func_70301_a(TileBaseElectricBlockWithInventory.java:60) ~[TileBaseElectricBlockWithInventory.class:?]
	at net.minecraft.tileentity.TileEntityHopper.func_174917_b(TileEntityHopper.java:337) ~[aqx.class:?]
	at net.minecraft.tileentity.TileEntityHopper.func_145891_a(TileEntityHopper.java:369) ~[aqx.class:?]
	at net.minecraft.tileentity.TileEntityHopper.func_145887_i(TileEntityHopper.java:207) ~[aqx.class:?]
	at net.minecraft.tileentity.TileEntityHopper.func_73660_a(TileEntityHopper.java:187) ~[aqx.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1804) ~[aid.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620) ~[ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) ~[MinecraftServer.class:?]
	... 4 more
[23:48:45] [Server thread/ERROR]: This crash report has been saved to: D:\Final Frontier\.\crash-reports\crash-2017-09-02_23.48.45-server.txt
[23:48:45] [Server thread/INFO]: Stopping server

**Comment by TheQuadShot** [comment] 2017-09-03 07:25
I can't repro this on SSP, I was able to place a hopper on all 6 sides of the Energy Module and the Energy Cluster, with power stored w/o powered stored, and receiving power via batteries and/or HeavyWire. I also tried to apply a redstone signal to hoppers. I know this is strange but what happens if you disable Davinci's Vessels? I'm pretty sure I had some very strange problems with that mod in the past.
Here's a complete list of installed mods:

MC: 1.10.2
Forge: 2422
CodeChickenLib-1.10.2-2.5.9.283-universal.jar
CoFHCore-1.10.2-4.1.11.16-universal.jar
EnderCore-1.10.2-0.4.1.66-beta.jar
EnderIO-1.10.2-3.1.193.jar
Galacticraft-Planets-1.10.2-4.0.0.117.jar
GalacticraftCore-1.10.2-4.0.0.117.jar
InventoryTweaks-1.61-58.jar
jei_1.10.2-3.14.7.419.jar
mcjtylib-1.1x-2.4.3.jar
MicdoodleCore-1.10.2-4.0.0.117.jar
MouseTweaks-2.8-mc1.10.2.jar
ThermalFoundation-1.10.2-2.1.5.12-universal.jar
Waila-1.7.0-B3_1.9.4.jar

**Comment by SteveKunG** [comment] 2017-09-18 06:52
Can't reproduce. Tested in development without other mods.

**Comment by radfast** [comment] 2017-10-02 21:51
Do you mean when a hopper touches **Electric Arc Furnace**?  This is issue #2981, fixed in next build 118.

I am closing this in the **hope** that that fixes it, if you're sure it was an Energy Storage Cluster please re-open and please provide a screenshot of your setup if possible.  (With this type of crash, likely the setup works OK when first built but will crash when the world is re-loaded after exiting.)

**Closed by radfast** 2017-10-02 21:51 UTC
