### ISSUE TITLE
Custom flag and team information not saved. (server)

### ISSUE THREAD

**Issue by BBoldt** [micdoodle8/Galacticraft#957] opened 2014-09-06 06:32 UTC
I know the whole "space race" feature isn't really complete yet, but the flag creation, teams, and colors all look like they *should* work. It kinda sucks when a player spends some time making a flag and it doesn't end up saving.

This isn't really a critical issue, it can probably wait. I just wanted to make sure you guys knew it was an issue.

Keep up the good work! I'm loving the new stuff in 1.7.10 so far.

**Comment by christopherftw09** [comment] 2015-02-07 12:39
I have the same issue with flag and team information not saving property on a multiplayer server but when I look in the world files the GCSpaceRaceData.dat file is there so I think the server is saving the information just isn't giving it to the players.

**Comment by christopherftw09** [comment] 2015-02-07 13:42
I'm having the same issue but it looks like the server is saving the information but not giving the players it back.

**Comment by radfast** [comment] 2015-02-08 02:31
oho, thanks @christopherftw09  that may help to shed some light on this mystery
Please explain more what you mean by "the server is saving the information", have you looked at the save files using NBTExplorer or similar?

**Comment by Hazado** [comment] 2015-02-08 02:33
You can open the dat file with winrar and look at the plain text the server saves for galacticraft

**Comment by Hazado** [comment] 2015-02-08 19:22
on my server there is a file called GCSpaceRaceData.dat. Ive made a flag twice already, and had it disappear both times. Figured it was because I dont have a space station yet.
Inside it is this information.
http://pastebin.com/iWbtwg3D

Its located at <server>/world/data/GCSpaceRaceData.dat

**Comment by christopherftw09** [comment] 2015-02-08 19:23
@radfast it is saving the information in a GCSpaceRaceData.dat file inside the world's data folder (/[worldname]/data/GCSpaceRaceData.dat)

I've checked in there and it contains all the information about team name, team member names, flag design.

**Comment by radfast** [comment] 2015-02-09 12:34
Server owners, please try out new build 3.0.8.263  (it's OK for your players to stay on some earlier 3.0.8.xxx version, there will be no issues if the players are not yet updated to .263).

There's a chance this will fix the problem, but if not I also included some logging to help see what's going on here.  To see the logging, in Galacticraft ```core.conf``` please switch on:
>    B:"Enable Debug Messages"=true

This will create a small amount of log spam as it enables all of Galacticraft's debug messages, so you'll likely want to switch that back to false when we are done testing the space race.

(The real problem here is I cannot reproduce the issue in my own testing, which always makes things hard to figure out - could be an obscure issue that depends on the Java version or it is different on a Linux server or something.)

**Comment by christopherftw09** [comment] 2015-02-09 15:49
I will give it a test now.

**Comment by christopherftw09** [comment] 2015-02-09 16:20
Didn't look like it worked

I have setup a server for you to test the issue on.

https://github.com/christopherftw09/galacticraft-test
I have added you as Collaborator to see the login info since i can't email it you.

**Comment by radfast** [comment] 2015-02-09 22:33
@christopherftw09  that's really kind of you and good thinking re the Github Collaborator approach.  But to "check out the issue" I need to make, and run on a server, temporary test builds of Galacticraft with extra logging added, see if that shows up any meaningful clues, then rinse and repeat.  Possibly also delve into the saved .dat file using the proper tool which is NBTExplorer.  I can only realistically do all that on my own LAN.

Let me try it on my LAN with a full Cauldron setup and that same modpack that you are using.  As soon as I can make the problem happen, then I can work on finding a fix.  (If not then I will speculate again that it could be due to differences in Java implementations - all my machines are Windows boxes running Java 7 - but let's not worry about that unless we need to.)

**Comment by radfast** [comment] 2015-02-11 19:53
I made a new build 3.0.8.264 which may come closer to fixing this issue.

When testing it on a server, please do set the "enable debug" in the config to true, and then look in your logs at server startup (map load) and shutdown (map save) for lines like these:
>[13:50:57] [Server thread/INFO] [Galacticraft]: Registered Dimension: -30
[13:50:57] [Server thread/INFO] [Galacticraft]: Registered Dimension: -29
[13:50:57] [Server thread/INFO] [Galacticraft]: Registered Dimension: -28
[13:50:57] [Server thread/INFO] [Galacticraft]: Loading spacerace data for team TeamRad
[13:50:57] [Server thread/INFO] [Galacticraft]: Loaded spacerace team data OK.

>[13:51:07] [Server thread/INFO]: Saving worlds
[13:51:07] [Server thread/INFO]: Saving chunks for level 'Flagtest'/Overworld
[13:51:07] [Server thread/INFO] [Galacticraft]: Saving spacerace data for team TeamRad
[13:51:07] [Server thread/INFO] [Galacticraft]: Saved spacerace team data OK.
[13:51:07] [Server thread/INFO]: Saving chunks for level 'Flagtest'/Nether
[13:51:07] [Server thread/INFO]: Saving chunks for level 'Flagtest'/The End
[13:51:07] [Server thread/INFO]: Saving chunks for level 'Flagtest'/moon.moon
[13:51:07] [Server thread/INFO]: Saving chunks for level 'Flagtest'/planet.mars
[13:51:07] [Server thread/INFO]: Saving chunks for level 'Flagtest'/planet.asteroids

Normally the spacerace data should load right after Galacticraft registers its dimensions.

**Comment by christopherftw09** [comment] 2015-02-12 01:32
Yeah radfast,

I have the same messages for server startup and shotdown.

```
[02:35:28] [Server thread/INFO]: Registered Dimension: -30
[02:35:28] [Server thread/INFO]: Registered Dimension: -29
[02:35:28] [Server thread/INFO]: Registered Dimension: -28
[02:35:28] [Server thread/INFO]: Loading spacerace data for team Chris's Team
[02:35:28] [Server thread/INFO]: Loaded spacerace team data OK.
[02:35:28] [Server thread/INFO]: Loading spacerace data for team Unnamed Team
[02:35:28] [Server thread/INFO]: Loaded spacerace team data OK.

[02:38:33] [Server thread/INFO]: Saving worlds
[02:38:33] [Server thread/INFO]: Saving chunks for level 'world'/Overworld
[02:38:33] [Server thread/INFO]: Saving spacerace data for team Unnamed Team
[02:38:33] [Server thread/INFO]: Saved spacerace team data OK.
[02:38:33] [Server thread/INFO]: Saving spacerace data for team Unnamed Team
[02:38:33] [Server thread/INFO]: Saved spacerace team data OK.
[02:38:34] [Server thread/INFO]: Saving chunks for level 'DIM1'/The End
[02:38:34] [Server thread/INFO]: Saving spacerace data for team Unnamed Team
[02:38:34] [Server thread/INFO]: Saved spacerace team data OK.
[02:38:34] [Server thread/INFO]: Saving spacerace data for team Unnamed Team
[02:38:34] [Server thread/INFO]: Saved spacerace team data OK.
[02:38:34] [Server thread/INFO]: Saving chunks for level 'DIM-1'/Nether
[02:38:34] [Server thread/INFO]: Saving spacerace data for team Unnamed Team
[02:38:34] [Server thread/INFO]: Saved spacerace team data OK.
[02:38:34] [Server thread/INFO]: Saving spacerace data for team Unnamed Team
[02:38:34] [Server thread/INFO]: Saved spacerace team data OK.
[02:38:34] [Server thread/INFO]: Saving chunks for level 'resources'/Overworld
[02:38:34] [Server thread/INFO]: Saving spacerace data for team Unnamed Team
[02:38:34] [Server thread/INFO]: Saved spacerace team data OK.
[02:38:34] [Server thread/INFO]: Saving spacerace data for team Unnamed Team
[02:38:34] [Server thread/INFO]: Saved spacerace team data OK.
[02:38:34] [Server thread/INFO]: Unloading dimension 0
[02:38:34] [Server thread/INFO]: Unloading dimension -1
[02:38:34] [Server thread/INFO]: Unloading dimension 1
[02:38:34] [Server thread/INFO]: Unloading dimension 2
```

**Comment by radfast** [comment] 2015-02-28 20:00
This issue should be fixed now.

The issue was that although servers were saving and loading the flag data correctly, servers were not always sending it to clients (players) when players login, unless the player happened to be standing close to a Flag.  This meant that when the player went to Space Race, the player was given a new blank Space Race with name Unnamed Team.

If this happened over and over, you would end up with a lot of (unwanted) Unnamed Teams on the server.

I'm not sure if those Unnamed Teams will cause an issue or not, if they do then we can look at this further.  (It's something server owners can fix themselves if you know how to use a tool __NBTExplorer__.)

Also note that flags that players saved previously, should now load OK for the players.  (Again if the player made a lot of teams, due to this saving issue, then I'm not too sure which one of those teams  will be the one which loads up - I hope it will be the most recent.)

**Closed by radfast** 2015-02-28 20:00 UTC

**Comment by radfast** [comment] 2015-02-28 20:02
Thanks are also due to _babybasher_ on the forum for additional testing which led to the solution to this.
http://forum.micdoodle8.com/index.php?threads/space-race-flag-saving.4944/

**Comment by radfast** [comment] 2015-02-28 21:54
Any more flag issues, please post 'em up here.
It would be great if someone could test, 2 players on a server, 2 teams, 2 flags - does each player see the other player's flag correctly?

**Comment by radfast** [comment] 2015-03-01 02:02
Build 3.0.8.269 with the flags fix is now available.
