### ISSUE TITLE
[All Versions] Question/Suggestion related to Dungeon Loot giving schematics

### ISSUE THREAD

**Issue by MJRLegends** [micdoodle8/Galacticraft#2745] opened 2017-05-24 01:29 UTC
Ok, so many mods are adding Tier 4 schematics, which can only be added to Moon dungeon loot since the mars one is locked to only providing the Tier 3 and Astro Miner.

I have a few suggestions related to this and how to make it better

## **Suggestion 1:**

Have the moon dungeon loot hard coded like the mars so that you get the schematics in the following order

1. Tier 2 Rocket
2. Moon Buggy
3. Any other schematic that has been added via addons (Can be checked by detecting how many schematics in a loot tier?)

and then have Mars as

1. Tier 3 Rocket
2. Astro Miner
3. Any other schematic that has been added via addons (Can be checked by detecting how many schematics in a loot tier?)

This would also add the ability for addons to add schematics to mars dungeons as atm it feels kinda weird for Tier 4 rocket schematics to be added before getting Tier 3 rocket schematic

## **Suggestion 2:**

Schematics have chance values based off 1 - 100% and the higher the % the more chances of the schematic spawning, this would make it so you could get some sort of order to the schematics but get the old chance of a different order which could be a reward.

This suggestion is open to ideas as its just a concept idea

**Comment by radfast** [comment] 2017-05-24 01:30
This is a duplicate of #2166.

Although these suggestions are helpful, we don't need 2 open issues on the same thing, and one will now be referenced there.

**Closed by radfast** 2017-05-24 01:30 UTC

**Comment by MJRLegends** [comment] 2017-05-24 01:31
@radfast yeah no problem i just wanted to get my thought across to you devs :D as i feel like something needs to be addressed in this area to improve addons abilities at 1.7 and 1.8+ levels
