### ISSUE TITLE
Error when stopping a server with SpongeForge loaded

### ISSUE THREAD

**Issue by define-evil** [micdoodle8/Galacticraft#3420] opened 2018-05-28 09:21 UTC
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 1.12.2-4.0.1.177.jar

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SMP

Galacticraft add-ons and other mods installed?
SpongeForge

Please provide screenshots / crash report / log as needed.
[Log](https://pastebin.com/sd9p0bg0)

Galaticraft unloads perfectly without SpongeForge. This error shows up in multiple forge and spongeforge versions ranging from 2675 to 2705 when stopping the server, though 2675 discarded the error:
`[17:17:18] [Server thread/ERROR] [FML]: Skipping event FMLServerStoppedEvent and marking errored mod galacticraftplanets since required dependency galacticraftcore has errored
[17:17:18] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
[17:17:18] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded.
`

**Comment by radfast** [comment] 2018-05-28 21:47
Duplicate of #2864

**Closed by radfast** 2018-05-28 21:47 UTC

**Comment by radfast** [comment] 2018-06-25 22:11
I'm told that this issue no longer exists with forge 2705 and sponge 1.12.2-2705-7.1.0-BETA-3136

Please try it!
