### ISSUE TITLE
Mars Dungeon Generation error [1.7.10]

### ISSUE THREAD

**Issue by TheRussianDragon** [micdoodle8/Galacticraft#2308] opened 2016-10-30 06:39 UTC
Encountered a bug where Mars Dungeons won't generate the boss room, but will generate the treasure room. Image (sorry for quality) taken using my JourneyMap, where, as you can see, there is no boss room.

Playing with Buildcraft, IronChests, OptiFine, Et Futurum, JourneyMap and NEI.

Doesn't seem to be overly common, since this is my fourth dungeon but the first to not generate a boss room.

![2016-10-30_16 26 00_1_7_10 forge world_mars_slice-29](https://cloud.githubusercontent.com/assets/23146983/19834893/53fc30de-9ebf-11e6-96b4-c2b756f0890b.png)

**Comment by EzerArch** [comment] 2016-10-30 19:20
If it's in 1.7.10: Duplicate of #1126.

**Comment by micdoodle8** [comment] 2016-11-28 19:13
Fixed in the latest build for 1.8.9

**Closed by micdoodle8** 2016-11-28 19:13 UTC

**Comment by EzerArch** [comment] 2017-03-15 03:35
Question: is this fix only available in 1.8.9?

(ref.: [forum post](https://forum.micdoodle8.com/index.php?threads/dungeons-not-generating-with-treasure-rooms.6642/), [youtube comment](https://www.youtube.com/watch?v=yCuaRFcUgoU&lc=z12vwfqahvfme1iki23nczngeojvzhoul))

**Comment by radfast** [comment] 2017-03-23 15:19
Yes, this fix is available only in 1.8.9 for now.  Sorry!  micdoodle8 has written all the dungeon generation code in 1.8.9 to cure issues like this.

There is currently no solution for this in 1.7.10, players should just go look for a different dungeon.  Most dungeons have the Boss Room and Treasure Room.
