### ISSUE TITLE
[1.10.2] Sound event null! - on Moon etc

### ISSUE THREAD

**Issue by EmosewaGamer** [micdoodle8/Galacticraft#2590] opened 2017-04-15 17:12 UTC
I'm using Beta 64 and while I was on the Moon out of nowhere I got this crash: https://pastebin.com/KgqcCryD
What I could guess is that it has something to do with sound.

**Comment by micdoodle8** [comment] 2017-04-15 20:47
Hmm, strange. I've fixed the crash and added a line to output the sound which triggered the problem, if you're getting "Sound event null!" in your game log please paste it here. It looks like this happened when you placed a block, do you happen to know which block you placed?

**Comment by EmosewaGamer** [comment] 2017-04-15 22:18
Not exactly. It was something from the Chisel mod. 😐

**Comment by radfast** [comment] 2017-05-06 16:14
Closing this because the issue is fixed.

If anyone gets ```**Sound event null!**``` in their log now, please comment or post details here.  (It's most likely a sound created by another mod which is erroring ... Chisel?)

**Closed by radfast** 2017-05-06 16:14 UTC
