### ISSUE TITLE
Helium, CO2, Argon not have Textures in Gregtech

### ISSUE THREAD

**Issue by Dream-Master** [micdoodle8/Galacticraft#1664] opened 2015-05-22 12:39 UTC
Helium, CO2, Argon not have Textures in GT because gt generate a own fluid for the machines.

We have a mod adding Fluids too and we using this code than it works.

super.getFluid().setIcons(stillIcon, flowingIcon); 

https://www.dropbox.com/s/5446m5jhwfbsz7c/Screenshot%202015-05-22%2014.36.48.png?dl=0

https://www.dropbox.com/s/pu2c6iqdma9qm1a/Screenshot%202015-05-22%2014.37.57.png?dl=0

https://www.dropbox.com/s/fq9rblrv70ppdga/Screenshot%202015-05-22%2014.38.06.png?dl=0

(Using Galacticraft 334 (because newer Version have Ordicted Tinkers Construct Blocks and tht not let my modtweaker code reloaded) together with Galaxy Space 1.8(Galaxy Space Author said the Gases are from Galacticraft)

**Comment by radfast** [comment] 2015-05-23 20:07
Duplicate of #1353 

We made a config to fix this, it's the Disable Helium config in ```asteroids.conf```

That config currently doesn't cover Argon and CO2, I guess we can easily add those to that config as well, but I'd prefer to do all at once - have you tested all the other GC gases (oxygen, hydrogen, nitrogen, atmospheric gases (air), liquid oxygen, liquid nitrogen)?

Please can you:
1.  test the Helium config to see if that fixes Helium for you and has Helium working in the way you expect
2.  check the other gases and give me a list of which ones you would like configurably not registered in GC

----

Any progress on the Oredict blocks issue?  As said before, seems like it must be a bug in modtweaker or your script, I think any mod which has Oredicted its blocks will cause the same bug to materialise.

**Comment by Dream-Master** [comment] 2015-05-23 20:41
I will test it and let you know.

**Comment by Dream-Master** [comment] 2015-05-23 21:38
Disable Helium in the asteroids cfg not give the texture back.

Is it possible only for me for testing that you disable the ordict for Tinkers Construct to see if this works with Modtweaker.

**Comment by dj3520** [comment] 2015-05-24 03:51
I hate to be this guy, but I hope you tested with fresh helium.

**Comment by Dream-Master** [comment] 2015-05-24 06:16
Helium gas

**Comment by Dream-Master** [comment] 2015-06-11 18:35
The textures still missing. Any news ?

**Comment by Dream-Master** [comment] 2015-09-15 19:07
The Config option not works.

**Comment by JasonMcRay** [comment] 2015-09-19 16:34
I can confirm that the texture of Helium Gas is missing with GT installed.

**Comment by Dream-Master** [comment] 2015-09-19 17:15
It is Helium, CO2 and Argon not have a Texture in GT.

**Comment by Dream-Master** [comment] 2015-10-07 13:15
@micdoodle8 
Con you look inside this too because the Textures are not there. The config option not workin too.

**Comment by Dream-Master** [comment] 2015-10-12 08:27
Now i see a new Argon Fluid(not shown any recipe in NEI) but the old Argon Gas not have any texture. Same for Helium Gas and CO2 Gas.(Gregtech installed)
@micdoodle8 
can you please look inside it. Thanks
(Test with newest version 364)

**Comment by Dream-Master** [comment] 2015-10-20 11:49
Any news here?

**Comment by Krysinski** [comment] 2015-10-20 16:43
I can confirm that the texture of Helium Gas is missing with GT installed. Even with the config set to true.

If you fill certus tank from ExtraCells mod with untextured gases (https://github.com/micdoodle8/Galacticraft/issues/1664) you get "already tesselating" error and crash client.
You cant connect to server more, you will getting crash. World will be broken for you then.

**Comment by micdoodle8** [comment] 2015-10-21 05:39
Note: This still isn't fully working. It seems as though the texture is still not working properly with GT/IC2, but it won't crash any more. I'll look into it more tomorrow.

**Comment by Dream-Master** [comment] 2015-10-22 16:57
Will test it when Galaxy Space is updatetd to the new Versions of Galacticraft.
Thanks for try to fix it.

**Closed** 2015-10-25 17:36 UTC

**Comment by Dream-Master** [comment] 2015-10-28 20:31
Works

**Comment by repo-alt** [comment] 2016-11-18 19:00
Did the fix got into any 1.7.10 release? because when I try .375 with extra cells certus tanks, I'm still getting null icon from helium fluid stack in https://github.com/ExtraCells/ExtraCells2/blob/4ac8d4c0f59ac46ee24ba11fcf55d5769797dc2a/src/main/scala/extracells/render/item/ItemRendererCertusTank.java#L49-L49

**Comment by dj3520** [comment] 2016-11-19 14:33
have you tried .463?

**Comment by repo-alt** [comment] 2016-11-19 17:31
Indeed, in .463 it works. I thought that .375 (last recommended 1.7.10 release) was released less than a year ago.
Thanks for pointing it out.

**Comment by dj3520** [comment] 2016-11-20 19:08
No problem. There seems to be a bit of confusion about the downloads page. The latest build is actually the one that is "recommended" for use.

**Comment by EzerArch** [comment] 2016-11-20 22:42
Certainly 463 should be promoted to recommended.

**Comment by dj3520** [comment] 2016-11-21 16:32
I feel like that would be the short term fix. @radfast said that the latest build is always the recommended one, so having them separate in the first place doesn't serve a purpose.
