### ISSUE TITLE
Rare client crash with Oxygen Bubble Distributor and Optifine 1.7.10 HD B7

### ISSUE THREAD

**Issue by FloxRoxX** [micdoodle8/Galacticraft#1706] opened 2015-06-11 12:34 UTC
Hello,
i have a player on my server that have problems at the space station.
It seems that a render function crashes his client.
Please take a look at his crash report: http://pastebin.com/Ak0dNkyt
Thanks!

**Comment by radfast** [comment] 2015-06-11 18:07
It's an Oxygen Bubble Distributor render problem.

I've never seen this before, it's not yet clear why it should happen.  There must be millions of players with Oxygen Bubble Distributors who are not experiencing crashes (otherwise we would know about it) so I am wondering if it is specific to this player's Java version or graphics card settings.

It's also possible it's a mod conflict, so I would strongly recommend a test with this player removing / disabling Optifine (and any other clientside mods which he can remove and still play on your server - maybe he can disabling the mapping mod?)

If that doesn't fix it then please test whether any other admin or player on your server can go to that space station.  If someone else can go there, maybe find the Oxygen Bubble Distributor, right click it and change its settings not to show the bubble - that might fix it for the crashing player.

**Comment by FloxRoxX** [comment] 2015-06-11 21:47
Hi,
yes my players have the option to disable Optifine, it seems that it is better for him now.
Maybe its  because of the new Optifine version (OptiFine_1.7.10_HD_U_B7)
Other players did not have the problem at all.

**Comment by radfast** [comment] 2015-06-12 01:24
Ok, that's good you have it fixed for your player.

I have changed the title to something more descriptive in case other players have a similar problem.

I will leave this open for now, as I need to test this more to see if I can reproduce the problem.

**Comment by FloxRoxX** [comment] 2015-06-15 16:02
Well it will be hard to reproduce i think. Maybe its his graphic card because i havent had this problem either, Else, the first thing we mentioned was the stargate (from SG Craft) he build at his space station. Maybe this is conflicting with someting... but yes i think its a rare problem on his computer...

**Comment by radfast** [comment] 2016-01-09 15:37
Changes were made to bubble rendering in https://github.com/micdoodle8/Galacticraft/commit/c5fef36f863795bd4e8f22e6d1e75a6fb7a2c29b

It may be this problem will no longer occur now.

Anyhow, it seems to be a very rare problem and I cannot reproduce it.

Closing this issue now.  Please re-open if this crash is still occurring in latest Galacticraft (please provide fresh crash report in that case).

**Closed by radfast** 2016-01-09 15:37 UTC
