### ISSUE TITLE
Oxygen sealers randomly unseal quickly.

### ISSUE THREAD

**Issue by BumblebeeCannon** [micdoodle8/Galacticraft#1425] opened 2015-02-04 15:11 UTC
This happens on Galaticraft 2 and 3 on all servers and Singleplayer. On Space Stations, all Oxygen is sealed but will randomly flash unsealed for a second then back to sealed. The only way I've found to fix this is by reloading the chunks on the Space Station. This has never happened to be on any other planet or moon, more information will be provided if needed.

**Comment by radfast** [comment] 2015-02-04 18:16
Please provide:
- which versions of GC2 and GC3 you have tested this with
- description of the room which is being sealed (how large, how many sealers etc)
- what is on the edge of the room (e.g. airlocks)
- screenshots
- simplest possible construction which has this issue, like does it happen in a 10x10x10 room?
- does it happen if Galacticraft is the only mod loaded?

I'm happy if you want to send me the World files for the actual Space Station dimension which has this problem.

**Comment by radfast** [comment] 2015-03-01 12:41
@BumblebeeCannon 
> more information will be provided if needed.

I would really appreciate that extra information here, as I need to be able to reproduce the problem before we can look at finding a fix.

**Comment by radfast** [comment] 2015-03-12 22:03
Closing due to lack of information.

This part of the wiki may also be helpful.  I think most players - even most server admins - do not properly understand how chunk loading works in Minecraft, especially the part about "active" chunks.
http://wiki.micdoodle8.com/wiki/Sealed_Space#Example_of_correct_sealer_spacing

**Closed by radfast** 2015-03-12 22:03 UTC
Labels: missing info
