### ISSUE TITLE
Oxygen pipes not working when unloaded?

### ISSUE THREAD

**Issue by logan2611** [micdoodle8/Galacticraft#2216] opened 2016-06-17 20:03 UTC
Whenever my moon base gets unloaded, when I go back to it the oxygen pipes do not work anymore and I have to replace it.

**Comment by EzerArch** [comment] 2016-06-17 23:04
Galacticraft version?

**Comment by logan2611** [comment] 2016-06-18 07:42
Latest version (Not home for specific version, but galacticraft 3)

**Comment by dj3520** [comment] 2016-06-18 12:46
>I think we had this problem long time ago, is it back?
Sounds familiar. Maybe I should check my emails (heh)

@logan2611 is your oxygen setup spread across more than one chunk? This might cause some portions to load before others.

**Comment by radfast** [comment] 2017-03-19 03:14
Oxygen pipes should be stable in all GC versions since .234 (November 2014).

I cannot reproduce this error in testing, I have tried a Moon base with unloaded chunks when I leave it.

Is it possible that the oxygen pipes were working fine, and systems from another mod (e.g. power) were not working?

This issue was from 9 months ago (sorry, I've been away from the mod all this time due to personal reasons).  I don't think any other player has reported this issue.  I will close this, but anyone is welcome to comment or re-open if they have this issue in the latest Galacticraft version (480).

 @logan2611 my guess is you have moved on to other things, as a lot of time has passed.  But if you still have this world and the problem is still occurring, then I'm happy to have more of a look at it.  Would need to have a screenshot of your base, all the oxygen equipment and pipes, with chunk boundaries shown (F9).  Also a mod list please, and detailed explanation of the position of any chunk loaders or Launch Controllers.

**Closed by radfast** 2017-03-19 03:14 UTC
Labels: 1.7

**Comment by logan2611** [comment] 2017-03-19 17:31
The issue was that when the chunks were unloaded the leaves for the oxygen generator were unloaded, and upon reloading the chunks,, for some reason, I would have to replace the oxygen pipes for the generator to work again. The fix is to put logs inside the leaves.

**Comment by radfast** [comment] 2017-03-19 18:09
hey, thanks!  guess you received an email from github :)
that's weird, most likely a behaviour of vanilla leaves.  Replacing a pipe would force all chunks which are connected to that pipe network to be refreshed, so yes, that could have something to do with it.

OK, I'm going to leave this issue closed as needing no action, but update the Wiki to advise players to use logs to preserve the leaves.

(As you can maybe see from the activity on the Github, we are trying to fix a number of long-standing bugs prior to the release of 1.8.9 and (future) 1.10.2 versions of Galacticraft, with Venus and other new stuff.)
