### ISSUE TITLE
[1.11.2] Going to spacestation crashes client server

### ISSUE THREAD

**Issue by ThomasAunvik** [micdoodle8/Galacticraft#2509] opened 2017-04-07 20:47 UTC
So i did /dimensiontp and created a station. And then i went in and crashed.
[Crash Log](https://pastebin.com/Wyzqr3AU)

Forge Version: forge-1.11.2-13.20.0.2265
MicDoodleCore: 1.11.2-4.0.0.53-BETA
GalacticraftCore: 1.11.2-4.0.0.53-BETA
GalacticraftPlanets: 1.11.2-4.0.0.53-BETA

[ModList](https://pastebin.com/J7HsMHWQ)

Edit:
A clean minecraft with only galacticraft
[Crash Log](https://pastebin.com/CDFNj6HJ)

**Comment by radfast** [comment] 2017-04-07 20:50
Thank you for beta testing.

We will be looking at all these as a priority, looks like we have a busy weekend ahead :)

Crashes are normally fairly easy to fix, as the log tells us exactly where to look.

**Comment by MJRLegends** [comment] 2017-04-07 23:41
Seems to be duplicate of #2506

**Comment by micdoodle8** [comment] 2017-04-08 21:25
Thanks, fixed in the next build.

**Closed by micdoodle8** 2017-04-08 21:25 UTC
