### ISSUE TITLE
Issue between Sync and Galacticraft.

### ISSUE THREAD

**Issue by MJRLegends** [micdoodle8/Galacticraft#1954] opened 2015-11-29 14:51 UTC
See https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/118 for information

**Comment by dj3520** [comment] 2015-11-30 01:36
Not seeing this myself [on my server with these mods](http://net.dj3520.net:8000/minecraft/modlist.btm)
Could be an interaction issue that isn't between these two mods.

**Comment by MJRLegends** [comment] 2016-01-01 13:17
I still think its a galacticraft issue

**Comment by dj3520** [comment] 2016-01-01 19:56
I run both Galacticraft and Sync on two servers and I'm seeing nothing
wrong.

**Comment by radfast** [comment] 2016-01-04 01:01
@MJRLegends which exact versions of both mods are you using?

**Comment by MJRLegends** [comment] 2016-01-04 01:03
@radfast Well at the time inwhich i reported this i was using Sync 4.0.0 and Galacticraft 1.7-3.0.12.404

**Comment by dj3520** [comment] 2016-01-04 02:23
![image](https://cloud.githubusercontent.com/assets/8284194/12082347/49912f3e-b25f-11e5-882d-b10c3b440ce2.png)
Sync and Galacticraft work together. Please insure this isn't caused by [another mod](http://pastebin.com/zpYfac2E).

**Comment by MJRLegends** [comment] 2016-01-04 02:31
@dj3520 the mods running together isnt the problem, see the original issue

**Comment by dj3520** [comment] 2016-01-04 07:41
If this isn't an issue between GC and sync then why do you insist it's GC?

**Comment by radfast** [comment] 2016-01-10 14:12
@MJRLegends:

Similar response to #1929

*  Galacticraft with Sync standalone does not have this issue - as @dj3520 said
*  therefore it is specific to Space Astronomy - it is something in that modpack or configs which is causing this
*  I do not have time or inclination to download, install and debug that modpack - I have limited time for working on Galacticraft and it will take time away from other issues which affect everyone, and progress on future features of the mod

If you can please do some A/B testing - on a test platform and with a new world, obviously do not test on an existing world or you can damage it - you should be able to identify in a few minutes which other mod is conflicting with Galacticraft+Sync and so causing this.

The best way is to do a binary search, so: remove half your mods (not Sync), start game, test if the issue still occurs.  If yes, then remove half of the remaining mods again (make a note which ones - easy to do using named folders) and test again - or if no, then put back in half the ones you removed. You should be able to identify the mod this way in 5, 6, or 7 iterations.

I suggest start with:
* 1.  Addons or submods like ***More Planets***
* 2.  The mods which are custom to that modpack or which have the smallest number of users, because if any of the major mods was having this issue then someone else would have reported it before.
* 3.  Any mod which can respawn players

**Comment by radfast** [comment] 2016-01-10 15:12
One more thing: try installing PlayerAPI.  That can sometimes fix some strange issues.

**Comment by radfast** [comment] 2016-01-10 16:20
[DOWNLOAD LINK](https://www.dropbox.com/s/5v1t2qdk7bf0xsw/Micdoodle_Core-1.7-3.0.12.411A.jar?dl=0) for the latest build of MicdoodleCore with this fix.

This is numbered version 411A and it can be used with any recent version of GalacticraftCore.  Replace MicdoodleCore in the /mods folder on the server with this.

**Comment by radfast** [comment] 2016-01-10 16:54
updated with the download link

**Comment by MJRLegends** [comment] 2016-01-10 16:55
Ok thanks so you found the issue?

**Comment by radfast** [comment] 2016-01-10 16:58
I found an issue, which may or may not be the cause of the problem your players have described.

I will need you to test it and see if it results in a fix.  That's the 'follow-up please' label.

Note, that clones created prior to this fix seem not to be useable by players after the fix is implemented... so you might not like the fix!

**Comment by MJRLegends** [comment] 2016-01-11 01:07
Ok i will give it a test and get back to you

**Comment by radfast** [comment] 2016-01-14 15:42
I would like to hear how well this works out in your modpack.  I recommend you use the latest GC version 418 now that the official website is working again :)

I think this issue should be fixed, so I am closing this now.  If there are any more problems, we can re-open this.

**Closed by radfast** 2016-01-14 15:42 UTC
Labels: fixed, follow-up please
