### ISSUE TITLE
Oxygen Bubble Distributor Not Working

### ISSUE THREAD

**Issue by ean521** [micdoodle8/Galacticraft#1718] opened 2015-06-16 16:25 UTC
My Oxygen Bubble Distributor on Mars is filled completely with oxygen & energy and has a steady supply of both. The bubble shows up, but when I go in it without my Oxygen Gear, it says "Oxygen Setup Invalid!" and I take damage. I am using build 344.

**Comment by radfast** [comment] 2015-06-21 15:35
I cannot reproduce this issue.

* Is it still happening for you or was it a one time thing?
* Please list other mods installed
* Place a torch on the ground inside the bubble - does the torch stay lit?

**Comment by EzerArch** [comment] 2015-06-21 19:18
I can't reproduce either. Tested with 341.

**Comment by ean521** [comment] 2015-06-21 21:50
I am using Little Blocks, Buildcraft, Thaumcraft (plus Thaumic Tinkerer), Computercraft, Blood Magic, and Dynamic Transport as well as, of course, Galacticraft. Torches do not stay lit, and it continues to happen occasionally yet not always

**Comment by TheQuadShot** [comment] 2015-06-22 00:17
I've had this problem on mar's as well, but it's not consistent (I always assume I'm doing something wrong which is why I haven't bugged it yet), The last time it occurred I tried to figure it out I noticed the following:
The distributor show's working, and 160 ox. used and the bubble is visible , but if you look at your ox gear it shows that you are using ox. and if you remove your helmet or tanks you get the invalid ox. setup message. 
So I start "back tracking" all of my connections (I was thinking that maybe the ui  didn't update to display an invalid configuration), ox connections were good and the power was good, when I went back inside (to the bubble) it was working fine. 
I have all of the equipment surrounding (and part of) the chunk I "beam into" with my RF teleporter. I also have 8 of the ox storage units and 4 power storage units in the same chunk that I beam into (just in case) they all show full or near full. I didn't try a torch since I use Tinkers torches (not sure that bug is fixed). I'm currently running the .339 builds. Not sure this helps any, but if you want me to try something just let me know.

**Comment by radfast** [comment] 2015-06-22 01:41
Thanks @EzerArch for testing as well, I really appreciate that.

Thanks @TheQuadShot for the detailed info.  Tinker's torches should behave the same way as regular vanilla torches in any recent build.

More info needed please
- was this playing on a server or in single player?
- did you already play other worlds in the same game session?
- if so, does re-starting Minecraft fresh and playing this world first fix the problem?
- is it a LAN server, or a single player game opened to LAN?

**Comment by TheQuadShot** [comment] 2015-06-22 02:04
I'm in single player, I have a moon base that this has not occurred on, The next time it occurs (if it happens) I'll try leaving the dimension, and restarting. I can also record it and upload to imgur for you.

**Comment by ean521** [comment] 2015-06-23 01:45
I was playing in Singleplayer. No, this world is the only one I play on at all currently. It is never open to LAN.

**Comment by DarknessShadow** [comment] 2015-07-05 15:02
I'm playing on a server with Infitech2 modpack v3.1.2
GalacticraftCore-1.7-3.0.12.345
Galacticraft-Planets-1.7-3.0.12.345

The Oxygen Bubble Distributor works fine after first placing it and giving energy/oxygen but after some time (leaving mars /logging out -> probably after unloading chunk) they stop working.
The GUI still says everything is fine and the bubble is also showing but you get the invalid oxygen message inside it but this only happens to some oxygen bubble distributors (I have 7 in my base and 5 stopped working) even though all are connected to same energy/oxygen system.
If I break and replace them it works fine again (so no problem with not enough energy/oxygen).

**Comment by EzerArch** [comment] 2015-07-09 03:29
@radfast , now I got the bug.

Built a minimal setup:
![2015-07-09_00 23 18](https://cloud.githubusercontent.com/assets/6743303/8587374/d70da19c-25d0-11e5-9a73-ceea76a2622b.png)

Then I killed myself and a few test-subjects:
![2015-07-09_00 23 24](https://cloud.githubusercontent.com/assets/6743303/8587378/e8f1053e-25d0-11e5-8592-fd6db7e4f988.png)

Respawned inside the bubble, entities start getting hurt:
![2015-07-09_00 25 44](https://cloud.githubusercontent.com/assets/6743303/8587386/09dd8dbc-25d1-11e5-9f06-a6faa521e3a5.png)

O noes piggy is gone and I suffocate if I remove the mask inside the bubble
![2015-07-09_00 27 00](https://cloud.githubusercontent.com/assets/6743303/8587401/53cc35f4-25d1-11e5-8c0b-6d5fef96b7a0.png)

Reloading the world seems to fix the issue. Poor piggy died for great science:
![2015-07-09_00 29 24](https://cloud.githubusercontent.com/assets/6743303/8587412/908415fc-25d1-11e5-850c-1f25ac439892.png)

LE FIN :')

**Comment by HyperionNexus** [comment] 2015-08-09 17:41
It also happens on multiplayer as a caching issue when you rejoin after disconnecting, timing out or "disconnected from server". It might be an issue with other mods involved but I'm not sure.

The way I counteracted this was getting an online player detector and making a small circuit to retract drawbridges from Tinker's Meckworks to pull the bubble distributor in and then extend it back out. This however comes with a bit of lag when doing so as I have quite a bit of 'em.

**Comment by EzerArch** [comment] 2015-08-10 05:16
Okay, when this bug starts to happen? Probably it's a version between 341 and 345. Can anyone test?

**Comment by mgwerner** [comment] 2015-08-13 15:15
I am having the same issue, using 350.

**Comment by HyperionNexus** [comment] 2015-08-15 00:02
Yeah even the latest dev release still has this issues on servers.

**Comment by EzerArch** [comment] 2015-08-15 04:19
@mgwerner and @HyperionNexus, try using 344. If this one doesn't work, try earlier versions. I tested 341 and it seems good.

**Comment by mgwerner** [comment] 2015-08-15 04:40
344 works for me.  Thanks.

**Comment by EzerArch** [comment] 2015-08-16 23:30
@mgwerner:

> 344 works for me. Thanks.

Did it? Not for me. The Oxygen Bubble doesn't work after player respawn. Not even 341 worked.

**Comment by mgwerner** [comment] 2015-08-17 01:16
Multiple visits to that dimension, Bubble Distributor is working.  I have even removed my O2 tanks to check, all is functioning properly.

**Comment by EzerArch** [comment] 2015-08-17 02:06
> Multiple visits to that dimension, Bubble Distributor is working.

Dimension change hasn't affected my Bubble Distributors at all, but death does.

**Comment by mgwerner** [comment] 2015-08-17 02:07
I died while on Mars, when I returned to my base it the BD was working fine.  Same with logouts and in.

**Comment by FreedomsFlame** [comment] 2015-09-10 05:10
I am also gettting this issue with 3.0.11.333

**Comment by EzerArch** [comment] 2015-09-10 06:02
@FreedomsFlame, try using the latest build: http://micdoodle8.com/mods/galacticraft/downloads

**Comment by mgwerner** [comment] 2015-09-12 15:54
BD is not working properly on Diona and Koentus, same issues as above.  Using GC 357 and MP 1.2.9.

**Comment by NolanSyKinsley** [comment] 2015-09-26 22:00
Can confirm, issue still present in latest build (357) of galacticraft.

**Comment by ShadowDrakken** [comment] 2016-03-26 00:12
Hate to bring up an old and closed thread, but I'm using Build 454 and this issue is still happening

**Comment by ShadowDrakken** [comment] 2016-03-29 18:31
Apparently in 454 it's also happening if the chunk unloads while you're exploring. When you come back the bubble is still visible, but not working.

**Comment by EzerArch** [comment] 2016-04-04 06:21
> The Oxygen Bubble will stop functioning correctly if a player dies, or if the chunk is unloaded and reloaded during exploration. Shutting down the game and restarting resolves the issue. (from: https://github.com/micdoodle8/Galacticraft/issues/2165#issue-144371480)

Just tested in 454. I let myself suffocate to death far away from the Oxygen Bubble. Respawned, without ox. gears, went in an Oxygen Bubble, it was working.

However I was having the said problem when I kept using `/dimenstiontp` and CustomNPCs' teleporter. The problem stopped happening when I had ceased using these tools in favor of rockets. Probably forcing dimension change, instead of using rockets, might be the cause.

**Comment by FreedomsFlame** [comment] 2016-04-04 13:00
When I was having this issue I was running a listen server over LAN, if that happens to be helpful. I never used dimension teleporting, just the rockets.

**Comment by ShadowDrakken** [comment] 2016-04-04 17:00
I wasn't using dimensional TP either, I'd respawn next to my bed inside the bubble and be suffocating instantly. Switched to sealers and no more problem. 

An interesting side effect I also noticed was that after a death where I respawn inside a broken bubble: putting on oxygen gear, the gear would drain oxygen at twice the normal rate. Again, this doesn't happen if I respawn inside a sealed room instead.

**Comment by EzerArch** [comment] 2016-04-20 06:41
Well, I tried to reproduce https://youtu.be/7p2fuMK4QGo?t=16m16s, with /gamerule keepInventory on and off. It's working for me. Am I doing something different?

**Comment by radfast** [comment] 2018-03-24 14:19
Closing due to (a) can't reproduce and (b) no recent reports.

If anyone has this issue in a current Galacticraft version, please comment or re-open.  Please give information about game version and steps to see this issue happening.  (e.g. die / re-log / leave chunk and return to it)

**Comment by remclave** [comment] 2018-09-19 20:21
Minecraft version: 1.12.2
Forge version: 2759
GalacticraftCore version: 181
Galacticraft-Planets version: 181
MicdoodleCore version: 181
Galacticraft Add-on-More Planets version: GC181
Galacticraft Tweaker version: 1.0.2

When I died (inside the bubble - due to mob attack), I respawned inside the oxygen bubble and began dying. And torches were unlit when placed. This is a new pack in development but it is sandbox build with minor recipe tweaks (like new spawn player inventory)

**Comment by teagan75** [comment] 2018-10-27 15:59
Minecraft version: 1.12.2
Forge version: 2718
GalacticraftCore version: 181
Galacticraft-Planets version: 181
MicdoodleCore version: 181
Galacticraft Add-on-More Planets version: GC181

I have the exact same issue as above and it is after death. I have to remove the oxygen bubble dist and replace it to work correctly. This affects all OBD in my base.

**Comment by radfast** [comment] 2018-12-02 00:11
thanks guys for the details, I have re-opened this, it's clear it needs testing in recent versions.

**Comment by spaceboy01218** [comment] 2018-12-08 22:58
minecraft version 1.11.2, galacticraft core, planets, and micdoodlecore 181
this issue is annoying when hosting a LAN server and minecraft crashes on leave. the rejoin does the trick but i wish you guys could fix this seems its a problem for all versions, though last time i played, it didnt happen.

**Comment by dj3520** [comment] 2018-12-23 07:56
@spaceboy01218 Please make a separate issue.

**Comment by micdoodle8** [comment] 2019-01-08 04:46
Should be fixed in the next build.

**Closed** 2019-01-08 04:45 UTC
Labels: 1.7, cant reproduce, cause unresolved

**Comment by Boscpeing** [comment] 2020-06-20 11:54
Minecraft version: 1.12.2
Forge version: 2847
GalacticraftCore version: 280
Galacticraft-Planets version: 280
MicdoodleCore version: 280
![2020-06-20_12 56 05](https://user-images.githubusercontent.com/67191537/85201075-c2ec7300-b2fc-11ea-8338-c1085edd451d.png)
this happened after I started minecraft clicked on the multiplayer then went to  singleplayer 
![2020-06-20_13 49 27](https://user-images.githubusercontent.com/67191537/85201134-3a220700-b2fd-11ea-879a-8bedb2998047.png) Then I went back to the menu and when i went back in the the one that was werjing failled and the ones which wen't are now working.
![2020-06-20_13 49 30](https://user-images.githubusercontent.com/67191537/85201175-85d4b080-b2fd-11ea-8e02-57c2e7892f6c.png)

**Comment by Boscpeing** [comment] 2020-06-20 12:03
It isn't consistent but it happens  fairly often .

**Comment by spaceboy01218** [comment] 2020-06-20 17:09
Is there ever going to be a solution?

**Comment by EyeofWolf** [comment] 2026-01-18 03:24
Probably not
