### ISSUE TITLE
Game crashes upon joining friend's server

### ISSUE THREAD

**Issue by yorshee** [micdoodle8/Galacticraft#2912] opened 2017-07-22 17:06 UTC
This randomly happened earlier, I was playing on my friend's server just fine and I went outside our house to kill a Witch that was annoying me. The game lagged for a few seconds when the Witch was about to die, and when the game kicked back in the Witch died (as well as me). Then the game crashed, and refuses to let me log back in. Sometimes it'll load for a split second - I'll see my hotbar - and then it'll kick me out again before any of the actual world loads.

Apparently this is a similar issue to [#2900](https://github.com/micdoodle8/Galacticraft/issues/2900) but that doesn't really make a lot of sense as 1) I don't have Optifine installed, and 2) Nothing happened in regards to the lighting panels, I was the only person online so nobody else could have been messing with the lighting panels. I read through the crash log and it does mention the lighting panels though, so...I have no idea.

I have also tried to join the server with the latest Galacticraft version, 4.0.0.114, but the same error still occurs.

Minecraft version: 1.11.2
Galacticraft version: 4.0.0.111
Forge version: 13.20.1.2393

Single player (SSP) or Multiplayer (SMP)? - Multiplayer

Galacticraft add-ons and other mods installed?
Biomes O'Plenty
Buildcraft
MrCrayfish's Furniture Mod
CodeChickenLib
CoFH Core
FoamFix
Galacticraft Core
Galacticraft Planets
Just Enough Items
MicdoodleCore
Pam's HarvestCraft
Thermal Expansion
Thermal Foundation
Treecapitator

[crash-2017-07-22_17.44.12-client.txt](https://github.com/micdoodle8/Galacticraft/files/1167496/crash-2017-07-22_17.44.12-client.txt)

**Comment by MJRLegends** [comment] 2017-07-23 16:39
Appears to be a duplicate of #2869 and #2900

**Comment by radfast** [comment] 2017-07-24 17:55
Thanks, this is very helpful as you **don't** have Optifine installed.

We will prioritise this, sorry you have experienced it.

**Closed** 2017-07-29 21:46 UTC
Labels: 1.11 only, Priority

**Comment by radfast** [comment] 2017-07-29 21:49
The problem is that - for reasons I don't understand - the chunk has a Panel Lighting block without the tileEntity it should have to go with it.

This is some kind of bug in vanilla/Forge chunk saving or server/client sync which I don't understand, but anyhow we can work around this so there will be no more crashes.

Fixed in 115.

(The Panel Lighting blocks in faulty chunks might revert to their default look, though: nothing we can do about that)
