### ISSUE TITLE
[FTB Infinity Lite] A Fatal Error has occurred, this connection is terminated #3217

### ISSUE THREAD

**Issue by ponne03333** [micdoodle8/Galacticraft#3218] opened 2018-03-01 17:27 UTC
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version:1,10,2
FTB Infinity Lite 1.10 

Multiplayer

**Comment by radfast** [comment] 2018-03-01 22:44
Please provide:

* Galacticraft exact version

* `fml-client` log from the game when this happened

* **server** log from the same game when this happened

Please also tell us steps to reproduce this ...   does it happen sometimes / every game?  When you login, or when you do something (what?) in the game?

**Comment by radfast** [comment] 2018-03-11 23:14
@ponne03333   please give the information requested - or as much as you can?

**Comment by radfast** [comment] 2018-03-12 20:09
We can't keep an issue open which is missing even basic information, like which Galacticraft version.

Seems like there's a chance this is a duplicate of #3157 in which case it's fixed already...  just update Galacticraft to the latest.

If the missing info is provided, please comment or re-open this.

**Closed by radfast** 2018-03-12 20:09 UTC
Labels: missing info
