### ISSUE TITLE
[Crash] Attempted to load class bdw for invalid side SERVER [1.7-3.0.12.375]

### ISSUE THREAD

**Issue by Sharkking** [micdoodle8/Galacticraft#2072] opened 2016-02-10 08:50 UTC
http://pastebin.com/nCEeXPsT

Happens when placing an RotaryCraft engine which needs Air to work. 
Afaik RotaryCraft loads the Galacticraft API beforehand.

**Comment by radfast** [comment] 2016-02-10 14:09
Duplicate of #1990.

This was fixed a month ago.

Did you even read the Notes for Contributors - link provided when you hit that New Issue button?  You are supposed to test whether your issue is an issue in latest Galacticraft, before posting it.  .375 is not the latest.

**Closed by radfast** 2016-02-10 14:09 UTC

**Comment by Sharkking** [comment] 2016-02-10 15:17
Sorry for double posting. Will upgrade and test again
