### ISSUE TITLE
Nasa workbench particles bug (s)

### ISSUE THREAD

**Issue by altrisi** [micdoodle8/Galacticraft#2360] opened 2016-12-28 21:15 UTC
There are two bugs related to that (the first one I'm not sure if it is a bug):

- When clicking a blank slot, the particles are also generated.

- When clicking a slot in a recipe that isn't the first (Tier 1 Rocket) the particles are generated in a wrong position (where the player is). It also happens when changing the recipe and returning to the first one (Tier 1 Rocket). 

## Other mods: _NotEnoughItems-1.7.10-1.0.5.120_ (with _CodeChickenCore-1.7.10-1.0.7.47_)

**Comment by dj3520** [comment] 2016-12-28 21:34
I've noticed bullet point 1 myself, though I'm not sure if it's intentional.

Seeing how this is a small, non-game breaking bug, it's likely not to be fixed since the focus on development has moved to the 1.8.9 version.

**Comment by radfast** [comment] 2017-03-17 23:09
Thank you for reporting.

The first is an issue in vanilla Minecraft, and we can't do much about it - sorry.  (The issue is that vanilla Minecraft calls `Slot.slotChanged()` even if the player clicks a blank slot, and we can't tell if the slot really changed or not.)

The second can be fixed in 1.8.9.  It cannot be fixed in 1.7.10 without making network changes (meaning clients with version 3.0.12.479 or earlier would give errors / disconnections from the server with version 3.0.12.480 or later on the server).  At this stage in the maturity of 1.7.10, I don't want to do that unless it is something gamebreaking.

**Comment by radfast** [comment] 2017-03-22 01:15
These particles will be correct in 1.8.9.  Thank you again for reporting.

**Closed** 2017-03-22 01:15 UTC
Labels: 1.8, minor
