### ISSUE TITLE
[1.12.2] Server time out

### ISSUE THREAD

**Issue by rerk1** [micdoodle8/Galacticraft#3169] opened 2018-02-10 11:11 UTC
Minecraft version: 1.12.2
Galacticraft version: 4.0.1.132
Forge version: 14.23.2.2613

Single player (SSP) or Multiplayer (SMP)? SMP

Galacticraft add-ons and other mods installed? Yes (Micdoodlecore 4.0.1.132, GC 4.0.1.132, Foamfix 0.9.2-Anarchy)

I have only the mods I've listed and nothing else. At first every time I would try to switch between the overworld and the moon I would time out from the server. I tried out the code given by Zi0P4tch0 in issue #3157 but to no avail. Then I gave the server 8RAM and changed the code by adding the xmx at the beginning: -Xmx8G -XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

Now I can return to the Overworld without timing out, but when I try to go to the moon again it still times me out. Sometimes the server would give me "handleDisconnection() called twice" and sometimes it won't.

![image](https://user-images.githubusercontent.com/36328309/36061465-4a33ae3c-0e63-11e8-8609-75b8f09c02e1.png)

P.S: I just signed up to github, sorry in advance if I missed to send a log or something. Just tell me and I'll provide

**Comment by radfast** [comment] 2018-02-10 11:44
welcome, and thank you this is a clear issue report.  bonus marks for "to no avail"

as you can see from #3157 we are having difficulty identifying the cause of this issue and whether it is indeed a Galacticraft issue

it would help to see your full modlist, and as with Zi0P4tch0 it would help me a lot if you can test your same game setup with a smaller modlist - ideally only Galacticraft + 1 other mod - and reproduce the same issue.

An issue with Galacticraft + 1 other mod I can troubleshoot, because I can load up the code for both mods in a development / debugging environment.  I can't do that (in any reasonable amount of my time) for a modlist with multiple mods.

**Comment by radfast** [comment] 2018-02-10 12:00
Also please enable

      B:"Enable Debug Messages"=true

in Galacticraft's config and post logs from the **server** for when this problem happens again, I'm looking for lines like this:

     DEBUG: Sending respawn packet to player for dim -28

**Comment by rerk1** [comment] 2018-02-10 12:12
Haha, thanks for that comment and the fast reply. I removed Foamfix so now I'm only using GC and MicDoodlecore. I enabled the debug mode and searched through the logs, I'm sending you both "latest.log" and "fml-junk-earlystartup.log" as I used CTRL+F and only the earlystartup had the line you are looking for.
[fml-junk-earlystartup.log](https://github.com/micdoodle8/Galacticraft/files/1713348/fml-junk-earlystartup.log)
[latest.log](https://github.com/micdoodle8/Galacticraft/files/1713349/latest.log)

**Comment by radfast** [comment] 2018-02-10 12:24
those logs are helpful, thank you.

You are missing ```Galacticraft-Planets``` which is the part of Galacticraft giving you Mars, Venus and Asteroids, as well as Tier 2 and Tier 3 rockets and a lot of other machines.  I'm not sure if that is the **cause** of this issue, but let's see ... please try downloading that (matching version 132) and test going to the Moon again.

I'm curious to know where you downloaded Galacticraft from as you're not the first person this week to be missing Galacticraft-Planets, but our [download page](https://www.micdoodle8.com/mods/galacticraft/downloads) should give all three files together.

**Comment by rerk1** [comment] 2018-02-10 12:27
I do have it downloaded, just for the sake of helping you narrow down the problem I removed it and did a clean reinstall. I'll give it a try now with the planets installed as well

**Comment by radfast** [comment] 2018-02-10 12:29
for cross-referencing, #3165 may be the same issue, though NEI also looks to be involved there

**Comment by rerk1** [comment] 2018-02-10 12:30
NEI? I just googled it and if it's Not Enough Items, then I don't have it installed.

**Comment by rerk1** [comment] 2018-02-10 12:36
Here this time I'll send 3 files. Just as I was about to stop the server it crashed. I also periodically have my server crash at random times, a bit of googling led me to an article that I think mentioned something about Venus making it crash. That however is a different issue so just fixing the dimension switching one would be of great help.

[fml-server-latest.log](https://github.com/micdoodle8/Galacticraft/files/1713363/fml-server-latest.log)
[latest.log](https://github.com/micdoodle8/Galacticraft/files/1713364/latest.log)
[fml-junk-earlystartup.log](https://github.com/micdoodle8/Galacticraft/files/1713365/fml-junk-earlystartup.log)

**Comment by radfast** [comment] 2018-02-10 12:45
thank you for your continuing patience and help with troubleshooting this.  Ignore my comment about NEI, that is for cross-referencing so that the two issues are linked on Github, which may help others in future who find either issue thread.

While we've been communicating I have spent 1 hour tracing through vanilla Minecraft code to try to find a possible cause for this.  Largely guesswork, but I've found one possibility - there's a concrete link between the Minecraft client running out of memory, and a client-server networking problem when changing dimensions (because the vanilla client, when it thinks it is running out of memory, clears the current world)

In your first post your talked about giving the **server** 8G of RAM (which should normally be plenty).  But it's actually your **client** which may be running out of RAM - please can you try changing the JVM on the client (in the Minecraft launcher profile, if you edit it, there should be an option to do that).

**Comment by radfast** [comment] 2018-02-10 12:51
sorry i missed that.  8 gigs should be plenty on the client.

Myself I run Galacticraft (+ a handful of other mods) in much less memory on the client thanks to FoamFix.  My settings:

     -Xmx900M -XX:+UseConcMarkSweepGC -XX:-UseAdaptiveSizePolicy

**Comment by rerk1** [comment] 2018-02-10 12:52
Wow, you're right. That is a LOT less memory. I tried FoamFix earlier but it didn't help. So I just removed it when you requested I only use GC + 1 mod

**Comment by rerk1** [comment] 2018-02-10 12:54
Also I should be the one thanking you for the patience and help. Troubleshooting can be nerve wracking, so much appreciated ^^

**Comment by radfast** [comment] 2018-02-10 13:02
I've now been able to reproduce the issue on my own PC by tinkering around with the memory settings, it's happening with what **should be** enough memory on the client.

I don't need to trouble you for any more help now that I can reproduce it here.  I'll investigate today and see what can be done to fix this.

**Comment by rerk1** [comment] 2018-02-10 13:03
Much appreciated, I'll still be checking in regardless, so if you need anything at all please feel free to ask away. Good luck! ^^

**Comment by radfast** [comment] 2018-02-10 18:13
Good news, I've found and fixed the problem.

A new build 133 will be released later today.

**Closed by radfast** 2018-02-10 18:13 UTC

**Comment by radfast** [comment] 2018-02-11 03:17
Build 133 is now available from the download site.
