### ISSUE TITLE
Solar panel on Venus

### ISSUE THREAD

**Issue by Romsik788** [micdoodle8/Galacticraft#3270] opened 2018-03-23 17:48 UTC
Minecraft version:1.12.2
Galacticraft version:4.0.1.164

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP not open to LAN
Galacticraft add-ons and other mods installed?
JEI, Scenter, Ecology mod
Please provide screenshots / crash report / log as needed.
Solar panels generate too much energy on Venus. I propose that the solar panels generate a maximum of 10 gJ / t (since Venus has a dense atmosphere).

**Comment by TheQuadShot** [comment] 2018-03-23 18:19
Sorry, I'm unclear about this, are you filing a bug? and if so how did you determine what the output should be and which solar panel are you talking about. Or are you making a change request?

**Comment by Romsik788** [comment] 2018-03-23 19:39
@TheQuadShot This is a change request. Since Venus has a dense atmosphere, therefore, an output of solar panel should be less. I suggest 10 gJ / t is ok. And this value for the advanced solar panel and solar panel.

**Comment by TheQuadShot** [comment] 2018-03-23 19:46
Ok, Then please close this bug report and post the request on the forums:
https://forum.micdoodle8.com/index.php
Thanks, The Dev's do read the forums on a regular basis.

**Comment by Romsik788** [comment] 2018-03-23 19:53
@TheQuadShot Why close? I think it should be open. Since in the morning on Venus the advanced solar panel generates about 109 gJ / t - that's too much. And I think that this is a serious drawback.

**Comment by TheQuadShot** [comment] 2018-03-23 20:04
Ultimately it's up to the Dev's, You said it's a change request, not a bug report and this is a bug tracking tool. This issue has kind of been covered already here:
**https://github.com/micdoodle8/Galacticraft/issues/2927**

**Comment by radfast** [comment] 2018-03-24 01:14
Exactly what TheQuadShot said.

**Closed** 2018-03-24 01:13 UTC

**Comment by Romsik788** [comment] 2018-03-24 04:39
@radfast then why does this problem still exist?
