### ISSUE TITLE
[1.11.2] Vacuum Glasses difficult to see in inventory

### ISSUE THREAD

**Issue by ThomasAunvik** [micdoodle8/Galacticraft#2564] opened 2017-04-11 14:36 UTC
Build 63
![Imgur](http://i.imgur.com/Cd5seJH.png)
![Imgur](http://i.imgur.com/wJ66evb.png)

**Comment by radfast** [comment] 2017-04-11 14:38
I don't think you are being creative enough with your glass :)

Try some angles and corners etc

Try an octagon

**Comment by ThomasAunvik** [comment] 2017-04-11 14:40
Happy?
![Imgur](http://i.imgur.com/0tI6hZO.png)

**Comment by radfast** [comment] 2017-04-11 18:22
hmm, there are some small bugs here which aren't seen in 1.8.9 :(

This is how it should be:  (you can get the colour using the Painter)

![2017-03-12_13 02 27](https://cloud.githubusercontent.com/assets/6842258/24924283/2a66f8aa-1eec-11e7-8389-a315be95c4ea.png)

**Comment by willtree8** [comment] 2017-04-14 14:18
On a related note, please differentiate between the glass's names because having 6 items all called 'Vacuum Glass' is incredibly annoying.

**Comment by teamMK** [comment] 2017-04-16 11:54
same prob in the 1.10.2 version ;-)

**Comment by radfast** [comment] 2017-04-25 03:33
A duplicate of this has been posted.  If that's OK with you, Thomas, I'll keep this closed and #2639 open now.

**Comment by ThomasAunvik** [comment] 2017-04-25 04:26
Not sure if it is fixed in the inventory, but this is what i see:
![Imgur](http://i.imgur.com/Pb1shQX.png)

**Comment by radfast** [comment] 2017-04-25 04:34
Yes, it's worse in 1.11 than in 1.8 for some reason.

**Comment by radfast** [comment] 2017-04-28 19:10
[I meant to close issue 2566 with that commit, not this 2564]

**Closed** 2017-04-28 19:11 UTC
Labels: 1.10+, 1.8, rendering

**Comment by ThomasAunvik** [comment] 2017-04-28 23:02
What version of Galacticraft does this get fixed on? Build 77?

**Comment by radfast** [comment] 2017-04-28 23:53
No, sorry that was an error in that commit, it meant to say fixed 2566 (I've now amended it, but it still leaves a trace message in this issue report).

This Vacuum Glass in inventory issue is fixed in 1.8.9 but not in 1.10.2 and 1.11.2.

The reason is that 1.10.2 and 1.11.2 render inventory items in a different way - certainly in JEI compared with NEI which I'm using in 1.8.9.

As mentioned above, I am leaving issue #2639 open until the inventory glass is fixed.  I'm hoping that micdoodle8 or one of the other contributors will fix it, because getting these inventory items "exactly correct" is outside my skill set.  If you look carefully at the game and which developer contributed which features, you'll see most of the items in your issue #2606 came from me ...
