### ISSUE TITLE
Minecraft EDU with Galaticraft

### ISSUE THREAD

**Issue by sordikof** [micdoodle8/Galacticraft#2207] opened 2016-06-08 04:44 UTC
Hi, I teach quite frequently using MinecraftEDU, 

We have been using different type of mods such as Paleocraft, Custom NPCs.

I wanted the kids to try out going to space, everything worked fine until i choose to land on the moon, first it would say downloading terrain after that i would just be stuck indefinetly, I disconnect and reconnect in the server, It now shows me in the lunar lander but it seems to be there forever, I've speeding up the land but nothing happens,

Please help me thank you very much.

The minecraftEDU version is 1.7.10

**Comment by dj3520** [comment] 2016-06-08 08:02
Hello. Sorry you're having issues. However as per [the guidlines]  (https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) there's a few more things that will be needed.
- Exact Galacticraft version that is being used. (for example the newest version is 1.7-3.0.12.460, though "460" is actually enough)
- Any other mods being used and their versions as well, including client side mods such as OptiFine.
- Not required, but the version of forge being used. Also if it's a server if it's a kcauldron/thermos server.
- Dedicated server, shared LAN, or singleplayer enviroment?

Most of this information could actually be found in the server log of when this issue is observed, which would also help diagnose the issue. Please post it using paste.ubuntu.com, gist.github.com, or pastebin.com as it's likely to be too large to post here (and people don't like it.)

**Comment by sordikof** [comment] 2016-06-13 07:10
Dear Dj,

The version of Minecraft EDU I'm using is is 1.7.10 (Stable Build 20). 

The Forge MinecraftEDU uses is 10.13.2.1291

It's a dedicated server using the server wizard provided but I turn it off after class.

**Comment by dj3520** [comment] 2016-06-13 08:43
Sorry, but there's still some unanswered questions.

- Exact Galacticraft version that is being used. (for example the newest version is 1.7-3.0.12.460, though "460" is actually enough)
- Any other mods being used and their versions as well, including client side mods such as OptiFine.

These two are important to reproducing the issue if needed.

As of right now all I can say is that the version of forge you're using is from 01/22/2015 and the most recent recommended version (10.13.4.1558) is from 11/10/2015. I'm not sure what specific version of Forge is needed for Galacticraft but updating the server and client forge versions is something I'd recommend even if there weren't any issues, as some mods will purposely fail with older forge versions. (for example another mod "Railcraft" needs version 10.13.4.1448 or higher of forge)

**Comment by radfast** [comment] 2016-06-25 17:18
Hi @sordikof, I'm the Galacticraft lead developer, please talk to me about this.

I am not familiar with MinecraftEDU but I can't imagine it is significantly different from regular Minecraft.  Galacticraft should work just fine with Forge 10.13.2.1291, @dj3520's information is incorrect.

My guess is this is possibly a network lag or packet loss issue.  The various steps involved in travelling to the Moon dimension, inserting the player in a lander, and then detecting that the lander has landed all involve server/client and client/server communications and this part of Galacticraft is - unfortunately - not very resilient to packet loss.  (That is something we are looking at improving long term, but it is difficult.)

To progress this, please provide logs from the game session when this occurred - fml-client-latest.log and fml-server-latest.log.  Ideally both logs should cover the same game session (the same time).

It will also help me if, before starting a game session to generate these logs, you go to your `.minecraft/config/Galacticraft/core.conf ` file and set Enable Debug Messaging to true.

**Comment by sordikof** [comment] 2016-06-25 18:06
Sorry for the late reply, was busy finishing the lessons,

http://paste.ubuntu.com/17868270/

https://gist.github.com/sordikof/97a511a2329b186fbb4fc1d2922360fb

Here are the logs and i also enabled debug messaging true,

So what i did in minecraft in the logs are:

Setup flat world, put launch pads, use rocket, bug happens (stuck in space with my character) I disconnect and reconnect now I'm on my lunar lander but it won't land.

**Comment by radfast** [comment] 2016-06-28 01:04
I'm not seeing Galacticraft mentioned at all in those logs, are you sure those are the right ones?

Please can you:

(1)  test your same world and mod list on a vanilla Minecraft + Forge setup.  Basically you would need to download Minecraft 1.7.10 server, install the same Forge version 10.13.2.1291 on that (easy enough), and then copy across the `/mods`, `/config` and '/world' folder from your MinecraftEDU server folder.  Then start that vanilla server, and run a vanilla client on the same computer to connect to it.  (You would need to copy the same `/mods` + `/config` folders to the vanilla Minecraft client)

(2)  also try testing with **only** Galacticraft installed, no other mods.

Test number 1 should reveal whether it is MinecraftEDU causing this issue - that seems possible, as I notice they offer teleport functionality, and that could be interfering somehow with the code that spawns a Galacticraft player on a new planet.

Test number 2 should reveal whether it is your specific combination of mods causing this issue, in which case we can start to look at which exact other mod is the problem.

Unfortunately I am not able to test MinecraftEDU with Galacticraft, as I don't have it and I'm not willing to spend money to purchase it.  So I'm going to need to ask for your continuing assistance here.

You may want to consider how much of your time you are able to spend helping us ... from our perspective there is no urgency to this, it can be a summer vacation project for you if you want, though I kind of have the feeling there is a classroom of students waiting to go to the Moon...

**Comment by sordikof** [comment] 2016-07-11 19:26
No, I want this to be in the lesson plan. Is it possible for me to send you the MinecraftEDU?

**Comment by dj3520** [comment] 2016-07-13 08:39
I believe that "sending" MinecraftEDU would technically be illegal software sharing, regardless of the intentions. As radfast mentioned above we can rule out the changes that MinecraftEDU makes by performing his first test. If the results of the test are the same with and without MinecraftEDU then it's likely that the issue is being caused by something else.

I've looked at your logs and see that the server is having performance issues, sometimes running as much as a minute behind it's intended time. Also in both Galacticraft isn't mentioned at all, which means it wasn't loaded.

**Comment by radfast** [comment] 2017-03-04 21:34
Closing this issue.  I can't do anything more to troubleshoot it without Minecraft EDU.  And it seems the server maybe had other issues, unconnected with Galacticraft.

(One thing to watch with servers on home PCs is the network bandwidth outgoing.  Minecraft is a network intensive game.  On a typical home copper wire internet connection, 8 MB/s download speed, 256 kB/s upload speed, it's hard to run a server, because there is not enough upload speed.  _Obviously this comment does not apply to people running the game on a LAN_)

@sordikof  you are welcome to re-open this if there is more info - see questions above - but I'm guessing your lesson plan has moved on since July 2016.

**Closed by radfast** 2017-03-04 21:34 UTC
Labels: 1.7, cant reproduce, follow-up please, missing info
