### ISSUE TITLE
The fluids are fake

### ISSUE THREAD

**Issue by awnc** [micdoodle8/Galacticraft#3145] opened 2018-02-03 09:28 UTC
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version:1.10.2
Galacticraft version:4.0.1.132
Forge [version:2511]

Single player (SSP) or Multiplayer (SMP)?
SSP
Galacticraft add-ons and other mods installed?
No
Please provide screenshots / crash report / log as needed.

**Comment by TheQuadShot** [comment] 2018-02-03 09:49
What/which fluid/s? and what do you mean "fake"?

**Comment by awnc** [comment] 2018-02-03 10:48
All the fluids,and "fake"means it's don't like commom fluid,player can't swim in it.

**Comment by radfast** [comment] 2018-02-03 11:23
Duplicate of #1623 #2120 #3140

**Closed by radfast** 2018-02-03 11:23 UTC

**Comment by EzerArch** [comment] 2018-02-06 12:59
> Duplicate of #1623 #2620 #3140

And of #3005.

The source of the complaints is this: players have BuildCraft and IC as golden standard for "how technical things should behave". While they see Galacticraft oil don't act like BC/IC ones, they see that something is off and will not stop reposting the same yet-another-oil-don't-act-like-liquid issues. :S

**Comment by radfast** [comment] 2018-02-06 17:23
Our oil has one very smart feature: it won't mix with water (or other liquids).

We can add the suffocation and viscosity and other aspects, we used to have that in the past so it's probably just a small bug, but I don't see it as high priority ....  If we had one more coder to help with fixing issues, like a "radfast 2", then I'm sure all the issues could be fixed.  But I'm not willing to spend 100% of my time fixing issues, I like to spend some time on new features ... like the new Hydraulic Platform. :)

**Comment by radfast** [comment] 2018-02-11 03:19
Build 133 is now available from the download site with a fix for this.

Also has a really nice new feature: **Hydraulic Platform**
