### ISSUE TITLE
[1.10.2] Lightning Panel crashes with Optifine

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#2869] opened 2017-06-30 16:14 UTC
Step to reproduce :
1. Start game and Create a new Debug World
2. And move closer to Lightning Panel (Or waiting for chunk load)

https://pastebin.com/7uwNwciu

**Comment by radfast** [comment] 2017-06-30 18:35
Thanks, I'll take a look.

**Comment by radfast** [comment] 2017-07-29 21:49
The problem is that - for reasons I don't understand - the chunk has a Panel Lighting block without the tileEntity it should have to go with it.

This is some kind of bug in vanilla/Forge chunk saving or server/client sync which I don't understand, but anyhow we can work around this so there will be no more crashes.

Fixed in 115.

(The Panel Lighting blocks in faulty chunks might revert to their default look, though: nothing we can do about that)

**Closed** 2017-07-29 21:50 UTC
