### ISSUE TITLE
Galacticraft Forcing Normal Difficultly every server start

### ISSUE THREAD

**Issue by BrisingrAerowing** [micdoodle8/Galacticraft#3156] opened 2018-02-07 06:14 UTC
Minecraft version: 1.12.2 (also noticed on 1.10.2 and 1.11.2. Not tested with 1.8.9 or before)
Galacticraft version: 4.0.1.132 (not the first build this has been noticed with)
Forge version: 6212 (Version does not seem to make a difference)

Basically, I play on Peaceful, and every time I start my world the difficultly has been changed to Normal. I currently use MoreCommands server startup commands to set the difficultly to get around this.

Single player (SSP) or Multiplayer (SMP)? SSP (not tested in SMP)

Galacticraft add-ons and other mods installed? None (Tested with only GC)

**Comment by radfast** [comment] 2018-02-07 09:57
duplicate of #3146

**Closed by radfast** 2018-02-07 09:57 UTC
