### ISSUE TITLE
I can't install on Server because he can only install from courseforge

### ISSUE THREAD

**Issue by Blocky10** [micdoodle8/Galacticraft#3786] opened 2019-09-07 12:48 UTC
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version:
Galacticraft version:

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?

Any Galacticraft add-ons installed? please list all

Please provide screenshots / crash report / log / full modlist as needed

If the game is not starting at all, please confirm that you downloaded from the official Galacticraft download site (https://micdoodle8.com/mods/galacticraft)

**Comment by TheQuadShot** [comment] 2019-09-07 13:24
Please close this report, it's not a bug and has been discussed extensively on the forums. The Mod Author has declined to post it and will not change his mind.
https://forum.micdoodle8.com/index.php
https://forum.micdoodle8.com/index.php?threads/curseforge.7052/#post-45545

**Closed** 2019-09-07 13:27 UTC
