### ISSUE TITLE
Bugged Time on GC Dimensions

### ISSUE THREAD

**Issue by FrostQ** [micdoodle8/Galacticraft#3271] opened 2018-03-23 21:55 UTC
Minecraft version: 1.12.2
Galacticraft version: 4.0.1.164

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Both

Galacticraft add-ons and other mods installed?
Yes

Please provide screenshots / crash report / log as needed.
Watch this on these videos
![day](https://user-images.githubusercontent.com/36822613/37854835-e3a51f70-2eec-11e8-99ae-890cf701a979.png)
https://youtu.be/zYKptF6XTKQ (Vanilla Dimensions)
https://youtu.be/uuGjIACJzQw (GC Dimensions)

Overworld, Nether and The End (Day 4)
Moon (Day 2)
Space Station (Day 0)
If you write "/time add 24000" on Moon (or other gc dimension), it will doubled
(Day 0) -> (Day 2) instead (Day 1)

**Comment by marcus8448** [comment] 2018-03-24 05:11
Duplicate of #2877

**Comment by FrostQ** [comment] 2018-03-24 09:20
Ok, i didn't found this issue

**Comment by radfast** [comment] 2018-03-24 11:25
Dev tends to focus on issues which are gamebreaking, affect compatibility with other mods, or affect worldgen.  This is none of those.

**Closed by radfast** 2018-03-24 11:25 UTC
