### ISSUE TITLE
[1.10.2] Client crash rendering still oil with near IC2 pump

### ISSUE THREAD

**Issue by DaveDevil** [micdoodle8/Galacticraft#2980] opened 2017-09-16 13:41 UTC
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.10.2
Galacticraft version: 1.10.2-4.0.0.106
Forge version:12.18.3.2185

Single player (SSP) or Multiplayer (SMP): SMP

Galacticraft add-ons and other mods installed? many (see crash report)

In gamemode 1 i tried to make a oil pump. i broke some stone on the bottom of the oil pool, and i placed IC2 pump. I placed near it the thermal dynamic fluxduct. when i placed under the pump a glass fibre cable my client crashed.

Now i am not able to approach that zone or the client crashes.

Tried in every other liquid the same thing and it works correctly, so i think it's a gc oil issue.

Crash report: https://pastebin.com/HRHdAkvu

**Comment by marcus8448** [comment] 2017-09-16 15:13
This is a duplicate of #2973

**Comment by DaveDevil** [comment] 2017-09-16 18:48
no, this is a rendering problem.

it is possibile to pump oil with IC2 pump (i'm actually doing it) but need to not put cables on the bottom

**Comment by radfast** [comment] 2017-10-07 14:21
Should be fixed in next build 119.

**Closed** 2017-10-07 14:25 UTC
Labels: fixed

**Comment by rockclimber36** [comment] 2017-10-25 22:26
So I am see the same issue. I see the fixed label has been placed on this. Does this mean its been fixed for the next build?
