### ISSUE TITLE
could not get provider type for dim crash

### ISSUE THREAD

**Issue by audenga** [micdoodle8/Galacticraft#2178] opened 2016-04-16 03:53 UTC
http://paste.ee/p/kLuTe

just looking at the creative tab to make sure all the mods i wanted are in my pack and this happened
not on a server

**Comment by radfast** [comment] 2016-06-25 19:21
Please can you repost this error log, if you still have it?

**Comment by EzerArch** [comment] 2016-06-25 22:28
@audenga, tip: use https://gist.github.com/ to save and manage logs.

**Comment by radfast** [comment] 2017-03-19 03:51
Duplicate of #1962 #2236 #2349 and others.

The cause of this is a dimension ID conflict with another mod.  This will be reported in the fml startup.log like this example:
 
>    Could not register dimension -19 - does it clash with another mod? Change the ID in config.

People reporting this are usually using Galacticraft add-ons like GalaxySpace or More Planets which add many more dimensions, and so give increased chance of dimension ID conflict.

Check the startup logs, fix the dimension ID conflict and this problem will not occur.

**Closed by radfast** 2017-03-19 03:51 UTC
Labels: 1.7, missing info

**Comment by radfast** [comment] 2017-03-19 04:24
In some cases these dimension ID conflict issues are caused by AE2's **Spatial Storage Cells**.  AE2 creates a new dimension for _every new storage cell_.  There may be a way to configure it to switch that off or to control which dimensions AE2 is allowed to use, but I am not an AE2 expert.
