### ISSUE TITLE
 The game is cracked when changing pages in the creative menu

### ISSUE THREAD

**Issue by Natetip72** [micdoodle8/Galacticraft#3476] opened 2018-07-14 17:53 UTC
I have an error with the Mixdoodle core that every time I change the inventory page in creative mode it puts me * Sutting down internal server * and I crashed the game putting this on: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.12.2 (1).jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 7/14/18 7:11 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at de.universallp.justenoughbuttons.client.handlers.ModSubsetButtonHandler.drawSubsetList(ModSubsetButtonHandler.java:100)
	at de.universallp.justenoughbuttons.client.handlers.EventHandlers.onDrawScreen(EventHandlers.java:81)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_246_EventHandlers_onDrawScreen_DrawScreenEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:354)
	at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at Reflector.callVoid(Reflector.java:614)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1449)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at de.universallp.justenoughbuttons.client.handlers.ModSubsetButtonHandler.drawSubsetList(ModSubsetButtonHandler.java:100)
	at de.universallp.justenoughbuttons.client.handlers.EventHandlers.onDrawScreen(EventHandlers.java:81)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_246_EventHandlers_onDrawScreen_DrawScreenEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:354)
	at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at Reflector.callVoid(Reflector.java:614)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
	Mouse location: Scaled: (108, 16). Absolute: (325, 673)
	Screen size: Scaled: (384, 241). Absolute: (1152, 722). Scale factor of 3

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [GCEntityClientPlayerMP['Natetip72'/384, l='MpServer', x=109.28, y=64.00, z=255.22]]
	Chunk stats: MultiplayerChunkCache: 284, 284
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (116,64,252), Chunk: (at 4,4,12 in 7,15; contains blocks 112,0,240 to 127,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1039 game time, 1039 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 96 total; [EntityVillager['Villager'/1, l='MpServer', x=34.50, y=96.00, z=242.50], EntityVillager['Villager'/2, l='MpServer', x=32.50, y=96.00, z=256.50], EntityArmorStand['Armor Stand'/3, l='MpServer', x=33.50, y=94.00, z=264.50], EntityArmorStand['Armor Stand'/4, l='MpServer', x=34.50, y=94.00, z=264.50], EntityArmorStand['Armor Stand'/5, l='MpServer', x=36.50, y=94.00, z=264.50], EntityArmorStand['Armor Stand'/6, l='MpServer', x=37.50, y=94.00, z=264.50], EntityArmorStand['Armor Stand'/14, l='MpServer', x=33.50, y=94.00, z=264.50], EntityArmorStand['Armor Stand'/15, l='MpServer', x=34.50, y=94.00, z=264.50], EntityArmorStand['Armor Stand'/16, l='MpServer', x=36.50, y=94.00, z=264.50], EntityArmorStand['Armor Stand'/17, l='MpServer', x=37.50, y=94.00, z=264.50], EntityVillager['Villager'/18, l='MpServer', x=48.50, y=89.00, z=244.50], EntityVillager['Villager'/19, l='MpServer', x=48.50, y=89.00, z=245.50], EntityVillager['Villager'/20, l='MpServer', x=48.50, y=95.00, z=265.50], EntityVillager['Villager'/25, l='MpServer', x=71.50, y=81.00, z=247.50], EntityVillager['Villager'/26, l='MpServer', x=56.50, y=97.00, z=268.50], EntityVillager['Villager'/27, l='MpServer', x=77.30, y=76.00, z=251.70], EntityVillager['Villager'/28, l='MpServer', x=77.73, y=72.00, z=284.63], EntityWolf['Wolf'/29, l='MpServer', x=120.53, y=66.00, z=256.85], EntityWolf['Wolf'/30, l='MpServer', x=97.68, y=67.00, z=269.48], EntityWolf['Wolf'/31, l='MpServer', x=107.50, y=66.00, z=269.50], EntityWolf['Wolf'/32, l='MpServer', x=102.35, y=66.00, z=271.19], EntityWolf['Wolf'/33, l='MpServer', x=142.51, y=67.00, z=254.43], EntityWolf['Wolf'/34, l='MpServer', x=139.36, y=68.00, z=238.53], EntityWolf['Wolf'/35, l='MpServer', x=141.26, y=67.00, z=244.72], EntityWolf['Wolf'/36, l='MpServer', x=150.31, y=66.00, z=254.57], EntityWolf['Wolf'/37, l='MpServer', x=146.43, y=66.00, z=253.60], EntityWolf['Wolf'/38, l='MpServer', x=151.36, y=65.00, z=258.55], EntityWolf['Wolf'/39, l='MpServer', x=153.28, y=64.00, z=276.50], EntityWolf['Wolf'/40, l='MpServer', x=150.31, y=64.00, z=283.63], EntityWolf['Wolf'/41, l='MpServer', x=151.56, y=66.00, z=251.48], EntityWolf['Wolf'/42, l='MpServer', x=157.50, y=66.00, z=254.50], EntityWolf['Wolf'/43, l='MpServer', x=159.50, y=67.00, z=254.50], EntityWolf['Wolf'/44, l='MpServer', x=156.50, y=66.00, z=257.50], EntityWolf['Wolf'/45, l='MpServer', x=161.50, y=66.00, z=267.50], EntityWolf['Wolf'/46, l='MpServer', x=163.50, y=66.00, z=270.50], EntityWolf['Wolf'/47, l='MpServer', x=165.50, y=67.00, z=273.50], EntityWolf['Wolf'/48, l='MpServer', x=166.50, y=67.00, z=266.50], EntityChicken['Chicken'/49, l='MpServer', x=152.50, y=64.00, z=277.50], EntityChicken['Chicken'/50, l='MpServer', x=152.94, y=64.00, z=275.27], EntityChicken['Chicken'/51, l='MpServer', x=153.50, y=64.00, z=275.50], EntityChicken['Chicken'/52, l='MpServer', x=152.50, y=64.00, z=273.50], EntityFishCod['Cod'/2117, l='MpServer', x=89.80, y=62.00, z=236.68], EntityItem['item.item.seeds'/2147, l='MpServer', x=99.66, y=63.00, z=249.15], EntityFallingBlock['Falling Block'/169, l='MpServer', x=-0.50, y=18.00, z=194.50], EntityFallingBlock['Falling Block'/172, l='MpServer', x=-0.50, y=20.00, z=198.50], EntityCreeper['Creeper'/2223, l='MpServer', x=41.50, y=56.00, z=276.50], EntityZombie['Zombie'/2335, l='MpServer', x=136.50, y=21.00, z=318.50], EntityAquaCreeper['Aqua Creeper'/2377, l='MpServer', x=124.12, y=42.00, z=340.60], EntityAquaCreeper['Aqua Creeper'/2400, l='MpServer', x=2.50, y=59.59, z=308.50], EntitySentry['Sentry'/2403, l='MpServer', x=143.50, y=67.00, z=238.26], EntitySentry['Sentry'/2405, l='MpServer', x=140.62, y=68.00, z=239.51], EntityFishCod['Cod'/2576, l='MpServer', x=187.67, y=51.00, z=236.51], EntityAquaCreeper['Aqua Creeper'/2577, l='MpServer', x=-2.50, y=60.00, z=308.50], EntityBat['Bat'/2582, l='MpServer', x=115.31, y=21.61, z=255.46], EntityAquaCreeper['Aqua Creeper'/2601, l='MpServer', x=148.50, y=54.59, z=351.50], EntityAquaCreeper['Aqua Creeper'/2603, l='MpServer', x=151.50, y=54.59, z=348.50], EntitySkeleton['Skeleton'/2604, l='MpServer', x=67.50, y=15.00, z=175.50], EntityGuard['Guard'/2616, l='MpServer', x=37.54, y=94.00, z=265.57], EntityGuard['Guard'/2617, l='MpServer', x=37.51, y=94.99, z=267.78], EntityGuard['Guard'/2618, l='MpServer', x=42.39, y=96.00, z=235.57], EntitySentry['Sentry'/2626, l='MpServer', x=132.80, y=68.00, z=234.50], EntitySentry['Sentry'/2627, l='MpServer', x=127.69, y=68.00, z=242.20], EntityAquaCreeper['Aqua Creeper'/2634, l='MpServer', x=110.50, y=51.00, z=143.50], EntityZombie['Zombie'/2645, l='MpServer', x=33.50, y=54.00, z=269.50], EntityFishCod['Cod'/2649, l='MpServer', x=155.50, y=48.00, z=327.50], EntityFishCod['Cod'/2650, l='MpServer', x=153.50, y=48.00, z=324.50], EntityZombie['Zombie'/2654, l='MpServer', x=33.50, y=54.00, z=268.50], EntityFishCod['Cod'/2714, l='MpServer', x=182.50, y=52.00, z=240.50], EntitySentry['Sentry'/2776, l='MpServer', x=85.50, y=70.00, z=285.50], EntitySentry['Sentry'/2777, l='MpServer', x=85.50, y=70.00, z=285.50], EntitySentry['Sentry'/2778, l='MpServer', x=85.50, y=70.00, z=285.50], EntityFallingBlock['Falling Block'/784, l='MpServer', x=-0.50, y=18.00, z=194.50], EntityFallingBlock['Falling Block'/786, l='MpServer', x=-0.50, y=20.00, z=198.50], GCEntityClientPlayerMP['Natetip72'/384, l='MpServer', x=109.28, y=64.00, z=255.22], EntityShopkeeper['Shopkeeper'/2024, l='MpServer', x=55.73, y=82.00, z=243.50], EntityGuard['Guard'/2025, l='MpServer', x=71.45, y=88.00, z=241.60], EntityShopkeeper['Shopkeeper'/2026, l='MpServer', x=63.49, y=86.00, z=255.73], EntityGuard['Guard'/2027, l='MpServer', x=75.34, y=74.17, z=281.59], EntityGuard['Guard'/2028, l='MpServer', x=67.30, y=89.00, z=277.15], EntityGuard['Guard'/2029, l='MpServer', x=104.54, y=65.00, z=271.72], EntityGuard['Guard'/2030, l='MpServer', x=69.49, y=89.11, z=270.93], EntityGuard['Guard'/2031, l='MpServer', x=71.67, y=94.00, z=272.47], EntityGuard['Guard'/2032, l='MpServer', x=71.51, y=94.00, z=271.56], EntityVillageLord['Village Lord'/2033, l='MpServer', x=66.46, y=94.00, z=269.59], EntityGuard['Guard'/2034, l='MpServer', x=66.54, y=89.42, z=271.70], EntityGuard['Guard'/2035, l='MpServer', x=71.09, y=94.00, z=272.61], EntityGuard['Guard'/2036, l='MpServer', x=69.87, y=98.00, z=270.65], EntityGuard['Guard'/2037, l='MpServer', x=71.70, y=98.00, z=272.15], EntityGuard['Guard'/2038, l='MpServer', x=71.64, y=98.00, z=270.30], EntitySpider['Spider'/1014, l='MpServer', x=32.50, y=43.00, z=303.50], EntityCreeper['Creeper'/1015, l='MpServer', x=46.50, y=18.00, z=194.50], EntityGuard['Guard'/2039, l='MpServer', x=70.92, y=98.00, z=272.70], EntityGuard['Guard'/2040, l='MpServer', x=60.26, y=95.25, z=268.21], EntityGuard['Guard'/2041, l='MpServer', x=68.67, y=102.50, z=266.51], EntityGuard['Guard'/2042, l='MpServer', x=68.38, y=89.00, z=267.42], EntityGuard['Guard'/2043, l='MpServer', x=72.51, y=102.50, z=271.51]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows Vista (amd64) version 6.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 334312456 bytes (318 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.1.2555 Optifine OptiFine_1.12.2_HD_U_C7 19 mods loaded, 19 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                  | Version      | Source                                  | Signature                                |
	|:--------- |:------------------- |:------------ |:--------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft           | 1.12.2       | minecraft.jar                           | None                                     |
	| UCHIJAAAA | mcp                 | 9.42         | minecraft.jar                           | None                                     |
	| UCHIJAAAA | FML                 | 8.0.99.99    | forge-1.12.2-14.23.1.2555.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge               | 14.23.1.2555 | forge-1.12.2-14.23.1.2555.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | micdoodlecore       |              | minecraft.jar                           | None                                     |
	| UCHIJAAAA | mercurius_updater   | 1.0          | MercuriusUpdater-1.12.2.jar             | None                                     |
	| UCHIJAAAA | ageofweapons        | 0.13.2_pre1  | Age-of-Weapons-Mod-1.12.2.jar           | None                                     |
	| UCHIJAAAA | aqua_creepers       | 1.2.3        | Aqua-Creepers-Mod-1.12.2.jar            | None                                     |
	| UCHIJAAAA | customnpcs          | 1.12         | CustomNPCs_1.12.2(09jul18).jar          | None                                     |
	| UCHIJAAAA | galacticraftcore    | 4.0.1.128    | GalacticraftCore-1.12.2 (1).jar         | None                                     |
	| UCHIJAAAA | galacticraftplanets | 4.0.1.121    | Galacticraft-Planets-Mod-1.12.2.jar     | None                                     |
	| UCHIJAAAA | gogskybox           | 1.1-3        | GoGSkybox-1.12.2.jar                    | None                                     |
	| UCHIJAAAA | imsm                | 1.12         | Instant-Massive-Structures-Mod-1.12.jar | None                                     |
	| UCHIJAAAA | jaff                | 1.7_for_1.12 | JustAFewFish-1.7_for_1.12.jar           | None                                     |
	| UCHIJAAAA | justenoughbuttons   | 1.12-1.2.1   | justenoughbuttons-1.12-1.2.1.jar        | None                                     |
	| UCHIJAAAA | moreplayermodels    | 1.12.2       | MorePlayerModels_1.12.2(18jan18).jar    | None                                     |
	| UCHIJAAAA | movillages          | 1.5.4        | MoVillages-1.12.2.jar                   | None                                     |
	| UCHIJAAAA | lteleporters        | 1.12.2-3.0.0 | Simple-Teleporters-1.12.2.jar           | None                                     |
	| UCHIJAAAA | toroquest           | 1.12.2-5.2   | toroquest-1.12.2-5.2.jar                | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.12.2 (1).jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 361.91' Renderer: 'GeForce GT 610/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.1.2555
	LWJGL: 2.9.4
	OpenGL: GeForce GT 610/PCIe/SSE2 GL version 4.5.0 NVIDIA 361.91, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM)2 Quad CPU Q6600 @ 2.40GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_C7
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 361.91
	OpenGlRenderer: GeForce GT 610/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

Minecraft version: 1.12.2
Galacticraft version: 4.0.1.128

Single player
Galacticraft add-ons and other mods installed: justenoughbuttons-1.12-1.2.1 , OptiFine_1.12.2_HD_U_C7 , GoGSkybox-1.12.2 , Simple-Teleporters-1.12.2 , MoVillages-1.12.2 , toroquest-1.12.2-5.2 , Galacticraft-Planets-Mod-1.12.2 , GalacticraftCore-1.12.2 , Aqua-Creepers-Mod-1.12.2 , MicdoodleCore-1.12.2 , JustAFewFish-1.7_for_1.12 , MorePlayerModels_1.12.2(18jan18) , Age-of-Weapons-Mod-1.12.2 , CustomNPCs_1.12.2(09jul18) , Instant-Massive-Structures-Mod-1.12 .

**Comment by TheQuadShot** [comment] 2018-07-14 20:06
Just Enough Buttons is crashing not GalacatiCraft. Please close this report and report it to them Thanks: https://github.com/univrsal/JustEnoughButtons/issues

**Comment by marcus8448** [comment] 2018-07-15 07:32
Also you have downloaded the mod from a site that reposts/steals mods. (9minecraft I think) please re-download Galacticraft from the official downloads page: https://micdoodle8.com/mods/galacticraft/downloads . Checkout http://stopmodreposts.org/ and #3430 for more information.

**Comment by radfast** [comment] 2018-07-29 14:59
Thanks guys :)

I will close this now.  @Natetip72 you can post a comment or re-open if the issue is happening with Galacticraft downloaded from an official source, and JustEnoughButtons uninstalled.  It's not clear why you are saying MicdoodleCore is causing this, seems unlikely as that has nothing to do with Creative tabs.

**Closed by radfast** 2018-07-29 14:59 UTC
