### ISSUE TITLE
Incompatibility with Lucraftcore and/or Heroesexpansion

### ISSUE THREAD

**Issue by X66Herobrine66X** [micdoodle8/Galacticraft#3705] opened 2019-06-16 19:20 UTC
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 4.0.2.210

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
None, game crashed on startup.

Any Galacticraft add-ons installed? please list all
None

Please provide screenshots / crash report / log / full modlist as needed
https://pastebin.com/gAkCGtax

If the game is not starting at all, please confirm that you downloaded from the official Galacticraft download site (https://micdoodle8.com/mods/galacticraft)
I did.

The issue appears to be with the new version of lucraft core and heroes expansion, by lucraft. In their mod, it hooks in with galacticraft if it is also installed. Players with god of thunder, kree hybrid, and kryptonian powers are supposed to be able to breathe in space without any suits or anything. Before this update, I tried renaming the lucraft mods .jar files to have a 1 in front of them (because I heard that makes them load first, and I had visual glitch concerning those mods) but as soon as I loaded them up it gave me this error message. So I renamed them back to their original names. Now the new update of lucraft core and heroesexpansion gives me the same crash on startup, even without renaming. Hope you can fix this!

**Comment by marcus8448** [comment] 2019-06-17 00:33
I think this is on LuecraftCore/HeroesExpansion's side.
They need to load AFTER Galacticraft so that they can access the event.

**Comment by X66Herobrine66X** [comment] 2019-06-17 00:46
Can i simply fix this be making sure the lucraft jar file is below galacticrafts in my mods folder?

**Comment by MJRLegends** [comment] 2019-06-17 00:50
No

**Comment by radfast** [comment] 2019-08-31 00:21
The order of loading should not matter here.  Forge and the basic Java classloader should take care of all references, no matter which order the mods load.

The references to `micdoodle8/mods/galacticraft/api/event/oxygen/GCCoreOxygenSuffocationEvent$Pre` look correct - they are correctly spelled, and [the class exists](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/api/event/oxygen/GCCoreOxygenSuffocationEvent.java#L32)

I think the real cause here is being hidden by Java's error logging cutting off at 50 lines:

Caused by: java.lang.ClassNotFoundException: micdoodle8.mods.galacticraft.api.event.oxygen.GCCoreOxygenSuffocationEvent$Pre
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 42 more
Caused by: java.lang.NullPointerException

That's where the error report stops, and - unfortunately - that's exactly at the place where it would point to the error location if it continued.  It is essential to know where that NullPointerException is actually located.   Probably it's one of the class transformers missing a null bytes check, but that could be in any mod - here, you have several mods in the list with class transformers or other "coremod" features.

At the end of the day this is likely to be a coding issue in one of the installed mods, in a class transformer.  It's not specifically caused by @X66Herobrine66X setup and there's probably nothing that a user can do to fix it.

**But** if earlier versions of LucraftCore / Heroes Expansion worked OK, and the newer one doesn't, that is strongly pointing to it being a coding issue in one of those mods - maybe report it [here](https://gitlab.com/threetag/LucraftCore/issues)

Another thing you could try, @X66Herobrine66X , is reducing your modlist, try only Galacticraft and LucraftCore and see if the issue still occurs.  If the issue does not occur with a small modlist then add mods in groups, restart, a few times until you figure out which mod makes the difference between crash and no crash.

We can't do more without seeing something pointing specifically to the error location.  So I will close this now (anyhow, it's probably not Galacticraft's error, otherwise it would error for everybody, at least for add-ons using this event).  Happy to re-open if something is pointing to it being a Galacticraft issue.

**Closed by radfast** 2019-08-31 00:21 UTC

**Comment by radfast** [comment] 2019-08-31 00:32
Not that it's any help, but some Googling showed someone else [posting a similar error report](https://pastebin.com/GgWExPx8) but with a partly different mods list.

**Comment by radfast** [comment] 2019-08-31 00:45
Could be related to CraftfallEssentials?

See also discussion [here](https://www.curseforge.com/minecraft/mc-mods/lucraft-core?filter-game-version=1738749986%3a628&sort=releasetype) - it's the same type of issue with Lucraft, and again the error report is cut off just where it gets interesting (just after the NullPointerException).  Here, Galacticraft is not present.

I now think this is **definitely** not a Galacticraft issue.

**Comment by radfast** [comment] 2019-08-31 11:55
It can also be an out of memory issue - try giving your Minecraft more memory in the JVM options.
