### ISSUE TITLE
[MrTJP Core] Already decorating crash

### ISSUE THREAD

**Issue by vadimyer** [micdoodle8/Galacticraft#2066] opened 2016-02-05 09:28 UTC
This one is really frustrating, it happens once in a month, I'm really not sure why.

```
---- Minecraft Crash Report ----
// There are four lights!

Time: 2/5/16 12:18 PM
Description: Exception in server tick loop

java.lang.RuntimeException: Already decorating!!
	at micdoodle8.mods.galacticraft.api.prefab.world.gen.BiomeDecoratorSpace.decorate(BiomeDecoratorSpace.java:24)
	at micdoodle8.mods.galacticraft.api.prefab.world.gen.ChunkProviderSpace.decoratePlanet(ChunkProviderSpace.java:341)
	at micdoodle8.mods.galacticraft.api.prefab.world.gen.ChunkProviderSpace.func_73153_a(ChunkProviderSpace.java:355)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:408)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1187)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:293)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:199)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:167)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:304)
	at net.minecraft.world.World.func_72964_e(World.java:751)
	at mrtjp.core.world.BlockUpdateHandler$.onTick(blocktickhook.scala:79)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_302_BlockUpdateHandler$_onTick_WorldTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:259)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:974)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	KCauldron Version: pw.prok:KCauldron:1.7.10-1614.175
	Operating System: Linux (amd64) version 3.16.0-4-amd64
	Java Version: 1.8.0_72, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Azul Systems, Inc.
	Memory: 1318252248 bytes (1257 MB) / 3094872064 bytes (2951 MB) up to 11453595648 bytes (10923 MB)
	JVM Flags: 1 total; -Xmx12G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 57 mods loaded, 57 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (KCauldron-1.7.10-1614.175.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (KCauldron-1.7.10-1614.175.jar) 
	UCHIJAAAA	kimagine{0.2} [KImagine] (minecraft.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	bspkrsCore{6.15} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.15.jar) 
	UCHIJAAAA	IC2{2.2.810-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.810-experimental.jar) 
	UCHIJAAAA	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (AdvancedSolarPanel-1.7.10-3.5.1.jar) 
	UCHIJAAAA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.12} [BuildCraft] (buildcraft-7.1.12.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.1.12} [BC Builders] (buildcraft-7.1.12.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.12} [BC Transport] (buildcraft-7.1.12.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.1.12} [BC Energy] (buildcraft-7.1.12.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.12} [BC Silicon] (buildcraft-7.1.12.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.1.12} [BC Robotics] (buildcraft-7.1.12.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.1.12} [BC Factory] (buildcraft-7.1.12.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.7} [Carpenter's Blocks] (Carpenters-Blocks-3.3.7.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	Railcraft{9.8.0.0} [Railcraft] (Railcraft-1.7.10-9.8.0.0.jar) 
	UCHIJAAAA	chisel{2.5.1.44} [Chisel 2] (Chisel2-2.5.1.44.jar) 
	UCHIJAAAA	cmd{1.4} [Custom Music Discs] (Custom Music Discs-1.4 Server.jar) 
	UCHIJAAAA	endercore{1.7.10-0.0.1.13_alpha} [EnderCore] (EnderCore-1.7.10-0.0.1.13_alpha.jar) 
	UCHIJAAAA	EventHelper{1.4} [EventHelper] (EventHelper-1.4.jar) 
	UCHIJAAAA	ExtrabiomesXL{3.16.3} [ExtrabiomesXL] (extrabiomesxl_1.7.10-3.16.3.jar) 
	UCHIJAAAA	Forestry{4.0.10.39} [Forestry for Minecraft] (forestry_1.7.10-4.0.10.39.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
	UCHIJAAAA	MCFrames{1.0} [MCFrames] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
	UCHIJAAAA	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar) 
	UCHIJAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.437.jar) 
	UCHIJAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.437.jar) 
	UCHIJAAAA	GraviSuite{1.7.10-2.0.3} [Graviation Suite] (GraviSuite-1.7.10-2.0.3.jar) 
	UCHIJAAAA	GraviSuiteReloaded{1.7.10-0.9.1} [GraviSuiteReloaded] (GraviSuite_Reloaded-1.7.10-0.9.1.jar) 
	UCHIJAAAA	IC2CA{1.14.5.06} [IndustrialCraft 2 Combo Armors] (ic2ca-1.7.10-1.14.5.06.jar) 
	UCHIJAAAA	IC2NuclearControl{2.3.4a} [Nuclear Control 2] (IC2NuclearControl-2.3.4a.jar) 
	UCHIJAAAA	IronChest{6.0.41.729} [Iron Chest] (Iron-Chests-Mod-1.7.10.jar) 
	UCHIJAAAA	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
	UCHIJAAAA	cfm{3.4.7} [�9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) 
	UCHIJAAAA	MrTJPCoreMod{1.1.0.31} [MrTJPCore] (MrTJPCore-1.7.10-1.1.0.31-universal.jar) 
	UCHIJAAAA	ProjRed|Core{4.7.0pre9.92} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre9.92-Base.jar) 
	UCHIJAAAA	ProjRed|Transmission{4.7.0pre9.92} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre9.92-Integration.jar) 
	UCHIJAAAA	ProjRed|Transportation{4.7.0pre9.92} [ProjectRed Transportation] (ProjectRed-1.7.10-4.7.0pre9.92-Mechanical.jar) 
	UCHIJAAAA	ProjRed|Exploration{4.7.0pre9.92} [ProjectRed Exploration] (ProjectRed-1.7.10-4.7.0pre9.92-World.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
	UCHIJAAAA	ProjRed|Compatibility{4.7.0pre9.92} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre9.92-Compat.jar) 
	UCHIJAAAA	ProjRed|Integration{4.7.0pre9.92} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre9.92-Integration.jar) 
	UCHIJAAAA	ProjRed|Fabrication{4.7.0pre9.92} [ProjectRed Fabrication] (ProjectRed-1.7.10-4.7.0pre9.92-Fabrication.jar) 
	UCHIJAAAA	ProjRed|Illumination{4.7.0pre9.92} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre9.92-Lighting.jar) 
	UCHIJAAAA	ProjRed|Expansion{4.7.0pre9.92} [ProjectRed Expansion] (ProjectRed-1.7.10-4.7.0pre9.92-Mechanical.jar) 
	UCHIJAAAA	RedstoneArsenal{1.7.10R1.1.1} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.1-89.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.0.3-303
	ThermalFoundation: -[1.7.10]1.2.0-102
	ThermalExpansion: -[1.7.10]4.0.3B1-218
	RedstoneArsenal: -[1.7.10]1.1.1-89
	Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Bukkit, Cauldron, or other Bukkit replacement
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
Info: The following plugins have been disabled in the config: mail, agricraft, enderio, erebus, extrautilities, growthcraft, harvestcraft, immersiveengineering, magicalcrops, natura, plantmegapack, witchery
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BC:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 29 / 100; [GCEntityPlayerMP['zomg'/828, l='world', x=-8.30, y=80.00, z=1564.70](zomg at -8.300000011920927,80.0,1564.699999988079), GCEntityPlayerMP['MrNs'/77359, l='world', x=-2009.59, y=138.00, z=6647.99](MrNs at -2009.5928834289648,138.0,6647.987500011921), GCEntityPlayerMP['DILLERON22'/134111, l='world', x=1560.67, y=101.00, z=7785.86](DILLERON22 at 1560.6665874124958,101.0,7785.864781206385), GCEntityPlayerMP['Listik'/230991, l='world', x=2516.70, y=63.00, z=2397.30](Listik at 2516.699999988079,63.0,2397.300000011921), GCEntityPlayerMP['Chicony'/232164, l='world', x=4602.37, y=93.27, z=3453.30](Chicony at 4602.371126923434,93.2712119209664,3453.300000011921), GCEntityPlayerMP['HelenWolfy'/310755, l='world', x=3018.15, y=62.00, z=2415.68](HelenWolfy at 3018.1452826087066,62.0,2415.675984027614), GCEntityPlayerMP['Kuzer'/346477, l='world', x=-4984.03, y=64.00, z=5792.28](Kuzer at -4984.029281377696,64.0,5792.276279624064), GCEntityPlayerMP['zedkill'/238907, l='world', x=-3590.31, y=107.85, z=8490.52](zedkill at -3590.312683631427,107.85077687783198,8490.51886464046), GCEntityPlayerMP['tbbm17'/403555, l='DIM-28', x=6780.47, y=65.89, z=4619.75](tbbm17 at 6780.46692479023,65.88502076643222,4619.753268273962), GCEntityPlayerMP['CrazyFail'/404637, l='world', x=1656.72, y=55.00, z=2885.21](CrazyFail at 1656.720940216602,55.0,2885.212268868219), GCEntityPlayerMP['LiRiK73'/414124, l='world', x=1929.94, y=73.00, z=2045.19](LiRiK73 at 1929.9435423357988,73.0,2045.1919982912946), GCEntityPlayerMP['anderr2'/447193, l='world', x=2994.60, y=58.00, z=2431.18](anderr2 at 2994.603274517798,58.0,2431.181134435058), GCEntityPlayerMP['FlarpzZ'/465551, l='world', x=1827.15, y=68.00, z=1728.16](FlarpzZ at 1827.153231498219,68.0,1728.155066971144), GCEntityPlayerMP['kirgis'/501947, l='world', x=-6176.63, y=81.00, z=2039.05](kirgis at -6176.62710685366,81.0,2039.0516757926944), GCEntityPlayerMP['maismais'/507363, l='DIM-28', x=6770.03, y=65.56, z=4625.04](maismais at 6770.026529827214,65.56228805231179,4625.038538339818), GCEntityPlayerMP['cerber'/510905, l='world', x=3106.35, y=64.00, z=7242.63](cerber at 3106.3519940808064,64.0,7242.629204788411), GCEntityPlayerMP['DimasZ'/512911, l='DIM-29', x=-4850.80, y=108.33, z=6719.13](DimasZ at -4850.795682139953,108.32838483138232,6719.1334894097345), GCEntityPlayerMP['TsiMax'/520992, l='world', x=1083.14, y=45.00, z=1024.50](TsiMax at 1083.1443698192274,45.0,1024.4982250424891), GCEntityPlayerMP['Wladimir'/532347, l='world', x=-8146.47, y=73.00, z=-4862.81](Wladimir at -8146.474395180982,73.0,-4862.809186201027), GCEntityPlayerMP['Ilya'/503135, l='world', x=85.20, y=92.00, z=930.56](Ilya at 85.20487783438841,92.0,930.5644120651871), GCEntityPlayerMP['Alex1117'/561611, l='world', x=-8168.84, y=34.00, z=-3997.25](Alex1117 at -8168.837343186937,34.0,-3997.2474531453313), GCEntityPlayerMP['Nemezko'/337382, l='world', x=1576.57, y=63.38, z=7846.05](Nemezko at 1576.5677001466197,63.379121777664,7846.049743847317), GCEntityPlayerMP['dimassan'/572833, l='world', x=2353.42, y=65.00, z=2348.70](dimassan at 2353.422747465908,65.0,2348.699999988079), GCEntityPlayerMP['Hummer'/511607, l='world', x=2290.78, y=57.36, z=3603.84](Hummer at 2290.784448764825,57.36450240000001,3603.8419178324416), GCEntityPlayerMP['VKLowe'/227924, l='world', x=4519.95, y=152.00, z=1391.63](VKLowe at 4519.9510945258135,152.0,1391.6330291886247), GCEntityPlayerMP['Guropatic'/602217, l='world', x=2742.72, y=11.00, z=3603.21](Guropatic at 2742.720006103366,11.0,3603.2111200761806), GCEntityPlayerMP['KurokuKZ'/603273, l='world', x=5783.51, y=86.00, z=2983.31](KurokuKZ at 5783.5100865818995,86.0,2983.3139753422465), GCEntityPlayerMP['ipik'/290356, l='DIM_SPACESTATION27', x=13.65, y=63.50, z=1.77](ipik at 13.645586072768133,63.49749547872681,1.7664089832685144), GCEntityPlayerMP['Nixon'/603849, l='world', x=1585.65, y=63.00, z=7855.52](Nixon at 1585.6544607929368,63.0,7855.522674038824)]
	Is Modded: Definitely; Server brand changed to 'kcauldron,cauldron,craftbukkit,mcpc,fml,forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by radfast** [comment] 2016-02-05 11:37
Probably not Galacticraft.
It's normally caused by another mod's code triggering worldgen at a time when it should not.
In this case it looks like MrTJP Core is the problem.

> at mrtjp.core.world.BlockUpdateHandler$.onTick(blocktickhook.scala:79)

Any information about which dimension this is in, and which blocks MrTJP adds?

**Comment by vadimyer** [comment] 2016-02-05 11:50
This happened twice, I think first time because of a player generating chunks on Mars, for the second time - I wasn't on a server, can't really say why, would like to... Maybe Mars again, too.

My config about generation is standard, here's a cut:
```
# If this is enabled, other mods' standard ores and all other features (eg. plants) can generate on the Moon and planets. Apart from looking wrong, this make cause 'Already Decorating!' type crashes.  NOT RECOMMENDED!  See Wiki.
    B:"Generate all other mods features on planets"=false

    # If generate other mods features is disabled as recommended, this setting can whitelist CoFHCore custom worldgen on planets.
    B:"Whitelist CoFHCore worldgen to generate its ores and lakes on planets"=false

    # If ThaumCraft is installed, ThaumCraft wild nodes can generate on the Moon and planets.
    B:"Generate ThaumCraft wild nodes on planetary surfaces"=true

    # Enter IDs of other mods' ores here for Galacticraft to generate them on the Moon and other planets. Format is BlockName or BlockName:metadata. Use optional parameters at end of each line: /RARE /UNCOMMON or /COMMON for rarity in a chunk; /DEEP /SHALLOW or /BOTH for height; /SINGLE /STANDARD or /LARGE for clump size; /XTRARANDOM for ores sometimes there sometimes not at all.  /ONLYMOON or /ONLYMARS if wanted on one planet only.  If nothing specified, defaults are /COMMON, /BOTH and /STANDARD.  Repeat lines to generate a huge quantity of ores.
    S:"Other mods ores for GC to generate on the Moon and planets" <
     >
```

MrTJP core is a base mod for ProjectRed, this mod's generating some ores and flowers, as well as volcanos in Overworld. I've never seen anything from this mod on planets.

**Comment by vadimyer** [comment] 2016-02-05 11:52
According to the stats from crash report: 2 players were in DIM-28, 1 in DIM-29, one at space station.

**Comment by Cronosus** [comment] 2016-02-06 14:14
crash on server, is this relevant to this issue?
http://pastebin.com/gAHd5mpE

**Comment by radfast** [comment] 2016-02-06 17:50
Thanks @Cronosus 
Kind of relevant, yeah.  On your server the crash is happening on the Overworld.

I still can see no reason for either crash.  There's nothing in Galacticraft obviously causing this.  It may be a coincidence - the same setup would have crashed even without Galacticraft.

These crashes are also super hard to troubleshoot, because they are so rare - I can't reproduce them by starting a new world and following steps X + Y + Z.

**Comment by Cronosus** [comment] 2016-02-06 19:38
my teammember just porting between worlds for this crash
here full log, maybe it helps
http://cronos.wz.cz/mc/err/2016-02-06-2.log

**Comment by radfast** [comment] 2016-02-06 22:12
@Cronosus please list other mods.  Especially any mod which can affect **tree generation** or something else in a Forest biome.  Maybe that is where the problem is.

**Comment by Cronosus** [comment] 2016-02-06 23:19
as you can see on crash report, i dont use any biome mod, only GC a some technic mods... only moreplanets add one planet with forest (Fronos)...nothing more with forest or trees.

**Comment by DraksterAU** [comment] 2016-02-24 03:19
@radfast This can be closed. It's fixed in at least Build 185+ of KCauldron (what I'm Using) and definitely in B200.

**Comment by DraksterAU** [comment] 2016-02-24 03:21
@cronusus are you still experiencing this?
I'm not.

**Comment by radfast** [comment] 2016-02-24 03:40
There are two different causes: Cronusus crash is not the same as the OP.

Cronusus crash happened in a server in some local map generation code - Galacticraft uses the same code as vanilla Maps to create an image of the Overworld around a player's base, used in the Overworld rocket launch sequence.

Vadimyer's crash happened in code called by MrTJPCore.

The only feature both crashes have in common is that they happened in a world tick end section.  I have not seen that before.  It could be connected with KCauldron or some type of multithreading I guess.  Basically it appears that a world tick is ending on the server, even while Minecraft is still running worldgen code elsewhere.  I don't know why.  Does KCauldron or a plugin have something to force slow ticks to end, to try to keep the TPS up?

Cronusus using KCauldron 189, Vadimyer 175.

Already Decorating issues are very hard to track down.  Minecraft has 2 stage worldgen: at stage 1, things like hills, stone, dirt and oceans are made.  At stage 2, called "Decorating", ores, trees, lakes, caverns and other similar "final" worldgen features are added to a chunk.  Any mod which adds ores can do some "Decorating".  The 'Already Decorating' error message occurs when worldgen code is asked to do stage 2 generation on a new chunk before it finished generating the earlier chunk.  The error message is intended to prevent the server from getting into an endless loop, though you could say it fires false positives.  Vanilla Minecraft has a smart algorithm for chunkgen which prevents the "already decorating" error message.

The most common cause for Already Decorating issues is a mod's worldgen code (it could be ores or whatever) which looks at neighbouring blocks to decide whether or not it can place a block at a position.  Depending on how it's coded, that can require neighbouring chunks to be loaded.  Loading an ungenerated chunk will start to generate it.  You can see how a server can get into a loop.  Any TileEntity (chests, or more complex machines, and goodness knows how GregTech ores work) placed or removed during worldgen can also cause this, because vanilla code when a TileEntity is placed or removed automatically does a block update on all surrounding blocks, and a block update requires the chunk to be loaded.

I do not think that is what is occurring here.  These are issues caused during the end phase of a server tick - not during normal worldgen when players move around the map.

**Comment by DraksterAU** [comment] 2016-02-24 04:18
@radfast fair enough, KCauldron had/has a time limit for ticks during generation before the loop is cancelled forcefully to prevent a hang. Not sure if that is it?

Sorry for jumping the gun... I had the issue pre 185 and no longer have it. I run not TJPCore and more planets.

**Comment by Robotia** [comment] 2016-02-24 11:02
Yes, this was fixed in Thermos

**Comment by vadimyer** [comment] 2016-02-24 11:04
I can confirm, got no crashes of this kind since relocating to Thermos.
Also, Thermos seems more stable. Chunk loading is much faster.
Keep up the good work, @Robotia!

**Comment by Robotia** [comment] 2016-02-24 12:21
Thanks @vadimyer!

**Comment by Cronosus** [comment] 2016-02-24 16:56
@DraksterAU 
No crashes yet

**Comment by radfast** [comment] 2016-02-24 20:49
> KCauldron had/has a time limit for ticks during generation before the loop is cancelled forcefully to prevent a hang. Not sure if that is it? It's 10 seconds... If that is mid tick could it be what your after?

That will be it.  I don't know if there's any way to check whether that time limit was triggered immediately prior to the crashes posted in this thread?  Anyhow, seems like it doesn't matter now - if everything is working better in Thermos - thanks to @Robotia - then I think this is problem solved.

**Closed by radfast** 2016-02-24 20:49 UTC
Labels: cant reproduce

**Comment by DraksterAU** [comment] 2016-02-24 22:06
@radfast Yeah there is no reason to use KCauldron anymore really. @robotia responds to issues within a day usually... The average for KCauldron guys to respond is in the weeks...

**Comment by DraksterAU** [comment] 2016-02-24 22:07
Ps that is to respond, not necessarily fix lol

**Comment by Cronosus** [comment] 2016-02-25 18:43
What is Thermos?

**Comment by Robotia** [comment] 2016-02-25 19:40
https://github.com/TCPR/Thermos

**Comment by Cronosus** [comment] 2016-02-25 19:58
ah.. thanks, i have now kcauldron 1614.. the same.. :D
