### ISSUE TITLE
Single dimension latency after updating galacticraft

### ISSUE THREAD

**Issue by hugeblank** [micdoodle8/Galacticraft#2942] opened 2017-08-08 03:23 UTC
Minecraft version: 1.11.2
Galacticraft version: 4.0.0.116
Forge version: 13.20.1.2393

Mod list can be found [here](https://kaos-network.com/servers/sonarx). (scroll down a little, it's there, trust me)

I am currently working on a server I plan on opening in the next couple of weeks. This server has been in the making for a while, and I wanted to add extraplanets. Extraplanets requires version 4.0.0.114 or higher. I was in version 4.0.0.111. Funnily enough, I had accidentally added extraplanets and booted the server before updating to 4.0.0.116, and everything worked near fine and dandy. It wasn't until I updated to the latest version when things got _really_ weird. 

A couple of things you might want to know before I get into what happened:
I manipulated these configs in /config/Galacticraft/[core.conf](https://github.com/micdoodle8/Galacticraft/files/1206768/core.txt):

    S:"Dimensions where rockets cannot launch" <
        1
        -1
        2
        0
     >
    I:idDimensionOverworld=3
    I:"Oil gen in external dimensions" <
        3
     >

essentially the goal of these manipulations were to keep rockets from launching in 2 dimensions. The server spawn (0), and the player shops dimensions (2), and focus excavation, launching, and that sort of stuff in the main dimension (3)

The jist of the bug (what I did in order of how I did it):
- I loaded into Dimension 0 perfectly fine. chunks and everything were loading normally.
- saying something in chat registered on servers console, but it took a damn long time to register on the client
- pinged my player from the server, registered 936ms
- pinged the server from my player registered nothing until ages after I typed it. it too registered 936ms.
- Jumped into a portal leading over into dimension 3. Also took a damn long time to work. But after it worked, the server seemed to skip a gazillion ticks, the sun flew across the sky, and I think I experienced 30 minutes worth of daylight cycle in a minute before it caught up with itself. 
- typing into chat works flawlessly in dimension 3.
- jumping into a portal leading back to dimension 0 loads the dimension, and starts the latency cycle again.

Essentially what I saw after loading into Dimension 0 again was a linear increase in ping, roughly a 20ms gain per second, but chunks have no issue loading. So this could be 1/2 things, an actual bug with the mod, or my own error with the config... and I'm leaning on the latter of the 2 :P

I'm fairly certain that this is not an issue to do with the extraplanets mod, as I contacted the developer and they said that there were no major, breaking differences between 4.0.0.114 and 4.0.0.116.

**Comment by TheQuadShot** [comment] 2017-08-08 23:14
What does ping time have to do with anything? Ping is an icmp "echo" request and doesn't have anything to do with programs running on the machine you are pinging... Its at a hardware level, and isn't seen by anything outside of the protocol stack.

**Comment by hugeblank** [comment] 2017-08-09 08:13
@TheQuadShot I was using a command (/ping) from a plugin. I don't think it works in exactly the same manner as the ping command that is used in the server console (outside of minecraft).

**Comment by radfast** [comment] 2017-08-09 13:10
You appear to have network issues, it does not seem likely these are caused by the Galacticraft mod.  You should start by looking at the server plugins which are making these extra dimensions.  Also make sure you read the documentation about [Sponge](https://wiki.micdoodle8.com/wiki/Sponge).

If you can identify a reproducable issue that's actually an issue in Galacticraft, that's something we can look at.  For now I will close this, but your're welcome to comment and give reasons to reopen.

**Closed by radfast** 2017-08-09 13:10 UTC
