### ISSUE TITLE
Galacticraft - Special Mobs client crash

### ISSUE THREAD

**Issue by DrStage** [micdoodle8/Galacticraft#1448] opened 2015-02-12 22:54 UTC
Hello!

I am running the Beyond Reality pack  (Galacticraft v.3.0.8.261) with a couple of extra mods, Special Mobs v. 3.0.3 included.
I had no problems with old versions of galacticraft and special mobs, with these however I got this crash:
I got attacked by a SM zombie, seconds after it my client crashed, same happened to a friend who got attacked by the same zombie Server had no issues.
Logging back in was not possible, instant crash.

Crashlog: http://pastebin.com/hBResRBT

**Comment by radfast** [comment] 2015-02-13 17:44
This is a duplicate of #1323 and #1365.

For the reasons explained on those issues, I do not think this is a bug in Galacticraft or anything we can help with.  It appears to be a bug in other mods which have mobs with special attacks which have magical effects (i.e. potion effects).  Galacticraft does not add any potion effects.

Because this seems to happen with several different mods, two things I suggest you check:
* are the server and the client running the __exact__ same version of every mod?
* are the server and the client running the exact same Forge version?

My guess is it's also possible that it's a bug in Forge or Cauldron.  I have not Googled to see how much this crash gets reported when Galacticraft is not installed, but you should definitely do that.

Obviously, if someone can show me a reason why this crash is connected with Galacticraft then I will look into it further.  (e.g. make a duplicate of the exact server world which is crashing on login, uninstall Galacticraft on server and client, login - does it still crash?)

**Closed by radfast** 2015-02-13 17:44 UTC
