### ISSUE TITLE
[More Planets mod]  Venus - error thermal armor

### ISSUE THREAD

**Issue by denwd** [micdoodle8/Galacticraft#2014] opened 2016-01-12 17:50 UTC
[18:03:23] [Server thread/ERROR]: Exception caught during firing event net.minecraftforge.event.entity.living.LivingEvent$LivingUpdateEvent@63a28044:
java.lang.ArithmeticException: / by zero
        at micdoodle8.mods.galacticraft.core.entities.player.GCPlayerHandler.checkThermalStatus(GCPlayerHandler.java:497) ~[GCPlayerHandler.class:?]
        at micdoodle8.mods.galacticraft.core.entities.player.GCPlayerHandler.onPlayerUpdate(GCPlayerHandler.java:1205) ~[GCPlayerHandler.class:?]
        at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.entityLivingEvent(EventHandlerGC.java:269) ~[EventHandlerGC.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_63_EventHandlerGC_entityLivingEvent_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1517.168]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:1.7.10-1517.168]
        at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:297) [ForgeHooks.class:1.7.10-1517.168]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1846) [sv.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:315) [yz.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:425) [mw.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:493) [nh.class:?]
        at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:36) [jd.class:?]
        at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:101) [jd.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:976) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:811) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:671) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_20]

http://joxi.ru/KAxMqL7u4vbgwr

**Comment by radfast** [comment] 2016-01-12 18:41
Are you playing any Galacticraft Add On mod?  For example, More Planets, 4Space, etc?

I think 90%+ chance this is caused by an Add On.  If so, please ask the Add On author to fix it.  It's because of a dangerous result from ```WorldProvider.getThermalLevelModifier();```

I am closing this for now.  We can re-open this issue if it is **not** caused by an Add On.

**Comment by radfast** [comment] 2016-01-12 18:51
See also: https://github.com/micdoodle8/Galacticraft/pull/1946

That was a similar issue, triggered by **More Planets** mod.  In that case the Galacticraft core code could be improved.  In this case, I do not see any error in the Galacticraft core code.

**Comment by denwd** [comment] 2016-01-12 19:01
Yes mod more planets, Venus is not working the thermal armor, and when you try to remove it causes a crash of the client.

**Comment by denwd** [comment] 2016-01-12 19:01
I have a bad English

**Comment by radfast** [comment] 2016-01-12 19:11
@denwd:  which Galacticraft version #?  3.0.12.409?

@SteveKunG some help here please :)

**Comment by denwd** [comment] 2016-01-12 19:15
Latest 411

**Comment by denwd** [comment] 2016-01-12 19:27
What was the edit? can code

**Comment by radfast** [comment] 2016-01-12 19:35
https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/entities/player/GCPlayerHandler.java#L497

I see no error.
* [This](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/entities/player/GCPlayerHandler.java#L452) already tests ```thermalLevelMod``` for zero.  
* [This](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/entities/player/GCPlayerHandler.java#L460) cannot make it zero.
* Also [this](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/entities/player/GCPlayerHandler.java#L454) and [this](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/entities/player/GCPlayerHandler.java#L461) should give / 0 error, already, if ```thermalLevelMod```== 0.

(actually I think [this line](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/entities/player/GCPlayerHandler.java#L461) looks dangerous, we should fix that)

So it looks like we have a situation where: ```thermalLevelModifier != 0 && Math.abs(thermalLevelModifier) == 0```

That is only possible if ```thermalLevelModifier == -0``` (negative zero).

@SteveKunG is it possible for Venus to be returning a thermal property of negative zero?

**Comment by denwd** [comment] 2016-01-12 19:38
Thanks for the help)

**Comment by SteveKunG** [comment] 2016-01-13 10:28
So many issue for this :( Will change thermal value for next release.

**Comment by radfast** [comment] 2016-01-13 13:35
No no, don't change it.  I wanted to know what the thermal value for Venus is.  [It is -1.0F.](https://github.com/SteveKunG/More-Planets/blob/1.8/src/main/java/stevekung/mods/moreplanets/planets/venus/dimension/WorldProviderVenus.java#L150)

So the question is, how can a value of -1.0F give rise to the "divide by zero" error, in GC's code?  I don't understand :/

**Comment by denwd** [comment] 2016-01-13 14:42
Good day, crashes are gone but the thermal armor does not protect fully and players die after 5 minutes without a reservation immediately

**Closed** 2016-01-14 00:02 UTC
Labels: duplicate

**Comment by radfast** [comment] 2016-01-14 00:07
I still don't know the cause of the crash, except it must be code like this ```if (intX % intY == 0) ...``` where ```intY == 0```.  My guess: the original crash was with a GC version prior to version .411.

Anyhow, the 14d31e0 fixes all possibilities of this.

@SteveKunG: I think you will need to test this against all your worlds which have thermal levels, to make sure the thermal armor still works OK.  @denwd is reporting that the world is more hot (or more cold) than even a full set of thermal armor can normalise, so the player must die from thermal damage after 5 minutes.

**Comment by SteveKunG** [comment] 2016-01-14 07:07
Thank you for helping. I will test it. :)

**Comment by SirWilli** [comment] 2016-01-15 14:40
Got the same issue with 4Space that the armor does no longer work. What's the max amount the armor can normalise?

**Comment by zapl** [comment] 2016-01-16 18:14
Had a look at the values and what happens on Mercury (4Planets), `thermalLevelMod` is `9` and the highest level that works with the armor is around `6`.

Compare http://ideone.com/6CtGJr - I've put the calculated values as comments

**Comment by radfast** [comment] 2016-01-16 18:46
Nice job @zapl.  If you can see a good way to fix this in ```checkThermalStatusTest``` so it works for Mercury (thermallevelMod 9) also, that would be fantastic, really appreciated.  You could post here or make a PR to have contributor credit :)

I am not the author of this thermal checks code, so at this point in time you probably know more about how that code works than I do.

**Comment by DeckerMMIV** [comment] 2016-01-18 19:21
@radfast 
May I suggest the following "clamp" of the `thermalLevelMod` value, [after getting it](https://github.com/micdoodle8/Galacticraft/blob/5738cd2c24828de4eb4d31e0a22a6def406ad563/src/main/java/micdoodle8/mods/galacticraft/core/entities/player/GCPlayerHandler.java#L454) from the provider:
```
  float thermalLevelMod = provider.getThermalLevelModifier();
  thermalLevelMod = Math.min(6.0F, Math.max(-6.0F, thermalLevelMod)); // <--- Clamp to -6 ... +6
  double absThermalLevelMod = Math.abs(thermalLevelMod);
```
Possibly use a configurable value for the minimum/maximum value of the thermal level modifier?

**Comment by radfast** [comment] 2016-01-18 19:26
But maybe some Add On authors want more extreme thermalLevelMod than 6, if they pair that with extremely strong thermal protection items?

Or Add On authors deliberately want to make a dimension in which you cannot survive for more than a few minutes even if you have maximum thermal protection - I think maybe Mercury could be like that during the day time.

**Comment by radfast** [comment] 2016-01-18 19:29
I guess I'm looking for a system where high ```thermalLevelMod``` combined with a high protection will still protect the player.

As I understand the problem here, it's connected with environments so extreme that the normalise tick wants to be less than 1, but is clamped at 1 minimum so as to avoid divide by zero errors.

**Comment by DeckerMMIV** [comment] 2016-01-18 19:38
Hmm. Yes, you got a good point there, which I didn't consider, regarding other addon mods.

My main concern regarding this "problem", is due to the Galactic Science pack, which was updated just recently. And apparently something "[broke](http://forum.feed-the-beast.com/threads/listed-1-7-10-hqm-survival-galactic-science-something-fresh.86203/page-110#post-1550806)", which as far as I have only shortly researched, is between 4Space's very high thermal level modifier values and the changes to checkThermalStatus().

**Comment by radfast** [comment] 2016-01-18 19:46
4Space should update itself to keep in line with Galacticraft, the parent mod.  Although we welcome players using Add Ons, I'm not going to code Galacticraft in a way that fixes a 4Space-specific problem, if that limits the ways that other Add On authors might want to use the systems.

I'm hoping that based on what @zapl did, someone can find a coding solution here which works for everyone.  I'm also hoping that that 'someone' doesn't have to be me - if I spend time on this type of thing it's taking time away from feature development.
