### ISSUE TITLE
Oxygen Collectors and Sealers - Server side issues

### ISSUE THREAD

**Issue by XeenRecoil** [micdoodle8/Galacticraft#1381] opened 2015-01-14 22:38 UTC
Hello

I have Minecraft 1.7.10 and GC version 3.0.6 and am experiencing what I can only describe as a catastrophic bug, I hate to sound dramatic but it's bad enough that it renders the GC mod unplayable.
Oxygen collectors and sealers break and start lagging the server and I mean huge amounts of lag on the order of 30 seconds or more when multiple machines bug simultaneously, I know this because Opis has been used to identify the problem.
I have tried using several different power delivery systems thinking that there may be an incompatibility issue, I have used Mekanism cables, Ender IO power and cables, Thermal Expansion power, and Solar Flux power, the issue happens with all of them so I'm convinced that either these machines are just flat broken or are incompatible with everything.
I can't believe that NO ONE but the server I play on is experiencing these issues, but I can't find any similar reports.

**Comment by radfast** [comment] 2015-01-15 01:49
These machines do not lag in my test builds on up to 120 machines with profiler running.  No other player has reported a similar issue.  So that we can investigate further.  Please provide
* exact Forge, Galacticraft and Java versions you are using
* full server log covering the period when this happened
* screenshots of the setup which you tested, so that I can understand & reproduce wiring and pipe connections
* Opis output showing the lag issue which you are referring to
* Details of any other test you have carried out to identify or isolate the cause of the problem

**Comment by radfast** [comment] 2015-01-15 01:52
Also you should have tested the latest GC build before posting an issue, please do that now.

**Comment by XeenRecoil** [comment] 2015-01-15 03:10
@thatcraniumguy is the server owner he will have to contribute the server infor, logs and Opis output.

**Comment by radfast** [comment] 2015-03-01 12:49
Any update guys?

**Comment by radfast** [comment] 2015-04-07 10:26
My guess is this could be a situation of this: http://wiki.micdoodle8.com/wiki/Sealed_Space#Constant_updates_between_sealing_and_unsealing

I'll leave this open for 1 more week (also as a reminder to myself to add the penalty system mentioned on the wiki) then will close this if there is no update.

**Closed** 2015-10-17 16:18 UTC
Labels: missing info
