### ISSUE TITLE
Issue when creating worlds with mods

### ISSUE THREAD

**Issue by JoshS1991** [micdoodle8/Galacticraft#2103] opened 2016-02-21 08:47 UTC
Hi, I am currently running the galacticraft mod on a 1.7.10 version of minecraft and cant seem to get it to work.

I installed the mod through forge and created the world, it is saved in the single player world list. However when I attempt to open the world I keep getting an error message saying "Shutting down internal server...", also I've got an error log with this.

Attached to this is the error report,

Thanks in advance for any help with this issue.

[21.2.16 galacticraft crash report.txt](https://github.com/micdoodle8/Galacticraft/files/139525/21.2.16.galacticraft.crash.report.txt)
_

**Comment by radfast** [comment] 2016-02-21 14:14
Duplicate of #619 and #1657.

Is your Search button not working?  (Rhetorical question, don't answer)

If you search Google you can also see the same issue being reported with other mods over the last 2 years, and maybe with vanilla Minecraft.

Theories are:
* It's something messed up in your vanilla installation of Minecraft, [this guy](https://github.com/BuildCraft/BuildCraft/issues/2460) says he fixed it by re-downloading Minecraft
* It's connected with your view distance, try turning the render distance down to 6 chunks or 8 chunks - you can access this in ```.minecraft/options.txt``` even without starting the game
* It's connected with your graphics driver or the OpenGL settings on your graphics card - looks like you have an Intel card so take a look at the OpenGL settings and search up what is recommended for Minecraft
* It's connected with your Java version or Java file locations - especially if you recently updated Java.

One thing I'm fairly sure of: it's not a Galacticraft issue.

Separately from all that: **you should be using Galacticraft 3.0.12.443, not 375**.

**Closed by radfast** 2016-02-21 14:14 UTC

**Comment by MCOfficer** [comment] 2017-01-01 11:44
just in case anyone else comes here via samebug - someone else solved it by deleting his options.txt
