### ISSUE TITLE
GC food not respecting HungerOverhaul

### ISSUE THREAD

**Issue by JasonMcRay** [micdoodle8/Galacticraft#1390] opened 2015-01-18 15:57 UTC
Galacticraft food is not respecting HungerOverhaul changes to saturation and hunger refil.
HungerOverhaul uses AppleCore api, which is used to change the food values: https://github.com/squeek502/AppleCore/blob/master/README.md

**Comment by radfast** [comment] 2015-01-18 19:01
Duplicate of #1215, I think

**Closed by radfast** 2015-01-18 19:01 UTC
