### ISSUE TITLE
[Finder Compass] Random Crash on Moon

### ISSUE THREAD

**Issue by JasonBourne007** [micdoodle8/Galacticraft#3183] opened 2018-02-22 05:04 UTC
I just went to a new creative world to test out galacticraft, to make sure it works. Everything went fine up until I started my decent on to the moon. Then it started "shutting down internal server" due to a "fatal error", and would put me in the multiplayer screen in the main menu. 

Whenever I crash, I don't have any lag or frame drops or anything. In fact the last time it crashed, I had over 500 frames. Everything was super smooth, and then, boom. Shut down. But I don't think it was an official crash becuase it didn't kick me to the launcher, or give a crash report. Just put me in the main menu. 

So here is the most recent Log File I have. I dragged the file itself into this post becuase the Log was too long. I hope this helps, and that you can see it.

Thank you.

VERSIONS:
Minecraft - 1.12.2
Forge - 1.12.2-14.23.2.2618
GalacticraftCore - 1.12.2-4.0.1.139
Galacticraft-Planets - 1.12.2-4.0.1.139
MicdoodleCore - 1.12.2-4.0.1.139

LOG FILE:

[latest.log](https://github.com/micdoodle8/Galacticraft/files/1746668/latest.log)

**Comment by MJRLegends** [comment] 2018-02-22 05:05
You need to include the crash log as that contains the needed info

**Comment by TheQuadShot** [comment] 2018-02-22 05:34
Try this, remove the Finder Compass mod and try again. It's a known issue and there are 2 bugs filed on it. In the future please search the db prior to filing. Then you can add your log/issue or new information on the issue. Thanks!

**Comment by radfast** [comment] 2018-02-22 11:50
Duplicate of #2932 and #3176.   The bug is in Finder Compass, not our mod - please report it to that mod's developer.  (Finder Compass crashes in any dimension which does not have Strongholds.)

As **TheQuadShot** says, remove the Finder Compass mod and everything should be good.

**Comment by JasonBourne007** [comment] 2018-02-23 01:44
Okay, that seemed to have worked. Thank you so much!

**Comment by radfast** [comment] 2018-02-23 02:47
Further investigation shows that there is a bug in Galacticraft linked to this, which is fixable.

A new Galacticraft build 140 will be released this weekend with the fix.

**Comment by radfast** [comment] 2018-02-23 22:30
Fix now coded in, look for build 140 later tonight.

**Closed by radfast** 2018-02-23 22:30 UTC
Labels: duplicate
