### ISSUE TITLE
[1.10.2] Astro Miner mines it's own base

### ISSUE THREAD

**Issue by tabepic** [micdoodle8/Galacticraft#2593] opened 2017-04-15 19:05 UTC
I'm unable to reproduce this, but once or twice I've set up an Astro Miner, and when it started to mine it went straight down, without going forwards. When it came back from mining, it came straight back up, and then "mined" it's own base.
I can't figure out how the Astro Miner's logic works though, so I can't get it to mine straight down again (to reproduce the bug)
GC Build 63, trying to reproduce in Build 64

**Comment by radfast** [comment] 2017-04-15 23:14
It was slightly bugged in build 63.   Should be OK in build 64.

Intended behaviour (on planets) is it travels around 30 blocks horizontally out from its base then it descends to mining depth.  It basically does this so as not to make holes in the floor of your beautiful base.

There was a bug in build 63 where depending on the direction the base was facing, in 2 directions (east and north) it started the wrong way for mining.  There's also logic which prevents it ever mining "behind" its own base, and therefore it travelled straight down.

Pretty sure this is fixed in build 64, it mines correctly in all 4 directions.  Therefore I will close this.  Please re-open if you notice any problems in 64.

>  it then "mined" it's own base

Do you mean it destroy stone and dirt and other supporting blocks (basic blocks) around its base, or it actually destroyed the yellow Astro Miner Dock?  It should be **totally impossible** for it to mine its own Astro Miner Dock or any other machines or similar.  It's very robustly coded not to do damage.  OK, not nuclear power plant robust, but you shouldn't ever see this happen.

The main issue with the Astro Miner I'm still aware of is that (like any other Minecraft entity) it will stop moving and stop mining if it enters an unloaded chunk ... because it gets unloaded too, of course.  This isn't usually a problem on planets because it doesn't mine too far away from its base, but it's a problem in the Asteroids where it moves faster and can travel quite far, it can easily go 200 blocks away or more in the Asteroids.  I may have a solution to this...

**Closed by radfast** 2017-04-15 23:14 UTC

**Comment by tabepic** [comment] 2017-04-15 23:57
If I can remember correctly, then yes it did actually mine the dock.
It may have also just came up beneath the base, complaining that the dock was in the way.
However, I've been using the Astro Miner in similar conditions now, and the issue didn't some back, so I believe it's been fixed now.

**Comment by radfast** [comment] 2017-04-16 00:02
>  It may have also just came up beneath the base, complaining that the dock was in the way.

This is exactly what it should do.  I think I'm going to assume, here, that that's what it did for you in 63 :)

"In the way" means it's a block which for safety reasons the Astro Miner cannot mine.  The AstroMiner AI, while very good in a lot of ways, is not smart enough to re-route to go around a block which is blocking its path.  

In build 63, I also noticed that a few times when it went "straight down", it made a mineshaft _directly_ beneath its own base and therefore it had the appearance of travelling through the floor of its base, in an impossible way.    That looked wrong, and I think this maybe helped your sense that it was doing something it should not do!
