### ISSUE TITLE
Oxygen Tank/Gear Damage

### ISSUE THREAD

**Issue by paduser** [micdoodle8/Galacticraft#2096] opened 2016-02-19 21:13 UTC
Got the following issue since im on 1.7-3.0.12.442

1. remove full oxygen tanks from gear.
2. add full oxygen tanks to gear
3. jump or walk out of oxygen bubble on the the moon
4. get the warning message for 1 second and get damage

Also the status of the oxygen tanks in the right corner doesen't refresh until you walked out of the bubble the first time.

**Comment by radfast** [comment] 2016-02-19 21:20
thanks for reporting, I'll take a look

**Comment by dj3520** [comment] 2016-02-20 01:14
Duplicate of #2043

**Comment by paduser** [comment] 2016-02-20 10:57
> Duplicate of #2043

Yes looks like its the same problem. But radfast said:
> This issue is fixed in build 441 now available.

I'm playing on 442 and still got the issue.

**Comment by dj3520** [comment] 2016-02-21 01:25
Then the correct methodology of reporting this issue would have been to say that the problem still exists when using 442 on the already existing thread. That way there isn't two issue reports for the  same issue. [As per the contributing guidlines](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) you agreed to when posting a new issue: 
>Do not duplicate known issues: do a search first. Check the closed issues also: maybe somebody already posted your issue and a fix was found.

Reporting the issue persists in the report that already existed would have re-opened it.

**Comment by radfast** [comment] 2016-02-21 01:39
I'm happy with @paduser opening a new issue.  To me, it can be considered a different issue because I think the previous issue was fixed.  Could be it's a different issue entirely, could be the fix isn't working properly.

**Comment by dj3520** [comment] 2016-02-21 01:45
I would test 441 & 442 to see if it reappeared, thought chaos would surely break out on my testing server due to #1702. I do a lot of long term power testing and attempts at finding infinite energy setups.

**Closed** 2016-02-21 01:56 UTC

**Comment by SteveKunG** [comment] 2016-02-21 05:53
@radfast Please re-open this because I getting damage when equip oxygen tanks.
![2559-02-21_12 53 15](https://cloud.githubusercontent.com/assets/6128413/13201210/14d1ed72-d89a-11e5-832c-3b1aada4c15d.png)

Using Eclipse for testing.

**Comment by dj3520** [comment] 2016-02-21 05:57
@SteveKunG I can see in your oxygen GUI that both tanks attached to your back have oxygen in them. The specific problem is that adding tanks has them momentarily treated as empty until something updates them. _They will show as empty even in the player's on screen display._ Your screenshot says otherwise. This looks like something else, unless your screenshot was a bit late.

**Comment by SteveKunG** [comment] 2016-02-21 06:03
Oops. My idiot sorry.

**Comment by paduser** [comment] 2016-02-21 12:44
For me everything works now fine with 1.7-3.0.12.443. Thanks guys

@dj3520 sorry that I opend a new issue. It's my fist week here so im still learing.

**Comment by radfast** [comment] 2016-02-21 14:23
@paduser - it was totally fine to open this new issue.
