### ISSUE TITLE
Crashing after loading world.  1.7.10

### ISSUE THREAD

**Issue by THISTEXT** [micdoodle8/Galacticraft#2482] opened 2017-03-28 10:08 UTC
https://pastebin.com/kiha2zgJ

This should be using the latest version of forge 1.7.10 and latest version of the mod.

**Comment by radfast** [comment] 2017-03-28 10:23
duplicate of #2311 #2162 

this is vanilla minecraft crashing, not Galacticraft

The reason is your **view distance** is too large for 1.7.10.
Most likely because you played Minecraft 1.8, 1.9, 1.10 or 1.11 then switched back to 1.7.10.  Minecraft later versions have longer view distances.

You can fix it easily by editing the `options.txt` file in your `.minecraft` main folder.  Look for a line like this:

>     renderDistance:32

change it to something like 12 or less

**Closed by radfast** 2017-03-28 10:23 UTC

**Comment by radfast** [comment] 2017-03-28 10:35
[Now added to the wiki](https://wiki.micdoodle8.com/wiki/Tutorials/Galacticraft_Installation_Guide#Minecraft_crashes_with:-_java.lang.IndexOutOfBoundsException)
