### ISSUE TITLE
Issues when trying to start a Multiplayer Server

### ISSUE THREAD

**Issue by Oscareaston** [micdoodle8/Galacticraft#1931] opened 2015-11-09 14:35 UTC
![galacticraft error](https://cloud.githubusercontent.com/assets/15731285/11036214/150196aa-86ef-11e5-90ed-b26ee1b7d8bc.png)

I keep getting this message when trying to start a multiplayer game on Galacticraft... any ideas?

**Comment by dj3520** [comment] 2015-11-09 17:14
This is switching a single player to LAN server, right? If so no clue. A
log might help.

**Comment by MJRLegends** [comment] 2015-11-15 20:11
Your client side mods and server side mods not match up, you need to have the same mods and same versions of the mods on both sides.

**Comment by radfast** [comment] 2016-01-04 01:07
Thanks to @MJRLegends for providing the solution.

This is not a bug in Galacticraft.  I am closing this.

**Closed by radfast** 2016-01-04 01:07 UTC
