### ISSUE TITLE
1.7.10 Crude Oil not acting like a liquid

### ISSUE THREAD

**Issue by poke454** [micdoodle8/Galacticraft#1734] opened 2015-06-21 16:00 UTC
When ever I stand in crude oil, I can't swim & I don't get a breath meter.
The crude oil also randomly drops crude oil items & doesn't go in a bucket

**Comment by EzerArch** [comment] 2015-06-21 19:50
> When ever I stand in crude oil, I can't swim & I don't get a breath meter.

I'm almost sure this always worked like this, although I'd expected this as well.

>  The crude oil also randomly drops crude oil items

Can't reproduce, never seen. In which situation does this happen?

>  & doesn't go in a bucket

You are supposed to use the Oil Extractor. Since it's a liquid, I would support the idea of implementing an Oil Bucket as long as it is way less effective/efficient than the Oil Extractor.

**Comment by dj3520** [comment] 2015-06-21 20:02
Since crude oil is supposed to be almost a copy of Buildcraft's oil, a
bucket should really only work if another mod uses that method, such as
Buildcraft

**Comment by radfast** [comment] 2015-06-22 00:58
> When ever I stand in crude oil, I can't swim
Try that IRL, tell us what happens

> & I don't get a breath meter.
Duplicate of #1623, please search before posting

> The crude oil also randomly drops crude oil items
No it doesn't, not in my testing anyhow.  If you provide screenshots or video evidence, I will happily re-open this issue.

> & doesn't go in a bucket
@EzerArch was already kind enough to answer this.  I'll add that buckets are not much use in space.

**Closed by radfast** 2015-06-22 00:58 UTC
