### ISSUE TITLE
Power transfer through Sealed Golden Kinesis Pipe

### ISSUE THREAD

**Issue by kyetan21** [micdoodle8/Galacticraft#1402] opened 2015-01-24 11:19 UTC
Not a crash but i cant seem to get power to transfer through the sealed golden kinesis pipe

I have a Big reactor setup connected to the new Ender IO Capacitor Banks.
From there tried connecting directly to the kinesis pipe with ender io conduit Would not connect
Mekanism Universal cable also wont connect

Then I tried using a BC Kinesis input pipe that will connect to both ender io conduit and universal cable,
But no power passes though the cable.

I have a Mekanism Power cube on the other end, but the usual green of power going through the universal cable is not present after connection to a kinesis pipe, or the appearance of power into the kinesis pipe.

THe only power transfer that i actually saw was using wooden input connected to gold, but would not transfer through the sealed kinesis.

I think it might be a overload of power being sent through my higher power tier conduits and cables
But not being able to use the emerald input pipe connected to golden instead of wood connected to golden. Uhg this seems more like a BC pipe issue.

Suggestion any chance of a sealed universal cable connection or ender io conduit connection?

https://www.dropbox.com/s/gtbjuclbfdp0qsq/Screenshot%202015-01-24%2002.57.55.png?dl=0

https://www.dropbox.com/s/7n8pdm3fzwk3enh/Screenshot%202015-01-24%2002.58.22.png?dl=0

https://www.dropbox.com/s/vlfuy7d476hi9jr/Screenshot%202015-01-24%2002.58.35.png?dl=0

**Comment by radfast** [comment] 2015-01-24 16:22
Related to #1393 

We'll be looking at fixing both issues together.  Meanwhile please use a block - for example, Energy Storage Module - at the place which needs to be sealed.

**Comment by kyetan21** [comment] 2015-01-24 17:49
Had to use the energy storage cluster, the module would connect but not allow power to be recieved or transfered, but the cluster allows for the high end power connectors.

You sir have been a life saver since i now see that the clusters can be connected to alum walkways

Thank you

**Comment by micdoodle8** [comment] 2015-03-29 06:28
Hey, can you test with the latest build of Galacticraft and Buildcraft? Seems as though I'm able to place them without issue:

![](http://i.imgur.com/d7pT9Q5.png)

**Comment by micdoodle8** [comment] 2015-05-07 22:16
Closing, reopen if anyone can confirm this is an issue.

**Closed by micdoodle8** 2015-05-07 22:16 UTC

**Comment by GmanAtheist** [comment] 2016-08-23 17:51
OK. So, I have a major problem in MC 1.7.10 . Galacticraft sealable Golden kinesis pipe disapears on first place and stays on second place, but will not connect to any pipe, Mekanism, Buildcraft or EnderIO.  I am using latest builds for MC 1.7.10 . Can anyone give me some good advice to fix this problem please. 
![snag-0000 23-08-2016 18 46 51 james1](https://cloud.githubusercontent.com/assets/5624207/17903230/9484f100-6962-11e6-9f14-8666b3516c3c.jpg)

**Comment by dj3520** [comment] 2016-08-23 18:44
Duplicate of #2208
