### ISSUE TITLE
Display screens lose their overview map after any edit

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#1665] opened 2015-05-23 16:18 UTC
Display screens will lose their overview map if you right-click on or break them. Reloading world most of times fix it.

![2015-05-23_13 12 51](https://cloud.githubusercontent.com/assets/6743303/7784894/115c0502-014e-11e5-9d05-5a7c81de8094.png)
![2015-05-23_13 13 02](https://cloud.githubusercontent.com/assets/6743303/7784893/1159d7b4-014e-11e5-9738-99d40b4c329f.png)

**Comment by radfast** [comment] 2015-05-23 19:58
Display Screens are a work in progress, there will be significant changes soon.  The map is really a placeholder just to show the Display Screen is working.

**Comment by radfast** [comment] 2016-02-13 03:47
This issue is fixed in new build 442.

There are many changes to the mapping - some still to come.

The current intended behaviour for Display Screens on the Overworld is to show a map which is different from the vanilla map.  It is supposed to be an "aerial view" of the world, from so high up that individual blocks are not shown but giving an accurate idea of overall terrain coloring.  These aerial views will in future be used as part of the Overworld launch sequence.

The Display Screen, for now, gives:
* on the Overworld, a preview of that "aerial view"
* on all other dimensions, a preview of a rotating Overworld [Work in Progress]

In future it is planned for the Display Screen to show two maps:
(1) in all dimensions, a local map similar to the vanilla Map item (and similar to the map shown in most mapping mods, which is also based on the vanilla Map)
(2) on the Overworld and Overworld Space Stations, a "satellite view" of a large area of the Overworld similar to the "aerial view" you are currently seeing but even more zoomed out.  This zoomed out map can be useful if you are playing in survival, for example it will help you to find Desert, Swamp or Jungle biomes which are all fairly rare in Minecraft 1.7.10.

Details of the "aerial view" map (current implementation)
* On the Overworld only, the Display Screen currently shows you a medium-scale local map, centered on the Display Screen's actual location
* The map is a detailed image with scale 1 pixel = 2x2 blocks.  It covers an area of 704x704 blocks, that is much larger than the vanilla map and well beyond the player's view distance.
* The map draws forests, deserts and similar biomes (including the icy biomes) in a stylised way, meaning the dark green pixels for trees do not correspond to actual tree positions - the green pixels for cactus in deserts do not correspond to actual cactus locations and in a roofed forest, the red/brown pixels for mushrooms do not correspond to actual mushrooms.
* Worldgen 'final decoration' features including water and lava pools, small sandy beaches, canyons, caves, and structures (such as temples and villages) are **not** shown.  It might be possible in future to add some of these - maybe the structures - in a stylised way.
* Player-built structures and farms - or any player-made changes to the map at all - are **not** shown.  This is not likely ever to change for these "aerial view" maps, it would place an impossible load on the server to map every block.
* If the player can see multiple Display Screens in his frustum, all screens will show the exact same map image.  So the map will be centered on the location of one of the screens, normally the last one built so it's not necessarily the one closest to the player - it could be 50+ blocks away from the player's current location.
* For this reason, it is occasionally possible for different players to see (slightly) different maps on the same screen tile - if one player turns his head so that he has different screen tiles in his frustum, that could change the map shown.
* The map is always drawn with North at the top (even if the screen is in some other orientation)
* The map can take a short time to generate - sometimes instant, sometimes up to 20 seconds.  While it is generating, the rotating Overworld image is shown.

The rotating Overworld image - shown on Display Screens in other dimensions - takes a long time to first generate, around 6 minutes when a world is first created or after updating to GC 442.  It generates slowly, a small amount each tick - if the server stops before the image is fully generated then it will try to generate it again the next time the server starts.  So during this first 6 minute period you will see the default flat Overworld image on Display Screens.  Once the rotating Overworld image has been generated, it is saved on the server.

What is actually going on is that the server is mapping the whole world (!) covering an area of 24576 x 6144 blocks.  (Possibly I will increase this to 24576 x 24576 blocks in future.)  A small scale map of the whole world is being prepared and saved, it will be used in future.  The "rotating Overworld" texture is based on the actual world map, so its oceans and continents correspond to the actual positions of oceans and continents in your game.

This will all make most sense on servers which set the world border at around 10,000 blocks or 12,000 blocks maximum.  It will also make sense in single player, as 99.9% of players in single player do not go that far away from spawn.

For people who like to break stuff and make their bases 100,000 blocks out from spawn, they will have a situation where any of the small scale maps in Galacticraft (the most zoomed out world maps) will show the world around spawn instead of the current location.  Not really a big deal.

**Closed by radfast** 2016-02-13 03:47 UTC
