### ISSUE TITLE
[1.10] [Lag] Issues with Rocket Launch

### ISSUE THREAD

**Issue by ErnestoPeroPezzi** [micdoodle8/Galacticraft#2569] opened 2017-04-12 00:49 UTC
1. Tested on Tier 1 and 3 creative pre-fuelled rocket: Rocket refused to fly after the "get a parachute or no backing out) even thought I kept trying to launch. Putting a parachute in my inventory made the message disaply again (only on tier 1 rocket however, message did not display on tier 2), but allowed me to launch.

Also, the tier 3 rocket doesnt have particles shooting out during the countdown.

2. Tested on Tier 1 and 3 creative pre-fuelled rocket: After launching, rockets fly up as normal. However, upon reaching height 1200 or so, the rocket dissapears, and the player starts falling. Tested 5 different times with different rockets, different worlds and in singleplayer and creative. After falling to the Earth, the camera constantly hiccups until I quit to the title screen.

After going back into the save I just left, one of two things occurs: Either the rocket noises play all around me, but everything else is normal, or I find myself back in the rocket at around the halfway mark of ascent, with the rocket flying diagonally this time, and the rocket despawns at the 1200 mark, however this time I remained glitched out in the air instead of falling. Gyazo link so you can see what happened after the rocket dissapears.

[https://gyazo.com/d26ec52c3dca8be6005b550cab6a11f9](url)

https://gyazo.com/d26ec52c3dca8be6005b550cab6a11f9

Keep up the good work guys :)

**Comment by tabepic** [comment] 2017-04-12 01:27
I have seen something similar, although for me the player falls for a bit, and then the Galanticraft planets menu comes up like normal.

**Comment by radfast** [comment] 2017-04-12 03:14
All in singleplayer?  Or some of these tests were on a server?

You can switch on "Enable debug message = true" in Galacticraft core config, that might have something helpful.  The ```fml-server-latest.log``` is the most interesting.

**Comment by tabepic** [comment] 2017-04-12 03:28
I don't see a `fml-server-latest.log`, however there is `latest.log` and `fml-client-latest.log`

**Comment by tabepic** [comment] 2017-04-12 03:30
The only thing in latest.log that happens at that time is possibly a `Can't keep up! Did the system time change, or is the server overloaded? Running XXXXms behind, skipping XX tick(s)`

**Comment by ErnestoPeroPezzi** [comment] 2017-04-12 05:21
All tests are in singleplayer running forge 12.18.3.2254

None of the issues I mentioned persisted when only Galacticraft was running.

I ran Galacticraft with the debug config on my modpack with no results.

My Modlist:
https://pastebin.com/RqVuvQdg        

Just to mention, this issue was not present with 

One last thing of note, I removed UpDownandAllAround and tested without it in my modpack, it was not the cause. 

Keep up the good work its just update after update I'm lovin it

**Comment by radfast** [comment] 2017-04-12 10:41
> None of the issues I mentioned persisted when only Galacticraft was running.

We need your help please, to figure out which of these other mods + Galacticraft results in the issue.
I am not set up to test all these different mods.  (It's near impossible to test a large modlist in a development environment.)

**Comment by tabepic** [comment] 2017-04-12 14:09
It's hard to test for me because it only happens once in a while, so I could change mods but I can't be sure the problem is gone. In fact when I first seen it I thought it was just lag.

**Comment by ErnestoPeroPezzi** [comment] 2017-04-12 21:55
Half half method. I narrowed it down to CompatLayer. Removing it solved it.

I tried again with my original modpack. This time, removing Compat Layer (and all of Mcjty's mods) did not solve the issue.

I tried again and narrowed it down to Baubles causing it. Removing both baubles and CompatLayer in my original modpack did not solve the issue.

Im starting to feel that maybe theres no singular cause to this. The only time it works properly is when there are either no mods or non-core mods. 

Im just going to hope the next release indirectly solves this issue.

**Comment by radfast** [comment] 2017-04-12 23:48
thank you, it sounds like we're close

if you can give me a set of, say, 4 mods which together cause the problem, I can put those together in a development environment and apply some breakpoints and stacktraces to figure out what is going on.

which mods still **did** work OK, when you said you "solved it" by removing CompatLayer?  (and same question for Baubles).  At least we can rule out all of those as being causes, I think?

**Comment by ErnestoPeroPezzi** [comment] 2017-04-13 01:59
I didnt have much time to test things today, but I tried some of them in samples and Rockhounding Rocks also caused it.

When i "solved it" I had nothing running except galacticraft, JEI, Journeymap and Compatlayer/OneProbe. Taking out OneProbe/compatlayer got rid of the issue, yet taking them out in my original pack yielded no results.

If you are not fed up by this yet I will keep testing tommorow haha

Keep up the good work

**Comment by radfast** [comment] 2017-04-13 02:45
Just to be clear: are you saying that this combination of 4 mods **has** the issue:
1. Galacticraft (build 63)
2. JEI
3. Journeymap
4. Compatlayer/OneProbe.

If that combination **has the issue**, please give me the **exact** versions of JEI, JourneyMap and Compatlayer/OneProbe you are using and I can do some tests here.

I know that you want to figure out how to make the issue go away, but I approach this differently: I want to know how to make the issue occur!!!

**Comment by ErnestoPeroPezzi** [comment] 2017-04-13 04:14
Apologies if I phrased that badly, but that is not what I meant. I meant taking OneProbe/Compat off that list fixed it.

I ran some more tests when I should have slept instead and I think I figured it out.

I played with nothing loaded except Galacticraft and OneProbe/Compat. Everything worked perfectly fine.
Afterwards, I added some other mods i had deemed "safe" (which had not caused problems). 

The issue manifested itself again. However, after going to the title screen then loading the world again, The rocket is shown to be halfway in its ascent, and when it reaches the top, I see my character in that glitchy warped state for a half second before the Solar System opens up.

This leads me to two conclusions;

The issue is not caused by any particular mod, and is instead caused by the system not responding fast enough (hence why relogging makes it work and the "Can't keep up!" warnings in the log). I take it once the rocket reaches (presumtively) 1200, the player gets suspended in place while you choose where to teleport to. However, if the system is too slow, the rocket despwans, the menu does not open up, and the player is instead shown to fall back to the Earth.

Or my computer is just totally screwed because this many mods should not be causing the same issue.

I hope that helped. cheers

**Comment by tabepic** [comment] 2017-04-13 04:17
That's what I thought before; that the issue is simply lag.

**Comment by ErnestoPeroPezzi** [comment] 2017-04-13 04:28
ditto :/

For me the player falls all the way down and since I was creative , I couldn't tell the blocks i broke were lagging because theres no drops in creative.

**Comment by radfast** [comment] 2017-05-04 00:11
- The "player falling all the way down" issue is fixed from build 80

- The "rocket disappears at height 1200" issues is fixed from around build 78 I don't remember which - behaviour now is that the rocket will keep on flying upwards, on the client, indefinitely, while it waits for a lagging server to catch up

- I think the other issues described in the first post were likely caused by pressing the SPACEBAR too quickly.  Currently rockets will only launch correctly if the SPACEBAR is pressed, then wait ~1 second, then press the SPACEBAR a second time.  I'm aware of this issue and looking for a fix.

Because these issues are basically fixed now, I am closing this.

**Please re-open** or comment if you are still seeing problems with the latest builds 80+

**Closed by radfast** 2017-05-04 00:11 UTC
Labels: conflict - large modlist
