### ISSUE TITLE
HELP! WHEN IM PLAYING TO AN WORLD THIS CRASH REPORT HAPPENS:

### ISSUE THREAD

**Issue by Andreaslag** [micdoodle8/Galacticraft#2311] opened 2016-10-31 12:07 UTC
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 31/10/2016 2:02 μμ
Description: Unexpected error

java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Unknown Source)
	at java.nio.DirectIntBufferU.get(Unknown Source)
	at net.minecraft.client.renderer.RenderGlobal.func_72712_a(RenderGlobal.java:350)
	at net.minecraft.client.renderer.RenderGlobal.func_72732_a(RenderGlobal.java:294)
	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2216)
	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2146)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:240)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:70)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:13)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.nio.Buffer.checkIndex(Unknown Source)
	at java.nio.DirectIntBufferU.get(Unknown Source)
	at net.minecraft.client.renderer.RenderGlobal.func_72712_a(RenderGlobal.java:350)
	at net.minecraft.client.renderer.RenderGlobal.func_72732_a(RenderGlobal.java:294)
	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2216)
	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2146)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:240)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:70)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:13)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Affected level --
Details:
	Level name: MpServer
	All players: 0 total; []
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 0 total; []
	Retry entities: 0 total; []
	Server brand: ~~ERROR~~ NullPointerException: null
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 141440832 bytes (134 MB) / 310960128 bytes (296 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.463.jar) 
	UCHIJAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.463.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1151.1008' Renderer: 'AMD Radeon HD 5700 Series'
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 5700 Series GL version 4.5.13399 Compatibility Profile Context 15.201.1151.1008, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by EzerArch** [comment] 2016-10-31 16:23
Isn't it cool that people don't bother giving details of "what you're doing" or "when it happens" or any info to help debug the mod but just barely post an error log as if they say "my car is broken, fix it"?

**Comment by dj3520** [comment] 2016-10-31 22:57
@EzerArch Technically `WHEN IM PLAYING TO AN WORLD THIS CRASH REPORT HAPPENS` is better than nothing but other than that I see your point. Added to the all caps and crash report in the post instead of on pastebin or an alternative, it reminds me of the [contribution guidelines.](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md)

1.7.10 with 1614 forge, GC v463 with no other mods. Not seeing GC in the stacktrace, however `Time: 31/10/2016 2:02 μμ` stands out to me.

**Comment by EzerArch** [comment] 2016-10-31 23:16
> 1.7.10 with 1614 forge, GC v463 with no other mods. Not seeing GC in the stacktrace, however Time: 31/10/2016 2:02 μμ stands out to me.

Just saying: I have also that java.lang.IndexOutOfBoundsException with no GC in the stacktrace every time I ride a rocket from SS dim to the Overworld. Never reported it because I think it's another mod that is affecting GC and I'll have to test mod by mod until I find the culprit. Pain in the neck. :P

**Comment by dj3520** [comment] 2016-10-31 23:19
Yeah wasn't saying it was/wasn't GC's fault because of the stacktrace or not. Bit strange though since it's the only loaded mod in the crash report. Mainly just extracting info from it.

**Comment by Andreaslag** [comment] 2016-11-02 06:20
and so what is the problem?

**Comment by Andreaslag** [comment] 2016-11-02 06:21
?

**Comment by Andreaslag** [comment] 2016-11-12 13:41
I had More Planets Mod. I downloaded and my worlds crashed, but when i remove it, still my worlds crash.

**Comment by C1ffisme** [comment] 2016-11-14 21:04
@Andreaslag Does the crash still happen when you start a new world?

**Comment by radfast** [comment] 2016-11-20 14:00
Guys, seriously.

At the top of the screen is a box marked **Search**.  Type into this box any unique word from this crash report - for example DirectIntU.  Look at the Issues returned by the search.  You will see that this issue has been reported 5 times now.  It is not a Galacticraft issue, and it is fixable just by changing your graphics config settings in standard Minecraft.

Duplicate of #2162.

**Closed by radfast** 2016-11-20 14:00 UTC

**Comment by EzerArch** [comment] 2016-11-20 22:47
@radfast, not urgent:
> It is not a Galacticraft issue, and it is fixable just by changing your graphics config settings in standard Minecraft.

What in the config could be changed to fix the issue? Is it the view distance?

**Comment by radfast** [comment] 2017-03-28 10:36
@EzerArch it's the view distance in the vanilla config, not the Galacticraft config

I've now [added something to our wiki ](https://wiki.micdoodle8.com/wiki/Tutorials/Galacticraft_Installation_Guide#Minecraft_crashes_with:-_java.lang.IndexOutOfBoundsException) to cover this, hopefully a few people with this problem will find that.

**Comment by EzerArch** [comment] 2017-03-29 05:55
> it's the view distance in the vanilla config, not the Galacticraft config

This is no longer an issue. I used to get crashes every time I rode a rocket from SS to any another dim until the day both Optifine and GC got fixes. I commented about it here: https://github.com/micdoodle8/Galacticraft/issues/2459#issuecomment-286929465

**Comment by radfast** [comment] 2017-03-29 12:26
I think some people still get this crash, it does get reported every couple of months - and @ghost doesn't have Optifine here.  On one of the other threads, the person reporting the crash had a view distance of 32 chunks after playing Minecraft 1.11, which I think is definitely too much for 1.7.10 unless you have a godly graphics card.

**Comment by dj3520** [comment] 2017-03-29 18:31
I usually run with a view distance of 16 but can do 32 just fine with Optifine and GC (computer has gtx 1070.) Perhaps high viewing distances are fixed with Optifine?

**Comment by radfast** [comment] 2017-03-29 23:14
> unless you have a godly graphics card

It certainly depends on your graphics card.  With a large view distance, Minecraft reserves more memory in the graphics card internals for some basic buffers it uses, and I think the crash may be caused by the buffer length exceeding what a low-end or mid-range graphics card can manage.

The amount of space needed depends on the view distance **squared**.

I don't think Optifine makes any difference to this specific issue.

**Comment by dj3520** [comment] 2017-03-30 05:33
>I think the crash may be caused by the buffer length exceeding what a low-end or mid-range graphics card can manage.

I also still have my old 1gig HD5450, as well as MSI Afterburner which can read out and log VRam usage.
