### ISSUE TITLE
GalactiCraft on Curse?

### ISSUE THREAD

**Issue by AlexisLatias** [micdoodle8/Galacticraft#3207] opened 2018-02-28 02:10 UTC
This is a question on how can I get the mod to work with twitch since curse has merged with or bought by twitch, but my main question is.

Why isn't the mod on twitch, when I have the mod in the mod folder for curse, the game crashes after stage 2, can you guys add it to curse so it could work or do I have to mod another way?

**Comment by MJRLegends** [comment] 2018-02-28 02:11
Mod packs will still get approved if the galacticraft is there.

**Comment by radfast** [comment] 2018-02-28 02:30
If you're a player wanting to play Galacticraft, please go to our [Downloads Page](https://www.micdoodle8.com/mods/galacticraft/downloads).  The mod files can be downloaded from there, just the same way you download your other mods from Curse.  Actually it's probably **easier** to download our mod, because the page is good and clear, and all three needed files are given to you on one page.

If you're wanting to make a modpack, this is a part duplicate of #2031.  For as long as we are **not** on Curse, you are welcome to include a copy of Galacticraft in your own modpack's core download files **on** Curse - like MJRLegends said.  Hope that's clear.  See also https://wiki.micdoodle8.com/wiki/Modpack_Permission

**Closed by radfast** 2018-02-28 02:30 UTC
