### ISSUE TITLE
[1.11.2] Doing /kill on a gc dimension crashes the client

### ISSUE THREAD

**Issue by ThomasAunvik** [micdoodle8/Galacticraft#2512] opened 2017-04-07 21:38 UTC
[Crash Report](https://pastebin.com/VaTUCWwq)
Followed with a #2508

Forge Version: forge-1.11.2-13.20.0.2265
MicDoodleCore: 1.11.2-4.0.0.53-BETA
GalacticraftCore: 1.11.2-4.0.0.53-BETA
GalacticraftPlanets: 1.11.2-4.0.0.53-BETA

**Comment by MJRLegends** [comment] 2017-04-07 23:30
@micdoodle8 @radfast To try and help you fix this/make your lifes easier, it seems the game is making the extended inventory item slots null
```
java.lang.NullPointerException: The validated object is null
    at org.apache.commons.lang3.Validate.notNull(Validate.java:222) ~[commons-lang3-3.3.2.jar:3.3.2]
    at org.apache.commons.lang3.Validate.notNull(Validate.java:203) ~[commons-lang3-3.3.2.jar:3.3.2]
    at net.minecraft.util.NonNullList.set(SourceFile:45) ~[dd.class:?]
    at micdoodle8.mods.galacticraft.core.inventory.InventoryExtended.func_70299_a(InventoryExtended.java:64) ~[InventoryExtended.class:?]
    at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.onPlayerDeath(EventHandlerGC.java:785) ~[EventHandlerGC.class:?]
```

**Comment by ThomasAunvik** [comment] 2017-04-08 15:22
Another issue. Doing /kill in the overworld gives out exceptions
```
[17:21:15] [Server thread/INFO]: Thaun_ fell out of the world
[17:21:15] [Server thread/ERROR]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerDropsEvent@7a6c869b:
java.lang.NullPointerException: The validated object is null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:222) ~[commons-lang3-3.3.2.jar:3.3.2]
	at org.apache.commons.lang3.Validate.notNull(Validate.java:203) ~[commons-lang3-3.3.2.jar:3.3.2]
	at net.minecraft.util.NonNullList.set(SourceFile:45) ~[dd.class:?]
	at micdoodle8.mods.galacticraft.core.inventory.InventoryExtended.func_70299_a(InventoryExtended.java:64) ~[InventoryExtended.class:?]
	at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.onPlayerDeath(EventHandlerGC.java:785) ~[EventHandlerGC.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_47_EventHandlerGC_onPlayerDeath_PlayerDropsEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:499) [ly.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:990) [sw.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1040) [aay.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:571) [ly.class:?]
	at net.minecraft.entity.EntityLivingBase.func_174812_G(EntityLivingBase.java:156) [sw.class:?]
	at net.minecraft.command.CommandKill.func_184881_a(SourceFile:35) [an.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [k.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [k.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:904) [mi.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:883) [mi.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [ip.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [ip.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fo$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) [cch.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
[17:21:15] [Server thread/ERROR]: Index: 1 Listeners:
[17:21:15] [Server thread/ERROR]: 0: NORMAL
[17:21:15] [Server thread/ERROR]: 1: ASM: micdoodle8.mods.galacticraft.core.event.EventHandlerGC@6500d306 onPlayerDeath(Lnet/minecraftforge/event/entity/player/PlayerDropsEvent;)V
[17:21:15] [Server thread/WARN]: Couldn't process command: 'kill'
java.lang.NullPointerException: The validated object is null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:222) ~[commons-lang3-3.3.2.jar:3.3.2]
	at org.apache.commons.lang3.Validate.notNull(Validate.java:203) ~[commons-lang3-3.3.2.jar:3.3.2]
	at net.minecraft.util.NonNullList.set(SourceFile:45) ~[dd.class:?]
	at micdoodle8.mods.galacticraft.core.inventory.InventoryExtended.func_70299_a(InventoryExtended.java:64) ~[InventoryExtended.class:?]
	at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.onPlayerDeath(EventHandlerGC.java:785) ~[EventHandlerGC.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_47_EventHandlerGC_onPlayerDeath_PlayerDropsEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:499) ~[ly.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:990) ~[sw.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1040) ~[aay.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:571) ~[ly.class:?]
	at net.minecraft.entity.EntityLivingBase.func_174812_G(EntityLivingBase.java:156) ~[sw.class:?]
	at net.minecraft.command.CommandKill.func_184881_a(SourceFile:35) ~[an.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [k.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [k.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:904) [mi.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:883) [mi.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [ip.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [ip.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fo$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) [cch.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
[17:21:15] [Client thread/INFO]: [CHAT] Thaun_ fell out of the world
[17:21:15] [Client thread/INFO]: [CHAT] An unknown error occurred while attempting to perform this command

```

**Comment by radfast** [comment] 2017-04-08 17:02
This is likely caused by an issue in **micdoodlecore** which we know about out, please bear with us until we get the next version out which should clear up a lot of things like this.

**Comment by radfast** [comment] 2017-04-09 19:11
This is likely now fixed in version 58 - @ThomasAunvik please can I trouble you to re-test it?

**Comment by ThomasAunvik** [comment] 2017-04-09 21:42
Ok, doing /kill in the moon does not crash the client, but it still will give out the exception:
```
[23:37:07] [Server thread/ERROR]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerDropsEvent@55cb256d:
java.lang.NullPointerException: The validated object is null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:222) ~[commons-lang3-3.3.2.jar:3.3.2]
	at org.apache.commons.lang3.Validate.notNull(Validate.java:203) ~[commons-lang3-3.3.2.jar:3.3.2]
	at net.minecraft.util.NonNullList.set(SourceFile:45) ~[dd.class:?]
	at micdoodle8.mods.galacticraft.core.inventory.InventoryExtended.func_70299_a(InventoryExtended.java:64) ~[InventoryExtended.class:?]
	at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.onPlayerDeath(EventHandlerGC.java:785) ~[EventHandlerGC.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_18_EventHandlerGC_onPlayerDeath_PlayerDropsEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:499) [ly.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:990) [sw.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1040) [aay.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:571) [ly.class:?]
	at micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP.func_70097_a(GCEntityPlayerMP.java:83) [GCEntityPlayerMP.class:?]
	at net.minecraft.entity.EntityLivingBase.func_174812_G(EntityLivingBase.java:156) [sw.class:?]
	at net.minecraft.command.CommandKill.func_184881_a(SourceFile:35) [an.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [k.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [k.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:904) [mi.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:883) [mi.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [ip.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [ip.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fo$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) [cch.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
[23:37:07] [Server thread/ERROR]: Index: 1 Listeners:
[23:37:07] [Server thread/ERROR]: 0: NORMAL
[23:37:07] [Server thread/ERROR]: 1: ASM: micdoodle8.mods.galacticraft.core.event.EventHandlerGC@5afef53 onPlayerDeath(Lnet/minecraftforge/event/entity/player/PlayerDropsEvent;)V
[23:37:07] [Server thread/WARN]: Couldn't process command: 'kill'
java.lang.NullPointerException: The validated object is null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:222) ~[commons-lang3-3.3.2.jar:3.3.2]
	at org.apache.commons.lang3.Validate.notNull(Validate.java:203) ~[commons-lang3-3.3.2.jar:3.3.2]
	at net.minecraft.util.NonNullList.set(SourceFile:45) ~[dd.class:?]
	at micdoodle8.mods.galacticraft.core.inventory.InventoryExtended.func_70299_a(InventoryExtended.java:64) ~[InventoryExtended.class:?]
	at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.onPlayerDeath(EventHandlerGC.java:785) ~[EventHandlerGC.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_18_EventHandlerGC_onPlayerDeath_PlayerDropsEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:499) ~[ly.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:990) ~[sw.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1040) ~[aay.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:571) ~[ly.class:?]
	at micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP.func_70097_a(GCEntityPlayerMP.java:83) ~[GCEntityPlayerMP.class:?]
	at net.minecraft.entity.EntityLivingBase.func_174812_G(EntityLivingBase.java:156) ~[sw.class:?]
	at net.minecraft.command.CommandKill.func_184881_a(SourceFile:35) ~[an.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [k.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [k.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:904) [mi.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:883) [mi.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [ip.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [ip.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fo$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) [cch.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
[23:37:07] [Client thread/INFO]: [CHAT] Thaun_ fell out of the world
```

Now, after i tried killing myself in the moon without /kill i crashed. But this time it crashed the server
[A log just when i died](https://pastebin.com/xgKDDZTE)
[And the crash log](https://pastebin.com/tmdybJQr)

**Comment by ThomasAunvik** [comment] 2017-04-13 22:32
**Landing too hard with moon lander with full set** (Server Crash)
java.lang.NullPointerException: The validated object is null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:222)
	at org.apache.commons.lang3.Validate.notNull(Validate.java:203)
	at net.minecraft.util.NonNullList.set(SourceFile:45)
	at micdoodle8.mods.galacticraft.core.inventory.InventoryExtended.func_70299_a(InventoryExtended.java:64)
	at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.onPlayerDeath(EventHandlerGC.java:785)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_16_EventHandlerGC_onPlayerDeath_PlayerDropsEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:499)
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:990)
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1040)
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:571)
	at micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP.func_70097_a(GCEntityPlayerMP.java:83)
	at net.minecraft.world.Explosion.func_77278_a(Explosion.java:159)
	at net.minecraft.world.WorldServer.func_72885_a(WorldServer.java:1177)
	at net.minecraft.world.World.func_72876_a(World.java:2258)
	at micdoodle8.mods.galacticraft.core.entities.EntityLander.onGroundHit(EntityLander.java:220)
	at micdoodle8.mods.galacticraft.core.entities.EntityAdvancedMotion.func_70071_h_(EntityAdvancedMotion.java:357)
	at micdoodle8.mods.galacticraft.core.entities.EntityLanderBase.func_70071_h_(EntityLanderBase.java:110)
	at micdoodle8.mods.galacticraft.core.entities.EntityLander.func_70071_h_(EntityLander.java:49)
	at net.minecraft.world.World.func_72866_a(World.java:1963)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1932)
	at net.minecraft.world.World.func_72939_s(World.java:1748)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

**Comment by radfast** [comment] 2017-04-13 22:53
Thank you for the crash report!

This ```NonNullList``` type of issue is specific to 1.11.2, we should be able to fix it fairly easily.

**Comment by micdoodle8** [comment] 2017-04-16 06:10
Should be fixed in the next build, please re-open if not. Thanks!

**Closed by micdoodle8** 2017-04-16 06:10 UTC
Labels: 1.11 only

**Comment by radfast** [comment] 2017-04-16 12:48
[build 66 now available](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/#post-43135)
