### ISSUE TITLE
Possible TileEntity leak in TileEntityOxygenSealer

### ISSUE THREAD

**Issue by codewarrior0** [micdoodle8/Galacticraft#1569] opened 2015-04-12 02:57 UTC
In [`TileEntityOxygenSealer.onChunkUnload`](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/tile/TileEntityOxygenSealer.java#L70) (and possibly `.invalidate`), the TileEntity is added to the static list when the chunk is unloaded. I won't speculate on the consequences, but I can confirm that `TileEntityOxygenSealer.loadedTiles` contains over 700 elements when the game is at the title screen. 

![image](https://cloud.githubusercontent.com/assets/307683/7104208/d0bcd308-e06b-11e4-9190-6079e9eb9464.png)

**Comment by radfast** [comment] 2015-04-12 03:23
Thank you, this is useful.  I'll take a look.

**Comment by codewarrior0** [comment] 2015-04-12 12:29
Cool.

For what it's worth, I came across this while trying to answer the eternal question "Why aren't my oxygen sealers sealing?". I had 47 of them evenly spaced 10 blocks apart in a 79x79x9 area with a small scattering of pillars and loose blocks. It turned out the answer I was looking for was "The breadth-first search for blocks to seal wasn't extending far enough to find the nearest sealers (with 10 blocks separating the sealers, the search stops just one block short), so I would have seven sealers doing seal checks at once without finding each other." I don't think that answers this issue, though.

**Comment by radfast** [comment] 2015-04-12 12:49
Your "eternal question" sounds like intended behaviour.  Even spacing is not good with sealers, they need to be clustered near the centre of the room if it's a large room like that.
http://wiki.micdoodle8.com/wiki/Sealed_Space#Tips

I am looking at the issue.

**Comment by radfast** [comment] 2015-04-12 13:16
The issue was a straightforward typing error, must have been in the code for a year at least!  Now fixed, thank you!  This should produce a slight performance gain, probably not noticeable in practice.

**Closed** 2015-04-12 13:15 UTC

**Comment by codewarrior0** [comment] 2015-04-12 14:13
>Even spacing is not good with sealers, they need to be clustered near the centre of the room if it's a large room like that.
Oh, I understand why that's the case now. I'm giving it a try.

![image](https://cloud.githubusercontent.com/assets/307683/7105853/e8cadd70-e0c8-11e4-9678-0fe1140f828e.png)

...nope, still not sealing. I know I have enough sealers by volume. I should only need 37 and I'm using 45. They're all powered and fed. I took a clue from a comment in `ThreadFindSeal` and disabled all of them but one to make that one the "head" sealer... still not sealing. 

Here's some info from the console with GC logging on:

```
[04:03:06] [Server thread/INFO] [Galacticraft]: Oxygen Sealer Check Completed at x4 y65 z-1
[04:03:06] [Server thread/INFO] [Galacticraft]:    Sealed: false
[04:03:06] [Server thread/INFO] [Galacticraft]:    Loop Time taken: 0.359545ms
[04:03:06] [Server thread/INFO] [Galacticraft]:    Place Time taken: 3.569213ms
[04:03:06] [Server thread/INFO] [Galacticraft]:    Total Time taken: 3.928758ms
[04:03:06] [Server thread/INFO] [Galacticraft]:    Found: 29 sealers
[04:03:06] [Server thread/INFO] [Galacticraft]:    Looped through: 1121 blocks
```

A heap dump also shows the `ThreadFindSeal` with 29 in its `sealers`. It also shows one "Sealer Check Completed" for each of the remaining 16 sealers. Even though all but one are disabled. ~~I can't figure out why it's not finding all of the sealers.~~

Actually, here's something. Before, I had only the sealer in the corner enabled as the "head".  When I changed that to the sealer in the center, it started to find all 45 sealers:

```
[04:08:54] [Server thread/INFO] [Galacticraft]: Oxygen Sealer Check Completed at x8 y65 z-4
[04:08:54] [Server thread/INFO] [Galacticraft]:    Sealed: false
[04:08:54] [Server thread/INFO] [Galacticraft]:    Loop Time taken: 0.397787ms
[04:08:54] [Server thread/INFO] [Galacticraft]:    Place Time taken: 3.088943ms
[04:08:54] [Server thread/INFO] [Galacticraft]:    Total Time taken: 3.48673ms
[04:08:54] [Server thread/INFO] [Galacticraft]:    Found: 45 sealers
[04:08:54] [Server thread/INFO] [Galacticraft]:    Looped through: 1181 blocks
```

But it's still not sealing. Is the "Looped through" supposed to be that small?

**Comment by codewarrior0** [comment] 2015-04-12 14:45
Oh, I see. That comment was wrong. I can't actually disable the other sealers because then they return 0 from `getFindSealChecks`.

Scratch all that. Sealed now.

**Comment by codewarrior0** [comment] 2015-04-12 14:58
It's probably worth noting that I needed far more sealers than the interior volume indicated. The sealer says `Looped through: 57476 blocks` but I know the volume is closer to 47,000 blocks.

**Comment by radfast** [comment] 2015-04-12 15:10
```Looped through``` is not only the interior volume, it is every block checked thus it includes the walls etc.

I'm confused as to what you actually did to make this work, and so it's hard to tell whether anything needs fixing!

The logic _should_ identify after a couple of passes if there is one sealer which is capable of sealing everything, and automatically make that one the "head" sealer.

If in the light of your experience you can see something in the code which can be improved here, I would very much welcome that - either post it up here or make a PR, either one is good.

**Comment by codewarrior0** [comment] 2015-04-13 00:09
I must have been doing several things wrong. Underestimating the volume, disabling sealers, putting the sealers just far enough away that they couldn't see each other....

The only thing I can see now that needs fixing is that the comment at [`ThreadFindSeal.java:356`](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/oxygen/ThreadFindSeal.java#L356) doesn't match the behavior. Disabling the sealer will set its range to zero for when the other active sealer finds it. 

And maybe make some notes or rename some methods to the effect of saying "The seal check is done in two passes. The first pass in `doLayer[NearMapEdge]` is only run when the area is initially unsealed. It finds all of the blocks inside the seal, including walls, and marks whether the area was sealed. The second pass in `loopThroughD[NearMapEdge]` goes through all of the blocks found by `doLayer` that make up the seal and updates them according to the seal state: Air becomes breathable or unbreathable, torches become lit or unlit, and fire is extinguished if unsealed. The second pass also detects when a new sealer is added to an unsealed area."

At least, that's my understanding of it.

**Comment by codewarrior0** [comment] 2015-04-13 00:17
I wanted to add a line to the Sealer Tips on the wiki, but when I try to create an account it just takes me to a blank white page and doesn't create the account.

Could you add "The walls that enclose the sealed area are counted as part of its volume." to [the first bullet-point about seal volume](http://wiki.micdoodle8.com/wiki/Sealed_Space#Tips) for me?

**Comment by radfast** [comment] 2015-04-13 01:02
About this: https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/oxygen/ThreadFindSeal.java#L356 : it's intended that if you disable all the sealers except one, then let it run for a short time, then re-enable all the others, the one which was always on should now be the head.

I think the logic can maybe be improved still, like if it's not sealing it should try each different sealer in turn to see if that one can be the head and make a seal.  Actually coding that is not straightfoward because "each different sealer in turn" is imprecise - how should it know which sealers are in the same room and which are not?  i guess if 2 sealers found each other then they know they are in the same room.

**Comment by radfast** [comment] 2015-04-13 01:05
Yes the wiki registration script seems to have problems for now, it's been that way for a couple of months at least - you'll have to take that up with micdoodle8, I don't have the perms or the skills for that.

**Comment by radfast** [comment] 2015-04-13 01:09
Do you have a shortcut for the markdown for those nice code links with line numbers?  I replicated it but I had to do the markdown manually.

**Comment by codewarrior0** [comment] 2015-04-13 01:15
> it's intended that if you disable all the sealers except one, then let it run for a short time, then re-enable all the others, the one which was always on should now be the head.

Sounds like the comment is right but the behavior is wrong. The current behavior seems to be that disabled sealers return 0 from `getFindSealChecks`; the log output for the one active sealer says it finds all 45 sealers but only checks ~1100 blocks. 

>Do you have a shortcut for the markdown for those nice code links with line numbers?

Not really. I just click the line number to get the line URL, and then type in the markdown link syntax around it.

**Comment by codewarrior0** [comment] 2015-04-13 01:20
Oh, I didn't see that you wrote "then re-enable all the others". Yeah, that's exactly what I did, and the outcome was as intended. The one enabled sealer became the head after I enabled all of the others.

**Comment by radfast** [comment] 2015-04-13 01:33
ok then things are as intended currently, thanks for clarifying.  The game should be able to automate the task of figuring out which one to make the head, however - after all, it is a computer.
