### ISSUE TITLE
[1.10.2] [WAILA] Crash on using the Cryogenic Chamber

### ISSUE THREAD

**Issue by Bobynoby** [micdoodle8/Galacticraft#2498] opened 2017-04-07 02:57 UTC
After right clicking on the Cryogenic Freezer the game locks up for a moment, Then crashes soon after.
Was able to recreate it, By left clicking on the block to break it as well (Which also crashed again).

Client has 140+ mods

**Galacticraft (And cores) Versions:**
GalacticraftCore-1.10.2-4.0.0.53-BETA
Galacticraft-Planets-1.10.2-4.0.0.53-BETA
MicdoodleCore-1.10.2-4.0.0.53-BETA

**Forge Version:** 1.10.2 12.18.3.2254
**Crash Report:** https://pastebin.com/HZvTFwSd

If you need any more information just ask, I would love to have this in our modpack :)

**Comment by radfast** [comment] 2017-04-07 09:08
Thanks for beta testing!

This issue is caused by an interaction between **WAILA** and large (multiblock) structures in Galacticraft.

If you are able to play without WAILA then please try that for now.  We are aiming to have a new BETA version with a fix for this out in the next 1-2 days.

**Comment by Bobynoby** [comment] 2017-04-07 09:27
Sweet, Happy to help out :)

**Comment by radfast** [comment] 2017-04-07 09:30
_Note to @micdoodle8 _:

I've looked at this.  Line 290 in ```BlockMulti``` is the key.  ```mainBlockID.getPickBlock(target, world, mainBlockPosition, player)``` is leading to something strange in vanilla ```Block.getPickBlock()``` code - looks like it's trying to get the damage value using the blockstate at ```target``` instead of using the blockstate at ```mainBlockPosition```.  I can't reproduce this in 1.8.9.

If necessary we could fix the vanilla behaviour by overriding getPickBlock() in BlockMachineMars and in all other blocks which are possibly the mainBlockID.

**Comment by micdoodle8** [comment] 2017-04-08 05:53
Should be fixed in the next build, thanks to both of you :)

**Closed by micdoodle8** 2017-04-08 05:53 UTC
Labels: 1.10, 1.11
