### ISSUE TITLE
Missing EntityEvolvedZombie class loading in dev environment

### ISSUE THREAD

**Issue by OreCruncher** [micdoodle8/Galacticraft#2092] opened 2016-02-19 00:02 UTC
Installed GalacticraftCore, Planets, and MicdoodleCore dev 1.7-3.0.12.441 JARs in my Eclipse sandbox so I can debug an issue in my mod.  Got the following exception during startup:
```
[15:56:11] [Client thread/ERROR] [FML]: Caught exception from GalacticraftCore
java.lang.NoClassDefFoundError: micdoodle8/mods/galacticraft/core/entities/EntityEvolvedZombie
	at micdoodle8.mods.galacticraft.core.GalacticraftCore.preInit(GalacticraftCore.java:219) ~[GalacticraftCore.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
```
Using Forge 1614.

**Comment by radfast** [comment] 2016-02-19 12:48
Is that the whole stacktrace?  Any 'caused by'?

I really don't see how this can be possible, there must be something else wrong with your setup.  Maybe provide the whole log.

**Comment by OreCruncher** [comment] 2016-02-19 13:00
[Pastebin](http://pastebin.com/4dbKn0Xm).  Nothing wrong with my sandbox.

**Comment by radfast** [comment] 2016-02-19 15:01
So your error pasted is a missing ```java.lang.ClassNotFoundException: micdoodle8.mods.galacticraft.api.entity.IEntityBreathable```.  See the "Caused by" lines - you could have reported that accurately in the first post.

It appears that that class in Galacticraft API is not present in your dev environment.  This is hard to understand, it should be impossible.  [The class is there](https://github.com/micdoodle8/Galacticraft-API/tree/master/src/main/java/micdoodle8/mods/galacticraft/api/entity).  Also your log shows the Galacticraft API as present:
> [04:58:18] [Client thread/DEBUG] [FML/]: Found API micdoodle8.mods.galacticraft.api.entity (owned by GalacticraftCore providing Galacticraft API) embedded in GalacticraftCore

Can you think of anything in your setup which could be interfering with this?

It's not because of using a dev version.  Any code which doesn't reference vanilla Minecraft should run identically in dev and obfuscated versions.

**Comment by OreCruncher** [comment] 2016-02-19 16:31
I can't think of anything specifically.  I have run into similar errors when there was a transform failure of some sort - sometimes the ASM manipulation occurs "successfully" but the problem shows downstream.  When I suspect that I use a CheckClassAdapter.verify() to verify the class bytes after to transform to catch them.

(Not saying that there is a transform error in this particular case.  Just saying that I ran into similar errors and they were related to transformation.)

Other thing that may be worth mentioning is that my mod does use ASM to do transforms of EntityRenderer, World, and WorldProvider.  Nothing related to Entities.  I also have an AT.cfg, but I cannot imagine how that could be an issue.

**Comment by OreCruncher** [comment] 2016-02-19 17:18
Stripped it down and issue.  It's a baffler.

**Comment by OreCruncher** [comment] 2016-02-19 17:32
I just dropped in the regular release versions of 442 into my dev environment and using CodeChicken's on the fly deobf.  It loaded and is running.  Not sure what is up with the dev JARs.

**Comment by radfast** [comment] 2016-02-19 21:22
Very strange.  I am looking at this, in case its a symptom of something more serious being wrong - we do want the dev versions to work for people.  Still, it sounds like you have things working OK now!

**Comment by OreCruncher** [comment] 2016-02-19 21:24
Yep - I was able to accomplish what I needed with the release versions.  If I happen to think of something I will let you know.  You can close if you need.

**Comment by radfast** [comment] 2016-02-21 15:05
Strange, I re-built my dev environment today after updating Forge and had a similar crash.  (A class which is definitely present in the GC API was reported as not found.)

My crash seems to have "fixed itself" just by restarting, possibly something cached has been cleared.

Anyhow, I'm fairly confident this is not a bug in Galacticaft.  Closing.

**Closed by radfast** 2016-02-21 15:05 UTC
Labels: missing info

**Comment by radfast** [comment] 2016-02-21 15:17
It could also be caused by your **code** in your dev environment including some classes from the Galacticraft API, which are outdated compared with what is in the dev builds.

In a development environment, any API you have source code for will override what is contained in .jars.  So when Forge is loading APIs, it has a system (using the @API annotation) so that it knows that it should load the "official" version of the API which comes with the actual associated mod - in priority to copies of the API distributed with other mods.  But this system doesn't work for coremods (something it took ReikaKalseki a while to realise in DragonAPI...) and it doesn't work where you have the actual source code.

Similar issue: http://bt.industrial-craft.net/view.php?id=1768

**Comment by OreCruncher** [comment] 2016-02-21 15:55
My code does not refer to Galacticraft in any way.  I was looking into an issue with my mod when Galacticraft is installed.  My mod adds biome sounds and the like and I got a report that these sounds were playing on the Moon when they shouldn't be.  I needed to understand the dynamic of dimension transition when a rocket leaves Overworld.

**Comment by radfast** [comment] 2016-02-21 17:26
Did you solve the issue?

I can't think of a reason for that, but it might be worth you looking at [this](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/event/EventHandlerGC.java#L375).

Could also be a biome ID conflict, by default Galacticraft registers biomes 102, 103, 104, 105.

**Comment by OreCruncher** [comment] 2016-02-21 23:55
My best guess as to what is really happening is that the player is still in the Overworld dimension in regular biomes even though they are at the solar system overlay display.  Dynamic Surroundings would continue playing terrestrial sounds because it didn't know better.

I worked around it indirectly.  I created what I call "fake biomes" for higher elevations.  At world build height +32 it becomes "OuterSpace" which has no sound.  What this means is that when a player launches in a rocket and his Y value increases at some point the sound will cut out because of "OuterSpace".

**Comment by radfast** [comment] 2016-02-22 00:34
> the player is still in the Overworld dimension in regular biomes even though they are at the solar system overlay display

This is correct.  The player is still in the original dimension, until he has chosen his new dimension.
Normally (unless using an admin cheat command, **/dimensiontp**) he will be at a high y value (y=1300 or more) and riding an entity.

Your solution based on y value seems perfect.  If you want to get very fancy about it, you could attenuate your mod's sounds between <build height> +32 and <build height> +200, let's say.
