### ISSUE TITLE
Suggest: When player wear a spacesuit, he will not harm in the water

### ISSUE THREAD

**Issue by MCTF-Alpha-27** [micdoodle8/Galacticraft#4082] opened 2022-01-01 04:36 UTC
It's not scientific to wear space equipment and not be able to breathe in water

**Comment by TheQuadShot** [comment] 2022-01-01 23:12
Dupe of #196

(Suggestion: have O2 mask provide air underwater #196)

**Closed** 2022-01-15 12:29 UTC
