### ISSUE TITLE
Console Spam (Editing Flag)

### ISSUE THREAD

**Issue by jonny3010** [micdoodle8/Galacticraft#1401] opened 2015-01-23 19:35 UTC
Basicly server console is spammed with  Running 252
Happends when a player is creating team flag

2015-01-23 19:32] [19:32:32 INFO]: [micdoodle8.mods.galacticraft.core.dimension.SpaceRaceManager]: hen676
[2015-01-23 19:32] [19:32:32 INFO]: Vector3 [0.0,0.9571428298950195,0.0]
[2015-01-23 19:32] [19:32:32 INFO]: micdoodle8.mods.galacticraft.core.wrappers.FlagData@5516d340
[2015-01-23 19:32] [19:32:37 INFO]: Team Hen
[2015-01-23 19:32] [19:32:37 INFO]: 1
[2015-01-23 19:32] [19:32:37 INFO]: [micdoodle8.mods.galacticraft.core.dimension.SpaceRaceManager]: hen676
[2015-01-23 19:32] [19:32:37 INFO]: Vector3 [0.0,0.9571428298950195,0.0]
[2015-01-23 19:32] [19:32:37 INFO]: micdoodle8.mods.galacticraft.core.wrappers.FlagData@19b7be82
[2015-01-23 19:32] [19:32:37 INFO]: [micdoodle8.mods.galacticraft.core.dimension.SpaceRaceManager]: hen676
[2015-01-23 19:32] [19:32:37 INFO]: Vector3 [0.0,0.9571428298950195,0.0]
[2015-01-23 19:32] [19:32:42 INFO]: 1
[2015-01-23 19:32] [19:32:42 INFO]: Vector3 [0.0,0.9571428298950195,0.0]
[2015-01-23 19:32] [19:32:42 INFO]: micdoodle8.mods.galacticraft.core.wrappers.FlagData@4ab48569
[2015-01-23 19:32] [19:32:42 INFO]: Team Hen
[2015-01-23 19:32] [19:32:42 INFO]: [micdoodle8.mods.galacticraft.core.dimension.SpaceRaceManager]: hen676
[2015-01-23 19:32] [19:32:47 INFO]: [micdoodle8.mods.galacticraft.core.dimension.SpaceRaceManager]: hen676
[2015-01-23 19:32] [19:32:47 INFO]: Vector3 [0.0,0.9571428298950195,0.0]
[2015-01-23 19:32] [19:32:47 INFO]: micdoodle8.mods.galacticraft.core.wrappers.FlagData@4e0d60c
[2015-01-23 19:32] [19:32:47 INFO]: Team Hen
[2015-01-23 19:32] [19:32:47 INFO]: 1
[2015-01-23 19:32] [19:32:48 INFO]: ThaBazZz has just earned the achievement [Getting Wood]
[2015-01-23 19:32] [19:32:52 INFO]: Team Hen
[2015-01-23 19:32] [19:32:52 INFO]: 1
[2015-01-23 19:32] [19:32:52 INFO]: [micdoodle8.mods.galacticraft.core.dimension.SpaceRaceManager]: hen676
[2015-01-23 19:32] [19:32:52 INFO]: Vector3 [0.0,0.9571428298950195,0.0]
[2015-01-23 19:32] [19:32:52 INFO]: micdoodle8.mods.galacticraft.core.wrappers.FlagData@17adbf8f
[2015-01-23 19:32] [19:32:52 INFO]: [micdoodle8.mods.galacticraft.core.dimension.SpaceRaceManager]: hen676
[2015-01-23 19:32] [19:32:52 INFO]: Vector3 [0.0,0.9571428298950195,0.0]
[2015-01-23 19:32] [19:32:57 INFO]: [micdoodle8.mods.galacticraft.core.dimension.SpaceRaceManager]: hen676
[2015-01-23 19:32] [19:32:57 INFO]: Vector3 [0.0,0.9571428298950195,0.0]
[2015-01-23 19:32] [19:32:57 INFO]: micdoodle8.mods.galacticraft.core.wrappers.FlagData@65d8bc6
[2015-01-23 19:32] [19:32:57 INFO]: Team Hen
[2015-01-23 19:32] [19:32:57 INFO]: 1

**Comment by radfast** [comment] 2015-01-23 20:35
Duplicate of #1235.

That's some logging micdoodle8 added, I guess connected with #957 which is not yet fixed.

Anyhow, we don't need to be spamming all servers with this, so in next build (which will be 3.0.8.257) I changed it so that it will only log those messages if Debug mode is enabled.

**Comment by jonny3010** [comment] 2015-01-23 20:47
Nice when's 257 coming out?

**Closed** 2015-01-23 21:17 UTC
