### ISSUE TITLE
Display Screens doesn't show the overworld map

### ISSUE THREAD

**Issue by chaNcharge** [micdoodle8/Galacticraft#1752] opened 2015-06-27 01:03 UTC
What I mean is, the display screens (along with the space station views) only shows the default Earth texture, shown in the image below. I remember before, it used to show almost everything in your world, such as your home, the lakes, and the rivers, somewhere near the spot where you take off. Is this a bug, or a known issue that's being fixed at the moment? This is in the latest Galacticraft version, build 345

![overworld texture bug](https://cloud.githubusercontent.com/assets/11594018/8389798/9c0833de-1c2d-11e5-9687-15cddbbf32b3.png)

**Comment by EzerArch** [comment] 2015-06-27 01:58
O hi! Search is your friend: https://github.com/micdoodle8/Galacticraft/issues/1665

**Comment by radfast** [comment] 2015-06-27 11:02
These issues are currently being worked on, with a view to a long term improvement in functionality.
You may find the map image appears if you leave it 10-15 minutes.

**Comment by chaNcharge** [comment] 2015-06-27 16:31
What about in Space Stations? In #1665 reloading the world fixes the issue with display screens, will reloading also fix it in space stations?

**Comment by radfast** [comment] 2016-01-08 02:56
See also #1334.  This is still being worked on, do not lose hope!

**Comment by radfast** [comment] 2016-02-13 04:03
This issue is fixed in new build 442.

There are many changes to the mapping - some still to come.

The current intended behaviour for Display Screens on the Overworld is to show a map which is different from the vanilla map.  It is supposed to be an "aerial view" of the world, from so high up that individual blocks are not shown but giving an accurate idea of overall terrain coloring.  These aerial views will in future be used as part of the Overworld launch sequence.

The Display Screen, for now, gives:
* on the Overworld, a preview of that "aerial view"
* on all other dimensions, a preview of a rotating Overworld [Work in Progress]

In future it is planned for the Display Screen to show two maps:
(1) in all dimensions, a local map similar to the vanilla Map item (and similar to the map shown in most mapping mods, which is also based on the vanilla Map)
(2) on the Overworld and Overworld Space Stations, a "satellite view" of a large area of the Overworld similar to the "aerial view" you are currently seeing but even more zoomed out.  This zoomed out map can be useful if you are playing in survival, for example it will help you to find Desert, Swamp or Jungle biomes which are all fairly rare in Minecraft 1.7.10.

Details of the "aerial view" map (current implementation)
* On the Overworld only, the Display Screen currently shows you a local map, centered on the Display Screen's actual location
* The map is a detailed image with scale 1 pixel = 2x2 blocks.  It covers an area of 704x704 blocks, that is much larger than the vanilla map and well beyond the player's view distance.
* The map draws forests, deserts and similar biomes (including the icy biomes) in a stylised way, meaning the dark green pixels for trees do not correspond to actual tree positions - the green pixels for cactus in deserts do not correspond to actual cactus locations and in a roofed forest, the red/brown pixels for mushrooms do not correspond to actual mushrooms.
* Worldgen 'final decoration' features including water and lava pools, small sandy beaches, canyons, caves, and structures (such as temples and villages) are **not** shown.  It might be possible in future to add some of these - maybe the structures - in a stylised way.
* Player-built structures and farms - or any player-made changes to the map at all - are **not** shown.  This is not likely ever to change for these "aerial view" maps, it would place an impossible load on the server to map every block.
* If the player can see multiple Display Screens in his frustum, all screens will show the exact same map image.  So the map will be centered on the location of one of the screens, normally the last one built so it's not necessarily the one closest to the player - it could be 50+ blocks away from the player's current location.
* For this reason, it is occasionally possible for different players to see (slightly) different maps on the same screen tile - if one player turns his head so that he has different screen tiles in his frustum, that could change the map shown.
* The map is always drawn with North at the top (even if the screen is in some other orientation)
* The map can take a short time to generate - sometimes instant, sometimes up to 20 seconds.  While it is generating, the rotating Overworld image is shown
* Mods which add new biomes to the game - for example ExtraBiomes or Natura - will have their biomes show up on the map in whichever colours were chosen by the makers of those mods - if they chose their colours badly these could be magenta or teal or something else very ugly looking.

The rotating Overworld image - shown on Display Screens in other dimensions - takes a long time to first generate, around 6 minutes.  But it only needs to generate once, normally when a world is first created or the first time the server runs after updating to GC 442.  Once the rotating Overworld image has been generated, it is saved permanently on the server.  It generates slowly, a small amount each tick - if the server stops before the image is fully generated then it will try to generate it again the next time the server starts.  During this first 6 minute period you will see the default flat Overworld image on Display Screens.  On low-performance / heavily loaded servers, generating the image can slow the server down - reducing the tick rate or producing "Can't keep up! Is the server overloaded?" messages.  It's best to let it finish, then it will never need to do it again.  Large servers might want to update to GC442 at a time when the server is not heavily loaded - or even use an offline copy of the server - with the same world seed - to generate this map.  (The map is saved in ```.minecraft/world/galacticraft/overworldMap/Overworld192x48.bin``` and if that file is present on a server then it will not be generated.)

What is actually going on is that the server is mapping the whole world (!) covering an area of 24576 x 6144 blocks.  (Possibly I will increase this to 24576 x 24576 blocks in future.)  That small scale map of the whole world is being saved, it will be used in future.  The "rotating Overworld" texture is then based on that actual world map, so its blocky oceans and continents correspond to the actual positions of oceans and continents in your game. :)

This should make total sense on servers which set the world border at around 10,000 blocks or 12,000 blocks maximum.  It will also make sense in single player, as 99.9% of players in single player never go so far away from spawn.

For people who like to break stuff and make their bases 100,000 blocks out from spawn, they will have a situation where any of the small scale maps in Galacticraft (the most zoomed out world maps) will show the world around spawn instead of the current location.  Not really a big deal.

**Closed by radfast** 2016-02-13 04:03 UTC

**Comment by EzerArch** [comment] 2016-02-13 06:22
This is just beautiful! 

Please, don't worry about the wiki. Let me port this text when I get around to.

**Comment by radfast** [comment] 2016-02-13 14:44
Yes, it aims to be a classy map.  It's based on mapping biomes not blocks - that means the map can be scaled to any size, and can cover parts of the server which have not yet been worldgenned.

The visual appearance is heavily modded from a "biomes map" because the biome map is ugly, the colours do not represent the blocks you see.   I have aimed to use colours which match the most common surface blocks in each biome.

It also makes use of a height map - this is necessary to show water correctly, I have managed to make this almost 100% accurate (for example check a river which sometimes has "dry" areas).  This also shows snow at high altitudes, 2 different ocean depths (and I may make that 3 eventually), and there is a slight lightening effect on higher terrain which you can see on your map there - I guess you have Forest Hills to the north of your location.
