### ISSUE TITLE
[Bungee server] Client login issue when on another planet

### ISSUE THREAD

**Issue by knoxz** [micdoodle8/Galacticraft#1164] opened 2014-10-18 01:19 UTC
Hi there,
some player seem to have an issue with logging in while on one of ur planets.
Its seems to be related to the Liteloader not finding the provider for the world?

Happened a few times now.

Crashlog: http://pastebin.com/iLnwHhQ7
Version: GalacticraftCore-BETA-1.7-3.0.5.223

**Comment by XCompWiz** [comment] 2015-02-21 16:25
Mystcraft sends a packet to the player at login with all registered dims, and updates all players when a new dim is registered.  I've not tested for compatibility with Bungee, so I don't know if there are issues there.
If anyone can test that and let us know if it works or not then I'll either know a way that DOES work or be able to join in on helping solve this.

**Comment by radfast** [comment] 2015-02-21 16:27
Hey XCompWiz :)  Sounds good, I'm extremely glad to have your input on this.

**Comment by radfast** [comment] 2015-02-21 20:10
I guess one solution would be the same as what has been proposed on the Forge thread to solve the 127 positive dimensions limit, I mean this:
> The issue with login can be resolved with no special change to the login protocol, by logging you into a special, low-numbered dimension first, and then teleporting you to the real location.

We could do that, it's maybe not too bad a solution is now I think about it.  It might also solve any issues with our current approach if packets arrive in a different order, which I guess is possible sometimes due to network latency.  Nobody has reported an issue like that, but I guess it can happen.

**Comment by SirWilli** [comment] 2015-02-22 04:50
@XCompWiz I can logout and login just fine in a mystcraft age with the version 0.11.0.00 and bungeecord. ;)

**Comment by XCompWiz** [comment] 2015-02-22 15:13
That's good.  That means my method probably works fine.
I use the ServerConnectionFromClientEvent event, not the log in event.
```
@SubscribeEvent
public void connectionOpened(ServerConnectionFromClientEvent event) {
    event.manager.scheduleOutboundPacket(MPacketDimensions.createPacket(Mystcraft.registeredDims));
    event.manager.scheduleOutboundPacket(MPacketConfigs.createPacket());
}
```
The packet handling registered dimensions is hopefully self-evident.  I basically just serialize the list of registered dims and then unpack it client-side.

**Comment by radfast** [comment] 2015-02-22 15:40
@XCompWiz   Thank you, really appreciate your help here.

We use the same ```ServerConnectionFromClientEvent```event, but according to this thread our way is not working :(
https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/network/ConnectionEvents.java#L55-69

It loks like there is maybe a difference in Bungee between event.manager.scheduleOutboundPacket() and event.handler.sendPacket().

I'll try the Mystcraft way when I get some time to make a build in the next 1-2 days, and if our testers would be kind enough to test that when it's ready.

**Comment by radfast** [comment] 2015-02-22 15:47
OK I guess it didn't take 1-2 days to make that build.
@SirWilli  if you're in a position to try out build 3.0.8.267 and let us know, that would be awesome
http://ci.micdoodle8.com/job/Galacticraft-1.7/267/

**Comment by SirWilli** [comment] 2015-02-22 19:30
Seems not to fix it. I still can't click on the Launch button and game crashes if I try to get in to the world via a command.

**Comment by XCompWiz** [comment] 2015-02-24 21:00
Rad: You might need to enable some limited debugging, indicating if the packet is sent and received in the log. That will at least enable you to see if either event occurs for SirWilli.
If both events occur, you might need to verify the contents of the packet (before sending and on arrival) and the unpacking of it.

**Comment by Slind14** [comment] 2015-02-24 21:13
Would I minimal test setup help?

**Comment by radfast** [comment] 2015-02-25 00:22
@Slind14 you're saying you can package up a Bungee server for me to unpack and test, without having to read Bungee documentation?  That would be incredibly awesome, I can do logging and testing myself without needing to ask people on a 2 day cycle...

@XCompWiz thank you, I will do exactly that - the fact that this works in your mod is great news, it means there __must__ be a solution for this.  I'm guessing I'm going to have to delve deeply into our packet handling.  Do you object if I decompile some of your classes if I need to?

**Comment by SirWilli** [comment] 2015-02-25 13:53
@radfast here: https://www.mediafire.com/?abz68l9kc48yjw7
Just start bungeecord and the Server then connect to localhost:25577

**Comment by XCompWiz** [comment] 2015-03-11 19:03
No objections, @radfast :)

**Comment by radfast** [comment] 2015-03-11 19:05
ok ty

**Comment by radfast** [comment] 2015-03-21 19:42
Good news:  I think this is fixed in the latest build 3.0.10.298.  (Obviously that build will be needed on both server and client).  For details of other recent changes: http://wiki.micdoodle8.com/wiki/Whats_New

Thank you __very much__ to everyone who has contributed to this thread, and thank you for your patience.  Special thanks to @XCompWiz for letting me look at Mystcraft code.

**Closed by radfast** 2015-03-21 19:42 UTC

**Comment by SirWilli** [comment] 2015-03-23 13:26
Just tested it and it works. Thank you so much for this fix :)
Would you mind pointing out what the issue was and how you fixed it, little curious?

**Comment by radfast** [comment] 2015-03-23 15:27
As covered already in the thread, the issue was that Bungee suppresses custom packets, at the time when Bungee (instead of a normal Forge/FML server) is handling the networking on the server, which is at that period between first connection to the server and completion of the player login.  Galacticraft, Mystcraft, and other mods need to send important network packets at that time.

I fixed it by instead using an FML custom channel for networking, at that time.  Mystcraft uses an FML custom channel for all its networking, and Mystcraft did not have the Bungee issue, so that's what gave the crucial clue that a custom channel can get past Bungee.

I expect some other mods may have the same types of Bungee issue which Galacticraft had, but it may not be so noticeable - for example you may find there are mods where the server configs do not override the player config values as they should, for players on Bungee servers.  I have not done a full study!  For most mods it is likely to be a much less obvious problem than it is for Galacticraft, because most mods don't have customised dimension handling.

**Comment by XCompWiz** [comment] 2015-03-24 18:01
Very good to know. Thanks for the update.

**Comment by SirWilli** [comment] 2015-06-24 10:59
@radfast got this only fixed for planets? I just got the issue now with space stations :/

**Comment by radfast** [comment] 2015-06-24 13:38
Please describe the exact issue you are now having, @SirWilli.
Provide any relevant logs or crash reports.

**Comment by Slind14** [comment] 2015-06-24 13:39
```
java.lang.IllegalArgumentException: Could not get provider type for dimension -127, does not exist
        at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:148)
        at net.minecraftforge.common.DimensionManager.createProviderFor(DimensionManager.java:302)
        at net.minecraft.world.WorldProvider.func_76570_a(WorldProvider.java:160)
        at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:54)
        at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:237)
        at com.mumfrey.liteloader.client.CallbackProxyClient.handleJoinGamePacket(CallbackProxyClient.java:93)
        at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile)
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
        at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78)
        at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1649)
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
        at net.minecraft.client.main.Main.main(SourceFile:148)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by radfast** [comment] 2015-06-24 13:45
How many space stations does the server have?  Over 100?  This error could be caused by having any higher than DIM127.

Do you have any other mods installed with extra dimensions?

**Comment by Slind14** [comment] 2015-06-24 13:46
not many https://i.imgur.com/e0qCAOK.png

**Comment by radfast** [comment] 2015-06-24 13:49
This is your problem, Galacticraft can't handle over 128.

You'll have to delete DIM129 and DIM138.  [Instructions](http://wiki.micdoodle8.com/wiki/Tutorials/Space_Station_for_Server_Admins#Deleting_a_space_station)

I don't understand why the DIM numbers would be so spread out like that for so few stations, normally they should be consecutive.  It seems like you might have manually deleted some space station dimension folders in the past, without fully deleting them as instructed on the wiki.

**Comment by radfast** [comment] 2015-06-24 13:53
It's actually a Forge issue which cannot handle dimensions outside the range -127 to 127.  [It has been raised at Forge but LexManos closed it](https://github.com/MinecraftForge/MinecraftForge/issues/1621).

**Comment by Slind14** [comment] 2015-06-24 18:40
Wow, I would have never thought that. I knew about the limitation from the minecraft protocol but wouldn't have thought of this with this exception. Thanks and great that it has been removed as this means I don't need to use dynamic world ids with a planned project :D

**Comment by SirWilli** [comment] 2015-06-25 14:23
Thanks, that fixed it.

**Comment by radfast** [comment] 2015-06-25 16:24
I still think you would be better off fixing your unused space station dimensions by deleting them properly.

I have not yet heard of any Galacticraft server with more than 100 active space stations.  The server which I used to manage, which had over 30,000 players, only had about 75-80 space stations created.  The vast majority of players simply did not progress in the game far enough to build a space station.  Other players chose not to spend their resources on that ... it was a PvP / raiding server so a space station was a visible target I guess ... :D

**Comment by Slind14** [comment] 2015-06-25 16:26
There are not many but it is skipping id's somehow. (Screenshot above)
