### ISSUE TITLE
Exploding beds not working as intended

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#1975] opened 2015-12-20 05:41 UTC
![2015-12-20_02 27 50](https://cloud.githubusercontent.com/assets/6743303/11916527/73f32cc2-a6c1-11e5-99f6-630d5c1c763f.png)

Something between 404 and 406 went wrong. At least fixed #1833, I think the explosion forced a mass block update of some sort.

**Comment by micdoodle8** [comment] 2015-12-21 22:10
Hmm, that's strange. I can't seem to reproduce this. Are you sure you didn't add another mod that prevents respawning?

**Comment by EzerArch** [comment] 2015-12-21 23:48
You mean this?

```
    # By default, you will respawn on galacticraft dimensions if you die. If you set this to true, you will respawn back on earth.
    B:"Force Overworld Spawn"=false
```
Honestly I *never* think that option would enable exploding beds.

I disabled that a week ago or so because I wouldn't like to find myself trapped in these infinite death-loop: die, respawn with no oxygen gear, run for your stuff, flight low gravity and hurt animation, 40 seconds later dead again, respawn with no oxygen gear, repeat the struggle on and on. 

If you don't have means to return to OW, you are stuck, forever. Respawning on OW would give me the chance to try again, even if my inventory is lost.

It happened I tried to use a bed just after updating to 406 with same-dim respawning disabled. I won a bad lottery. :)

**Comment by radfast** [comment] 2016-01-06 01:49
Don't close this issue yet!  The beds shouldn't explode if you set that to re-spawn on the Overworld.

**Comment by dj3520** [comment] 2016-01-06 02:45
They shouldn't? Then what's the point of the cryogenic chamber?

**Comment by radfast** [comment] 2016-01-07 20:47
The intended situation is:
* beds in GC dimensions do not allow you to sleep in them - you will not sleep through the night
* beds in GC dimensions should **not** explode
* the (Cryogenic Chamber)[http://wiki.micdoodle8.com/wiki/Cryogenic_Chamber] allows you to sleep through the night in whichever dimension it is in

(and eventually, if we ever make buildable spaceships which can travel between worlds ... no promises, but it is a frequent suggestion/request ... then the Cryogenic Chamber will allow you to sleep through that journey instead of spending a lot of in-game time doing nothing)

**Comment by dj3520** [comment] 2016-01-08 01:38
Ah I see. I thought all beds on mars exploded.

**Closed** 2016-01-09 02:25 UTC

**Comment by radfast** [comment] 2016-01-09 02:38
As of build 411 beds will work like this, in Galacticraft dimensions:

On space stations:  beds do nothing at all (but they don't explode) - they are purely decorative items

On Planets (and Asteroids):
* players cannot sleep in beds, the player will not lie down
* however, beds can be right-clicked to set the player's respawn point for if he later dies in that dimension - the spawn point will be set, even though the player does not get to sleep
* prior to placing any bed, the respawn point on a planet is where the player's lander first landed
* respawning on planets - either at the bed or at the lander location - will be overridden by the "Force Overworld Spawn" setting if true - but if that setting is set to false, any bed which was right-clicked meanwhile will be used again as the spawn point
* if other mods have some functionality with beds, that may still work on planets, but I have not tested this

Galacticraft Add-ons can change this behaviour for their own planets - they can allow beds to explode instead, i.e. the pre-build 411 behaviour.  @SteveKunG you may be interested in this?  :)

Additionally, whenever a player first clicks a bed in space - whether on a space station or on a planet - a message "I'll need a Cryogenic Chamber if I want to get a good night of sleep in space" is shown :D

**Comment by SteveKunG** [comment] 2016-01-09 11:32
It's OK, I'll implement this later. Thanks! But could you add hook for allow the nether portal can be create in the breathable planet?

**Comment by radfast** [comment] 2016-01-09 14:23
@SteveKunG I'll add a property to IGalacticraftWorldProvider: ".netherPortalsOperational".  You can set that to true on any planets where you want the Nether Portals to work.  The default will be false.

Please note that it should be impossible for a player to create a Nether Portal in any location where there is no oxygen, because he cannot make the fire needed to ignite it.  But maybe some players can find a way to do it - including using firestarting mechanisms from other mods.

Nether Portals can exist on space worlds - even in airless locations.  Here are some ways:
* they were created using fire in some way
* they were created using a Fire Charge in pre-411 versions of Galacticraft
* they were created inside oxygen (e.g. Oxygen Bubble) and then the oxygen was removed but the Nether Portal was left intact.

**Comment by dj3520** [comment] 2016-01-23 20:37
Question: What if I don't install mars/asteroids and try to use a bed on a space station?

**Comment by katzenpapst** [comment] 2016-04-12 23:17
I still have problems with this with #454: 
a) Carpenter's Blocks beds still explode in space stations
b) the cryogenic chamber doesn't work for me. I can't sleep in them, I see myself in thirdpersion in the chamber for a short moment, but then I am back in first person, still somewhat intersecting the chamber, but no time has passed, and I can rightclick the thing right away. I'm not sure, but I think in the third persion view of myself I am lying down, as if it was a bed.

The console doesn't say anything interesting when I try to sleep, only that: 
[01:19:09] [Client thread/INFO]: net.minecraft.client.gui.GuiSleepMP
I suppose it might be another mod's fault, but is there something else that I could try before I start disabling mods and trying whenever it begins to work?
