### ISSUE TITLE
1.7.10 the IPartialSealableBlock Interface is not being called at the right places, at least if you want to return false

### ISSUE THREAD

**Issue by GregoriusT** [micdoodle8/Galacticraft#2978] opened 2017-09-11 13:05 UTC
Minecraft version: 1.7.10
Galacticraft version: 502
Forge version: 1614

According to Guidelines this counts to me as "things not working as intended", and while I am a somewhat competent Coder, in some cases of your Code I dont know if it could have side effects to change the order of the thing I want to address. (there is likely no side effect, but I'm always insecure about other peoples Code)

It is about the functions "canBlockPassAir" in OxygenPressureProtocol and "canBlockPassAirCheck" in ThreadFindSeal.

Both of these Functions call the isSealed Function of IPartialSealableBlock, however the Interface is entirely ignored if

A: The Block happens to be Opaque, what makes it impossible to create Wool, Sponges and other porous things.
(This is the most critical Issue I have with the current implementation at the moment as it's impossible to work around it)

B: The Block happens to extend BlockGlass, BlockStainedGlass or BlockLeaves
(this is a perfectly valid default and should ofcourse be called before the isOpaqueBlock check, but it should still be called after the Interface check)

C: The Block happens to be in the list of "OxygenPressureProtocol.nonPermeableBlocks"
(this is called before the Interface check on one Code and after the Interface check in another Code, so it's very inconsistent)

Shouldn't this Interface be the very first thing to be called whenever there is a check for Sealing? Since if someone implements that Interface, they expect this Interface to not be entirely ignored at all times.

Also the check for one Interface is way better for performance than checking a List of Blocks or having multiple if-instanceof-SomeBlock checks in a row, so this would be a tiny improvement on that part aswell.

**Comment by GregoriusT** [comment] 2017-09-11 13:19
Decided to see if there was a GitHub Editor for quick File Editing, guess I found that thing and made requests for each of the Files to be fixed. I'm not sure if it works but logically speaking it should work. ^^

**Comment by GregoriusT** [comment] 2017-09-11 15:14
Also I cannot have any Block implement that Interface without Minecraft crashing BEFORE startup with this Exception and I would like to know how to fix that:

```
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: gregapi/block/prefixblock/PrefixBlock
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: gregapi/block/prefixblock/PrefixBlock
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:42)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:512)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
	... 10 more
Caused by: java.lang.ClassNotFoundException: gregapi.block.prefixblock.PrefixBlock
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 36 more
Caused by: java.lang.NoClassDefFoundError: micdoodle8/mods/galacticraft/api/block/IPartialSealableBlock
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 38 more
Caused by: java.lang.ClassNotFoundException: micdoodle8.mods.galacticraft.api.block.IPartialSealableBlock
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 42 more
```
After investigating what the Issue might be I got this Exception when I tried to access the Interface Class
```
// I bet Cylons wouldn't have this problem.

Time: 11/09/17 16:59
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: micdoodle8/mods/galacticraft/api/block/IPartialSealableBlock
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: micdoodle8/mods/galacticraft/api/block/IPartialSealableBlock
	at gregapi.GT_API.<init>(GT_API.java:134)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at cpw.mods.fml.common.ILanguageAdapter$JavaAdapter.getNewInstance(ILanguageAdapter.java:173)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:506)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
	... 10 more
Caused by: java.lang.ClassNotFoundException: micdoodle8.mods.galacticraft.api.block.IPartialSealableBlock
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 40 more
Caused by: java.lang.NullPointerException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at micdoodle8.mods.miccore.MicdoodleTransformer.startInjection(MicdoodleTransformer.java:1995)
	at micdoodle8.mods.miccore.MicdoodleTransformer.transformCustomAnnotations(MicdoodleTransformer.java:1025)
	at micdoodle8.mods.miccore.MicdoodleTransformer.transform(MicdoodleTransformer.java:345)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 42 more
```
After asking around at my IRC Channel to find the culprit, someone said this was an ASM related Issue on MicdoodleTransformer, that is at the bottom of the Stacktrace.

I don't want to play the blame game or anything, but could anyone tell me how to fix this Issue? It makes it impossible for me to add compatiblity at all, and I guess it will also happen with all the other GalactiCraft Classes aswell.

**Comment by TheQuadShot** [comment] 2017-09-11 17:58
Not sure this will help... You can make almost any opaque block "non-opaque" in the ../config/Galacticraft/core.conf file. I remember something on the wiki about an incompatibility with GregTech but don't remember exactly what it was atm.

**Comment by GregoriusT** [comment] 2017-09-11 18:13
Nope, that won't really help at all. The Issue is that it ignores its
own Interfaces per default. I simply fixed that in my Pull Request
after I found out that it is THAT simple to edit on GitHub.

And if you did not notice, I am GregoriusT, the creator of GregTech,
who at this moment tries to figure out how things work, and noticed
that the Interface made for compatibility gets ignored seemingly
randomly, according to its Code. Thirdhand Information on the Wiki
won't help with that at all.

The real issue I get right now (even if my pull request gets
accepted), is that I cant have any Block implement the Interface
without causing ClassLoader Issues, what clearly means that GC is
making some weird ASM Stuff that breaks its API, because GregTech does
not contain any ASM in itself (because I have no clue how the fuck ASM
works and I never touched it), so it cant be my fault if ASM is the
reason for it to break.

I just want to have nice compatiblity and things working together, is
that too much to ask for? ;)

**Comment by GregoriusT** [comment] 2017-09-11 20:13
Also as for "why not registering Blocks via the Config", that is not an option for things like my Wires and Pipes, which are supposed to be sealable when they have dried Construction Foam (all sides) or a Cover (1 to 6 sides) on them. And especially for the Covers, that requires TileEntity access.

I'm trying to give as much info on this issue as possible so that if a reply happens while I sleep, that said reply should contain some viable answer for me.

Because right now even with just GregTech-6 (with code that uses the Interface), NEI and the 3 Galacticraft Mods on an Forge 1614 Instance, I still get the Error that the Interface doesn't exist at all or that the Classloader cannot find it.

**Comment by GregoriusT** [comment] 2017-09-12 10:10
Okay I fixed the Issue that causes the NoClassDefFoundError, and that without including any API Files in my Mod Jar. Apparently just the sheer existence of a part of my code that loads before Galacticraft causes this Error.

GregTech itself consists out of 3 mods in 1 Mod File, one part that loads before all known Mods, one that loads after all known Mods and GregTech itself that loads after the one that loads after all known Mods.

I solved the Issue by letting the part that usually loads before all other Mods, load after GC and Micdoodlecore, meaning that the GC Code gets loaded by the GC Acces Transformer first before GregTech starts loading.

-----

This leaves only the Issue that I added a Fix request for, that the Interface gets ignored in most of the cases, which was easily solveable by just changing the order of Code as shown in my Pull Request on this Thread.

**Comment by Marlon2481** [comment] 2017-09-13 01:37
@GregoriusT You can simplify for me ? One guy relacioned this post for me , ( Crashing Minecraft )(https://github.com/micdoodle8/Galacticraft/issues/2979 ) I Need Help :3

**Comment by GregoriusT** [comment] 2017-09-13 08:48
Posted a reply on your Issue ;)

Simple: Make sure MorePlanets loads after GalactiCraft, if you somehow have the power to sort Mods

**Comment by radfast** [comment] 2017-09-14 13:24
Hi @GregoriusT thank you for looking in, welcome on board!

I will take a detailed look at this and your PRs and respond again after I have done that.  Generally we are not updating 1.7.10 much - but we are still happy to fix inter-mod compatibility issues of this nature, and probably there will be consequent fixes for 1.8.9+.

**Comment by GregoriusT** [comment] 2017-09-14 17:43
"not updating 1.7.10 much" is way better than "accepting pull requests and ignoring them since May 2016" like other repos apparently do (*cough* rail *cough* craft *cough*). ;)

For most compatiblity Issues I will try to find a GregTech sided Solution, like for my electric Items discharging in GC GUIs, or my Wires connecting to GC Machines, and filling the Oxygen Tanks in a GT Canning Machine.

Right now the Energy Loss for converting GT-EU to GC Power is gigantic in most cases since GC apparently consumes insanely low amounts of IC2-EU (which are equal to GT-EU), and even a single Low Voltage Packet is way more than any GC Machine can accept at once, so I had to do a workaround for that to make sure that Energy isn't massively wasted every tick due to topping-off the GC Machine Power Buffers (I simply check how full the Energy Storage is before filling it to ensure a full EU-Packet is able to enter).

Lots and lots of Compat work to be done for Space for me. I will try my best to make things as compatible as possible on my end, because fun. :D

**Comment by radfast** [comment] 2018-03-10 17:04
@GregoriusT  I have merged this into Galacticraft 1.7.10 branch.

(This will also automatically be picked up in 1.8.9 through to 1.12.2)

Your logic is correct, if a block uses this Interface then we should check its sealed status first, to give it the opportunity to return `false`.  Or `true`, if it's a sub-class of sponge or gravel etc.......

I apologise that you had a difficulty caused by our ASM transformer.  Forge loads that early because it is a CoreMod.  It seems that if you have a class implementing this `IPartialSealableBlock` interface then the ClassLoader tries to load the interface class even before Galacticraft is loaded.  Because the ClassLoader cannot find the interface yet, it creates a class with `null` for its byte array of code.  The ASM transformer is not expecting `null` for any of Galacticraft's own classes.

Your solution of including the referenced Galacticraft API interface in your mod's distributed `.jar` is a good solution, that's fine for us.

(You could also tell Forge to load your mod after `GalacticraftCore`, although I appreciate that if every mod had a long list of other mods it must load after, then Forge can end up in a situation where it's impossible to find a good mod loading order.... !)

I will include a null check in MicdoodleTransformer to try to reduce the chance of this happening again, although that might cause obscure issues.  We need the ASM transformer because there are some things in vanilla Minecraft we want to hook into where Forge does not provide hooks - for example gravity acceleration on entities, but also many other things major and minor.

-----

If you think our IC2 EU power conversion is incorrect, I am interested to talk about that with you.  I take pride in making it correct, of course subject to the different concepts in our own GC energy system.  If supplied with EU, our machines are intended to have a buffer which holds the surplus EU until our machine is able to accept it.

I want this to be correct, because part of Galacticraft's legacy is that we inherited from the old "Universal Electricity" project.  Our goal is to be fully compatible with IC2, Mekanism, and RF energy (also Forge energy but nobody uses that, also Buildcraft MJ for people who still use Buildcraft 6) while preserving our own features.  One of our features is that our code runs very **efficiently** server-side on **large builds** (for example 100 power cables, 100 machines emitting or accepting energy in the same grid).  As you might know, power grids in most other mods can be a severe source of lag on servers, if players are allowed to build huge power factories.

There are not so many mods with IC2 EU compatibility.  I love IC2 and I see this as a way for us to support the continuation of IC2.  Because your mod inherits from the IC2 EU system, this means it is also important to me that we have compatibility with GT.

------

Finally I apologise it has taken ~6 months for me to look at this properly.  I am not really working on 1.7.10  branch much, and I took a complete break from Galacticraft in October through December, then in January / February there has been a big push to release a 1.12.2 version.

**Closed** 2018-03-10 17:09 UTC

**Comment by GregoriusT** [comment] 2018-03-10 17:30
Its not a problem for me, dont worry about that, I fixed it "somehow" on my end so it works.

As for the IC2 EU Conversion.  Your Machines take like 1 EU/t, and that is the lowestof lowest Tier of IC2. IC2 Batboxes emit 32 EU/t, so maybe the Energy Ratio is a bit strange. Like IC2 has proper Generators for "Household Electricity" while Galacticraft has a Power Usage to the equivalent of those tiny Calculator/Wristwatch Batteries in comparision. Now compare that to GregTech that uses massive amounts of EU and you get the issue that a Battery that has a minimum output of 32EU/t will fill the buffer 10 times over with one tick. I fixed the Issue on my end ofcourse, so everything works fine by now, but it is still kinda unbalanced.

And having a Galacticraft Factory with 100 Machines seems a bit high, but I guess with Mekanism you can get the rate up to that factor.

But I will repeat again, I made everything work, so its fine. ;)

(also my mod loads both, before and after every compatible Mod, I have 3 Mods in that one jar File, each with a different Load order so I can do stuff before and after other mods whenever needed)

**Comment by QuantumStatement** [comment] 2018-03-10 18:17
>Buildcraft MJ for people who still use Buildcraft 6

Buildcraft developers [returned](https://www.reddit.com/r/feedthebeast/comments/4qz70t/looks_like_buildcraft_is_bringing_back_michael/) to using MJ system in 7.99.* versions (Minecraft 1.11.2+)

**Comment by radfast** [comment] 2018-03-10 21:33
> Buildcraft developers returned to using MJ system in 7.99.* versions (Minecraft 1.11.2+)

oho thank you, I did not know that.  We'll have to restore MJ compatibility in those versions then, shouldn't be too hard I hope because we have it working well in 1.7.10.

**Comment by radfast** [comment] 2018-03-10 21:36
>  our Machines take like 1 EU/t, and that is the lowestof lowest Tier of IC2. IC2 Batboxes emit 32 EU/t, so maybe the Energy Ratio is a bit strange. Like IC2 has proper Generators for "Household Electricity" while Galacticraft has a Power Usage to the equivalent of those tiny Calculator/Wristwatch Batteries in comparision

I'll look into this, thank you :)
