### ISSUE TITLE
Tinker's Construct Stone Torch Works on Moon

### ISSUE THREAD

**Issue by Mochnant** [micdoodle8/Galacticraft#1396] opened 2015-01-20 21:36 UTC
The Tinker's Construct (https://github.com/SlimeKnights/TinkersConstruct) stone torches (1 stone rod + 1 coal) work on the Moon (likely all planets/space).  They do not "fizzle out" like standard Minecraft torches, which I assume they should based on burning coal.

**Comment by radfast** [comment] 2015-01-20 23:22
Yes, any non-vanilla torch will work in space.  This is a duplicate of #413.

There is no way for us to fix this - at least, a fix would involve us creating a new "unlit" version of the Tinker's Construct torch, I mean drawing it (making the graphics for it) - that's a lot of work for a small issue like this.

The simple answer is, players who want their Moon / space bases to look good, should not place Tinker's Construct stone torches!

**Closed by radfast** 2015-01-20 23:22 UTC

**Comment by Mochnant** [comment] 2015-01-21 22:29
Sorry for the duplicate ticket!  I also agree 100% that they shouldn't use it to look good on a space base.

My thinking on the bug report (not considering the technical limitations mentioned in #413) was that it makes exploration of space a lot easier than the expensive glowstone torch.  I *can* see that it is not possible and managing all possible light sources in all possible is a deep rabbit hole.  

Sounds like what we need is an object attribute like "requiresOxygen" that all modders could set.  Something at the Forge level, perhaps.

Thanks again.

**Comment by radfast** [comment] 2015-01-22 16:48
I'm not saying it will never happen: because we are an open-source mod, if somebody feels strongly enough about it, they can code it and make a Pull Request.  But like a say, it's a lot of work for a small change, because new torch graphics would be needed.
