### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Bajosi** [micdoodle8/Galacticraft#3182] opened 2018-02-21 15:18 UTC
Minecraft version:1.12.2
Galacticraft version:4.0.1.139
Forge version:14.23.2.2618

Single player (SSP) or Multiplayer (SMP): SSP

Galacticraft add-ons and other mods installed:YES / JUST EXTRAPLANETS

Please provide screenshots / crash report / log as needed.
[crash-2018-02-21_17.08.45-client.txt](https://github.com/micdoodle8/Galacticraft/files/1744499/crash-2018-02-21_17.08.45-client.txt)
[crash-2018-02-21_17.06.36-client.txt](https://github.com/micdoodle8/Galacticraft/files/1744508/crash-2018-02-21_17.06.36-client.txt)

**Comment by radfast** [comment] 2018-02-21 16:00
duplicate of #2972 

Possible Solutions:

1.  reduce your mods list - remove any mods you are not actually using

2.  (advanced)  (may not be possible!)  change your graphics card texture memory size in OpenGL settings

3.  try running the game on a different PC with a more modern gaphics card

4.  remove ExtraPlanets  :(

**Comment by MJRLegends** [comment] 2018-02-21 16:01
The issue isnt mod related its to do with not having enough GPU ram free

**Closed by radfast** 2018-02-21 16:00 UTC

**Comment by radfast** [comment] 2018-02-21 16:02
each mod adds more textures to the atlas, and ExtraPlanets adds some large textures ... this one reported is 1024x1024

(and yes I know GalacticraftCore has a couple of those too...)

**Comment by Bajosi** [comment] 2018-02-21 16:02
sometimes i can play but sometimes it doesnt work.

**Comment by radfast** [comment] 2018-02-21 16:04
try adding **foamfix** mod, it can maybe help with memory issues if you are on the cusp of having it working

**Comment by MJRLegends** [comment] 2018-02-21 16:09
I will see what i can do to reduce texture sizes for ExtraPlanets but your gpu is quite out dated and you'd probably find it difficult to even play modern first player shooters for example too. 

ExtraPlanets has a lot of high resolution models and textures for certain things.

Indeed as radfast example foamfix will help. The reason you can play some times as some times the gpu ram will have less in so more space for textures and some times it will be quite full so will reach 100% before mc has loaded all its textures

**Comment by Bajosi** [comment] 2018-02-21 16:13
when i try to play in 1024x768 it gives error before loading textures. i changed it to 1280x720 and it can load all textures and i can play. i think i fixed my problem.. thanks for helping
PS i know this gpu is very bad :)
