### ISSUE TITLE
Add to Direwolf20?

### ISSUE THREAD

**Issue by thebrunswickian** [micdoodle8/Galacticraft#3867] opened 2020-01-27 04:37 UTC
REVIEW THE GUIDELINES - see [Contributing](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) link on right side.

Minecraft version: 1.12.2
Galacticraft version: Latest

I am attempting to install Galaticraft to the Direwolf20 1.12 modpack to enhance that pack for a personal use server. However I am have very little experience with pack customisation and was hoping for some tips on how to go about the install Galaticraft to the pack.

**Comment by TheQuadShot** [comment] 2020-01-27 04:39
Please post this question on the forums as this is not a bug, also please close this report.
https://forum.micdoodle8.com/index.php

**Closed** 2020-01-27 04:40 UTC
