### ISSUE TITLE
[1.7.10] Overlapping tile entities in IC2.EnergyNet

### ISSUE THREAD

**Issue by dj3520** [micdoodle8/Galacticraft#2421] opened 2017-02-26 17:15 UTC
I'm not particularly sure what's going on here but it's as if there are two tile entities in the same block. When viewing the GUI on some of these machines it flashes back and forth between two states, one powered one not.

`[11:40:10] [Server thread/WARN] [IC2.EnergyNet/]: EnergyNet.addTileEntity: micdoodle8.mods.galacticraft.core.tile.TileEntityAluminumWire@1aeea9df (micdoodle8.mods.galacticraft.core.tile.TileEntityAluminumWire@1aeea9df) is still conflicting with micdoodle8.mods.galacticraft.core.tile.TileEntityAluminumWire@2f4eed0 using the same position (overlapping), aborting`

I'll spare you some extra lines of reading and say this happens for the following (but not limited to this list.)
TileEntityAluminumWire
TileEntityOxygenSealer
TileEntityElectrolyzer
TileEntityOxygenCollector
TileEntityMethaneSynthesizer
TileEntityOxygenStorageModule
TileEntityGasLiquefier
TileEntityOxygenCompressor

I feel like I should mention **this is on my space station** and I _think_ it only happens with machines that are there.

I did a bit of looking up and found `Update on this, I spoke to the ic2 classic dev a he pointed out that there is an event that is fired in the tile entity for on chunk unload, ic2 expects on this event the tile to be unloaded from the energy net, the next build should fix this.` on [this page from another mod](https://minecraft.curseforge.com/projects/power-converters3?comment=29)

EDIT: Whoops forgot this is v466

**Comment by radfast** [comment] 2017-02-26 17:49
Which IC2 version?

**Comment by radfast** [comment] 2017-02-26 17:58
Galacticraft correctly fires IC2 API's EnergyTileLoadEvent and EnergyTileUnloadEvent, and has done since the beginning.  (Otherwise Galacticraft wiring with IC2 machines just would not work at all.)

The issue here seems more likely to be some type of chunk loading/unloading issue resulting in tileEntities not being invalidated.  Possibly the same issue as #2385.  Is this on a server/client setup?  Please provide precise (relevant) details of your setup, especially if you have Thermos / Bukkit / etc on top of standard Forge.

Please also eliminate all mods except IC2 and GC and see if the issue still occurs - obviously save your world first, or it will be corrupted when you remove mods.

**Comment by dj3520** [comment] 2017-02-26 18:25
>Which IC2 version?

industrialcraft-2-2.2.827-experimental

server/client no bukkit

>Please provide precise (relevant) details of your setup

It's been a while 😆 https://youtu.be/hpbZHUHQFxs

Tried to reproduce clientside with only IC2 and GC v467 and no luck. I think it's chunkloading dependent.

**Comment by radfast** [comment] 2017-02-26 19:37
> EDIT: This might be a difficult one. Restarted the server and it's gone.

Can we explore this some more?  What condition on the server makes it occur?  Maybe it's only seen if the server has been running for 10 hours?  Or there was some prior error in another mod, and it started to go wrong after that?

**Comment by dj3520** [comment] 2017-02-27 16:10
>Can we explore this some more?

I'd imagine it'll come back again so of course. A restart just stops it from happening for a while.

>What condition on the server makes it occur?

I don't know exactly what but I think it's related to chunkloading. I only have one chunkloader in my space station (railcraft) and the only machines that seem to exhibit this behavior are the ones not inside a chunkloaded area.

>Maybe it's only seen if the server has been running for 10 hours? Or there was some prior error in another mod, and it started to go wrong after that?

Unfortunately the logs were automatically cleared so I don't know. If/when it happens again I should be able to figure this out.

**Comment by radfast** [comment] 2017-03-07 14:24
I still think this is likely the same issue as #2385.

If so, it's related to:
* leaving and returning to the dimension in rockets or other ways (teleport, nether portals, etc) - when you leave, chunks outside the chunkloaded area are supposed to be unloaded
* another mod - most likely a wiring mod, maybe IC2 itself - wrongly reloading those chunks (which are supposed to be unloaded) over and over

1.  Please list all mods, and highlight any wiring / power / pipe / itemduct mods

2.  Please test the types of things I just described, and see if you can cause this issue to occur again

---

If you **can't** cause it to occur again, then this should stay closed as a one-off occurrence which is probably not caused by GC at all.

If you **can** cause it to occur again, please re-open.

**Closed by radfast** 2017-03-07 14:24 UTC
Labels: 1.7, missing info

**Comment by dj3520** [comment] 2017-03-07 21:41
I _did_ see it happen another time, but noticed it was present in a larger way (buildcraft pipes also flickered between full and empty.

[modlist](http://net.dj3520.net:8000/minecraft/modlist.btm)

> Maybe it's only seen if the server has been running for 10 hours?

I believe it happened once when I was on the overworld and used the sync mod to get to my space station just after a restart. However if I restart the server and spawn in the space station this doesn't happen. Again, everything in the chunkloaded area was fine. [Here's a quickly made quick tour.](https://youtu.be/JUj3o0soO3E)

**Comment by radfast** [comment] 2017-03-07 22:10
Wow, thank you for making the tour.  I very much like that you have working systems for continuous production of everything you need - especially the automatically adjusted production of LOX.

Your base is kinda too large for me to use for bug testing purposes - too many different machines, too much going on...

But you have given very useful info:
- the Oxygen Sealers and other tiles **outside** the chunkloader radius derp
- the Oxygen Sealers and other tiles **inside** the chunkloader radius are OK

That's especially interesting for the row of 4 Oxygen Sealers which are next to each other - 2 are inside the chunkloader radius, 2 are outside.

What I am now interested in is identifying all of the chunk-to-chunk connections at that boundary (bearing in mind, they could follow indirect routes).  So for the Oxygen Sealers themselves I'm seeing GC wires and GC oxygen pipes, connecting between the two chunks.

If you have time, I think what could really help me would be if you can make a few test chunks at your chunkloader edge - best make these new clean chunks with no other machinery in them, so maybe use another Railcraft chunkloader positioned something like 128 blocks away from your base, to make sure all is clean aroud there.   Then run some of your different connection types from 1 chunkloaded chunk to 1 non-chunkloaded chunk there.

For example like this:

_R_
G#2
_B_

So in this each letter is one chunk, viewed from above:
* _ is an empty or unbuilt chunk
*  # is the chunk with the Railcraft chunkloader in it (set to load 1 chunk only)
*  R is a chunk which has Railcraft connections, for example railtrack and any other stuff you can think of, running into the # chunk
*  G is a chunk which has Galacticraft connections, for example alu wire and oxygen pipe, running into the # chunk, maybe place an Oxygen Storage Module and Energy Storage Module in the # chunk and sealers in the G chunk
*  2 is the same with IC2 machines and wires running into the # chunk
*  B is the same with Buildcraft pipes

Hope this makes sense

Then I'm interested to know which of these chunks R, G, 2, B derps...

**Comment by dj3520** [comment] 2017-03-08 00:15
>Wow, thank you for making the tour.

Easy video. Can't understand why it's stuck at 360p though. Also serves as something I can look back upon when I'm miles ahead of where I am now.

>I very much like that you have working systems for continuous production of everything you need - especially the automatically adjusted production of LOX.

I didn't explain it in the video but the same goes for the methane and hydrogen. The amount of machines allowed to run changes on how full the tanks are. It's also why I enjoy my redstone fork. Otherwise I'd have to cut energy to machines to control them.

>Your base is kinda too large for me to use for bug testing purposes - too many different machines, too much going on...

What about if I forget the massive free-range tree farm? Haha anyway...

>But you have given very useful info:
the Oxygen Sealers and other tiles outside the chunkloader radius derp
the Oxygen Sealers and other tiles inside the chunkloader radius are OK

Additionally when the anchor ran out, everything derped.

>another Railcraft chunkloader positioned something like 128 blocks away from your base

Gah. Don't have an angel block so I'd need to build out that far.

>L is the chunk with the Railcraft chunkloader in it (set to load 1 chunk only)

Not particularly sure how to do that (unless you use anchor sentinel) by default it's a 3x3 of chunks iirc

>Then I'm interested to know which of these chunks R, G, 2, B derps...

Through seeing this happen I can _guess_ the following
G and B will most likely derp
L will be fine because it never unloaded.
R and 2 are unknown (but a minecart might disappear)

Hopefully it doesn't take long to get this tested.

UPDATE: Just caught it in the act ([VIDEO HERE](https://youtu.be/iGuAp6e8vJg)) OPIS reports correct count of machines, so they're not actually on top of each other...

**Comment by radfast** [comment] 2017-03-08 00:27
ok the video very clearly shows the derping!

It's possible that Opis is only running on one side of the derp, if that makes sense?  So it only sees one version of each machine.

IF you can find a way to build G B L R 2  - I guess using a 3x3 chunk boundary and building G B R 2 outside that - then I think G will not derp :)   What I want to see is which of the others does derp ...

**Comment by dj3520** [comment] 2017-03-08 00:54
wonder if this happens on my testing server (which is creative) would be easier to test

Opis saw the right amount of derping machines (water electrolyzers were derping, but still counted 12)

Oh I see what you're trying to determine (seperate mod per chunk to find strange chunk loading)

**Comment by radfast** [comment] 2017-03-08 02:01
This is based on the theory that it's some type of connecting item which causes the strange chunk loading.

It is also possible that it's another mod - including IC2 itself - making use of the GC wiring to do its own wacky connections.

(If IC2 is present, GC wiring works as - essentially - another type of IC2 cable, as well as doing everything else it does.  So if IC2's own cables derp, that can maybe make GC cables derp as well, when IC2 is installed.)

**Comment by radfast** [comment] 2017-03-14 16:01
Any update on this, please?  Your video shows the issue clearly at the Railcraft chunkloader boundary.  Seems to me your testing is going to be the best way of finding and maybe fixing the cause of this.

If you don't have time, you could maybe zip up and send me your world (`save` folder for this world, `mods` folder, `configs` folder, and all other `.dat`, `.nbt` and similar files if your mods are putting them in other places).  I do not need standard Minecraft files which come in all Minecraft installations, for example `versions` or libraries.  And I probably do not need your DIM0, DIM-28 and other numbered dimension folders, except for the space station dimension itself.

**Comment by dj3520** [comment] 2017-03-15 18:09
While I do have time I'm not able to reproduce this on my testing server and it's probably only a matter of time before I look into chunkloading the entire base with OpenComputers (uses just energy instead of enderpearls)

Meanwhile I figure the only way this might be solved is by [sharing the world](http://net.dj3520.net:8000/servitup/OAU%20(trim4gc2421)%203-14-2017%2021-15-44-75.zip) for you to look at as you've requested. (Holy cow the original backup was just under 3GB and this file is 121MB) If you need anything else for testing purposes just let me know.
