### ISSUE TITLE
Space race GUI opens on world creation

### ISSUE THREAD

**Issue by Brycey92** [micdoodle8/Galacticraft#1554] opened 2015-04-07 16:00 UTC
Every time I create a world, whether creative or survival, the space race menu opens. I am running GC build 312.

**Comment by radfast** [comment] 2015-04-07 16:03
That's intended in new worlds.  When you close it, it will not now open again (unless deliberately opened from the Options menu).

**Comment by Brycey92** [comment] 2015-04-07 19:51
Ah, ok. I assumed it was part of the bug recently fixed where it would open at random times. May I suggest a bit of text on world-creation in the space race menu, though, like "Welcome to your new world! Create your flag and start your race to space!"

**Comment by halvors** [comment] 2015-04-07 20:43
It opens whenever the server is restarted.

**Comment by dj3520** [comment] 2015-04-07 20:48
Did you make a team? I found mine opens up every time I join unless I've created a team.

**Comment by halvors** [comment] 2015-04-08 07:23
No i didn't. Or i did a while ago, but that suddenly disappeard.

**Comment by radfast** [comment] 2015-04-08 09:01
I'm going to re-open this issue as it seems like there may still be some problems.

The currently intended behaviour is that this interface opens once per player per game.  (And after that it is accessible from the bottom right in the Options menu.)

**Comment by radfast** [comment] 2015-04-08 09:45
@halvors which version are you using?  Please check whether the same issue occurs in the __latest__ version on a server.  (Note: a server can update to the latest version even if the players do not.)

**Comment by halvors** [comment] 2015-04-08 10:14
I'm sure that the version is 3.0.11.315 on both the client and the server. I will check when i get home :+1:

**Comment by dj3520** [comment] 2015-04-08 17:13
@radfast What are the conditions the game checks for to determine opening the GUI?

**Comment by radfast** [comment] 2015-04-08 18:08
@dj3520  only one check, whether it was opened already for the player.  Like all other player information, it will be saved on a 'per world' basis.  If it's opening more than once per player per world, that's a sign that something more serious may be wrong like the player data not saving correctly.  There's no point speculating about that until @halvors (or someone else?) confirms that it's happening in the latest Galacticraft version.

**Comment by halvors** [comment] 2015-04-08 22:37
Negative. Does not happend on server with latest build. Even if the server was restarted. :+1:

**Closed** 2015-04-11 16:27 UTC
