### ISSUE TITLE
Galacticraft universe map loads all SpaceStations?

### ISSUE THREAD

**Issue by SirWilli** [micdoodle8/Galacticraft#2001] opened 2016-01-10 06:38 UTC
hey,

for which reason does galacticraft load all space stations if someone starts a rocket and gets into the universe map instead of loading the world he goes to?

The loading of many space stations is very performance intense.

**Comment by radfast** [comment] 2016-01-10 13:45
Please provide evidence for:
* all the space stations being loaded
* the performance issue you mention

AFAIAA Galacticraft does not load any dimensions in the galaxy map.  And anyhow, loading a dimension is not performance intense.

What Galacticraft **does** do, during the rocket countdown and rocket flight - a period of around 40 seconds to 1 minute - is slowly generate map chunks in the **possible destination planets** in the area where the rocket can land.  This is so that the Moon / Mars / Asteroids will be pregenerated - similar to Overworld spawn area - when the player first arrives.  Unless you have a crazy server with 100+ players online, this should not cause any noticeable lag.  Galacticraft generates 1 or 2 chunks per tick, only - the load will be similar to a player running / flying across an ungenerated region of the Overworld map.  And if you do **not** let Galacticraft do this, then it must generate 300+ chunks when the player lands on the Moon / Mars / Asteroids which will cause a lag spike at that point.

**Comment by SirWilli** [comment] 2016-01-10 17:38
Hm, if it shouldn't load all dimensions then it seems to be an issue on cauldron side. 
I already tested it with forge but it doesn't seem to show a message if a world gets loaded or unloaded so I can't really see if it loads them too.

I currently have the issue that the rockets start a world load/unload loop until the server runs out of memory and crashes.
http://pastebin.com/raw/pnk6Tq0L

**Comment by dj3520** [comment] 2016-01-10 17:45
How many space stations exist? That log shows the possibility of 1,216
dimensions!

**Comment by dj3520** [comment] 2016-01-10 17:51
Update: log shows max space station dimension 1334!

**Comment by SirWilli** [comment] 2016-01-10 17:52
38 space stations but +90 other dimensions

**Comment by radfast** [comment] 2016-01-10 18:58
OK that crash report I can work with.  You should have given that to me in the first post.

I will look at this and try to identify the issue (if it is a Galacticraft issue).

**Comment by radfast** [comment] 2016-01-10 19:19
Hmm I apologise: it looks like Galacticraft is briefly attempting to load **all* of its dimensions, as part of the rocket function.  It does this to check that the dimension is available on the server and is a Galacticraft dimension (so, not overridden by some other mod).

However, this should **not** cause lag or other problems, it is not loading chunks in the dimensions.  Loading a dimension with no chunks should create no load at all - really nothing is "loaded" it is just flagged as an available dimension.

I am still looking into this.

**Comment by radfast** [comment] 2016-01-11 03:32
The brief loading of dimensions is activating any chunk loaders present in the GC dimensions.
(Galacticraft Launch Controllers themselves act as chunk loaders.)

This is placing a lot of extra load on the server suddenly, if you have a chunk loaders in those GC dimensions.  Where there are chunk loaders, the relevant chunks all suddenly become active together and have to be loaded off disk and the map built etc.  I don't think it's a world load/unload infinite loop, just 40+ iterations, one iteration for each GC dimension, but 40 iterations may be enough to load the server severely if there are chunk loaders.

I am thinking about how we can reduce or avoid this problem.  It's not going to be easy.
* GC needs to know which destinations are reachable with the rocket tier, before it draws the celestial map, because some planets (etc) are shown as reachable and some as unreachable.
* The tier of rocket can be different for each dimension
* Currently that tier information is internal to the dimension (the WorldProvider for it) so that it can only be obtained if the dimension is first loaded.  This also in theory allows the dimension to change rocket tiers (e.g. as time passes, or if something on the dimension is unlocked) although I don't know if any addons use that, all GC's own dimensions have fixed rocket tiers.
* In theory dimensions could also allow themselves to be reached by rocket tier 2 only (not 1 or 3), although GC's own model is that the higher tiers can always do what the lower tiers can do.

I can see that changes to this system are needed to fix the performance issue, although with a few simple rules we may be OK.  2 simple rules: rocket tiers are fixed for each dimension, and if a Tier 2 rocket (for example) can reach the dimension then any *higher* tier can also reach it no problem.

Meanwhile I have made a small fix 8bdb38f, which will be in build 412.  This will not load space stations which the current player (riding the rocket) does not have permission to access.  Make sure you have this setting true:
> ```    B:"Space Stations Require Permission"=true```

Also note that any player who is opped can access all space stations, so this high load situation will be recreated if an opped player rides a rocket (or uses ```/dimensiontp```).

**Comment by radfast** [comment] 2016-01-11 03:39
Another solution could be to set some of the GC dimensions as static loaded dimensions in the config, note you should use GC version 411 or later for that to avoid static dimensions keeping large numbers of chunks loaded.

The static loaded dimensions will have chunk loaders active all the time.  But at least you then won't have a situation (except at server start) where they all come online together.

**Comment by SirWilli** [comment] 2016-01-11 09:02
Where can I get build 412 if jenkins is down?

**Comment by Slind14** [comment] 2016-01-11 10:45
What about loading the dimensions once at server start to gather the information and cache it, or could  planets be created later on?

**Comment by radfast** [comment] 2016-01-11 12:28
I can't even *make* build 412 if Jenkins is down.  You could build it yourself from the code on the Github if you have a friendly Java dev.

@Slind14 loading the dimensions once at server start will activate all the chunk loaders - that's basically the same as making static loading dimensions.  On a large server like SirWilli's server, I expect the server admins do not want to load all the space stations of all the players, otherwise you will have chunk loaders running for players who are maybe offline for 2 weeks.

**Comment by Slind14** [comment] 2016-01-11 12:39
hmm ok and forcing a worldunload doesn't work?

**Comment by radfast** [comment] 2016-01-11 12:43
@Slind14 thank you I know what to do, it's more a question of making sure the changes I plan do not break anything in existing GC addons, that is the reason for discussing the details in public.

A world unload will not solve the problem of 40+ dimensions simultaneously demanding to load their chunk-loaded chunks, which is the issue reported by SirWilli.

I am planning a solution which does not involve loading the dynamic dimensions at all.

Build 412 does not load all the dimensions unless - for some reason, e.g. being opped - the player has permission to access all the space stations.  For normal players who can only access 1 or 2 space stations, build 412 will already solve the problem.

**Comment by Slind14** [comment] 2016-01-11 12:51
sorry, I'm just trying to understand :)

**Comment by Slind14** [comment] 2016-01-11 12:58
For reference, going to compile the latest source for comparison and edit it in.
Steps: logging in at 13:50, placing a rocket and starting, loading/unloading loop starts once the catalog opens. The loop it self is probably caused by cauldron, due to more aggressive world unloading.
![](https://i.imgur.com/oKLEWKy.png)
log: https://gist.github.com/Slind14/aa29a8474f108280c4c7

**Comment by radfast** [comment] 2016-01-11 13:03
OK here's the plan.  From build 413 there will be fixed rules for space station rocket tier access.

* Space Stations orbiting an underlying planet (e.g. Overworld) will be accessible by players on **other planets** by the same tier rocket as is needed for the player to reach the underlying planet.
* For players who are already **on** the underlying planet (or on another space station in orbit around the same planet) the space stations will be accessible by that player using any rocket including a Tier 1 rocket.  Config option to force this also - even in this situation - to be the same tier as for the underlying planet.

That is more logical anyhow.  If you need a Tier8 rocket to reach a moon of Saturn from the Overworld, you shouldn't need a Tier8 rocket to transfer from one space station in orbit round that moon to another.  (But maybe a Tier8 rocket is what you have there anyhow, that's fine.)

**Comment by radfast** [comment] 2016-01-11 13:05
I am uploading temporary builds 412a - which are basically 412 built manually by me - to my Dropbox, I will make the links available very shortly.

@Slind14 was the person who travelled into space opped, when you ran that test?  Is it on SirWilli's server with the 40+ space dimensions?

**Comment by Slind14** [comment] 2016-01-11 13:07
Is there a specific task I need to run pre building it? I did checkout the sub module and ran a normal gradle build.

**Comment by Slind14** [comment] 2016-01-11 13:09
Its a copy of the server and yes the user was opped, but gonna deop for the 412a.

**Comment by radfast** [comment] 2016-01-11 13:25
Download links:
* [GalacticraftCore version 3.0.12.412a](http://s000.tinyupload.com/index.php?file_id=59551121696600070106)
* [GalacticraftPlanets version 3.0.12.412a](https://www.dropbox.com/s/r6cr39vd7no9wle/GalacticraftPlanets-1.7-3.0.12.412a.jar?dl=0)
* [MicdoodleCore version 3.0.12.412a](https://www.dropbox.com/s/tvr5xsr3e9rofkh/MicdoodleCore-1.7-3.0.12.412a.jar?dl=0)

**Comment by Slind14** [comment] 2016-01-11 13:26
thanks, the first link is broken

**Comment by Slind14** [comment] 2016-01-11 13:48
unfortunately its unchanged. I made sure I'm not op and I do not have any space stations. Edited it into the previous post.

**Comment by BlesseNtumble** [comment] 2016-01-11 14:04
Radfast, Dev version?

**Comment by radfast** [comment] 2016-01-11 15:39
@Slind14 thank you the logs you posted are great, showing the dimensions loading and unloading.  

At the end of the 412a test I see a group of 4 dimensions loading and unloading over and over and over - are those ones which you as a de-opped player have access to?

**Comment by radfast** [comment] 2016-01-11 15:42
@Slind14 that's space station numbers 11, 226, 766 and 1251.  You would have to look inside the ```world/data``` folder at the individual spacestation.dat files to figure out the name, owner and invited players for each of those.  (Some time I should make a tool to do that.)

overall it looks like there is a lot more dimension loading happening than I expected.  I'm wondering if some of it is an interaction with Tardis mod, but anyhow let's see where this ends up.

**Comment by Slind14** [comment] 2016-01-11 15:44
I'm not familiar with galcticraft. I did look at the earth and moon, there were no stations listed. Is that the way to travel to them?

I did the same test with forge only, here is the log: https://gist.github.com/Slind14/19aaeffbd08fc79375cb (I logged in and out a few times.)

I'm certain now, that the main issue is the aggressive world unloading from bukkit/spigot (cauldron).
Do you know why it is loading the world again after it being forcibly unloaded, causing a loop?

**Comment by Slind14** [comment] 2016-01-11 15:49
The world data directory contains villages.dat and eh.worldStorage<id>.dat, which are empty besides the id:
![](https://i.imgur.com/ATrt3Fk.png)

**Comment by radfast** [comment] 2016-01-11 16:21
The ```world/data``` folder should contain, in addition to ```villages.dat```, a large number of files named similarly to: ```spacestation_4.dat```.  Also ```GCFlagData.dat``` and a few other GC files.  It may be that your Bukkit-modded server configuration places mod .dat files in a different location, a search by filename should easily find them.

In Galacticraft to access a station:
1.  ride a fueled rocket to the top of the atmosphere  (or use the ```/dimensiontp``` command as a shortcut) -> the Solar System map will open
2.  in the Solar System map, click on the Overworld (the Earth), that should zoom in to it and show you orbiting symbols for space stations and the Moon.   If your player did not yet make a space station, you should also have the option to 'Create' on the right hand side.  That has a materials cost unless you are in Creative mode.
3.  Click on the orbiting symbol for space stations, and it should present you on the top-right of the GUI with a list, by name, of one or more space stations which you can access
4.  Select one of those space stations, then click the green 'Launch' button in top right of the GUI, alternatively use the ENTER key.

My question to you about those 4 dimension IDs can maybe be answered at step 3: it will show you there the stations which your player can access, if there are 4 listed then we have the answer I am expecting :)

**Comment by Slind14** [comment] 2016-01-11 16:24
https://i.imgur.com/9gUtkOy.png
https://i.imgur.com/LJ6gYog.png

Could it be that those are empty space stations?

**Comment by radfast** [comment] 2016-01-11 16:34
> I did the same test with forge only, here is the log: https://gist.github.com/Slind14/19aaeffbd08fc79375cb (I logged in and out a few times.)

> I'm certain now, that the main issue is the aggressive world unloading from bukkit/spigot (cauldron).
Do you know why it is loading the world again after it being forcibly unloaded, causing a loop?
For me this whole matter is way above my experience level (on the dev side) and I struggle with it. 

Thank you for this, I am still investigating.  I will test on a Cauldron platform.

Please show me your ```configs/galacticraft/core.conf``` and also ```bukkit.yml``` and ```spigot.yml```.  I know some server owners like to keep these setup details confidential, you can email them to rradfast@gmail.com if you prefer.

Are you using FastCraft or any Bukkit plugin (such as ClearLag) which claims to optimise performance?

**Comment by Slind14** [comment] 2016-01-11 16:34
hmm, I don't see  anything regarding space stations :(
https://i.imgur.com/5jObzQj.png
https://i.imgur.com/3VkKVzr.png

**Comment by Slind14** [comment] 2016-01-11 16:36
galacticraft https://gist.github.com/Slind14/7ea71491cf2e3e19d3b9
bukkit https://gist.github.com/Slind14/6b7c5c31b00624c92b6e
spigot https://gist.github.com/Slind14/c95deb4b229ba6d82648

**Comment by radfast** [comment] 2016-01-11 16:38
Your player's space station situaton is weird: it looks like you do not have access to any stations, therefore it should offer you the ability to create one of your own when the Overworld is selected in that map.  I did notice in the logs a bunch of 'Info' type errors about space stations lacking world providers and the default being used, which suggests space station save data is missing (at least on your copy of the server).

Anyhow, I'm not going to worry about that now.  That is not the issue here - the issue must be, as you say, connected with Cauldron / Spigot.  We want Galacticraft to run smoothly on large public servers as well as small, so I will keep looking at this until we have a more solid solution.

**Comment by Slind14** [comment] 2016-01-11 16:48
@radfast thank you so much for looking into this sincerely. You are one of the very few that is taking the time to improve and fix things which are not easily and solely with the mod it self reproducible and doesn't turn the back on the user once a server environment is the case. Highly appreciated :)

**Comment by radfast** [comment] 2016-01-11 16:48
aargh.  I don't like the look of these, I am not going to troubleshoot for these:
*  **aperf**
*  **ChunkManagerForge**
*  **ChunkPurge**
or anything similar.  By the sound of it, those mods could be altering chunk or dimension loading + unloading systems.  They could even be conflicting with each other, are you supposed to have them all running side by side?

----

The Forge Log with a lot of space station info each time you login is just a debug message that I left in GC by accident when building 412a for you guys.  That is Galacticraft verifying that its mod-specific player data for the logged in matches the mod-specific saved spacestation data, it's like a data cleanup check.  It has nothing to do with the issue.

To recreate the server load situation, you would need to repeatedly ride rockets to the top of the atmosphere, or use the ```/dimensiontp``` command in-game as a shortcut.  (It is also usable from console if you specify the player name.)

I recommend test GC 412a:  (1) in Forge only   (2) with Forge + Cauldron  - in both cases, with a reduced modlist (without those ones I have listed above).  Each time do an A/B test for when the player is opped (= can access 40 spacestations) and when the player is not opped.

**Comment by Slind14** [comment] 2016-01-11 16:50
I can reproduce it without those, they sound worse as they are. Give me second and I'll upload a screen and log without those.

**Comment by radfast** [comment] 2016-01-11 16:53
Thank you for your kind comment :)

Like I say, we intend for Galacticraft to run smoothly on public multiplayer servers, as that's probably the most fun way to play the mod.

It helps that in a previous life, I was a server admin/manager on one of the largest, heaviest usage public servers out there...  So I understand the problems you face.

**Comment by radfast** [comment] 2016-01-11 16:55
I'll be back in a few hours.

**Comment by Slind14** [comment] 2016-01-11 17:00
Cauldron without those mods and all other "custom" mods.

![](https://i.imgur.com/mhHFUD8.png)
log https://gist.github.com/Slind14/ee957a0f10b9fc1f6a96

Forge only including those mods, does not have the issue. (tested before https://github.com/micdoodle8/Galacticraft/issues/2001#issuecomment-170591833)

Will do more testing with less mods.

**Comment by Slind14** [comment] 2016-01-11 17:47
Interesting:

Cauldron with the following mods is still loading/unloading but the memory leak is gone
![](https://i.imgur.com/xxsBluZ.png)
log https://gist.github.com/Slind14/eabedc36a9e007dc7db8
```
1.7.10
4Space-4.1.9.jar
CodeChickenCore-1.7.10-1.0.7.47-universal.jar
CoFHCore-[1.7.10]3.0.3-303.jar
Dalek Mod
Dalek_Mod_1710.jar
darkcore-0.3-45.jar
GalacticraftCore-1.7-3.0.12.412a.jar
GalacticraftPlanets-1.7-3.0.12.412a.jar
MicdoodleCore-1.7-3.0.12.412a.jar
SGCraft-1.9.3-mc1.7.10.jar
tardismod-1.7.10-0.99-207.jar
```

**Comment by Slind14** [comment] 2016-01-12 00:08
We could identify the memory leak issue. It is a leak in the forge source. If a world with non released tickets is being unloaded it is staying as reference forever, even if the tickets do not have any outer reference.

**Comment by radfast** [comment] 2016-01-12 01:16
Where in Forge source?  Which class?  Any references to this I can read about?

If it's a simple fix, I can probably write code in Galacticraft to hotfix it.

**Comment by radfast** [comment] 2016-01-12 01:18
Also I would guess that mod removal fixed the problem because removing the mod deleted whichever block/tile in the world was creating a chunk loader.  It didn't really fix the underlying problem, just removed the trigger.

**Comment by SirWilli** [comment] 2016-01-12 01:21
Latest build seems to have an NPE:
```
[02:17:35] [Server thread/INFO]: SirWill[/178.26.43.31:56603] logged in with entity id 14050 at ([DIM-28] -4707.5, 70.4, 3800.5)
[02:17:36] [Server thread/INFO]: Loaded player file for SirWill
[02:17:36] [Server thread/INFO]: Sending server configs to client for com.enderio.core.common.config.ConfigHandler
[02:17:36] [Server thread/INFO]: Syncing data to client...
[02:17:36] [Server thread/INFO]: Sync Complete...
[02:17:36] [Server thread/INFO]: Checking SS: SirWill 1216
[02:17:36] [Server thread/INFO]: Player does not own station: Station: Legion96 with home planet 0
[02:17:36] [Server thread/ERROR]: Exception caught during firing event cpw.mods.fml.common.gameevent.PlayerEvent$PlayerLoggedInEvent@1263fd11:
java.lang.NullPointerException
	at micdoodle8.mods.galacticraft.core.dimension.SpaceStationWorldData.updateSSOwnership(SpaceStationWorldData.java:359) ~[SpaceStationWorldData.class:?]
	at micdoodle8.mods.galacticraft.core.dimension.SpaceStationWorldData.checkAllStations(SpaceStationWorldData.java:370) ~[SpaceStationWorldData.class:?]
	at micdoodle8.mods.galacticraft.core.network.ConnectionEvents.onPlayerLogin(ConnectionEvents.java:48) ~[ConnectionEvents.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_211_ConnectionEvents_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1492.MyM.4]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:1.7.10-1492.MyM.4]
	at cpw.mods.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:571) [FMLCommonHandler.class:1.7.10-1492.MyM.4]
	at net.minecraft.server.management.ServerConfigurationManager.initializeConnectionToPlayer(ServerConfigurationManager.java:235) [oi.class:?]
	at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:190) [NetworkDispatcher.class:1.7.10-1492.MyM.4]
	at cpw.mods.fml.common.network.handshake.NetworkDispatcher.completeHandshake(NetworkDispatcher.java:465) [NetworkDispatcher.class:1.7.10-1492.MyM.4]
	at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:21) [HandshakeCompletionHandler.class:1.7.10-1492.MyM.4]
	at cpw.mods.fml.common.network.internal.HandshakeCompletionHandler.channelRead0(HandshakeCompletionHandler.java:11) [HandshakeCompletionHandler.class:1.7.10-1492.MyM.4]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:1.7.10-1492.MyM.4]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
```

**Comment by SirWilli** [comment] 2016-01-12 01:23
I will leave your question for slind as he worked on that fix.

**Comment by radfast** [comment] 2016-01-12 01:23
Thank you for NPE report, I'll get on that right now.  Thank you to Slind for all his help.

**Comment by radfast** [comment] 2016-01-12 02:24
> We could identify the memory leak issue. It is a leak in the forge source. If a world with non released tickets is being unloaded it is staying in reference, even if the tickets do not have any outer reference.

>Where in Forge source? Which class? ForgeChunkManager? Any references to this I can read about?  If it's a simple fix, I can probably write code in Galacticraft to hotfix it.

I think I see one of the bugs, at least.  ```ForgeChunkManager.loadWorld``` is adding more [world, ArrayList<ticket>] mappings each time a dimension is loaded, because each time a dimension is freshly loaded it has a different world - it's not the same Java object, and World.equals(obj) will return false even if the dimension is the same.

If you're running Cauldron, presumably it's KCauldron and the code we are interested in for the loading and unloading over and over looks something like this [Forge 1291 code](https://gitlab.prok.pw/KCauldron/KCauldron/blob/495e0435d567c0ed57ad13ca95ae5f91d854ec3d/patches/net/minecraftforge/common/DimensionManager.java.patch)

**Comment by radfast** [comment] 2016-01-12 04:37
**Download links for version 413a**: fixes the NPE and other stuff:
* [MicdoodleCore](https://www.dropbox.com/s/dq1mm7c75hp36ho/MicdoodleCore-1.7-3.0.12.413a.jar?dl=0)
* [GalacticraftCore](http://s000.tinyupload.com/index.php?file_id=07118995117372599371)
* [GalacticraftPlanets](https://www.dropbox.com/s/pnc28mk4m2r39q8/GalacticraftPlanets-1.7-3.0.12.413a.jar?dl=0)

**Comment by SirWilli** [comment] 2016-01-12 04:38
Ah, thanks. just started cloning the project^^

**Comment by radfast** [comment] 2016-01-12 04:42
This are unofficial builds taken off my dev platform, they work in my own testing but please do report any more issues you see.  In case of serious issues, you might want to roll back to build 411 off the temporary micdoodle8.com site.

**Comment by BlesseNtumble** [comment] 2016-01-12 06:16
radfast, 
```
@Override
    public int compareTo(CelestialBody other)
    {
        ScalableDistance thisDistance = this.getRelativeDistanceFromCenter();
        ScalableDistance otherDistance = other.getRelativeDistanceFromCenter();
        return otherDistance.unScaledDistance < thisDistance.unScaledDistance ? 1 : (otherDistance.unScaledDistance > thisDistance.unScaledDistance ? -1 : 0);
    }
```

But here should not be so ?:
return otherDistance.unScaledDistance < thisDistance.scaledDistance ? 1 : (otherDistance.unScaledDistance > thisDistance.scaledDistance ? -1 : 0);

**Comment by Slind14** [comment] 2016-01-12 11:37
At this location: https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/common/ForgeChunkManager.java#L551
We added code that would release all non released tickets for this world.

**Comment by radfast** [comment] 2016-01-12 13:43
@Slind14 I agree.

I'm not sure whether that is the sole cause of the issue - since the described issue is only severe with Cauldron installed, not Forge alone - but I agree with you that the tickets are not being cleared.  That must result in a memory leak, maybe worse depending on what is attached to the ticket.  Even when a dimension is unloaded and then reloaded, that will not clear its tickets from the <World, Ticket> map because [this line](https://github.com/MinecraftForge/MinecraftForge/blob/master/src/main/java/net/minecraftforge/common/ForgeChunkManager.java#L399) creates a new entry in that map for the reloaded dimension, because on reloading the dimension the World object will be a different object - a WorldServer is newly created every time a dimension loads.

(I mentioned this in my original draft of [this comment](https://github.com/micdoodle8/Galacticraft/issues/2001#issuecomment-170761566) but edited it out because I wanted to see if you had come up with the same thing ... it does make me nervous to find a bug in Forge!)

Do you think your patch would benefit from an additional line like this?
>  ```tickets.remove(world):```

You could argue it is in theory unnecessary as the keys in that ```tickets``` map are ```WeakReference``` so should be removed anyhow if the world object becomes removable by the Garbage Collector.  But a common coding problem is that mods retain a strong reference to a world object - also known as a 'world leak'.

Anyhow, I think we should report this on the Forge issue tracker - more accurately, you should as you found it!  A quick search seems to show it has not previously been reported.

-----

What technique are you using to patch that change into ```ForgeChunkManager``` at runtime?  If you have the bytecode, or even a re-compiled version of the ```ForgeChunkManager.class``` that would be great to see ... can save me at least an hour of work, as basically I plan to add a list of bytecode instructions to MicdoodleCore for this alongside our other runtime patches.

**Comment by Slind14** [comment] 2016-01-12 17:10
In fact, we left it be due to being a weak ref, your explanation makes sense and we should probably change that along with a few more security checks (e.g. got a npe when the world doesn't exist..).

Do you think forge should fix it, although we couldn't reproduce it with forge only? I'm a little on the fence on weather only cauldron should handle it.

We patched it the same way forge does, with runtime bin patches via. cauldron.

**Comment by radfast** [comment] 2016-01-12 18:43
Hmm.  Maybe ask Cauldron to take care of it.  They do patch bugs in Forge sometimes.  Also you have more chance of seeing the patch included in 1.7.10 that way, I think the Forge devs are only interested in 1.8 now unless something is badly broken in 1.7.10.

**Comment by radfast** [comment] 2016-01-13 03:07
NEW DOWNLOAD LINKS:  (fixes the NPE in Oxygen Sealers; implements the reduction in dimension loading for Celestial Map as discussed in this thread)
* [MicdoodleCore 3.0.12.314a](https://www.dropbox.com/s/s2v44kd19l34m3o/MicdoodleCore-1.7-3.0.12.414a.jar?dl=0)
* [GalacticraftCore 3.0.12.314a](http://s000.tinyupload.com/index.php?file_id=89929972857947768399)
* [GalacticraftPlanets 3.0.12.314a](https://www.dropbox.com/s/i48f87wmrf9w0g1/GalacticraftPlanets-1.7-3.0.12.414a.jar?dl=0)

**Comment by radfast** [comment] 2016-01-13 03:12
This new build 314 should dramatically reduce the original problem of dimension loading - now only the planet dimensions should be iterated when the Celestial Map is created, not any of the space stations.  Iterating the planet dimensions should not create server load, because planet dimensions are all automatically registered as static dimensions (unless a GC Add On borked that) meaning the dimensions should already be loaded and stay loaded.

I'm interested to know if it completely solves the problem - even using the unpatched Cauldron.

If there is still a problem, that suggests there is still some dimension loading being done by GC which I have not caught yet.

I've tested this with all GC dimensions on my test server and all seems good, but as with the other builds on this thread, it will need wider testing by players before it can be considered "stable".

**Comment by BlesseNtumble** [comment] 2016-01-13 06:36
314?
Maybe, 414?

**Comment by radfast** [comment] 2016-01-13 13:30
Thank you @BlesseNtumble I have corrected the description of the links.  The links are - and always have been - to the intended version 414 :)

**Comment by BungeeTheCookie** [comment] 2016-01-13 23:51
Is 414 stable? Also, is this issue present on build 406?

**Comment by radfast** [comment] 2016-01-14 00:19
@BungeeTheCookie - this issue is present on build 406, also present on all GC builds ever made prior to version 414a.

You should only see the issue severely if you have a Cauldron server with a large number of players and dimensions and chunk loaders.  (But I guess it could affect any server on an underpowered machine or which does not have enough memory allocated.)

Version 414a is stable as far as I know - there have been no crash reports.

Normally people are advised to be using the latest Galacticraft anyhow, it should usually be more stable than prior versions, due to a large number bugfixes.

**Closed** 2016-01-14 01:19 UTC
Labels: follow-up please, Priority

**Comment by radfast** [comment] 2016-01-14 01:30
I found the cause of the dimension loading seeming to be in a loop in the OP.  Actually GC was creating its map of rocket-accessible dimensions (which involved hotloading the dimension each time to check) every tick on the server for as long as the player had the map screen open.  Eek!  Fairly shocking, I'm sorry about this I didn't realise before that we were doing this like this.

From version 414a:  building the map should not normally load and unload any dimensions - it loads only the planet and moon dimensions, but the planet and moon dimensions are already permanently loaded (unless something is done differently in an Add On, or if another mod hooks into to GC's rockets system so that its dimension can also be accessed by rocket - which is possible in theory but I don't know any mod which does this)

From 415a: the destinations map is only updated once every 50 ticks while the map selection screen is open - the only reason for updates at all is in case another player created a space station or changed space station permissions meanwhile.

I think this issue can be considered 'Fixed'.

I welcome feedback on performance of 414a and 415a - really I hope that 414a already solved the issue.

I will not report the tickets issue to Forge/Cauldron but I hope that @Slind14 will report it.

**Comment by Slind14** [comment] 2016-01-14 18:11
thanks a lot @radfast
