### ISSUE TITLE
Crash on world load involving TileEntityTelemetry

### ISSUE THREAD

**Issue by coiax** [micdoodle8/Galacticraft#1951] opened 2015-11-27 10:10 UTC
Log follows. I tried deleting what I think was the Telemetry Unit from my player's inventory with NBT editing, but it didn't help.

[09:46:52] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 27/11/15 09:46
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at micdoodle8.mods.galacticraft.core.tile.TileEntityTelemetry.frequencyModulePlayer(TileEntityTelemetry.java:231)
	at micdoodle8.mods.galacticraft.core.entities.player.GCPlayerHandler.checkGear(GCPlayerHandler.java:182)
	at micdoodle8.mods.galacticraft.core.entities.player.GCPlayerHandler.onPlayerUpdate(GCPlayerHandler.java:1127)
	at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.entityLivingEvent(EventHandlerGC.java:239)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_11_EventHandlerGC_entityLivingEvent_LivingUpdateEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:287)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1560)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295)
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303)
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
	at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at micdoodle8.mods.galacticraft.core.tile.TileEntityTelemetry.frequencyModulePlayer(TileEntityTelemetry.java:231)
	at micdoodle8.mods.galacticraft.core.entities.player.GCPlayerHandler.checkGear(GCPlayerHandler.java:182)
	at micdoodle8.mods.galacticraft.core.entities.player.GCPlayerHandler.onPlayerUpdate(GCPlayerHandler.java:1127)
	at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.entityLivingEvent(EventHandlerGC.java:239)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_11_EventHandlerGC_entityLivingEvent_LivingUpdateEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:287)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1560)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)

-- Player being ticked --
Details:
	Entity Type: null (micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP)
	Entity ID: 8
	Entity Name: coiax
	Entity's Exact location: 89.89, 80.00, 214.28
	Entity's Block location: World: (89,80,214), Chunk: (at 9,5,6 in 5,13; contains blocks 80,0,208 to 95,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.01, 0.00
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295)
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303)
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
	at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@196ae30
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_65, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 349925328 bytes (333 MB) / 921698304 bytes (879 MB) up to 1431830528 bytes (1365 MB)
	JVM Flags: 3 total; -Xms256M -Xmx1536M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 85 mods loaded, 85 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
	UCHIJAAAA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.6.43} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.4.107} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.107-universal.jar) 
	UCHIJAAAA	notimefix{2.1.0} [No Time Fix] (minecraft.jar) 
	UCHIJAAAA	OpenComputers|Core{1.5.14.30} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAA	OpenModsCore{0.7.3} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	&lt;CoFH ASM&gt;{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.345.jar) 
	UCHIJAAAA	SpaceCore{4.1.9} [4Space Core] (4Space-4.1.9.jar) 
	UCHIJAAAA	ExoCore{0.1.2} [4Space Exoplanets Core] (4Space-4.1.9.jar) 
	UCHIJAAAA	ExoElipse{0.1.2} [4Space Exoplanets Elipse] (4Space-4.1.9.jar) 
	UCHIJAAAA	SpaceCallisto{4.1.9} [4Space Callisto] (4Space-4.1.9.jar) 
	UCHIJAAAA	SpaceEuropa{4.1.9} [4Space Europa] (4Space-4.1.9.jar) 
	UCHIJAAAA	SpaceVenus{4.1.9} [4Space Venus] (4Space-4.1.9.jar) 
	UCHIJAAAA	SpaceIo{4.1.9} [4Space Io] (4Space-4.1.9.jar) 
	UCHIJAAAA	SpaceMercury{4.1.9} [4Space Mercury] (4Space-4.1.9.jar) 
	UCHIJAAAA	SpacePluto{4.1.9} [4Space Pluto] (4Space-4.1.9.jar) 
	UCHIJAAAA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHIJAAAA	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
	UCHIJAAAA	armourersWorkshop{1.7.10-0.36.0.92} [Armourer's Workshop] (Armourers-Workshop-1.7.10-0.36.0.92.jar) 
	UCHIJAAAA	plushieWrapper{0.0.0} [Plushie Wrapper] (Armourers-Workshop-1.7.10-0.36.0.92.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCHIJAAAA	AwesomeSauceCore{0.1.0} [AwesomeSauce Core] (AwesomeSauceCore-1.7.x-b52.jar) 
	UCHIJAAAA	AwesomeSauceComponents{0.1.0} [AwesomeSauce Components] (AwesomeSauceCore-1.7.x-b52.jar) 
	UCHIJAAAA	bdlib{1.9.1.97} [BD Lib] (bdlib-1.9.1.97-mc1.7.10.jar) 
	UCHIJAAAA	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-11.jar) 
	UCHIJAAAA	bookshelf{1.1.2} [Bookshelf] (Bookshelf-1.7.10-1.1.2.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.6} [Carpenter's Blocks] (Carpenter's Blocks v3.3.6 - MC 1.7.10.jar) 
	UCHIJAAAA	chisel{2.4.1.40} [Chisel 2] (Chisel2-2.4.1.40.jar) 
	UCHIJAAAA	ctmlib{1.0.1.5} [CTMLib] (Chisel2-2.4.1.40.jar) 
	UCHIJAAAA	CustomMainMenu{1.6} [Custom Main Menu] (CustomMainMenu-MC1.7.10-1.6.jar) 
	UCHIJAAAA	darkcore{0.25} [Dark Core] (darkcore-0.25-35.jar) 
	UCHIJAAAA	ImmibisCore{59.1.1} [Immibis Core] (immibis-core-59.1.1.jar) 
	UCHIJAAAA	DimensionalAnchors{59.0.3} [Dimensional Anchors] (dimensional-anchor-59.0.3.jar) 
	UCHIJAAAA	dimstorage{1.3} [DimStorage] (DimStorage-1.7.2-1.3.jar) 
	UCHIJAAAA	Eln{50} [Electrical Age] (ElectricalAge_BETA-1.10_r50.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.2.8.381} [Ender IO] (EnderIO-1.7.10-2.2.8.381.jar) 
	UCHIJAAAA	exnihilo{1.37} [Ex Nihilo] (Ex-Nihilo-1.37.jar) 
	UCHIJAAAA	exastris{1.15} [Ex Astris] (Ex-Astris-1.15.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.8} [Extra Utilities] (extrautilities-1.2.8.jar) 
	UCHIJAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.345.jar) 
	UCHIJAAAA	GalacticScience_Tweaks{1.0} [GalacticScience-Tweaks] (GalacticScience_Tweaks-1.2.jar) 
	UCHIJAAAA	minechem{5.0.5.398} [Minechem] (Minechem-1.7.10-5.0.5.398.jar) 
	UCHIJAAAA	advgenerators{0.9.16.99} [Advanced Generators] (generators-0.9.16.99-mc1.7.10.jar) 
	UCHIJAAAA	GregsLighting{1.11.2} [Greg's Lighting] (GregsLighting-1.11.2-mc1.7.10.jar) 
	UCHIJAAAA	hardcoremapreset{2.2.0} [HardcoreMapReset] (HardCoreMapReset-2.2.0.jar) 
	UCHIJAAAA	HardcoreQuesting{The Journey (4.2.4)} [Hardcore Questing Mode] (HQM-The Journey (4.2.4).jar) 
	UCHIJAAAA	inpure|core{1.7.10R1.0.0B9} [INpureCore] (INpureCore-[1.7.10]1.0.0B9-62.jar) 
	UCHIJAAAA	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) 
	UCHIJAAAA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UCHIJAAAA	MineTweaker3{3.0.9B} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.9C [Edited].jar) 
	UCHIJAAAA	modtweaker2{0.8.2} [Mod Tweaker 2] (ModTweaker 2-0.8.1.jar) 
	UCHIJAAAA	modularsystemsapi{0.0.1} [Modular Systems API] (Modular Systems-1.7.10-1.7.3.jar) 
	UCHIJAAAA	modularsystems{1.7.3} [Modular Systems] (Modular Systems-1.7.10-1.7.3.jar) 
	UCHIJAAAA	NEIAddons{1.12.7.21} [NEI Addons] (neiaddons-mc1710-1.12.7.21.jar) 
	UCHIJAAAA	NEIAddons|AppEng{1.12.7.21} [NEI Addons: Applied Energistics 2] (neiaddons-mc1710-1.12.7.21.jar) 
	UCHIJAAAA	NEIAddons|Botany{1.12.7.21} [NEI Addons: Botany] (neiaddons-mc1710-1.12.7.21.jar) 
	UCHIJAAAA	NEIAddons|Forestry{1.12.7.21} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.7.21.jar) 
	UCHIJAAAA	NEIAddons|CraftingTables{1.12.7.21} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.7.21.jar) 
	UCHIJAAAA	NEIAddons|ExNihilo{1.12.7.21} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.7.21.jar) 
	UCHIJAAAA	Netherless{0.9.0} [Netherless] (Netherless-0.9.0.jar) 
	UCHIJAAAA	NuclearCraft{0.0.1.5} [NuclearCraft] (NuclearCraft-0.0.1.5--1.7.10.jar) 
	UCHIJAAAA	OpenComputers{1.5.14.30} [OpenComputers] (OpenComputers-MC1.7.10-1.5.14.30-universal.jar) 
	UCHIJAAAA	OpenAutomation{1.7.x-b218} [OpenAutomation] (OpenAutomation-1.7.x-b218.jar) 
	UCHIJAAAA	OpenMods{0.7.3} [OpenMods] (OpenModsLib-1.7.10-0.7.3.jar) 
	UCHIJAAAA	OpenBlocks{1.4.3} [OpenBlocks] (OpenBlocks-1.7.10-1.4.3.jar) 
	UCHIJAAAA	progressiveautomation{1.6.27} [Progressive Automation] (ProgressiveAutomation-1.7.10-1.6.27.jar) 
	UCHIJAAAA	quantumflux{1.7.10-1.3.0-b2} [QuantumFlux] (QuantumFlux-1.7.10-1.3.0-b2.jar) 
	UCHIJAAAA	RandomThings{2.2.4} [Random Things] (RandomThings-2.2.4.jar) 
	UCHIJAAAA	RefinedRelocation{1.0.8b} [Refined Relocation] (RefinedRelocation-1.7.10-1.0.8b.jar) 
	UCHIJAAAA	ResourceLoader{1.2} [Resource Loader] (ResourceLoader-1.2.jar) 
	UCHIJAAAA	rftools{2.80} [RFTools] (rftools-2.80.jar) 
	UCHIJAAAA	RouterReborn{1.2.0.34} [Router Reborn] (RouterReborn-1.7.10-1.2.0.34-universal.jar) 
	UCHIJAAAA	SGCraft{1.9.3} [Greg's SG Craft] (SGCraft-1.9.3-mc1.7.10.jar) 
	UCHIJAAAA	SolarFlux{1.7.10-0.8a} [Solar Flux] (SolarFlux-1.7.10-0.8a.jar) 
	UCHIJAAAA	superMassiveTech{0.2.0-alpha} [Super Massive Tech] (SuperMassiveTech-MC1.7.10-0.2.0-alpha-86.jar) 
	UCHIJAAAA	TardisMod{0.985} [Tardis Mod] (tardismod-1.7.10-0.985-150.jar) 
	UCHIJAAAA	thedalekmod{39.51} [The Dalek Mod] (the_dalek_mod_1.7.10.zip) 
	UCHIJAAAA	yampst{1.3.5} [YAMPST] (Yampst-gs-1.4.0.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	CoFHCore: -[1.7.10]3.0.3-303
	Mantle Environment: Environment healthy.
	List of loaded APIs: 
		* appliedenergistics2|API (rv2) from tardismod-1.7.10-0.985-150.jar
		* armourersWorkshopAPI (1.7.10-10.13.4.1448-1.7.10) from Armourers-Workshop-1.7.10-0.36.0.92.jar
		* BuildCraftAPI|core (1.0) from extrautilities-1.2.8.jar
		* BuildCraftAPI|tools (1.0) from extrautilities-1.2.8.jar
		* ChiselAPI (0.1.0) from Chisel2-2.4.1.40.jar
		* ChiselAPI|Carving (0.1.0) from Chisel2-2.4.1.40.jar
		* ChiselAPI|Rendering (0.1.0) from Chisel2-2.4.1.40.jar
		* CoFHAPI (1.7.10R1.0.2) from Bookshelf-1.7.10-1.1.2.jar
		* CoFHAPI|block (1.7.10R1.0.13) from ProgressiveAutomation-1.7.10-1.6.27.jar
		* CoFHAPI|core (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|energy (1.7.10R1.0.0) from Minechem-1.7.10-5.0.5.398.jar
		* CoFHAPI|fluid (1.7.10R1.0.12) from RouterReborn-1.7.10-1.2.0.34-universal.jar
		* CoFHAPI|inventory (1.7.10R1.0.10) from NuclearCraft-0.0.1.5--1.7.10.jar
		* CoFHAPI|item (1.7.10R1.0.12) from RouterReborn-1.7.10-1.2.0.34-universal.jar
		* CoFHAPI|modhelpers (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|tileentity (1.7.10R1.0.3) from EnderIO-1.7.10-2.2.8.381.jar
		* CoFHAPI|transport (1.7.10R1.0.3) from EnderIO-1.7.10-2.2.8.381.jar
		* CoFHAPI|world (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|audio (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui|container (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui|element (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui|element|listbox (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui|slot (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|inventory (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|render (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|render|particle (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|util (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|util|helpers (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|util|position (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|world (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|world|feature (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* EnderIOAPI (0.0.2) from EnderIO-1.7.10-2.2.8.381.jar
		* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.7.10-2.2.8.381.jar
		* EnderIOAPI|Tools (0.0.2) from EnderIO-1.7.10-2.2.8.381.jar
		* Galacticraft API (1.0) from GalacticraftCore-1.7-3.0.12.345.jar
		* inpure|api (1.7) from INpureCore-[1.7.10]1.0.0B9-62.jar
		* minechemAPI (1.7.10R1) from Minechem-1.7.10-5.0.5.398.jar
		* OpenBlocks|API (1.0) from OpenBlocks-1.7.10-1.4.3.jar
		* OpenComputersAPI|Component (5.5.3) from OpenComputers-MC1.7.10-1.5.14.30-universal.jar
		* OpenComputersAPI|Core (5.5.3) from OpenComputers-MC1.7.10-1.5.14.30-universal.jar
		* OpenComputersAPI|Driver (5.5.3) from OpenComputers-MC1.7.10-1.5.14.30-universal.jar
		* OpenComputersAPI|Driver|Item (5.5.3) from OpenComputers-MC1.7.10-1.5.14.30-universal.jar
		* OpenComputersAPI|Event (5.5.3) from OpenComputers-MC1.7.10-1.5.14.30-universal.jar
		* OpenComputersAPI|FileSystem (5.5.3) from OpenComputers-MC1.7.10-1.5.14.30-universal.jar
		* OpenComputersAPI|Internal (5.5.3) from OpenComputers-MC1.7.10-1.5.14.30-universal.jar
		* OpenComputersAPI|Machine (5.5.3) from OpenComputers-MC1.7.10-1.5.14.30-universal.jar
		* OpenComputersAPI|Manual (5.5.3) from OpenComputers-MC1.7.10-1.5.14.30-universal.jar
		* OpenComputersAPI|Network (5.5.3) from OpenComputers-MC1.7.10-1.5.14.30-universal.jar
		* OpenComputersAPI|Prefab (5.5.3) from OpenComputers-MC1.7.10-1.5.14.30-universal.jar
		* RefinedRelocationAPI (1.0.0) from RefinedRelocation-1.7.10-1.0.8b.jar
		* Thaumcraft|API (4.2.2.0) from tardismod-1.7.10-0.985-150.jar
		* WailaAPI (1.2) from Waila-1.5.10_1.7.10.jar
	Modpack Version: 1.4.15
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [GCEntityPlayerMP['coiax'/8, l='Moonduck', x=89.89, y=80.00, z=214.28]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by radfast** [comment] 2016-01-05 01:19
Duplicate of #1805 and #1816.
This issue was fixed 2 months ago, please update to a more recent version of Galacticraft.

**Closed by radfast** 2016-01-05 01:19 UTC
