### ISSUE TITLE
[1.8.9]Build 61 visual bugs

### ISSUE THREAD

**Issue by gug2** [micdoodle8/Galacticraft#2548] opened 2017-04-10 05:31 UTC
Tier 1 dungeon key:
![2017-04-10_09 26 35](https://cloud.githubusercontent.com/assets/19577359/24847177/765dbe28-1dd0-11e7-9f21-453cd89daf21.png)
Communication dish:
![2017-04-10_09 45 09](https://cloud.githubusercontent.com/assets/19577359/24847545/9d9f833e-1dd2-11e7-8daa-a3b4bbc20fd1.png)
In the hand rendering piece of the cryogenic chamber:
![2017-04-10_09 47 57](https://cloud.githubusercontent.com/assets/19577359/24847610/065aa098-1dd3-11e7-8591-90321243cd3c.png)
Space glass is not available in creative tab GC
![2017-04-10_09 51 38](https://cloud.githubusercontent.com/assets/19577359/24847647/4d2e1842-1dd3-11e7-86c5-6751566fa3d7.png)

**Comment by ThomasAunvik** [comment] 2017-04-10 06:09
First one is a duplication of: https://github.com/micdoodle8/Galacticraft/issues/2503

**Comment by radfast** [comment] 2017-04-11 00:28
Thank you for beta testing!

Dungeon Key and Cryogenic Chamber:  these are weird ones, I can see they've been reported more than once but I actually can't reproduce in my testing.

Communications Dish:  this will be added soon.

Space Glass in Creative Tab:  thank you, this is fixed in next build 62.  (Now named **Vacuum Glass** in English.  It's totally up to you if you want to change the Russian translation, just make it whatever sounds good in Russian.  The Tooltip Reference to [Transparent Aluminum](https://en.wikipedia.org/wiki/List_of_Star_Trek_materials#Transparent_aluminum) is a shoutout to Star Trek!)

**Comment by radfast** [comment] 2017-04-12 12:12
Because everything is now fixed except the Cryogenic Chamber, I'm moving that one to the list of rendering issues in #2480 so that this can be closed.

**Closed** 2017-04-16 13:00 UTC
Labels: 1.10+, 1.8, rendering

**Comment by ThomasAunvik** [comment] 2017-04-16 13:51
Build 66: (1.11.2)
```
15:49:56	TEXTURE ERRORS	+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=
15:49:56	TEXTURE ERRORS	The following texture errors were found.
15:49:56	TEXTURE ERRORS	==================================================
15:49:56	TEXTURE ERRORS	  DOMAIN galacticraftplanets
15:49:56	TEXTURE ERRORS	--------------------------------------------------
15:49:56	TEXTURE ERRORS	  domain galacticraftplanets is missing 2 textures
15:49:56	TEXTURE ERRORS	    domain galacticraftplanets has 1 location:
15:49:56	TEXTURE ERRORS	      unknown resourcepack type net.minecraft.client.resources.LegacyV2Adapter : FMLFileResourcePack:Galacticraft Planets
15:49:56	TEXTURE ERRORS	-------------------------
15:49:56	TEXTURE ERRORS	    The missing resources for domain galacticraftplanets are:
15:49:56	TEXTURE ERRORS	      textures/items/key_t2.png
15:49:56	TEXTURE ERRORS	      textures/items/key_t3.png
15:49:56	TEXTURE ERRORS	-------------------------
15:49:56	TEXTURE ERRORS	    No other errors exist for domain galacticraftplanets
15:49:56	TEXTURE ERRORS	==================================================
15:49:56	TEXTURE ERRORS	+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=
```

**Comment by radfast** [comment] 2017-04-16 14:34
Thanks.  Key textures are fixed in https://github.com/micdoodle8/Galacticraft/commit/ed7ea43c6f839534dfeb2dd4fccf1afd41a1cbb8

The item in hand position, for keys, in third person, I'm not sure about - is it correct in **first person**?   I'm not sure we have any special third person version of that.

**Comment by ThomasAunvik** [comment] 2017-04-16 15:40
No, first person is the same as it is in third person. And you cannot even see the key.
![2017-04-16_17 40 23](https://cloud.githubusercontent.com/assets/9968151/25072338/cad544ee-22cb-11e7-83da-f535911570e6.png)
