### ISSUE TITLE
[1.11.2] Deobf version requires a specific Dev Environment

### ISSUE THREAD

**Issue by MJRLegends** [micdoodle8/Galacticraft#2844] opened 2017-06-20 00:18 UTC
Hello,

When i do /dimensiontp or a rocket to get to the solar system teleport screen i get the following crash

https://pastebin.com/rpxywBb7

only seems to be a 1.11.2 things though...

**Comment by Barteks2x** [comment] 2017-06-20 00:24
This is a duplicate of this issue I had: https://github.com/micdoodle8/Galacticraft/issues/2817.
You would need to use the same mappings as galacitcraft in dev environment. You can workaround this issue by modifying the jar file, but the coremod is likely to break too if you have different mappings

**Comment by MJRLegends** [comment] 2017-06-20 00:29
That doesn't seem a good way to get around the issue though as i means anyone wants to use the api has to do the changes seems a bit weird....

**Comment by Barteks2x** [comment] 2017-06-20 00:34
This is only a problem in dev environment, and only because recently some very frequently used mappings have been changed. This can be fixed on Galacticraft side (as I explained in the issue, even the coremod can be fixed), now that I see someone else is affected I may submit a PR that fixes it.

**Comment by MJRLegends** [comment] 2017-06-20 00:35
@Barteks2x yeah i feel like it needs a 100% fix

**Comment by MJRLegends** [comment] 2017-06-20 00:40
@Barteks2x how can i fix it now :D

**Comment by Barteks2x** [comment] 2017-06-20 00:43
It's unlikely you can make it work without recompiling the mod. It worked for me only because of the crazy mod I was using it with, that made is skip some broken modified vanilla code.

**Comment by MJRLegends** [comment] 2017-06-20 00:43
@Barteks2x i can recomplie stuff if i need too :D

**Comment by MJRLegends** [comment] 2017-06-20 00:44
@Barteks2x because im testing is currently very hard as im trying to fix a bug with a planet but cant teleport there in my dev environment

**Comment by Barteks2x** [comment] 2017-06-20 00:52
Ok, so this is not the "right" way to do it, but I'm not really that determined to find out how to do it properly.
If you feel masichistic you can go through all of these https://github.com/micdoodle8/MicdoodleCore/blob/0381217a8d57fee60241bb419a6cb2dbec8cbaf7/src/main/java/micdoodle8/mods/miccore/MicdoodleTransformer.java#L51-L153 manually and update these mappings. And same for `micdoodlecore_at.deob` file. And then compile.

Or you can take the lazier way:
1. First you need to make galacticraft compile locally. Once you compile it: 
 * In `micdoodlecore.jar`:
    * remove `micdoodlecore_at.deobf`
    * move `micdoodlecore_at.cfg` to `META-INF`
    * Edit `META-INF/MANIFEST.MF` and change `AccessTransformer` to `FMLAT`

2. This will give you a version that goes a bit further. If it works - you are done. If it doesn't work - find where it crashes, find the mapping that causes the crash, and update it to your version in https://github.com/micdoodle8/MicdoodleCore/blob/master/src/main/java/micdoodle8/mods/miccore/MicdoodleTransformer.java. Go back to step 1.

**Comment by Barteks2x** [comment] 2017-06-20 00:55
The real fix would be to get the local mappings dynamically in the code.

**Comment by Barteks2x** [comment] 2017-06-20 01:00
Unless you have a very big mod it may be easier to downgrade mappings in your mod.

**Comment by MJRLegends** [comment] 2017-06-20 01:01
Thanks

**Comment by radfast** [comment] 2017-06-20 10:15
or ... just use the Galacticraft sources in a workspace with the mappings our code is designed for, you can see the mappings by looking at the ```build.gradle```

**Closed** 2017-06-24 01:22 UTC
