### ISSUE TITLE
java.lang.NoClassDefFoundError: ic2/api/recipe/IRecipeInput

### ISSUE THREAD

**Issue by 23Link89** [micdoodle8/Galacticraft#2690] opened 2017-05-06 21:22 UTC
I have the latest version of forge: 12.18.3.2281
and the latest Galacticraft: 1.10.2-4.0.0.83-BETA
I have no other mods installed
https://pastebin.com/4sEvP9Eh

**Comment by radfast** [comment] 2017-05-06 21:42
Thanks for beta testing!

This is a duplicate of #2687 and #2688. 

Please update to build 84 which fixes this, now available on the Jenkins download site (same link as build 83).

**Closed by radfast** 2017-05-06 21:42 UTC
