### ISSUE TITLE
[Add-on]Double-Clicking new Solar systems still leads back to the default Solar System.

### ISSUE THREAD

**Issue by Alex-the-666** [micdoodle8/Galacticraft#1607] opened 2015-04-25 02:20 UTC
my issue, #1488 , was closed prematurely, as of  build 139 clicking on a custom Solar System still leads back to the default one.

**Comment by trollyface** [comment] 2015-04-26 23:31
yup its annoying af. plz add support to your maps?  up down left right or click and drag..

**Comment by micdoodle8** [comment] 2015-05-02 17:12
Build 139? Is that a typo? The latest build is 325.

Also, what new solar systems are you testing with? Ones you have created yourself?

Using the latest build of Galacticraft and the "More Planets" source, I'm able to zoom into other solar systems just fine.

**Comment by Alex-the-666** [comment] 2015-05-05 14:28
hmm... maybe Im downloading from the wrong place, do you have an adress to the build?

**Comment by radfast** [comment] 2015-05-05 15:48
The latest build is at http://micdoodle8.com/mods/galacticraft/downloads

It's best to test in a standard obfuscated environment, i.e. using the vanilla Minecraft launcher.

If that works OK, but something does not work running the game in a dev build or inside Eclipse, then that's a different issue.

I'm going to close this now, because micdoodle8 said it's working with other Add Ons so it seems like a problem in your Add On only.  Even when the issue is closed, you can still write comments here and we will see them and respond.  If it turns out there is a bug in Galacticraft's own code then of course I will re-open this.  __Do not start another new issue on this please.__

**Closed by radfast** 2015-05-05 15:48 UTC
