### ISSUE TITLE
Thermal Padding Not Working!

### ISSUE THREAD

**Issue by CoolDude450** [micdoodle8/Galacticraft#1474] opened 2015-03-02 20:34 UTC
I put on the thermal padding and it still said invalid thermal protection. I have it fully on and it still does not work.

**Comment by radfast** [comment] 2015-03-03 13:02
It should work.
Please provide a screenshot - show us your player inventory with the thermal padding on.
Also which exact Galacticraft version, which dimension are you in, and do you have any Add-Ons installed.

**Comment by CoolDude450** [comment] 2015-03-03 20:44
![2015-03-03_15 42 12](https://cloud.githubusercontent.com/assets/3999803/6471795/0052a56c-c1bc-11e4-80a7-d1a234a88bee.png)
![2015-03-03_15 42 21](https://cloud.githubusercontent.com/assets/3999803/6471796/0056478a-c1bc-11e4-85dc-765069943c92.png)

Running Galacticraft 3.0.8 and Planets Addon 3.0.8

In the Space Station Area.

**Comment by radfast** [comment] 2015-03-03 20:46
Try it without the More Planets Addon.  __Backup your world first__

I think the More Planets mentioned he was looking at changing thermal protection.

**Comment by CoolDude450** [comment] 2015-03-03 20:47
ok

**Comment by CoolDude450** [comment] 2015-03-03 20:48
Still not working.

**Comment by SteveKunG** [comment] 2015-03-04 10:23
Hi. I'm not changing the thermal system. And I'm not change anything in Galacticraft. except Mars sky provider.

**Comment by CoolDude450** [comment] 2015-03-05 22:32
So is there anything else that could cause a thermal padding error?

**Comment by micdoodle8** [comment] 2015-03-27 19:52
Is this recreatable? If you take off the armor and put it back on again, or try reloading the world, or anything similar, does it still happen?

**Comment by radfast** [comment] 2015-04-05 22:12
My guess is the issue was caused by the player being previously in a frozen world (Mars or Asteroids) without protection, then taking a rocket or teleporting to the Space Station.

Once in the Space Station, the thermal level would not be updated (even if full thermal padding is being worn) so that the player would stay frozen ...

If my guess is good, then this is fixed by the latest commit.

**Closed** 2015-04-05 22:12 UTC
Labels: missing info
