### ISSUE TITLE
Corrupted DIM1 (end) replaced by Space Station

### ISSUE THREAD

**Issue by MasterIO02** [micdoodle8/Galacticraft#3744] opened 2019-07-27 13:05 UTC
Hello. I have a REALLY strange bug with Galacticraft.
It appears that Galacticraft replaced the end with a Space Station, resulting to a fully corrupted end!

When I try to go to the end, the logs says :
[Server thread/INFO] [Sponge]: Loading world [DIM1] (Space Station)

No errors, warns, just this with the "loaded achievement tree" etc...

I'm on SpongeForge 1.12.2 2768 (7.1.6) on a Multiplayer server.
I only have Galacticraft 4.0.2.211, MicdoodleCore (same version) and Galacticraft Planets (same version too)

I did not change any of the config files of Galacticraft, the end got corrupted after a reboot of the server. Before the reboot, I created a Space Station but all was working fine.

I think Minecraft tries to generate the end but Galacticraft tries to generate the space station, but i'm not sure.
There is a screenshot of the end :
https://imgur.com/AqXaIIg

I hope somebody can help me because the players on my server cannot go to the end at the moment...

**Comment by TheQuadShot** [comment] 2019-07-27 14:09
GC doesn't tough Dim1, the space station is dim-27, unless you changed it in the configs. Are you sure your got your files from:
https://micdoodle8.com/mods/galacticraft/downloads

**Comment by MasterIO02** [comment] 2019-07-27 14:48
I dont have the DIM-27 dimension, all the space stations are different dimensions "DIM_SPACESTATION6" and the number change for each space station.
I did not changed the config, and I downloaded the mod on the micdoodle8 site.

**Comment by TheQuadShot** [comment] 2019-07-27 15:36
looks like it may be related to
https://github.com/micdoodle8/Galacticraft/issues/3206

**Comment by micdoodle8** [comment] 2019-07-27 16:12
Possibly also related to #3729, looking at that crash log

I'm going to need your full server log please

**Comment by MJRLegends** [comment] 2019-07-27 19:14
Yeah it is related to both issues above

**Comment by MasterIO02** [comment] 2019-07-27 20:06
[latest.log](https://github.com/micdoodle8/Galacticraft/files/3438549/latest.log)
There is the logs for the time I was in the corrupted end. I'll watch the others issue that is related.

**Comment by bluelightning32** [comment] 2019-08-25 19:43
I filed a new bug for this:
https://github.com/micdoodle8/Galacticraft/issues/3775

**Comment by radfast** [comment] 2019-08-26 21:21
Duplicate of #3665.  We hope this will be fixed in next build, sorry it has taken so long to get to it.  Thanks for the additional info posted by @bluelightning32 which led to us isolating the problem.

**Closed by radfast** 2019-08-26 21:21 UTC

**Comment by radfast** [comment] 2019-08-27 03:19
Please try build 1.12.2 - 4.0.2.234, this is fixed.

**Comment by MasterIO02** [comment] 2019-08-29 16:37
Thanks :D
