### ISSUE TITLE
PDF of Issues I've Found

### ISSUE THREAD

**Issue by Preminenc3** [micdoodle8/Galacticraft#2585] opened 2017-04-14 21:38 UTC
[
[GalacticCraft4 1.10.2 BetaTesting Issues.pdf](https://github.com/micdoodle8/Galacticraft/files/922994/GalacticCraft4.1.10.2.BetaTesting.Issues.pdf)
](url)

**Comment by ThomasAunvik** [comment] 2017-04-15 00:14
1: Aleready reported in #2548 
13-18: Alerady reported in #2564

**Comment by radfast** [comment] 2017-05-11 23:48
<details><summary>POINTS 1-12</summary>1. Communications Dish ​(Broken JEI Texture and No Ingame Texture/Placing in the World Doesn't
Show) (No crafting recipe showing for JEI “if there is one”)
2. tile.boss_spawner.name ​ (Broken JEI Texture and No Ingame Texture/Placing in the World Doesn't
Show)
3. til.slab_gc_double.tin_bricks_slab_1.name ​ (Server crash when I tried to place block) (Broken
JEI Texture and No Ingame Texture/Placing in the World Doesn't Show)
a. The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Cannot set property PropertyEnum{name=half,
clazz=class net.minecraft.block.BlockSlab$EnumBlockHalf, values=[top, bottom]} as it does not
exist in BlockStateContainer{block=galacticraftcore:slab_gc_double, properties=[variant]}
4. tile.slab_gc_double.tin_bricks_slab_2.name ​(Server crash when I tried to place block) (Broken
JEI Texture and No Ingame Texture/Placing in the World Doesn't Show)
a. The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Cannot set property PropertyEnum{name=half,
clazz=class net.minecraft.block.BlockSlab$EnumBlockHalf, values=[top, bottom]} as it does not
exist in BlockStateContainer{block=galacticraftcore:slab_gc_double, properties=[variant]}
5. tile.slab_gc_double.moon_slab.name ​(Server crash when I tried to place block) (Broken JEI
Texture and No Ingame Texture/Placing in the World Doesn't Show)
a. The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Cannot set property PropertyEnum{name=half,
clazz=class net.minecraft.block.BlockSlab$EnumBlockHalf, values=[top, bottom]} as it does not
exist in BlockStateContainer{block=galacticraftcore:slab_gc_double, properties=[variant]}
6. tile.slab_gc_double.moon_bricks_slab.name ​(Server crash when I tried to place block) (Broken
JEI Texture and No Ingame Texture/Placing in the World Doesn't Show)
a. The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Cannot set property PropertyEnum{name=half,
clazz=class net.minecraft.block.BlockSlab$EnumBlockHalf, values=[top, bottom]} as it does not
exist in BlockStateContainer{block=galacticraftcore:slab_gc_double, properties=[variant]}
7. tile.slab_gc_double.mars_slab.name ​(Server crash when I tried to place block) (Broken JEI
Texture and No Ingame Texture/Placing in the World Doesn't Show)
a. The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Cannot set property PropertyEnum{name=half,
clazz=class net.minecraft.block.BlockSlab$EnumBlockHalf, values=[top, bottom]} as it does not
exist in BlockStateContainer{block=galacticraftcore:slab_gc_double, properties=[variant]}
8. tile.slab_gc_double.mars_bricks_slab.name ​(Server crash when I tried to place block) (Broken
JEI Texture and No Ingame Texture/Placing in the World Doesn't Show)
a. The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Cannot set property PropertyEnum{name=half,
clazz=class net.minecraft.block.BlockSlab$EnumBlockHalf, values=[top, bottom]} as it does not
exist in BlockStateContainer{block=galacticraftcore:slab_gc_double, properties=[variant]}
9. tile.boss_spawner_mars.name ​(Broken JEI Texture and No Ingame Texture/Placing in the World
Doesn't Show)
10. tile.block_multi.null.name ​ (Has no JEI picture, just a empty space)
11. tile.boss_spawner_venus.name ​ (Broken JEI Texture and No Ingame Texture/Placing in the World
Doesn't Show)
12. tile.telepad_fake.name ​ (Server crash when I tried to place block) (Broken JEI Texture and No
Ingame Texture/Placing in the World Doesn't Show)</details>

These are all basically the same issue: JEI is not hiding items which should be hidden in the itemlist.  This is fixed in latest GC versions.

**Comment by radfast** [comment] 2017-05-11 23:51
Like ThomasAnvuik said, 13-18 (Vacuum Glass) are duplicates of an open issue.

**Comment by radfast** [comment] 2017-05-11 23:56
**19. Rockets [Tier 1, Tier 2, & Tier 3] , Blue Solar Wafer, Basic Wafer, Advanced
Wafer, All Buggies, Heavy-Duty Plate [Tier 1, Tier 2, & Tier 3], Compressed [Tin.
Copper, Aluminum, Steel, Iron, Meteoric Iron, Titanium, Desh, & Bronze], Astro
Miner, Pre-Launch Checklist, NASA Workbench [Moon Buggy, Tier 2 Rocket,
Astro Miner, Automatic Cargo Rocket, Tier 3 Rocket], Volcanic Pickaxe, Sticky
Desh Pickaxe, Thermal Padding [Helm, Chestpiece, Leggings, Boots], Shield
Controller, Geothermal Generator ​ (Recipe doesn’t show up in JEI)**

JEI recipe compatibility for our special machines and NASA workbench is issue #2607.  This is now included in latest Galacticraft versions.

**20. Torch ​ (2 copies of the Galacticraft Torch in JEI)**

**21. Rocket Launch Pad ​ (2 copies of the Galacticraft Rocket Launch Pad in JEI) (Can’t place them in a
3x3 area, only lets me place it 1 block away from another one)**

**23. Fluid Pipe ​ (2 copies of the Galacticraft Fluid Pipe in JEI)**

All three of these, same issue as 1-12, the second copy is intended to be hidden in JEI.  Fixed in latest GC versions.

**24. Short Range Telepad ​ (In hand it covers up a lot of the screen)**

I'm moving this issue to #2606 where it belongs better

**Comment by radfast** [comment] 2017-05-11 23:58
22. Aluminum Wire ​(Doesn’t connect to machines)

**Please explain this issue and provide a screenshot?**

**Comment by radfast** [comment] 2017-05-16 15:22
> 22. Aluminum Wire ​(Doesn’t connect to machines)

Any more info?  I haven't been able to reproduce this problem:

![alu-wire-crop](https://cloud.githubusercontent.com/assets/6842258/26113908/c7e64b3a-3a53-11e7-98b8-4ddb96501cc0.jpg)

**Comment by radfast** [comment] 2017-05-17 17:30
Can anyone else comment at all on this "Aluminium Wire doesn't connect to machines" issue report?

(Otherwise I'm going to close this as impossible to resolve without more description of what the issue is.)

**Comment by Preminenc3** [comment] 2017-05-17 23:41
Sorry, I can't get back to you until the weekend.

**Comment by radfast** [comment] 2017-05-18 01:28
No worries, weekend will be fine :)

**Comment by radfast** [comment] 2017-05-22 22:32
@Preminenc3  any chance can you remember which machines you meant, when you originally posted this?

**Comment by radfast** [comment] 2017-05-26 00:40
Closing due to insufficient information.  It's possible the wire connection issue has been fixed along the way, there were a couple of Galacticraft machines whose electrical sides were wrong (Circuit Fabricator and Oxygen Decompressor), and RF mods connections and IC2 are now working properly I think, see my screenshot.

**Closed by radfast** 2017-05-26 00:40 UTC
Labels: cant reproduce, missing info
