### ISSUE TITLE
internal server error

### ISSUE THREAD

**Issue by Nbgreen** [micdoodle8/Galacticraft#3920] opened 2020-03-31 03:11 UTC
REVIEW THE GUIDELINES - see [Contributing](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) link on right side.
at random server starts having packet error that doesn't let players join
Minecraft version: 1.12.2
Galacticraft version: 1.12.2-4.0.2.244

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
- If SMP server, please mention if it has **Sponge**, AtomMC, BukkitForge, BungeeCord etc.
server with spongeforge-1.12.2-2838-7.1.11-RC4007
Any Galacticraft add-ons installed? please list all
GalaxySpace-1.12.2-2.0.11
Please provide screenshots / crash report / log / full modlist as needed
main error that causes the internal server error to start
https://paste.dimdev.org/uvuyeqoxad.rb
logs
http://downloads.thebobsgamingnetwork.net/log.log

If the game is not starting at all, please confirm that you downloaded from the official Galacticraft download site (https://micdoodle8.com/mods/galacticraft)

**Comment by Nbgreen** [comment] 2020-04-01 14:25
Was told to update sponge so I updated to 1.12.2-2838-7.2.1-RC4010 which is the latest build and it did not fix the issue

**Comment by radfast** [comment] 2020-04-04 11:17
Why are you reporting this as a Galacticraft issue?  I've examined the log and I don't see a link.

(I can see at the very end of the stacktrace some Galacticraft code but that does not mean our mod is causing this.  At that point our mod is running some fairly standard dimension initialisation code, similar to what the vanilla game does the first time you go to the Nether or the End.   In particular, we call the vanilla code `MinecraftServer.getWorld()`.  That is not the cause of this issue.)

This issue appears to be caused by one of the mods you have installed having a buggy Advancement, or else a generalised Sponge issue.  I am not following Sponge development - sorry, I don't have time to do that as well as work on our own mod - so I can't help any further.

In summary, I am fairly confident this is **not** a Galacticraft issue.  Therefore I am closing this.  If there is a clear sign that this is a Galacticraft issue (I'm happy to talk to Sponge devs about this if they want to jump in) then we can re-open this.

----

My recommendation is that you test with a reduced mod list, until this stops happening, then start putting back in the mods you removed.  This should highlight which mod is the cause.  You will need Galacticraft installed in all tests, as you will need our dimension changes which seemed to trigger this.  You can use the command `/dimensiontp` to travel quickly to new planets.

If you add/remove mods methodically using a "binary search method" you should be able to figure it out in 6 or 7 game restarts. 

**Obviously either do all testing in a new world, or fully back up the server world, because adding/removing mods in an existing map is a guaranteed way to produce block and item loss.**

**Comment by Aaron1011** [comment] 2020-04-04 22:33
@radfast: There are multiple issues in the provided log - however, one of them is definitely caused by Galacticraft.

In `PacketDynamic`, you're trying to load a world:

https://github.com/micdoodle8/Galacticraft/blob/a9e6ff096d31247075ee690863cc40aa77e658d6/src/main/java/micdoodle8/mods/galacticraft/core/network/PacketDynamic.java#L96

However, `decodeInto` gets called from a Netty handler thread, not the main server thread. While this will only cause an exception when Sponge is installed, it can lead to world corruption on a plain Forge server (since the Minecraft server instance is not thread-safe).

**Comment by radfast** [comment] 2020-04-05 13:21
@Aaron1011 thank you, I see that.   My bad for not spotting that this was the cause.  We should fix that as a priority.

**Comment by Nbgreen** [comment] 2020-04-09 16:21
Im not trying to be rude or anything and I know y’all have lifes other then deving this mod but I was wondering if I could get an ETA or an emergency fix for this. I dev the Lapito’s Galacticraft Modpack and I’m losing a lot of players on my official server because of this issue. I’m having to restart my server once every 3 hours or so so players can connect. The issue is random sometimes it happens on server start other times the server can go all day with no issues. I’ve been dealing with this issue for over two weeks and my players are getting tired of it. If we could get a fix we would appreciate it greatly.

**Comment by radfast** [comment] 2020-04-10 11:26
>   y’all have lifes other then deving this mod

This.

I hope to spend some time on Galacticraft over this weekend.  This is flagged "Priority" so please be assured it's at the top of the list.

**Closed** 2020-04-13 15:04 UTC
Labels: Priority, sponge

**Comment by radfast** [comment] 2020-04-13 22:01
@Nbgreen  I can't update Galacticraft 1.12 on the official download server today, the issues with that might take several days to resolve as the download server is not managed by me.

Meanwhile I made a manual build only for you, to use on your server/servers, named 4.0.2.244A.  This should be the same as official build 4.0.2.245 whenever that comes.

You can run this manual build **server-side only**.

I mean, it is not necessary for your players to run 4.0.2.244A, your players can keep using an older "official" build like 4.0.2.244 on their clients.  Build mismatches between server and client are OK in Galacticraft (unless we update the minor version, like when 4.0.1 became 4.0.2).

(GalacticraftCore-4.0.2.244A.jar](https://drive.google.com/open?id=1mNRm-wdzbh6CuhWRBWupSqWN5cRrg3_1]
(Galacticraft-Planets-4.0.2.244A.jar](https://drive.google.com/open?id=15bMGgmeUZF1xvGeVAMqsBOPJ_-FONx7e)

No need for you to update MicdoodleCore, that has not changed so please continue using build 244 of that.

**Comment by Nbgreen** [comment] 2020-04-13 23:07
@radfast thank you @marcus8448 gave me a dev build Friday that fixed the issue on the server.

**Comment by radfast** [comment] 2020-04-13 23:41
OK that was nice of him, he didn't tell me!

Build 244A fixes a couple of other issues, including tps lag from the Magnetic Crafting Table if used with a large item pipe system from another mod.  So you're welcome to switch up to 244A anyhow, next time you restart the server, or just wait for our official build 245, totally up to you.

**Comment by micdoodle8** [comment] 2020-04-16 07:39
Official build 245 is now available
