### ISSUE TITLE
Wrong item texture in inventory

### ISSUE THREAD

**Issue by PhysicalNova** [micdoodle8/Galacticraft#3555] opened 2018-11-23 17:02 UTC
Minecraft version: 1.12.2
Galacticraft version: 1.12.2-4.0.1.181
--------------------
Java version (if it helps) : 
-jre1.8.0_191
-jdk1.8.0_191 (For coding)
--------------------
Single player (SSP).
--------------------
Mod list : 
-Bilbiocraft (v2.4.5)
-Crayfish furniture mod (v5.16.0)
-CodeChickenLib (v3.2.1.351)
-IchunUtil (v7.1.4)
-Industrialcraft (v2.8.96-ex112)
-Just enouth items (v4.8.5.159)
-Journeymap (v5.5.2)
-Optifine (vHD_U_E1)
-PortalGun (v7.0.2)
-RedstoneFlux (v2.0.2.3)
-SpawnerCraft+ (v4.0.0)
-torohealth (v11)
--------------------
What happens : The moon rock has a moon copper ore when held, but not when placed (in the world)
Furthermore, this texture glitch doesn't happen if only Galacticraft is installed. 
--------------------
Screenshot : 
![texture bug](https://user-images.githubusercontent.com/40638280/48954384-8eaaa800-ef49-11e8-9933-894b2285ee2e.png)

**Comment by PhysicalNova** [comment] 2018-11-23 17:04
I know that there was already a thread about this glitch, but I could not find it. 
Thus I don't remember the mods that person had, and which version was used.

**Comment by TheQuadShot** [comment] 2018-11-23 17:36
Dupe of https://github.com/micdoodle8/Galacticraft/issues/3546

**Comment by PhysicalNova** [comment] 2018-11-23 19:41
Yes, thank you for answering. 
But there isn't any apparent conflict. (I will test for mods that can cause the glitch, and tell you).

**Comment by PhysicalNova** [comment] 2018-11-23 22:30
And even after updating JEI, the problem persists.

**Comment by MauveCloud** [comment] 2018-12-01 17:50
> Furthermore, this texture glitch doesn't happen if only Galacticraft is installed.

Are you sure about that?  It does for me (I haven't used Galacticraft in a while, but I decided to double-check this), so perhaps it's not accurate to blame JEI for this:
![2018-12-01_09 46 06](https://user-images.githubusercontent.com/8942955/49331195-36c5ff80-f54e-11e8-92a7-66f742deaf31.png)

**Comment by PhysicalNova** [comment] 2018-12-03 22:00
Oh ! interesting ! For me, it glitched only when JEI was installed. And here you have only galacticraft... Well, I can't put the finger on what causes the issues :-/...

**Comment by micdoodle8** [comment] 2019-01-09 01:12
Should be fixed in the next build. Thanks!

**Closed by micdoodle8** 2019-01-09 01:12 UTC
