### ISSUE TITLE
[Deconstruction Mod] Crash when using Inventory to craft

### ISSUE THREAD

**Issue by Ctrlaltdenied** [micdoodle8/Galacticraft#2199] opened 2016-05-25 15:56 UTC
Ok, so I launched a world, broke a tree, converted the wood to planks, and upon placing the third plank to create a crafting table it crashes the client.

This doesn't happen with the mods removed, obviously I tried the latest, will try the current recommended now. 

EDIT: Also crashes the same way there too.
EDIT2: When I log back on to the game, the wood I had inside is gone, like I never broke and collected the wood

**EDIT3 - I went through a full process of elimination, it crashes when Galactic Craft and Deconstruction Table are installed, removing Deconstruction Table also fixes the bug. The version of Deconstruction Mod that I am using is v2.2.7: Any ideas?** 

Here is my report.

> ---- Minecraft Crash Report ----
> // Shall we play a game?
> 
> Time: 25/05/16 16:50
> Description: Updating screen events
> 
> java.lang.NullPointerException: Updating screen events
>   at net.minecraft.item.crafting.ShapelessRecipes.func_77569_a(SourceFile:36)
>   at net.minecraft.item.crafting.CraftingManager.func_82787_a(CraftingManager.java:323)
>   at net.minecraft.inventory.ContainerPlayer.func_75130_a(ContainerPlayer.java:80)
>   at net.minecraft.inventory.InventoryCrafting.func_70299_a(SourceFile:81)
>   at net.minecraft.inventory.Slot.func_75215_d(Slot.java:77)
>   at net.minecraft.inventory.Container.func_75144_a(SourceFile:222)
>   at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
>   at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:504)
>   at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638)
>   at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java)
>   at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
>   at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
>   at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:453)
>   at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
>   at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:607)
>   at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
>   at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
>   at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
>   at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
>   at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
>   at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
>   at net.minecraft.client.main.Main.main(SourceFile:148)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>   at java.lang.reflect.Method.invoke(Unknown Source)
>   at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
>   at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> ## A detailed walkthrough of the error, its code path and all known details is as follows:
> 
> -- Head --
> Stacktrace:
>   at net.minecraft.item.crafting.ShapelessRecipes.func_77569_a(SourceFile:36)
>   at net.minecraft.item.crafting.CraftingManager.func_82787_a(CraftingManager.java:323)
>   at net.minecraft.inventory.ContainerPlayer.func_75130_a(ContainerPlayer.java:80)
>   at net.minecraft.inventory.InventoryCrafting.func_70299_a(SourceFile:81)
>   at net.minecraft.inventory.Slot.func_75215_d(Slot.java:77)
>   at net.minecraft.inventory.Container.func_75144_a(SourceFile:222)
>   at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
>   at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:504)
>   at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638)
>   at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java)
>   at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
>   at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
>   at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:453)
>   at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
>   at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:607)
>   at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
>   at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
>   at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
>   at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
> 
> -- Affected screen --
> Details:
>   Screen name: net.minecraft.client.gui.inventory.GuiInventory
> 
> -- Affected level --
> Details:
>   Level name: MpServer
>   All players: 1 total; [GCEntityClientPlayerMP['CtrlAltDenied'/249, l='MpServer', x=153.11, y=91.62, z=254.94]]
>   Chunk stats: MultiplayerChunkCache: 420, 429
>   Level seed: 0
>   Level generator: ID 00 - default, ver 1. Features enabled: false
>   Level generator options: 
>   Level spawn location: World: (152,64,256), Chunk: (at 8,4,0 in 9,16; contains blocks 144,0,256 to 159,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
>   Level time: 895 game time, 895 day time
>   Level dimension: 0
>   Level storage version: 0x00000 - Unknown?
>   Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
>   Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
>   Forced entities: 51 total; [EntityBat['Bat'/128, l='MpServer', x=137.50, y=11.00, z=313.38], EntitySheep['Sheep'/134, l='MpServer', x=157.72, y=71.00, z=304.84], EntitySheep['Sheep'/135, l='MpServer', x=154.50, y=77.00, z=309.50], EntitySheep['Sheep'/136, l='MpServer', x=154.50, y=78.00, z=306.50], EntityBat['Bat'/137, l='MpServer', x=150.84, y=14.00, z=334.78], EntitySheep['Sheep'/140, l='MpServer', x=168.47, y=83.00, z=266.53], EntitySheep['Sheep'/141, l='MpServer', x=171.47, y=64.69, z=313.47], EntityBat['Bat'/148, l='MpServer', x=188.28, y=16.00, z=177.53], EntitySheep['Sheep'/149, l='MpServer', x=181.53, y=77.00, z=250.64], EntitySheep['Sheep'/150, l='MpServer', x=186.88, y=78.00, z=264.95], EntitySheep['Sheep'/151, l='MpServer', x=179.38, y=79.00, z=268.47], EntityBat['Bat'/152, l='MpServer', x=181.38, y=42.00, z=331.66], EntityBat['Bat'/157, l='MpServer', x=190.00, y=36.00, z=325.25], EntitySheep['Sheep'/159, l='MpServer', x=214.50, y=86.00, z=177.50], EntitySheep['Sheep'/160, l='MpServer', x=211.50, y=91.00, z=180.50], EntitySheep['Sheep'/161, l='MpServer', x=208.50, y=93.00, z=182.50], EntitySheep['Sheep'/73, l='MpServer', x=77.50, y=100.00, z=222.50], EntitySheep['Sheep'/74, l='MpServer', x=79.78, y=99.00, z=224.22], EntitySheep['Sheep'/75, l='MpServer', x=78.09, y=99.00, z=225.47], EntitySheep['Sheep'/76, l='MpServer', x=78.59, y=99.00, z=226.53], EntityBat['Bat'/77, l='MpServer', x=74.06, y=17.00, z=319.22], EntityBat['Bat'/82, l='MpServer', x=92.22, y=52.00, z=273.94], EntitySheep['Sheep'/83, l='MpServer', x=86.50, y=79.00, z=280.50], EntitySheep['Sheep'/84, l='MpServer', x=85.50, y=78.00, z=283.50], EntitySheep['Sheep'/85, l='MpServer', x=94.09, y=82.00, z=288.91], EntitySheep['Sheep'/86, l='MpServer', x=86.38, y=78.00, z=287.69], EntitySheep['Sheep'/91, l='MpServer', x=108.50, y=92.00, z=265.81], EntitySheep['Sheep'/92, l='MpServer', x=112.44, y=92.00, z=259.34], EntitySheep['Sheep'/93, l='MpServer', x=109.31, y=86.00, z=268.97], EntitySheep['Sheep'/94, l='MpServer', x=108.34, y=87.00, z=267.47], EntitySheep['Sheep'/100, l='MpServer', x=120.47, y=84.00, z=207.38], EntitySheep['Sheep'/101, l='MpServer', x=116.78, y=85.00, z=210.50], EntitySheep['Sheep'/102, l='MpServer', x=120.78, y=84.00, z=220.41], EntitySheep['Sheep'/103, l='MpServer', x=115.19, y=85.00, z=210.50], EntitySheep['Sheep'/104, l='MpServer', x=122.41, y=86.00, z=231.53], EntitySheep['Sheep'/105, l='MpServer', x=116.97, y=89.00, z=237.09], EntitySheep['Sheep'/106, l='MpServer', x=121.50, y=84.00, z=271.50], EntitySheep['Sheep'/107, l='MpServer', x=126.50, y=82.00, z=276.50], EntitySheep['Sheep'/108, l='MpServer', x=125.50, y=84.00, z=273.50], EntitySheep['Sheep'/109, l='MpServer', x=125.50, y=83.00, z=278.50], EntitySheep['Sheep'/110, l='MpServer', x=115.50, y=77.00, z=303.50], EntitySheep['Sheep'/111, l='MpServer', x=112.13, y=80.00, z=298.53], EntitySheep['Sheep'/112, l='MpServer', x=121.63, y=79.00, z=299.53], EntitySheep['Sheep'/113, l='MpServer', x=112.50, y=82.00, z=296.34], EntitySheep['Sheep'/114, l='MpServer', x=116.53, y=76.00, z=306.53], GCEntityClientPlayerMP['CtrlAltDenied'/249, l='MpServer', x=153.11, y=91.62, z=254.94], EntitySheep['Sheep'/123, l='MpServer', x=130.78, y=84.00, z=229.50], EntitySheep['Sheep'/124, l='MpServer', x=127.06, y=84.00, z=226.94], EntitySheep['Sheep'/125, l='MpServer', x=129.50, y=82.00, z=302.09], EntitySheep['Sheep'/126, l='MpServer', x=131.06, y=83.00, z=294.16], EntitySheep['Sheep'/127, l='MpServer', x=132.31, y=83.00, z=296.16]]
>   Retry entities: 0 total; []
>   Server brand: fml,forge
>   Server type: Integrated singleplayer server
> Stacktrace:
>   at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
>   at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
>   at net.minecraft.client.main.Main.main(SourceFile:148)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>   at java.lang.reflect.Method.invoke(Unknown Source)
>   at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
>   at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 
> -- System Details --
> Details:
>   Minecraft Version: 1.7.10
>   Operating System: Windows 7 (amd64) version 6.1
>   Java Version: 1.8.0_91, Oracle Corporation
>   Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
>   Memory: 1799147336 bytes (1715 MB) / 2462056448 bytes (2348 MB) up to 2462056448 bytes (2348 MB)
>   Mod Pack: Unknown / None
>   LiteLoader Mods: 2 loaded mod(s)
>           - Presence Footsteps version r4 for 1.7.10
>           - MAtmos version r29 for 1.7.10
>   LaunchWrapper: 37 active transformer(s)
>           - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
>           - Transformer: optifine.OptiFineClassTransformer
>           - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
>           - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
>           - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
>           - Transformer: net.minecraftforge.classloading.FluidIdTransformer
>           - Transformer: codechicken.lib.asm.ClassHeirachyManager
>           - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
>           - Transformer: codechicken.core.asm.TweakTransformer
>           - Transformer: codechicken.core.asm.DelegatedTransformer
>           - Transformer: codechicken.core.asm.DefaultImplementationTransformer
>           - Transformer: micdoodle8.mods.miccore.MicdoodleTransformer
>           - Transformer: codechicken.nei.asm.NEITransformer
>           - Transformer: atomicstryker.dynamiclights.common.DLTransformer
>           - Transformer: invtweaks.forge.asm.ContainerTransformer
>           - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
>           - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
>           - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
>           - Transformer: me.guichaguri.betterfps.transformers.MathTransformer
>           - Transformer: me.guichaguri.betterfps.transformers.EventTransformer
>           - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
>           - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
>           - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
>           - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
>           - Transformer: micdoodle8.mods.miccore.MicdoodleAccessTransformer
>           - Transformer: invtweaks.forge.asm.ITAccessTransformer
>           - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
>           - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
>           - Transformer: shadersmodcore.transform.SMCClassTransformer
>           - Transformer: com.enderio.core.common.transform.EnderCoreTransformer
>           - Transformer: com.enderio.core.common.transform.EnderCoreTransformerClient
>           - Transformer: fastcraft.J
>           - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
>           - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
>           - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
>           - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
>           - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
>   JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2560m -Xmx2560m
>   AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
>   IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
>   FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D4 42 mods loaded, 42 mods active
>   States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
>   UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
>   UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](modpack.jar) 
>   UCHIJAAAA   Forge{10.13.4.1614} [Minecraft Forge](modpack.jar) 
>   UCHIJAAAA   CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar) 
>   UCHIJAAAA   Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) 
>   UCHIJAAAA   NotEnoughItems{1.0.5.120} [Not Enough Items](Core - %28CodeChicken%29 Not Enough Items v1.0.5.120.jar) 
>   UCHIJAAAA   FastCraft{1.23} [FastCraft](Client - Fastcraft v1.23.jar) 
>   UCHIJAAAA   endercore{1.7.10-0.2.0.32_beta} [EnderCore](API - Ender Core v0.2.0.32 Beta.jar) 
>   UCHIJAAAA   soundfilters{0.8_for_1.7.X} [Sound Filters](Client - SoundFilters v0.8.jar) 
>   UCHIJAAAA   bspkrsCore{6.16} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.16.jar) 
>   UCHIJAAAA   Treecapitator{1.7.10} [Treecapitator](Core - %28Bspkrs%29 Treecapitator v2.0.4.jar) 
>   UCHIJAAAA   VeinMiner{0.31.4_build.unknown} [Vein Miner](Core - %28Bspkrs%29 Vein Miner v0.31.4.jar) 
>   UCHIJAAAA   VeinMinerModSupport{0.31.4_build.unknown} [Mod Support](Core - %28Bspkrs%29 Vein Miner v0.31.4.jar) 
>   UCHIJAAAA   NEIAddons{1.12.15.41} [NEI Addons](Core - %28CodeChicken%29 Not Enough Addons v1.12.15.41.jar) 
>   UCHIJAAAA   NEIAddons|Developer{1.12.15.41} [NEI Addons: Developer Tools](Core - %28CodeChicken%29 Not Enough Addons v1.12.15.41.jar) 
>   UCHIJAAAA   NEIAddons|AppEng{1.12.15.41} [NEI Addons: Applied Energistics 2](Core - %28CodeChicken%29 Not Enough Addons v1.12.15.41.jar) 
>   UCHIJAAAA   NEIAddons|Botany{1.12.15.41} [NEI Addons: Botany](Core - %28CodeChicken%29 Not Enough Addons v1.12.15.41.jar) 
>   UCHIJAAAA   NEIAddons|Forestry{1.12.15.41} [NEI Addons: Forestry](Core - %28CodeChicken%29 Not Enough Addons v1.12.15.41.jar) 
>   UCHIJAAAA   NEIAddons|CraftingTables{1.12.15.41} [NEI Addons: Crafting Tables](Core - %28CodeChicken%29 Not Enough Addons v1.12.15.41.jar) 
>   UCHIJAAAA   NEIAddons|ExNihilo{1.12.15.41} [NEI Addons: Ex Nihilo](Core - %28CodeChicken%29 Not Enough Addons v1.12.15.41.jar) 
>   UCHIJAAAA   neiintegration{1.1.2} [NEI Integration](Core - %28CodeChicken%29 Not Enough Integration v1.1.2.jar) 
>   UCHIJAAAA   NEIPlugins{1.1.0.11-unofficial} [NEI Plugins Unofficial](Core - %28CodeChicken%29 Not Enough Plugins v1.1.0.11.jar) 
>   UCHIJAAAA   neresources{0.1.0.ManuallyBuilt} [Not Enough Resources](Core - %28CodeChicken%29 Not Enough Resources v0.1.0-122.jar) 
>   UCHIJAAAA   Waila{1.5.10} [Waila](Core - %28NotEnoughItems%29 Waila v1.5.10.jar) 
>   UCHIJAAAA   WailaHarvestability{1.1.6} [Waila Harvestability](Core - %28Waila%29 Harvestability v1.1.6.jar) 
>   UCHIJAAAA   wailaplugins{MC1.7.10-0.2.0-23} [WAILA Plugins](Core - %28Waila%29%28EnderCore%29 Plugins v0.2.0-23.jar) 
>   UCHIJAAAA   deconstruction{2.2.7} [The Deconstruction Mod](Core - Deconstruct Mod v2.2.7.jar) 
>   UCHIJAAAA   DynamicLights{1.3.9} [Dynamic Lights](Core - DynamicLights-1.7.10.jar) 
>   UCHIJAAAA   DynamicLights_onFire{1.0.5} [Dynamic Lights Burning Entity Module](Core - DynamicLights-1.7.10.jar) 
>   UCHIJAAAA   DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module](Core - DynamicLights-1.7.10.jar) 
>   UCHIJAAAA   DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module](Core - DynamicLights-1.7.10.jar) 
>   UCHIJAAAA   DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module](Core - DynamicLights-1.7.10.jar) 
>   UCHIJAAAA   DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module](Core - DynamicLights-1.7.10.jar) 
>   UCHIJAAAA   DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module](Core - DynamicLights-1.7.10.jar) 
>   UCHIJAAAA   DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light](Core - DynamicLights-1.7.10.jar) 
>   UCHIJAAAA   DynamicLights_otherPlayers{1.0.8} [Dynamic Lights OtherPlayers Light Module](Core - DynamicLights-1.7.10.jar) 
>   UCHIJAAAA   DynamicLights_thePlayer{1.1.4} [Dynamic Lights Player Light Module](Core - DynamicLights-1.7.10.jar) 
>   UCHIJAAAA   inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](Core - Inventory Tweaks v1.59-152.jar) 
>   UCHIJAAAA   projectbench{0.5.0} [Project Bench Updated](Core - ProjectBench v0.5.jar) 
>   UCHIJAAAA   quickhotbar{1.04} [Quick Hotbar](Core - Quick Hotbar v1.04.jar) 
>   UCHIJAAAA   GalacticraftCore{3.0.12} [Galacticraft Core](Mod - Galacticraft Core v3.0.12.460.jar) 
>   UCHIJAAAA   GalacticraftMars{3.0.12} [Galacticraft Planets](Mod - Galacticraft Planets v3.0.12.460.jar) 
>   Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
>   LWJGL: 2.9.1
>   OpenGL: GeForce GTX 980 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 365.19, NVIDIA Corporation
>   GL Caps: Using GL 1.3 multitexturing.
> Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
> Anisotropic filtering is supported and maximum anisotropy is 16.
> Shaders are available because OpenGL 2.1 is supported.
> 
>   Is Modded: Definitely; Client brand changed to 'fml,forge'
>   Type: Client (map_client.txt)
>   Resource Packs: [Default HD v1.7.zip, VanillaBDcraft 128x MC17.zip, Minecraft Sound Improvement.zip, PF_Resources.zip]
>   Current Language: English (US)
>   Profiler Position: N/A (disabled)
>   Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
>   Anisotropic Filtering: Off (1)
>   OptiFine Version: OptiFine_1.7.10_HD_U_D4
>   Render Distance Chunks: 10
>   Mipmaps: 4
>   Anisotropic Filtering: 1
>   Antialiasing: 0
>   Multitexture: false
>   OpenGlVersion: 4.5.0 NVIDIA 365.19
>   OpenGlRenderer: GeForce GTX 980 Ti/PCIe/SSE2
>   OpenGlVendor: NVIDIA Corporation
>   CpuCount: 8
> 
> [crash-2016-05-25_16.50.24-client.txt](https://github.com/micdoodle8/Galacticraft/files/282340/crash-2016-05-25_16.50.24-client.txt)

**Comment by dj3520** [comment] 2016-05-25 18:56
Crash caused by NEI not Galacticraft

**Comment by Ctrlaltdenied** [comment] 2016-05-25 19:13
I first thought it was GC because that was the latest mod I put in, but have since ruled it out to be the deconstruct mod. The issue doesn't come up when it is removed from my pack. But the issue doesn't come up with just deconstruct in the pack with no GC either. The issue is only reproduced when GC and Deconstruction mod are combined.

**Comment by Ctrlaltdenied** [comment] 2016-06-25 17:55
I agreed with you at first, but curiously enough when NEI and Deconstruction mod are together without GC, no crash, when GC is added in then it crashes.

I will reproduce this error again for you as I have been busy busy with the modpack and solder.
If needed I will provide a download link to the full pack for your examination.

**Comment by Ctrlaltdenied** [comment] 2016-06-25 18:58
@radfast Ok, so I decided to record a quick and dirty video of the process. I start the game with GC NEI and Deconstruction in there. Then later I fumble a bit as I stupidly forgot to remove the core, then I boot the game without GC and the issue goes away. Observe the video evidence...

https://www.youtube.com/watch?v=xOCDd647THQ&feature=youtu.be

**Comment by radfast** [comment] 2016-06-25 19:10
I can't understand the video, the text is too blurry to read.  I do notice you are using the Technic launcher and shaders.  It's best to test issues in the simplest possible environment - meaning vanilla launcher, no other mods.

Please specify the **exact** versions of all three mods NEI, Deconstruction and GC causing a crash, and which Forge version.  Post the fml-client-latest.log so I can look for any logged non-critical errors.

**Comment by Ctrlaltdenied** [comment] 2016-06-25 19:18
Dude the quality is 1440p 60fps, I'm confused about how it can be blurred.

But as you wish...
Crash report: http://pastebin.com/Lzx2berJ
Current entire mod list: https://i.imgur.com/Ww9EzV6.png

Shortened Modlist:
# NEI v1.0.5.120
# Deconstruction v2.2.7
# GC v3.0.12.375
# Forge v10.13.4.1614 for 1.7.10

**Comment by Ctrlaltdenied** [comment] 2016-06-25 19:35
@radfast Sorry for the editfest, I have now updated the post to final version with everything you wanted.

As for testing with just the launcher vanilla, yeah I get that, but the crash doesn't happen until I put GC in, with the other mods on their own the crash just doesn't happen.

**Comment by radfast** [comment] 2016-06-25 20:03
Please test with GC 3.0.12.460.  As instructed in the guidelines when you created this thread, we can only support issues in the latest version of Galacticraft.

**Comment by Ctrlaltdenied** [comment] 2016-06-25 21:08
Grabbed all 3 of the 460 mods, dropped them in. Same crash. 
Do you want the logs or do you want me to try the latest dev versions?

**Comment by Ctrlaltdenied** [comment] 2016-06-25 21:27
@radfast, happens with Deconstruction v2.2.6 too.

**Comment by Ctrlaltdenied** [comment] 2016-06-25 21:50
@radfast Ok so since just having deconstruction mod, GC and the core in my mods folders still produces the crash, and doesn't without them. I can only assume it's maybe my Java version? Which is 1.8.0-91

**Comment by radfast** [comment] 2016-06-25 22:27
OK just tell me again the exact steps to reproduce the crash.  I understood:
1) Create new world
2) Punch tree to get wood
3) In player inventory, craft wood to wooden planks
4) In player inventory, craft 4 wooden planks to make a Crafting Table

and step 4 causes the crash?

Could be an NEI bug, I'm not using the same NEI version currently as you are testing.

Yes please post your `fml-client-latest.log`

Dev versions are not for this purpose.  (They are for mod developers only - special version of the mod that can be launched from inside a programming system.)

**Comment by Ctrlaltdenied** [comment] 2016-06-25 22:33
You've got that correct.
1) create new world
2) Punch tree to get wood
3) In player inventory, craft wood to wooden planks
4) Place planks in any configuration to the 3rd plank and it crashes.

If it was an NEI bug would it not crash without GC being involved?

[fml-client-latest.txt](https://github.com/micdoodle8/Galacticraft/files/333321/fml-client-latest.txt)
[crash-2016-06-25_22.48.50-client.txt](https://github.com/micdoodle8/Galacticraft/files/333322/crash-2016-06-25_22.48.50-client.txt)

**Comment by radfast** [comment] 2016-06-25 22:40
Thank you, I'll look at the logs.

> If it was an NEI bug would it not crash without GC being involved?

You can say the same about whether it is a GC bug.  I'll take a look now, keeping an open mind, and try to figure out the actual cause of this.

**Comment by Ctrlaltdenied** [comment] 2016-06-25 22:47
I'd really love to know myself, don't see how the two mods can mess with such a fundamental part of Minecraft in this way.

**Comment by radfast** [comment] 2016-06-26 17:18
You log shows you tested this without NEI and still had the crash.

I have tested the same versions of Deconstruction and Galacticraft, following the same steps I am not seeing any crash.

This leads me to think it must be something else connected with your setup.  Please test yours using the **vanilla launcher**, default Minecraft options, and the simplest possible list of mods and see if the problem still occurs.

FWIW, there is nothing at all in the crash report to suggest this is connected with Galacticraft.

**Comment by Ctrlaltdenied** [comment] 2016-06-26 17:37
I have already tried with the simplest mods, as in just those required to get GC to work, and deconstruction mod. I haven't tried without the technic plaform, but I am using technic solder to act as a modpack manager and download proxy/cache. 

Is there any indication of the source of the issue in the logs at all? I don't understand either how you are unable to reproduce the error.

**Comment by radfast** [comment] 2016-06-26 18:26
The log shows the source of the error in vanilla Minecraft code, which is unusual.

Please try this in the vanilla launcher.

**Comment by radfast** [comment] 2017-02-25 19:12
Closing due to lack of follow-up.

Please re-open if this is still an issue - if re-opening, please also provide a link to the report of this to the **Deconstruction** mod author, as it may be an issue in that mod.

**Closed by radfast** 2017-02-25 19:12 UTC
Labels: 1.7, cant reproduce, not a Galacticraft issue
