### ISSUE TITLE
Oxygen Bubble failing

### ISSUE THREAD

**Issue by ShadowDrakken** [micdoodle8/Galacticraft#2165] opened 2016-03-29 20:03 UTC
This was previously brought up as a bug that was supposedly resolved, but it's occurring again in build 454.

The Oxygen Bubble will stop functioning correctly if a player dies, or if the chunk is unloaded and reloaded during exploration. Shutting down the game and restarting resolves the issue.

Basically what happens is the bubble is still visually there, and it still consumes oxygen and power, but it counts as an invalid oxygen setup and the player suffocates without gear on, or consumes oxygen from their gear if their gear is valid.

**Comment by radfast** [comment] 2016-04-03 12:41
Duplicate of #1718.

**Comment by ShadowDrakken** [comment] 2016-04-03 20:46
Yup, it's dupe because the other issue was closed as having been fixed and updates to it were being ignored

**Comment by EzerArch** [comment] 2016-04-04 05:48
Just tested in 454. I let myself suffocate to death far away from the Oxygen Bubble. Respawned, without ox. gears, went in an Oxygen Bubble, it was working.

However I was having the said problem when I kept using ```/dimenstiontp`` and CustomNPCs' teleporter. The problem stopped happening when I had ceased using these tools in favor of rockets. Probably forcing dimension change, instead of using rockets, might be the cause.

**Comment by radfast** [comment] 2016-06-26 17:22
We do not need two issues open, I have re-opened issue #1718 for now.

**Closed by radfast** 2016-06-26 17:22 UTC
