### ISSUE TITLE
Crash? Is this Normal?

### ISSUE THREAD

**Issue by Cracks777** [micdoodle8/Galacticraft#2075] opened 2016-02-11 15:54 UTC
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 2/11/16 9:50 AM
Description: Unexpected error

java.lang.ClassCastException: micdoodle8.mods.galacticraft.core.client.model.ModelPlayerGC cannot be cast to api.player.model.ModelPlayer
	at net.smart.render.playerapi.SmartRenderRenderPlayerBase.createModel(SmartRenderRenderPlayerBase.java:48)
	at net.smart.render.SmartRenderRender.<init>(SmartRenderRender.java:39)
	at net.smart.render.playerapi.SmartRenderRenderPlayerBase.getRenderRender(SmartRenderRenderPlayerBase.java:41)
	at net.smart.render.playerapi.SmartRenderRenderPlayerBase.renderFirstPersonArm(SmartRenderRenderPlayerBase.java:77)
	at api.player.render.RenderPlayerAPI.renderFirstPersonArm(Unknown Source)
	at api.player.render.RenderPlayerAPI.renderFirstPersonArm(Unknown Source)
	at net.minecraft.client.renderer.entity.RenderPlayer.func_82441_a(RenderPlayer.java)
	at net.minecraft.client.renderer.ItemRenderer.func_78440_a(ItemRenderer.java:531)
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:971)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1759)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1334)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by XFactHD** [comment] 2016-02-11 16:08
Do you have PlayerAPI? If not, try it again with that installed.

**Comment by Cracks777** [comment] 2016-02-11 16:12
SmartRender-1.7.10-2.1
SmartMoving-1.7.10-15.6
PlayerAPI-1.7.10-1.4
RenderPlayerAPI-1.7.10-1.4

**Comment by XFactHD** [comment] 2016-02-11 16:13
Ok, are you using the latest version of GC and the mods you just posted?

**Comment by Cracks777** [comment] 2016-02-11 16:25
yes.

**Comment by XFactHD** [comment] 2016-02-11 16:26
I am out of ideas...

**Comment by Cracks777** [comment] 2016-02-11 16:29
The Messed up thing is, it doesn't crash the game till i go load a world?

**Comment by XFactHD** [comment] 2016-02-11 16:32
That's normal, when the world is loaded, an instance of the ModelPlayer is created. It can not crash on an object that is not created (or at least not with this exception).l

**Comment by Cracks777** [comment] 2016-02-11 16:32
Oh. IDK Then

**Comment by radfast** [comment] 2016-02-11 17:55
This actually seems to be the same issue as #961, but let's leave this open.
It should NOT be happening...  We will look for a fix asap.

**Comment by radfast** [comment] 2016-02-11 18:00
The same type of crash was also recently reported [here](https://github.com/micdoodle8/Galacticraft/issues/1437#issuecomment-180793496) but it's not relevant to the issues on that thread ... so let's keep this as the active thread for the issue.

**Comment by radfast** [comment] 2016-02-11 18:04
I have not been able to reproduce the crash in my own testing :(

According to the crash report, it's with RenderPlayerAPI and SmartRender, when viewing in 'first person mode' (i.e. Minecraft normal mode).

Approximately what is happening here is that Galacticraft's default rendering (i.e. without SmartRender) is being used even when SmartRender is installed.  Seems like Galacticraft is not properly detecting SmartRender.  We use the ModID of course.

**It would help me a lot to see a full fml-client-latest.log for the game session when this crash happens.**

**Comment by Cracks777** [comment] 2016-02-11 18:43
http://www.mediafire.com/download/qnw485h7vowa844/fml-client-latest.log

**Comment by radfast** [comment] 2016-02-11 21:15
Please can someone who has this issue do me a favour, and test the same setup without any of the following:
* LiteLoader
* OpenBlocks and OpenModsLib
* Optifine
* any Galacticraft addons (e.g. More Planets, GalaxySpace)

**You'll need to create a new test world, because removing OpenMods from the mod list will likely cause block/item loss in existing worlds.**

**Comment by Cracks777** [comment] 2016-02-11 23:48
Et Futurum-1.5.4 is the cause of this crash.

http://www.curse.com/mc-mods/minecraft/230114-et-futurum

**Comment by EzerArch** [comment] 2016-02-11 23:52
It's because of "cannot be cast to api.player.model.ModelPlayer". Both EtFuturum and SmartMoving try to modify the player model at the same time.

To avoid that, read my EDIT here: https://github.com/ganymedes01/Et-Futurum/issues/55#issue-120309463

**Comment by Cracks777** [comment] 2016-02-12 00:00
still crashes with B:"Skin overlays"=false

**Comment by radfast** [comment] 2016-02-12 18:57
@RobijnVogel who reported the same crash on #1437 - see my link above - does not have **Et Futurum**.  But he does have **OpenBlocks**...

Guys, like I said already, I'm 65% sure this is because of another mod making actual changes to Galacticraft.  I think this because Galacticraft + RenderPlayerAPI + SmartMoving standalone does not have this issue, and Galacticraft is already coded not to have this problem ... in more detail, in coding terms, Galacticraft *looks* to see if SmartRender is present, and if SmartRender is present then Galacticraft does *not* use ```ModelPlayerGC```.

I have not had time to study / test OpenBlocks in detail, but looking at the logs, OpenBlocks is making some kind of change to Galacticraft's player rendering.  I think it's possible OpenBlocks looked at our code and changed something for compatibility, but only looked at the way our code works when SmartRender is not present.  (Galacticraft has two totally different code paths for player rendering, depending on whether SmartRender is present or not.)

**Comment by Cracks777** [comment] 2016-02-12 19:24
i have open blocks and it only crashes when i put it on with Et Futurum?

**Comment by radfast** [comment] 2016-02-12 19:27
Ok, interesting

Could be different causes of similar-looking crashes for different people.  (I think the oldest, #961 was due to a shader mod).

Looking at [OpenBlocks code](https://github.com/OpenMods/OpenModsLib/blob/master/src/main/java/openmods/core/OpenModsClassTransformer.java) I can't see anything they are doing which messes up Galacticraft, anyhow.

**Comment by Robijnvogel** [comment] 2016-02-12 20:46
I'll test this on my modpack without Liteloader, OpenMods, Optifine and More Planets. If that works, I'll add those again, one by one.

**Comment by radfast** [comment] 2016-02-12 20:50
This line in the log posted by Cracks777 higher up shows that Galacticraft is working correctly in its 'Render Player API' mode.

> [12:04:25] [Client thread/INFO] [STDOUT/GalacticraftCore]: [api.player.render.RenderPlayerAPI:register:485]: Render Player: registered GalacticraftCore

The cause of this crash is still a total mystery to me.

If someone can tell me a **small** collection of mods I can combine to reproduce this crash, that will be the quickest way to find a fix.  It's difficult / impossible for me to troubleshoot issues which I'm not seeing on my own test platforms.  Unfortunately I'm not willing/able to create a modpack of 100+ mods for testing (it would probably not run on my machine anyhow, as I need to be running Eclipse and debuggers alongside Minecraft).

**Comment by Cracks777** [comment] 2016-02-12 21:54
@radfast Working on it

**Comment by Cracks777** [comment] 2016-02-12 22:06
something to do with the addons?
almost got a small list ready.

**Comment by Cracks777** [comment] 2016-02-12 22:12
More planets addon is the cause.

**Comment by Robijnvogel** [comment] 2016-02-14 12:13
Confirmed, just removing More Planets from my massive modpack makes the crash disappear.
Liteloader, Voxelmap, Optifine and OpenMods don't seem to cause a problem.

So I guess this is indeed something for @SteveKunG to fix.

**Comment by radfast** [comment] 2016-02-14 16:14
Thanks for the tests.

I'm closing this thread, as it seems its not a Galacticraft issue.  (More Planets is not Galacticraft, and has its own issue tracker anyhow...)

I'm fine if @SteveKunG or other contributors to this thread want to continue to use this as a place to discuss the issue.  You should be able to add comments even after the thread is "closed".

**Closed by radfast** 2016-02-14 16:14 UTC
Labels: cant reproduce, missing info, Priority
