### ISSUE TITLE
GC Tab in wrong place with CustomNPC's

### ISSUE THREAD

**Issue by morlanius** [micdoodle8/Galacticraft#1373] opened 2015-01-10 16:58 UTC
The tab appears in the wrong place when you have CustomNPC's installed. you have to click factions then click quests to see that dialog as the GC tab is in the same position as the quests tab.

**Comment by radfast** [comment] 2015-01-10 21:39
Duplicate of #831, as a search would have shown.

See also: http://wiki.micdoodle8.com/wiki/Compatibility#Custom_NPCs

Our tabs are using the same system as Tinker's Construct for compatibility with that mod.  We cannot change it unless Tinker's Construct also changes, and I think that is not likely to happen.  It would be better if Custom NPCs made the necessary change (e.g. with a config option).  Meanwhile players will have to use the workaround you mention.

**Closed by radfast** 2015-01-10 21:39 UTC

**Comment by morlanius** [comment] 2015-01-11 15:35
Thanks
