### ISSUE TITLE
Galacticraft 3 space station - Head sticks to ceiling (3.0.12.357)

### ISSUE THREAD

**Issue by draykshaper** [micdoodle8/Galacticraft#1833] opened 2015-09-03 03:00 UTC
I am using, and have always used with this world, the latest version, 3.0.12.357

Similar symptoms as a previously reported issue (which was closed?), linked at the bottom. All the following observations apply to survival mode only, no kind of jetpack or other movement item (i.e. Boots of the Traveler) equipped. 
- When I "bump into" the ceiling of my space station by jumping, I become stuck to the ceiling. 
- I can move forward/back, but side-to-side movement (A and D) does nothing, and pressing or holding shift or jump does nothing. 
- Moving to a wall does nothing, still stuck to the ceiling. 
- This happens both in a 2-block high room and 3+ high. 
- If I move to where there is an empty block above me, I "resume" normal free-fall and can move up and down, but still cannot move side-to-side. I notice when I cross from a ceiling block above me to empty space above me, I have a small amount of upward momentum (I can stop this momentum with Sneak (shift) as normal since I'm back in free-fall). 
- Related to the previous point: if I'm walking normally and I walk over an empty space, I enter free-fall (intended) but I have a slight upward momentum (not intended?). 
- Since I've encountered being "stuck" to the ceiling, all side-to-side movement in free-fall (using A and D) has completely stopped working. Even when I land on the ground and can walk around normally, if I jump and start free-falling, pressing A and D does nothing. 
- Restarting the client both while stuck to the ceiling, and while on the ground, changes nothing; I continue to get stuck to the ceiling and I have no side-to-side movement in free-fall.
- Returning to the overworld and then back to the space station, the problem is still encountered, both being stuck to the ceiling and no side-to-side movement in free-fall. 
- I'm not the only one on my server that has encountered this problem. This was actually first reported to me by another player, and I confirmed it and have gone through these testing steps. 

As mentioned in the previous issue, one way I've found of resolving being stuck, besides breaking the block above you or moving to an empty space above you, is to go Creative mode, double-jump to fly (which functions completely normally), and hold shift to descend. This is not an option for anyone without op privileges. 
- If I go back to Survival mode, the original problem still persists, including no side-to-side movement. 

Additional observations on some mechanics after equipping a Mekanism jetpack. 
- If I put the jetpack into Hover mode (default keybind F), I can use Sneak (shift) to go down. Going down all the way to the floor makes me "land" and I can walk normally, even while still in Hover mode (in the Overworld you cannot "land" while in Hover mode, you are still "hovering" even at ground level, with modified horizontal momentum mechanics). 
- If I walk over an empty space, I enter free-fall and continue to have a slight upward momentum, even in Hover mode. 
- Hover mode seems to only affect my up/down position, with no affect on up/down momentum. After "unsticking" from the ceiling using Hover mode + Sneak, while still in the air, I continue to have a slight upward momentum. If I again press Sneak to go down more while remaining in the air, that same small upward momentum remains. Additionally because I'm still in free-fall, side-to-side movement (A and D) continues to not work.
- If I'm on the ground and walking around normally, if I jump without a jetpack, I immediately enter free-fall and have a moderate amount of upward momentum. However, if I'm on the ground and walking around normally and am in Hover mode, if I jump, I travel a short distance off the ground then stop (as usually happens in Hover mode in the Overworld), then after about 1 second it's like the space station "realizes" I'm in the air and puts me into free-fall with a slight upward momentum. 

Previously reported issue: https://github.com/micdoodle8/Galacticraft/issues/1828

**Comment by dj3520** [comment] 2015-11-06 18:29
Having the same issue. For me I've noticed the upward momentum triggers while in freefall and moving forward. As for the problem of bonking your head and not being able to go down, the grappling hook is my answer and has saved me a few times on my survival server while I'm tapping the sneak key.

**Comment by EzerArch** [comment] 2015-12-20 04:06
Moved from #1841:

This issue is hard to reproduce and happens in several ways:

1. The player spawns in the space station and moves slowly upwards to the ceiling, and then he gets stuck. The sneak key doesn't work, unless he breaks the block above the head or walks away from the ceiling.

2. If there's no air blocks (I couldn't reproduce the bug in pressurized rooms) and the player moves up (jump key) and touches the ceiling, he can no longer move down. Same workaround above applies.

3. I couldn't reproduce this bug in a newly generated world, only on old ones, but still I noticed the player head gets "sticky" if the touches the ceiling in airless rooms in the new worlds.

Probably related to the bug:

* The player will always move upwards after dismounting a rocket or world reload, and in this case 1 block up.

* Sometimes the player spawns at the Arrival Block 1 block up, at y=66, instead of y=65. Rarely at y=67, getting suffocation.

-----

Copy from a post to @micdoodle8, with some rephrasing:

I've never managed to reproduce or isolate that. But today I made a space station module on the overworld ([link](https://twitter.com/EzerArch/status/678166928951758848)) and then I copied and pasted it with World Edit in my space station dimension. This is what I got: the sections which were built in-site, no problem, except I can notice the player model first bounces up and down once to start moving down. But the new sections made with WE ([link](https://twitter.com/EzerArch/status/678424661437390848)), I get my head stuck all the time. Regardless how much I press shift, I keep bouncing to the ceiling. It seems there's an upward momentum that negates any downward movement.

Even if I use /tp, the upward momentum is persistent.

**Comment by radfast** [comment] 2016-01-17 19:07
Thank you for ultra-detailed description of the issue, that really helps me when trying to reproduce and test this.

I am looking for a fix.

**Comment by radfast** [comment] 2016-01-29 13:48
Additional info from #2049 is that adding a Spin Thruster to the space station cures this problem.

**Comment by radfast** [comment] 2016-01-29 13:51
The "moving upwards" thing is probably the cause of this, it's resulting in the player becoming stuck in a block above him.

That was introduced deliberately, though, to stop the player becoming stuck in the block below ...

**Comment by EzerArch** [comment] 2016-01-29 21:06
> The "moving upwards" thing is probably the cause of this

Is this also related to "can't swim in GC dimensions" (ref: #1238)? Or is it a vanilla feature? When a player is in water he is forced upwards in low gravity, at least from what I've seen.

**Comment by radfast** [comment] 2016-02-03 13:19
> This issue is hard to reproduce and happens in several ways:

I am having trouble reproducing this.  I've spent about an hour moving around a space station in various ways - including rooms 2 blocks, 3 blocks and 4 blocks high - and I just can't seem to make it happen.  Actually in my own playing I have **never** experienced this issue.

Wondering if other players are doing something different with their fingers from me?  I mean, I probably always "instinctively" use the WASD movement keys in a certain way without realising it.

> I couldn't reproduce this bug in a newly generated world, only on old ones

Whaaattttt?   I really don't see how that can be possible.  Anyhow, assuming it is ... how old do I have to go, to experience the issue?

**Comment by radfast** [comment] 2016-02-03 13:30
Other issues (not the 'head stuck in block + can't move' issue):

1.  The player is rendered 1/8th block (2 Minecraft pixels) too high, when his head touches the ceiling, so that helmet + 1 line of pixels from his head seem to disappear into the block above.

2.  The player appears to have a quick involuntary "bounce" down and up when starting downward movement in freefall, this is the result of the 'Sneak' mechanics in the vanilla game and is something we are working very hard to eliminate

3.  There is a built-in upward drift if the player walks horizontally and then feet leave the ground and he freefalls (e.g. because a platform ends).  This is **intended behaviour**.  In game mechanics it's part of what stops players becoming stuck in blocks below them.  In terms of realism, it's connected with the way bipeds walk - a walking step involves an upwards bounce off the ground until the next foot hits the ground.  You could ask "then how can players walk on a space station without leaving the ground".  My concept is that as the player is able to keep walking on blocks, the player stays on the blocks and can walk normally.  You can think of it that he has magnetic boots, or velcro boots, automatically on space stations - these don't have to be crafted, it's just one of the many abstractions in the game...

4.  The Mekanism jetpack issue I will have to deal with separately.

**Comment by pielorz** [comment] 2016-02-03 21:32
I am also getting the 'Head stuck to ceiling' bug. I can walk around on the floor as normal and then after using Space to go up, I can no longer go down using the Sneak (Shift) key. I can move forward and backwards, just not down.

Like another person said, I can use the Grapple to bring myself back down to the floor.

Its definitely a bug radfast.

**Comment by radfast** [comment] 2016-02-04 00:36
@pielorz:  new world or an existing one?  Anything special I must press or do to make it start happening?  Is it your own space station?  Single player or on a server?

Like I say, I'm not seeing this when I go to my space stations, and until I see this happening for myself I can't start to fix it.  I'm not denying its happening - several people have reported it - but it's not happening for me so far.

**Comment by radfast** [comment] 2016-02-04 02:07
Please try out [build 438](http://ci.micdoodle8.com/job/Galacticraft-1.7/438/), I think it may have improved this.

It's certainly improved issue 2 that I mentioned ...

I still have not been able to reproduce the main issue, I am wondering whether it is connected with how hard you smash into the ceiling.

**Comment by dj3520** [comment] 2016-02-04 02:36
Used to happen to me a lot. Now I can't remember the last time it happened.
Same world.

**Comment by radfast** [comment] 2016-02-04 02:44
I think I will keep this open for now, in case it gets lost.

**Comment by EzerArch** [comment] 2016-02-04 03:39
Isn't the way how the game memorizes the air-filled regions? It's like "oh, these are the voxels where the player can breath and move around this and that way".

Copying an oxygen-sealed room from the Overworld and pasting it in the space station dim with MCEdit or WorldEdit somewhat disturbed that memory. The room built in-situ was okay, but those rooms pasted with WorldEdit was bugged and I got constantly stuck in the ceiling. Until that day a bed exploded in my space station letting all the air to be vented away into space and the bug miraculously disappeared.

**Comment by radfast** [comment] 2016-02-04 03:48
In a sealed room you cannot be in "freefall", the game assumes that the room takes you with itself (even if you are jumping or something).

But if you drift in a vacuum between rooms - out of range of walls - then you are in freefall.

I think this is realistic, if you have better ideas (within the realms of Minecraft physics), let's have em :)

----

I think you are telling me the issue is with sealed rooms?  I didn't try a sealed space station recently, but I guess there could be a problem with that ...

**Comment by pielorz** [comment] 2016-02-04 10:31
Thanks radfast, I'll give that a go when i get home from work. I appriciate all the work you put into this.

My initial post was more a reaction of discovering the bug, searching the web for fellow bug sufferers and posting that i too had come across it. So i will attempt to post more detailed info when I can.

I've just done a bit of limited research at work and I can tell you that I'm using modpack Space Astronomy which is using Galacticraft version GalacticraftCore-1.7-3.0.12.428 / Galacticraft-Planets-1.7-3.0.12.428.jar

As for a new or old world. Its not a world that has been moved from another MC version or anything weird, its was a world created by the modpack and has probably has had its Forge updated as well as other the other mods.

I hope this helps a little! As soon as I get home, I'll try out build 438 and report back.

**Comment by pielorz** [comment] 2016-02-04 19:44
Ive just tried the latest build and it has fixed the ceiling issue :)

**Comment by radfast** [comment] 2016-02-04 21:01
nice, good to know :)

**Comment by EzerArch** [comment] 2016-02-05 00:42
Tested in 440 with a new world. Nothing found.

(Maybe you might want  to close this)

**Comment by radfast** [comment] 2016-02-06 14:02
Although I love closing issues :)  I'm still seeing one of the issues described in this thread:

* Sometimes the player spawns at the Arrival Block 1 block up, at y=66, instead of y=65. Rarely at y=67, getting suffocation.


More accurately, it looks like logging out and logging back in again sometimes places the player 1 block higher than he was before, on Space Stations.

[Also the Mekanism jetpack hover issue reported by @draykshaper I have made a full note of, but I am not going to attempt to fix that in this thread.]

**Closed** 2016-02-06 16:11 UTC
Labels: fixed, follow-up please

**Comment by EzerArch** [comment] 2016-02-06 18:29
@radfast:

> More accurately, it looks like logging out and logging back in again sometimes places the player 1 block higher than he was before, on Space Stations.

Not sure if it is related, and perhaps this needs to be in a separate issue, but being positioned "1 block higher than before" also happens with cryo-chambers, moon landers and with rockets (at least with the tier 3, need to see the others). As to the rockets: when I dismount a rocket on the Overworld, I always fall 3 blocks and get fall damage.
