### ISSUE TITLE
Bucket Dupes in GC With Forge

### ISSUE THREAD

**Issue by kenijey** [micdoodle8/Galacticraft#2723] opened 2017-05-19 17:41 UTC
i don't know should i report this, but i just noticed there are already fuel, bacterial sludge and sulphuric acid buckets in Forge (tested in 2298, don't remember since when). If you didn't aware of this, just install JEI then search for bucket. it will help GC4 development, i think. using Minecraft 1.11.2.
sorry if this already requested or known or i'm just a stupid about this topic. thx
![123](https://cloud.githubusercontent.com/assets/24831406/26261238/15ae4016-3cd9-11e7-95eb-dd339ff36ffd.PNG)
btw, you need to install GC4 to see the buckets (dunno why, maybe i'm wrong about dupe)

**Comment by radfast** [comment] 2017-05-19 19:27
Duplicate of issue #2694.  This is currently intended behaviour, for the reasons explained there.

**Closed by radfast** 2017-05-19 19:27 UTC

**Comment by radfast** [comment] 2017-05-19 19:30
Your graphic is nice, shows quite well why I don't like the Forge buckets.  The colours are wrong and the 32 bit texture is nasty, looks more like a cup than a bucket!

(And worse, some other mods like Tinker's Construct change the colour of that Forge bucket to something medievel which looks totally inappropriate in a mod about space...)

**Comment by kenijey** [comment] 2017-05-19 19:34
i have a custom resource pack, includes plenty of mods support, and all vanilla textures. i can share it with u. (it requires optifine for some of the textures, however you can use it alone too.)

**Comment by radfast** [comment] 2017-05-19 19:40
I don't want to distribute a resource pack with Galacticraft, as that might conflict with other resource packs, and/or can still be overwritten by other resource packs or Forge mods.

**Comment by kenijey** [comment] 2017-05-19 19:41
hmm, i can make a resource pack which has only fine bucket textures?
